Not String.txt

Implement a method `notString(String str)` that returns a new string with `"not "` added to the front unless the original string already starts with `"not"`. If the string begins with `"not"`, return it unchanged. Use `.equals()` or `.startsWith()` for accurate string comparison. This task helps practice string manipulation and conditional logic. For example, `notString("candy")` returns `"not candy"`, `notString("x")` returns `"not x"`, and `notString("not bad")` returns `"not bad"`.

TRA814:Not String – Add "not " Prefix Unless Already Present

---

Shaima/NotString.txt

The notString method adds "not " to the front of the string, unless it already starts with "not" — then it returns the string as it is.

TRA544: Not String - Add not  Prefix Unless Already Present

---

plag_test_tool/from_Haitham/TRA746.java

Implement a method mixStart(String str) that returns true if the string begins with any character followed by "ix", return false otherwise.

TRA746: MixStart – Check if String Starts with Any Char Followed by "ix"

---

plag_test_tool/from_Haitham/TRA730.java

Implement a method front22(String str) that returns a new string with the first two characters added to both the front and back of the original string.
note:
If the string length is less than 2, use the whole string as the prefix and suffix.

TRA730: Front22 – Add First Two Chars to Front and Back of String

---

plag_test_tool/from_Haitham/TRA458.java

The sleepIn method in the TRA458 class checks whether a person can sleep in based on two conditions: if it's not a weekday or if the person is on vacation, then they can sleep in (returns true); otherwise, they can't (returns false).

TRA458: Sleep-In Logic – Implement sleepIn(weekday, vacation)

---

From_Mulk/WithoutXTwo.java

In this code, the trimXFromStartTwo method in the WithoutXTwo class removes 'x' characters from the first two positions of the input string str. It first checks if the string is empty and returns an empty string. If both the first and second characters are 'x', it removes them by returning the substring starting from index 2. If only the first character is 'x', it removes it; if only the second character is 'x', it removes just that character by combining the first character with the substring starting from index 2. If neither of the first two characters is 'x', it returns the original string.

solution of WithoutXTwo task

---

from_hanin/DiceGame.java

The method `sumWithoutDoubles` calculates the sum of two dice rolls, `die1` and `die2`, with special handling when the `noDoubles` flag is `true`. If doubles are not allowed (`noDoubles` is `true`) and both dice show the same value, the method increments `die1` by 1 to avoid a double; if `die1` is already 6, it wraps around to 1. Finally, it returns the sum of the adjusted `die1` and `die2`.

TRA 2768:Logic-1 > withoutDoubles

---

From_Mulk/WithoutDoubles.java

This method takes two dice rolls (die1 and die2) and a boolean noDoubles. Normally, it returns the sum of the dice. If noDoubles is true and the dice show the same number, it increases the second die by 1 to avoid doubles unless both dice show 6, then it just adds 1 to the second die’s value (which might go beyond 6). If noDoubles is false or the dice are different, it simply returns their sum.

Logic-1 > WithoutDoubles task

---

From_Mulk/MirrorPrefixFinder.java

This method finds the longest prefix of a string that mirrors the end of the string in reverse. It compares characters from the start and end moving inward and stops at the first mismatch. The matching prefix is then returned.

String-3 >  MirrorEnds task

---

From_Shaima/ZPatternCompressor.java

The code removes the middle character and keeps only "zp". All other characters in the string remain unchanged.

TRA3848: zipZap--Remove Middle Character from z?p Patterns

---

from_Haitham/StarOut.java

The `StarOut` class contains a method named `starBehindRemover` that removes all `'*'` characters from the input string **along with the characters immediately next to them** (both before and after). It loops through each character in the string and uses conditions to skip characters that are either a `'*'` or are adjacent to a `'*'`. Only characters that are not `'*'` and not directly next to a `'*'` are added to the result. For example, given `"ab*cd"`, the method would return `"ad"` (removing `'*'` and the characters `'b'` and `'c'`). The method uses a `StringBuilder` for efficient string construction.

TRA-3322: StarOut task is done

---

from_hanin/SkipAdjacentPicker.java

The `groupNoAdj` method checks if it's possible to pick a group of non-adjacent numbers from the array `nums`, starting at index `start`, that adds up to the given `target`. It works recursively: first, if the `target` is 0, it returns `true` (a valid subset is found). If the index goes beyond the array length, it returns `false` (no valid subset). Otherwise, it tries two choices — skip the current number and move to the next index (`start + 1`), or include the current number (subtract it from the target) and skip the next index (`start + 2`) to avoid picking adjacent numbers. If either choice leads to the target, it returns `true`.

Tra 4362: Recursion-2 > groupNoAdj

---

from_hanin/ClumpedGroupSum.java

The `groupSumClump` method checks if a subset of numbers can sum to a target, treating adjacent identical numbers as a single "clump" that must be either all included or all excluded. It finds the size of each clump starting at index `start`, then recursively tries both options: skipping the clump or including the entire clump (value × count). It returns true if any valid combination of clumps adds up to the target.

Tra 4364: Recursion-2 > groupSumClump

---

from_Kaltham/HiStringCounter.java

I created a class called HiStringCounter with a method named countHiExcludingX that counts the occurrences of "hi" in a string, but ignores any "hi" that is immediately preceded by 'x', using recursion.
How it works:
Base case:
If the string length is 1 or less, return 0 because "hi" can’t exist.
Check for "xhi":
If the first three characters are "xhi", skip them and recursively process the rest of the string (str.substring(3)) because this "hi" should not be counted.
Check for "hi":
If the first two characters are "hi", add 1 and recursively process the rest of the string starting after the "hi" (str.substring(2)).
Otherwise:
Recursively process the string starting from the next character (str.substring(1)).
The recursion continues until the string is fully processed, giving the total …

TRA-4436: Recursion-1 >=The solution for Recursion-1 > countHi2 Task

---

From_Manal/GroupSumClumpSolver.java

Implemented groupSumClump(start, nums, target) to determine if a subset of integers can sum to a target value, with the constraint that adjacent identical values (clumps) must be treated as a single decision unit—either all included or all excluded.
Used one loop to detect clump boundaries, then applied recursive backtracking to explore valid groupings. No loops used beyond clump detection.

TRA-4382-Recursion-2: groupSumClump

---

From_Mulk/LimitedCharSwap.java

This method swaps the first two words that share the same starting letter and ensures each starting letter only causes one swap by marking it as used after the first swap.

Map-2 > FirstSwap task

---

from_Muiayed/Fix34.java

The `fix34` problem focuses on rearranging elements in an integer array so that every `3` is immediately followed by a `4`. The assumption is that the array contains the same number of `3`s and `4`s, and no `3` is followed by another `3`. The goal is to preserve the relative order of other elements while ensuring that each `3` is paired with a `4` directly after it. The method works by scanning the array for any `3` not followed by a `4`, then searching for a standalone `4` (one not already placed after a `3`) and swapping it into the correct position. This approach uses a clone of the original array to avoid modifying it directly and ensures that each `3` gets its own `4` without disrupting the rest of the array. It's a great exercise in array manipulation, nested loops, and conditional …

#TRA-4339: Array-3 > fix34

---

from_Muiayed/Fix45.java

The fix45 problem is a classic array manipulation challenge where the goal is to rearrange elements so that every 4 is immediately followed by a 5. The assumption is that the array contains equal numbers of 4s and 5s, and no 4 is followed by another 4. The method works by scanning the array for any 4 not followed by a 5, then searching for a standalone 5—one that isn’t already placed directly after a 4. Once found, it swaps that 5 into the correct position after the 4. This ensures that each 4 is paired with a 5 without disrupting the rest of the array’s structure. The use of a cloned array preserves the original input, and the nested loop logic ensures that each 5` is used only once. It’s a great exercise in control flow, array traversal, and understanding how to maintain constraints …

#TRA-4340: Array-3 > fix45

---

from_Muiayed/ZeroFront.java

The ZeroFront class defines a method that rearranges an integer array so that all zeroes are moved to the front, while preserving the order of non-zero elements. The zeroFront method creates a new array of the same length and uses a two-pass approach: the first loop inserts all zeroes at the beginning, and the second loop appends the non-zero values after them. This ensures a clean separation between zero and non-zero elements without sorting or modifying the original order. The main method demonstrates this with examples like [0, 0, 1, 1], [0, 0, 1, 1, 1], and [0, 1].

#TRA-4333: Array-2 > zeroFront

---

from_Muiayed/notReplace.java

The notReplace class modifies a given string by replacing standalone occurrences of the word "is" with "is not", while preserving embedded instances like "isthis" or "this". The notReplace method uses a StringBuilder to construct the result and iterates through the string character by character. It checks whether "is" appears at the current position and ensures it's not part of a larger word by verifying that the characters before and after are not letters. If the condition is met, it appends "is not" and skips ahead; otherwise, it appends the current character. This logic ensures accurate word-boundary detection and avoids false replacements. The main method showcases various test cases, demonstrating the method’s precision in handling different contexts

#TRA4197: String-3 > notReplace

---

from_Muiayed/EvenlySpaced.java

The class you've posted is named `EvenlySpaced`, but its method and logic actually belong to a `BlackJack` implementation. The method `blackjack(int a, int b)` determines which of the two input values is closest to 21 without going over. If both values exceed 21, it returns 0, indicating a bust. If only one value is over 21, it returns the other. Otherwise, it returns the higher of the two using `Math.max(a, b)`. This logic mirrors the rules of the card game Blackjack, where players aim to get as close to 21 as possible without exceeding it. The method is cleanly structured and handles edge cases effectively. However, to maintain clarity and proper naming conventions, the class name should be updated to `BlackJack` to reflect its actual functionality.

#TRA-3713: logic-2 > EvenlySpaced

---

from_Muiayed/ShareDigit.java

The `ShareDigit` class in Java defines a method that checks whether two two-digit numbers share at least one digit. The method `shareDigit(int a, int b)` extracts the tens and units digits of both numbers using division and modulo operations. Specifically, `a1` and `a2` represent the tens and units digits of `a`, while `b1` and `b2` represent those of `b`. The method then compares all combinations of these digits and returns `true` if any match is found. In the `main` method, the first example `shareDigit(12, 23)` returns `true` because both numbers share the digit 2; the second and third examples return `false` since there are no shared digits. This class provides a simple and efficient way to detect digit overlap between two numbers.

#TRA-3704: Logic-1 > ShareDigit 

---

from_Muiayed/WithoutDoubles.java

The `WithoutDoubles` class in Java defines a method that calculates the sum of two dice rolls, with an optional rule to avoid doubles. The method `withoutDoubles(int die1, int die2, boolean noDoubles)` checks if the `noDoubles` flag is set to `true` and both dice show the same value. If so, it adjusts `die1` by incrementing it—unless it's already 6, in which case it wraps around to 1, simulating a standard die roll. This ensures that the result avoids a double while staying within valid die values. The method then returns the sum of the two dice. In the `main` method, the first example returns 5 because the dice are different; the second returns 7 because the double 3 is adjusted to 4; and the third returns 6 because doubles are allowed. This class cleverly handles dice logic with a …

#TRA-3699: Logic-1 > WithoutDoubles 

---

from_Muiayed/Old35.java

The `Old35` class in Java showcases a smart use of boolean logic to determine whether a number is divisible by either 3 or 5, but not both. The method `old35(int n)` first checks divisibility using the modulo operator and stores the results in two boolean variables: `div3` and `div5`. It then returns `true` only if one of these conditions is true exclusively, using the expression `(div3 || div5) && !(div3 && div5)`. This ensures that numbers like 3 and 10 return `true`, while 15—divisible by both—returns `false`. This kind of logic is particularly useful in scenarios where overlapping conditions must be filtered out, such as eligibility rules, game mechanics, or custom business logic. The structure is clean, readable, and demonstrates how combining simple checks can lead to precise …

#TRA-3686: Logic-1 > Old35 

---

from_Muiayed/NotString.java

The `NotString` class contains a method called `notString` that manipulates a given string based on whether it starts with the word `"not"`. If the input string already begins with `"not"` (checked using `str.substring(0, 3).equals("not")`), the method simply returns the original string unchanged. However, if it doesn't, the method prepends `"not "` to the beginning of the string and returns the modified result. This kind of logic is useful in scenarios where you want to ensure a specific prefix is present in a string, such as for tagging, formatting, or enforcing a naming convention. The method is concise, readable, and demonstrates basic string handling in Java.

#TRA-3477: Warmup-1 > NotString 

---

from_Kaltham/ClumpedSubsetSumChecker.java

The class ClumpedSubsetSumChecker has a method canAchieveTargetWithClumps that checks if a subset of numbers can sum to a given target, treating consecutive identical numbers as a single “clump.”
How it works:
It finds the sum of consecutive identical numbers starting at start.
Recursively, it either includes the clump in the sum or skips it.
Returns true if any combination reaches the target, false otherwise.

TRA-5103: Recursion-2 >=The solution for groupSumClump Task
