- Huria/Sum Double – Return Sum or Double the Sum.txt
The objective of this task is to implement the sumDouble(int a, int b) method, which returns the sum of two integers. If the two integers are different, the method should simply return their sum (a + b). However, if the two integers are equal, it should return double their sum (2 * (a + b)). This exercise helps reinforce the use of conditional statements and basic arithmetic operations in programming.
> TRA514:Sum Double

- Huria/Diff 21 – Return Absolute Difference or Double If Over 21.txt
The task is to implement the method `diff21(int n)`, which calculates the difference between the input number `n` and 21. If `n` is less than or equal to 21, the method should return the simple difference `21 - n`. However, if `n` is greater than 21, it should return double the difference `2 * (n - 21)`. This exercise helps practice conditional logic and working with absolute value concepts in programming.
> TRA516:Diff 21

- Huria/MixStart – Check if String Starts with Any Char Followed by ix.txt
I implement a method mixStart(String str) that returns true if the string has "ix" starting at index 1 (i.e., any character followed by "ix", like "mix", "pix", "9ix"); otherwise, return false.
Ask ChatGPT
> TRA537: MixStart

- Huria/DelDel – Remove del Starting at Index 1 if Present.txt
I implement a method delDel(String str) that returns a new string where the substring "del" is removed if it appears starting at index 1. If "del" is not at index 1, return the original string unchanged.
> TRA536: DelDel

- Huria/Lone Teen – Check if Exactly One Number is a Teen (13 to 19).txt
I implement a method loneTeen(int a, int b) that returns true if exactly one of the two numbers is in the teen range (13 to 19 inclusive); otherwise, it returns false.
> TRA535:Lone Teen

- Huria/EndUp – Uppercase Last 3 Characters of a String.txt
I implement a method endUp(String str) that returns a new string with the last 3 characters converted to uppercase. If the string has fewer than 3 characters, convert the entire string to uppercase.
> TRA546: EndUp Add

- Huria/StringE – Check if String Contains Between 1 and 3 'e' Characters.txt
I implement a method stringE(String str) that returns true if the input string contains between 1 and 3 occurrences of the character 'e' (inclusive); otherwise, return false.
> TRA543: StringE add

- Huria/Max1020 – Return Larger Value in Range 10..20 or 0 if None.txt
I implement a method max1020(int a, int b) that returns the larger of the two values if it falls within the range 10 to 20 inclusive. If both values are in the range, return the larger one; if neither is in the range, return 0.
> TRA542: Max1020

- Huria/In3050 – Check if Both Numbers Are in 30..40 or 40..50 Range.txt
I implement a method in3050(int a, int b) that returns true if both numbers are in the range 30–40 inclusive, or both are in the range 40–50 inclusive; otherwise, return false.
> TRA541: In3050

- Huria/Close10 – Return the Number Closest to 10 or 0 if Tie.txt
I implement a method close10(int a, int b) that returns the number closest to 10. If both numbers are equally close, return 0. Use Math.abs() to compute the absolute difference from 10.
> TRA540: Close10

- Huria/In1020 – Check if Either Number is in Range 10 to 20.txt
I implement a method in1020(int a, int b) that returns true if either a or b is between 10 and 20, inclusive; otherwise, it returns false.
> TRA531:In1020

- Huria/Icy Hot – Check Temperatures for Opposite Extremes.txt
Implement a method icyHot(int temp1, int temp2) that returns true if one of the temperatures is below 0 and the other is above 100; otherwise, it returns false.
> TRA530:Icy Hot

- Huria/StartHi – Check if String Starts with hi.txt
I implement a method startHi(String str) that returns true if the string starts with "hi"; otherwise, it returns false.
> TRA529:StartHi

- Huria/Front Back – Swap First and Last Characters of a String.txt
Implement a method front back(String str) that returns a new string with the first and last characters swapped. If the string has a length of 1 or less, return it unchanged.
> TRA524:Front Back

- Huria/Not String – Add not  Prefix Unless Already Present.txt
Implement a method notString(String str) that returns the original string with "not " added to the front, unless the string already starts with "not", in which case it is returned unchanged. Use .equals() for comparisons to practice string manipulation and conditionals.
> TRA522: NotString

- Huria/PosNeg – Return True Based on Value Signs and a Flag.txt
Implement a method posNeg(int a, int b, boolean negative) that returns true if one number is negative and the other is positive, unless the negative flag is true—in which case it returns true only if both numbers are negative. This practices using conditional logic with boolean flags.
> TRA519:PosNeg

- Huria/Makes 10 – Check if Either Value or Their Sum is 10.txt
Implement a method makes10(int a, int b) that returns true if either number is 10 or if their sum is 10; otherwise, it returns false. This helps practice logical OR conditions and basic arithmetic.
> TRA518: Makes 10

- from_Kaltham/Diff21.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
**The first description for first code:** 
I create a class call DeleteChar then I create method call missingchar
which return String and have two parameters that is str and n 
the method check if str not null and n is grater than 0 AND n is less than and equal to str.length 
(it find the length of str) (str.length is method from String) if the all condition true then 
converted str to stringBuilder (str2) so I can edit it because string is immutible we can't change
then I use method deleteCharAt(Index) from stringBuilder
so this method will delete char and the Index will be n and then save in str2 
then convert stringbuilder str2 to string (newStr)then return str
otherwise return "The String is Null"
**The second description for second code**:
I create a class called DeleteChar then I …
> TRA597: Missing Char – Remove Character at Given Index

- from_Kaltham/BackAround.txt
- from_Kaltham/Close10.txt
- from_Kaltham/DelDel.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/HasTeen.txt
- from_Kaltham/IcyHot.txt
- from_Kaltham/In1020.txt
- from_Kaltham/IntMax.txt
- from_Kaltham/LoneTeen.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MixStart.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/StartOz.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I created a class called CloseToTen.
In the method close10, I calculate how close each number a and b is to the number 10.
I use Math.abs(a - 10) to get the absolute difference between a and 10, and store it in aclose.
I do the same for b, storing the result in bclose.
Then:
If both values are equally close to 10 (aclose == bclose), I return 0.
If a is closer to 10 than b, I return a.
Otherwise, I return b.
> TRA806: Close10 – Return the Number Closest to 10 or 0 if Tie

- from_Kaltham/BackAround.txt
- from_Kaltham/Close10.txt
- from_Kaltham/DelDel.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/HasTeen.txt
- from_Kaltham/IcyHot.txt
- from_Kaltham/In1020.txt
- from_Kaltham/In3050.txt
- from_Kaltham/IntMax.txt
- from_Kaltham/LoneTeen.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MixStart.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/StartOz.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I created a class called CheckNumRange.
In the method in3050, I check whether both integers a and b fall within the same valid range.
There are two valid ranges:
From 30 to 40 (inclusive)
From 40 to 50 (inclusive)
The method returns true if:
Both a and b are in the 30–40 range, or
Both a and b are in the 40–50 range
> TRA807: In3050 – Check if Both Numbers Are in 30..40 or 40..50 Range

- from_Kaltham/BackAround.txt
- from_Kaltham/Close10.txt
- from_Kaltham/DelDel.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/HasTeen.txt
- from_Kaltham/IcyHot.txt
- from_Kaltham/In1020.txt
- from_Kaltham/In3050.txt
- from_Kaltham/IntMax.txt
- from_Kaltham/LoneTeen.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/Max1020.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MixStart.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/StartOz.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I created a class called NumMax1020.
In the method max1020, I want to return the larger value between a and b, but only if it's in the range 10 to 20 (inclusive).
If neither value is in the range, I return 0.
Here’s how it works:
I create a variable maxA:
If a is between 10 and 20 (inclusive), I assign a to maxA.
Otherwise, I assign 0 to maxA.
I create a variable maxB:
If b is between 10 and 20 (inclusive), I assign b to maxB.
Otherwise, I assign 0 to maxB.
I use Math.max(maxA, maxB) to get the larger value between the two (only if they were in the valid range).
If both are 0 (outside the range), it returns 0.
> TRA808: Max1020 – Return Larger Value in Range 10..20 or 0 if None

- from_Kaltham/BackAround.txt
- from_Kaltham/Close10.txt
- from_Kaltham/DelDel.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/EndUp.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/HasTeen.txt
- from_Kaltham/IcyHot.txt
- from_Kaltham/In1020.txt
- from_Kaltham/In3050.txt
- from_Kaltham/IntMax.txt
- from_Kaltham/LastDigit.txt
- from_Kaltham/LoneTeen.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/Max1020.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MixStart.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/StartOz.txt
- from_Kaltham/StringE.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I created a class called EndUp. In the method endUp:
I first check if the string length is greater than 3.
If true:
I take the last 3 characters using substring(str.length() - 3).
I convert them to uppercase using .toUpperCase().
I take the first part of the string (excluding the last 3 characters) using substring(0, str.length() - 3).
I return the front part + the uppercase back part.
If the string length is 3 or less:
I return the entire string in uppercase using .toUpperCase().
> TRA821: EndUp – Uppercase Last 3 Characters of a String

- from_Kaltham/BackAround.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I create a class called BackAroundString then I create method called backAround
which return String and have one parameter that is String (str)  
the method check if the lenght of str is not equal to 0 if contion true
then converte str to stringBilder(newStr) 
take the last index and save it in char (lastIndex)
then I used the method insert to add the char (lastIndex) in 0 index
and again insert char (lastIndex) in last index 
then convers (newStr)to (finalString)
then return finalString
otherwise return "The string is null"
I created a class called BackAroundString
In the method backAround, I first check if the string is not empty.
Then I convert the string to a char array named strToArray.
I create a new char array that is 2 characters longer than the original.
I store the last …
> TRA600: Back Around – Add Last Char to Front and Back of String

- from_Kaltham/BackAround.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I created a class called StartHiString.
In the method startHi, I check two conditions using a logical AND (&&):
First, I check if the string has at least 2 characters (str.length() >= 2).
If it does, I check if the first two characters of the string are equal to "hi" using substring(0, 2).equals("hi").
If both conditions are true, the method returns true. Otherwise, it returns false.
This method is used to check if a given string starts with "hi".
> TRA797: StartHi – Check if String Starts with "hi"

- from_Kaltham/BackAround.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/IcyHot.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I created a class called CheckTemperatures.
In the method icyHot, I check if one temperature is icy (less than 0) and the other is hot (greater than 100).
I use two conditions combined with the logical OR ||:
(temp1 < 0 && temp2 > 100): checks if temp1 is icy and temp2 is hot.
(temp1 > 0 && temp2 < 100): this part checks if both values are normal (not icy or hot), which doesn’t match the "icy-hot" idea.
So this second condition is logically incorrect based on the problem definition.
The method should only return true when:
One of the temperatures is less than 0 and
The other is greater than 100.
> TRA798: Icy Hot – Check Temperatures for Opposite Extremes

- from_Kaltham/BackAround.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/IcyHot.txt
- from_Kaltham/In1020.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I created a class called CheckNum.
In the method in1020, I check whether either of the two numbers a or b falls within the range 10 to 20 (inclusive).
I use two conditions combined with the logical OR ||:
The first checks if a is greater than or equal to 10 and less than or equal to 20.
The second checks the same range for b.
If either condition is true, the method returns true; otherwise, it returns false.
> TRA799: In1020 – Check if Either Number is in Range 10 to 20

- from_Kaltham/BackAround.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/HasTeen.txt
- from_Kaltham/IcyHot.txt
- from_Kaltham/In1020.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I created a class called CheckTeenNumber.
In the method hasTeen, I check if any of the three input numbers (a, b, or c) is within the "teen" range (from 13 to 19 inclusive).
I use three separate conditions combined with the logical OR ||:
The first checks if a is between 13 and 19.
The second checks if b is between 13 and 19.
The third checks if c is between 13 and 19.
If at least one of these conditions is true, the method returns true; otherwise, it returns false.
> TRA800: Has Teen – Check if Any Number is a Teen (13 to 19)

- from_Kaltham/BackAround.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/HasTeen.txt
- from_Kaltham/IcyHot.txt
- from_Kaltham/In1020.txt
- from_Kaltham/LoneTeen.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I created a class called CheckLoneTeen.
In the method loneTeen, I check whether exactly one of the two input numbers (a or b) is in the teen range (13 to 19 inclusive).
I use the bitwise XOR operator (^), which works like logical XOR in this case because the expressions return boolean values.
If both a and b are teens → returns false
If neither a nor b is a teen → returns false
If only one of them is a teen → returns true
So, the method returns true only when one of the two numbers is a teen, and the other is not.
> TRA801: Lone Teen – Check if Exactly One Number is a Teen (13 to 19)

- from_Kaltham/BackAround.txt
- from_Kaltham/DelDel.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/HasTeen.txt
- from_Kaltham/IcyHot.txt
- from_Kaltham/In1020.txt
- from_Kaltham/LoneTeen.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MixStart.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I created a class called MixString.
In the method mixStart, I first check if the string length is greater than 3 (which means it has at least 4 characters).
Then I check if the substring starting at index 1 and ending at index 3 is equal to "ix".
If this condition is true, I return true. Otherwise, I return false.
This method checks if the string starts with any character followed by "ix", like "mix", "pix", etc.
> TRA803: MixStart – Check if String Starts with Any Char Followed by "ix"

- from_Kaltham/BackAround.txt
- from_Kaltham/DelDel.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/HasTeen.txt
- from_Kaltham/IcyHot.txt
- from_Kaltham/In1020.txt
- from_Kaltham/LoneTeen.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MixStart.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/StartOz.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I created a class called OzStart.
In the method startOz, I check if the string starts with 'o' at index 0, and/or 'z' at index 1.
Here’s what happens step-by-step:
If the string is empty (length == 0), I return "The string is empty".
If the first two characters are exactly "oz", I return "oz".
If the second character (index 1) is 'z', I return "z".
If the first character (index 0) is 'o', I return "o".
If none of those conditions are met, I return "There is no (o) or (z)".
> TRA804: StartOz – Return "o" if First Char is 'o' and "z" if Second Char is 'z'

- from_Kaltham/BackAround.txt
- from_Kaltham/Close10.txt
- from_Kaltham/DelDel.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/HasTeen.txt
- from_Kaltham/IcyHot.txt
- from_Kaltham/In1020.txt
- from_Kaltham/In3050.txt
- from_Kaltham/IntMax.txt
- from_Kaltham/LoneTeen.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/Max1020.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MixStart.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/StartOz.txt
- from_Kaltham/StringE.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
//The first description for first code:
I created a class called StringE. and the method stringE:
I create a counter c to count how many times the letter 'e' appears.
I loop over each character in the string using a for loop:
I use str.charAt(i) to get the character at position i.
If the character is 'e', I increase the counter c by 1.
After the loop, I check if c is between 1 and 3 (inclusive).
If it is, I return true. Otherwise, I return false.
//The second description for second code:
I created a class called StringE. and the method stringE:
I convert the original string to a character array using toCharArray(), and store it in strToArray.
I create a counter c to count how many 'e' characters are in the array.
I use a for loop to go through each character in strToArray.
If the …
> TRA819: StringE – Check if String Contains Between 1 and 3 'e' Characters

- from_Kaltham/BackAround.txt
- from_Kaltham/Close10.txt
- from_Kaltham/DelDel.txt
- from_Kaltham/Diff21.txt
- from_Kaltham/Front22.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/HasTeen.txt
- from_Kaltham/IcyHot.txt
- from_Kaltham/In1020.txt
- from_Kaltham/In3050.txt
- from_Kaltham/IntMax.txt
- from_Kaltham/LastDigit.txt
- from_Kaltham/LoneTeen.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/Max1020.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MixStart.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/Or35.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/StartHi.txt
- from_Kaltham/StartOz.txt
- from_Kaltham/StringE.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
I created a class called LastDigit. In the method lastDigit:
I check if both numbers a and b are greater than 0.
If true, I calculate the last digit of each number using the modulo operator %:
lastDigitA = a % 10
lastDigitB = b % 10
I compare the two last digits:
If they are equal, I return true.
If not equal or one of them is not positive, I return false.
> TRA820: Last Digit – Check if Two Numbers Have the Same Last Digit

- from_Kaltham/Diff21.txt
- from_Kaltham/Front3.txt
- from_Kaltham/FrontBack.txt
- from_Kaltham/Makes10.txt
- from_Kaltham/MissingChar.txt
- from_Kaltham/MonkeyTrouble.txt
- from_Kaltham/NearHundred.txt
- from_Kaltham/NotString.txt
- from_Kaltham/PosNeg.txt
- from_Kaltham/Sleep-In-Logic.txt
- from_Kaltham/Sum.txt
- from_Kaltham/parrotTrouble.txt
//The first description for first code:
I create a class call StrFront then I create method call front3
which return String and have one parameter that is String (str)  
the method check if the lenght of str is grater than or equal to 3 if contion true
then take the slicing of str from 0 to 2 and save it in string str1
then return str1+str1+str1 
else return str
//The second description for second code:
I create a class call StrFront then I create method call front3
which return String and have one parameter that is String (str)  
the method will converted str to char Array (strToArray)
then new variable to save first 3 index to it that is char(chars)
the new int j=0 for new Index chars
then if the lenght of str is grater than or equal to 3
make for loop to save the index in from …
> TRA599: Front3 – Repeat the Front of a String Three Times

- Close10.txt
The close10 method compares two integer values to determine which one is closer to the number 10. It calculates the absolute difference between each number and 10 using Math.abs(). If one number is closer, that number is returned; if both are equally close, the method returns 0. This method practices using absolute values and conditional logic to compare distances.
> TRA877:Close10 – Return the Number Closest to 10 or 0 if Tie

- In3050.txt
The in3050 method checks if two integer values both fall within the same specified range: either 30 to 40 inclusive or 40 to 50 inclusive. It uses compound boolean conditions to verify if both numbers lie within one of these two ranges. This method reinforces the practice of combining range checks and logical operators to validate multiple conditions simultaneously.
> TRA868; In3050 – Check if Both Numbers Are in 30..40 or 40..50 Range

- StringE.txt
The stringE method counts how many times the character 'e' appears in a given string and returns true if the count is between 1 and 3 inclusive. If the count is zero or more than three, it returns false. This method practices character counting within a string and applying conditional logic based on the count.
> TRA880:Add STRING E

- EndUp.txt
The endUp method returns a new string where the last three characters are converted to uppercase. If the input string has fewer than three characters, it converts the entire string to uppercase. This method combines string slicing to separate the last three characters from the rest of the string and then applies uppercase conversion to just that part, demonstrating practical string manipulation techniques.
> TRA882:EndUp – Uppercase Last 3 Characters of a String

- EveryNth.txt
The everyNth method constructs a new string by starting from the first character (index 0) of the input string and then selecting every nth character thereafter. By looping through the string with increments of n, the method efficiently extracts characters at the desired positions, practicing controlled string iteration and indexing.
> TRA883: EveryNth – Build String Using Every Nth 

- StartOz.txt
The startOz method constructs a new string based on the first two characters of the input string. It includes the first character only if it is 'o' and includes the second character only if it is 'z'. The method first checks if the string length is at least 1 and 2 to safely access characters without errors. This approach practices conditional string building and character checks to selectively form a result.
> TRA875: StartOz – Return "o" if First Char is 'o' and "z" if Second Char is 'z'

- MixStart.txt
The mixStart method checks if the input string begins with any single character followed by the substring "ix". This means the string’s characters at index 1 and 2 should be "i" and "x" respectively, regardless of the first character. The method first verifies that the string length is at least 3 to avoid errors, then uses substring checking to confirm if str.substring(1, 3).equals("ix"). If so, it returns true; otherwise, false. This exercise practices flexible substring matching and boundary condition handling.
> TRA874:Add MixStart – Check if String Starts with Any Char Followed by "ix.txt

- Lone Teen.txt
The loneTeen method returns true if exactly one of the two given integers, a or b, falls within the teen range of 13 to 19 inclusive. This involves checking whether one is in the range while the other is not. To do this, each number is tested against the teen condition (x >= 13 && x <= 19), and then the result uses the exclusive OR (XOR) logic—true only when the two conditions are different. This task is a good exercise in applying exclusive conditions and boolean logic for control flow.
> TRA872:Lone Teen – Check if Exactly One Number is a Teen (13 to 19)

- In1020.txt
The in1020 method determines whether either of the two input integers, a or b, falls within the inclusive range of 10 to 20. This is done using a boolean condition that checks if a >= 10 && a <= 20 or b >= 10 && b <= 20. If either condition is true, the method returns true; otherwise, it returns false. This task is a great way to practice combining comparison operators and boolean logic for range validation.
> TRA870:In1020 – Check if Either Number is in Range 10 to 20

- Icy Hot.txt
The icyHot method checks two integer temperature values and returns true only if one of them is below 0 (icy) and the other is above 100 (hot). This is achieved using a compound boolean condition that evaluates whether temp1 < 0 && temp2 > 100 or temp2 < 0 && temp1 > 100. The method ensures that the extremes are opposite, practicing logical operators and conditional evaluation — a key concept in control flow and decision-making.
> TRA869: 🌡️Icy Hot – Check Temperatures for Opposite Extremes

- StartHi.txt
The startHi method checks whether the input string begins with the substring "hi". This is done using the startsWith() method, which efficiently determines if a string has the specified prefix. If the input string starts with "hi", the method returns true; otherwise, it returns false. This approach ensures a concise and reliable way to perform prefix checking, which is a common pattern in string manipulation and input validation tasks.
> TRA868:StartHi – Check if String Starts with "hi"

- Front3.txt
The front3 method creates a new string by repeating the "front" of the input string three times. The "front" is defined as the first 3 characters of the string, but if the string is shorter than 3 characters, the entire string is used instead. This is achieved by first extracting the front portion using substring(0, Math.min(3, str.length())), ensuring it handles short strings safely, and then concatenating that substring three times to form the final result. This solution emphasizes string slicing and repetition, matching the task’s goal.
> TRA862:  Front3 – Repeat the Front of a String Three Times

- Missing Char.txt
The `missingChar` method solves the task by using string slicing to remove the character at the specified index `n` from the input string. It does this by combining two parts of the string: the substring from the beginning up to (but not including) index `n`, and the substring from index `n + 1` to the end. This effectively skips over the character at position `n`, resulting in a new string with that character removed. The approach is efficient and leverages built-in string operations, ensuring the solution is concise, readable, and meets the problem constraints.
> TRA861: Missing Char – Remove Character at Given Index

- FrontBack.txt
Implement a method `frontBack(String str)` that returns a new string with the first and last characters swapped. If the string has a length of 1 or less, return it unchanged. This exercise helps practice string manipulation and handling edge cases. For example, `frontBack("code")` returns `"eodc"`, `frontBack("a")` returns `"a"`, and `frontBack("ab")` returns `"ba"`.
> TRA815:Front Back – Swap First and Last Characters of a String

- NearHundred.txt
Implement a method `nearHundred(int n)` that returns `true` if the number `n` is within 10 units of either 100 or 200. To determine this, use `Math.abs()` to calculate the absolute difference between `n` and 100, and between `n` and 200. Return `true` if either difference is less than or equal to 10; otherwise, return `false`. This exercise helps practice using `Math.abs()` and writing conditions based on numerical proximity. For example, `nearHundred(93)` and `nearHundred(90)` return `true`, while `nearHundred(89)` returns `false`.
> TRA813:Near Hundred – Check if Number is Within 10 of 100 or 200

- PosNeg.txt
Implement a method posNeg(int a, int b, boolean negative) that returns true based on the sign of the integers a and b, with behavior influenced by the negative flag. If negative is false, return true only if one value is negative and the other is positive. If negative is true, return true only if both values are negative. This task focuses on practicing conditional evaluation using boolean flags and sign checks. For example, posNeg(1, -1, false) returns true, posNeg(-1, 1, false) returns true, and posNeg(-4, -5, true) returns true.
> TRA: PosNeg – Return True Based on Value Signs and a Flag

- Diff 21.txt
Implement a method diff21(int n) that returns the absolute difference between the input number n and the number 21. If n is less than or equal to 21, return 21 - n. If n is greater than 21, return double the absolute difference, calculated as 2 * (n - 21). This task helps practice conditional logic and working with absolute differences. For example, diff21(19) returns 2, diff21(10) returns 11, and diff21(21) returns 0.
> TRA809: Diff 21 – Return Absolute Difference or Double If Over 21

- Parrot Trouble.txt
Implement a method `parrotTrouble(boolean talking, int hour)` that returns `true` if we are in trouble due to a talking parrot. We are in trouble if the parrot **is talking** (`talking == true`) **and** the current hour is **before 7** (`hour < 7`) or **after 20** (`hour > 20`). In all other cases, we are not in trouble, so the method should return `false`. This task is designed to help practice combining boolean logic with comparison operators. For example, `parrotTrouble(true, 6)` returns `true`, `parrotTrouble(true, 7)` returns `false`, and `parrotTrouble(false, 6)` returns `false`.
> TRA810:  Parrot Trouble – Check for Talking Parrot at Bad Hours

- Shaima/class Sleeping.txt
The sleepIn method determines whether we can sleep in based on two conditions: if it is not a weekday or if we are on vacation. We are allowed to sleep in if it is not a weekday we are on vacation. The method returns true when we can sleep in, and false otherwise.
> TRA505 :Sleep-In

- Shaima/class Summing.txt
The sumDouble method returns the sum of two numbers. But if the numbers are the same, it returns double their sum instead.
> TRA507 : Sum Double - Return Sum or Double the Sum

- Shaima/class Subtraction.txt
The diff21 method returns how far a number is from 21. If the number is over 21, it returns double that difference.
> TRA508: Diff 21 - Return Absolute Difference or Double If Over 21

- Shaima/class Number10.txt
The makes10 method returns true if either number is 10 or their sum is 10.
> TRA512: Makes 10 - Check if Either Value or Their Sum is 10

- Shaima/class PosNeg.txt
The posNeg method returns true if one number is positive and the other is negative, unless negative is true — then it returns true only if both numbers are negative.
> TRA515: PosNeg - Return True Based on Value Signs and a Flag

- Shaima/class NearHundred.txt
The nearHundred method returns true if the number is within 10 of 100 or 200. It uses Math.abs() to find the difference.
> TRA520 :Near Hundred - Check if Number is Within 10 of 100 or 200

- Shaima/class Front3.txt
The front3 method takes the first 3 letters of the string and repeats it 3 times.
> TRA551:Front3 - Repeat the Front of a String Three Times

- Shaima/class HasTeen.txt
The hasTeen method returns true if any of the numbers is between 13 and 19, inclusive.
> TRA772: Has Teen - Check if Any Number is a Teen (13 to 19)

- Shaima/classMixStart.txt
The mixStart method returns true if the string has "ix" starting at index 1, like in "mix" or "pix". Otherwise, it returns false.
> TRA562: MixStart - Check if String Starts with Any Char Followed by ix

- Shaima/classStartOz.txt
The startOz method checks the first two letters. It adds 'o' if the first letter is 'o' and 'z' if the second letter is 'z' to the result.
> TRA563: StartOz - Return 'o' if First Char is 'o' and 'z' if Second Char is 'z'

- Shaima/classIntMax.txt
The intMax method returns the largest of the three numbers.
> TRA565: IntMax - Return the Largest of Three Integers

- Shaima/class In3050.txt
The in3050 method returns true if both numbers are in 30–40 or both are in 40–50.
> TRA569: In3050 - Check if Both Numbers Are in 30..40 or 40..50 Range

- Shaima/class Max1020.txt
The max1020 method returns the bigger number between a and b that is between 10 and 20. If neither is in that range, it returns 0.
> TRA570: Max1020 - Return Larger Value in Range 10..20 or 0 if None

- Shaima/classEndup.txt
The endUp method makes the last 3 letters uppercase. If the string is shorter than 3, it makes the whole string uppercase.
> TRA573: EndUp - Uppercase Last 3 Characters of a String

- From_Maha/TRA-674.txt
Returns true if it's not a weekday or if on vacation, allowing you to sleep in.
>  Implement sleepIn

- From_Maha/TRA-674.txt
- From_Maha/TRA-675.txt
Returns the sum of two integers, or double their sum if the values are equal.
> Sum Double – Return Sum or Double the Sum

- Shaima/class StringE.txt
The stringE method returns true if the string has 1 to 3 'e' letters.
> TRA571: StringE - Check if String Contains Between 1 and 3 'e' Characters

- plag_test_tool/from_Haitham/TRA673.java
Implement a method everyNth(String str, int n) that returns a new string made of characters starting at index 0 and then every nth character thereafter.
with check of this:
n is guaranteed to be 1 or more.
The input string is non-empty.
> TRA673: EveryNth – Build String Using Every Nth Character

- plag_test_tool/from_Haitham/TRA753.java
Implement a method stringE(String str) that returns true if the string contains between 1 and 3 'e' characters (inclusive).
> TRA753: StringE – Check if String Contains Between 1 and 3 'e' Characters

- plag_test_tool/from_Haitham/TRA756.java
Implement a method endUp(String str) that returns a new string where the last 3 characters are converted to uppercase.
With make sure of that:
If the string length is less than 3, uppercase the whole string.
> TRA756: EndUp – Uppercase Last 3 Characters of a String

- plag_test_tool/from_Haitham/TRA755.java
Implement a method lastDigit(int a, int b) that returns true if the two non-negative integers have the same last digit.
By using the modulo operator % to get the last digit (number % 10).
> TRA755: Last Digit – Check if Two Numbers Have the Same Last Digit

- plag_test_tool/from_Haitham/TRA752.java
Implement a method in3050(int a, int b) that returns true if both numbers are:
In the range 30 to 40 (inclusive) or in the range 40 to 50 (inclusive).
> TRA752: In3050 – Check if Both Numbers Are in 30..40 or 40..50 Range

- plag_test_tool/from_Haitham/TRA751.java
Implement a method close10(int a, int b) that returns the value which is nearest to 10.
with make care of:
If both numbers are equally close to 10, return 0.
> TRA751: Close10 – Return the Number Closest to 10 or 0 if Tie

- plag_test_tool/from_Haitham/TRA749.java
Implement a method intMax(int a, int b, int c) that returns the largest of the three given integer values.
> TRA749: IntMax – Return the Largest of Three Integers

- plag_test_tool/from_Haitham/TRA735.java
Implement a method loneTeen(int a, int b) that returns true if exactly one of the two given numbers is in the teen range (13 to 19 inclusive).
> TRA735: Lone Teen – Check if Exactly One Number is a Teen (13 to 19)

- plag_test_tool/from_Haitham/TRA734.java
Implement a method hasTeen(int a, int b, int c) that returns true if one or more of the given numbers are in the teen range (13 to 19 inclusive).
> TRA734: Has Teen – Check if Any Number is a Teen (13 to 19)

- plag_test_tool/from_Haitham/TRA733.java
Implement a method in1020(int a, int b) that returns true if either a or b is within the range 10 to 20 (inclusive).
> TRA733: In1020 – Check if Either Number is in Range 10 to 20

- plag_test_tool/from_Haitham/TRA732.java
Implement a method icyHot(int temp1, int temp2) that returns true if one temperature is less than 0 and the other is greater than 100.
> TRA732: Icy Hot – Check Temperatures for Opposite Extremes

- plag_test_tool/from_Haitham/TRA731.java
Implement a method startHi(String str) that returns true if the given string starts with "hi", and false otherwise.
> TRA731: StartHi – Check if String Starts with "hi"

- plag_test_tool/from_Haitham/TRA695.java
Implement a method front3(String str) that returns a new string made of 3 copies of the front of the string.
note:
The front is defined as the first 3 characters of the string.
If the string length is less than 3, use the whole string as the front.
> TRA695: Front3 – Repeat the Front of a String Three Times

- plag_test_tool/from_Haitham/TRA694.java
Implement a method frontBack(String str) that returns a new string where the first and last characters have been swapped.
the code should aware about:
If the string length is 1 or less, return the string unchanged.
> TRA694: Front Back – Swap First and Last Characters of a String

- plag_test_tool/from_Haitham/TRA691.java
Implement a method nearHundred(int n) that returns true if the given number n is within 10 of either 100 or 200:
Return true if Math.abs(n - 100) <= 10 or Math.abs(n - 200) <= 10
> TRA691: Near Hundred – Check if Number is Within 10 of 100 or 200

- plag_test_tool/from_Haitham/TRA499.java
Implement a method makes10(int a, int b) that returns true if:
Either a is 10 or b is 10, or
The sum of a and b is 10
> TRA500: Makes 10 – Check if Either Value or Their Sum is 10

- plag_test_tool/from_Haitham/TRA478.java
The monkeyTrouble method returns true if both monkeys are smiling or neither of them is smiling, which means we're in trouble; otherwise, it returns false if only one monkey is smiling.
> TRA478: Monkey Trouble – Determine if We Are in Trouble

- From_Horiya_Albusaidi/CheckDigitValues.java
I created checkIfValueLessByTen method that return true if one of them is 10 or more less than one of the others.
> TRA-2639: Solving Logic-1 > lessBy10 Task

- From_Horiya_Albusaidi/CompareValues.java
I created checkEqualityOfValues that accept 3 int values, a b c and return their sum. However, if one of the values is the same as another of the values, it does not count towards the sum.
> TRA-2649: Solving Logic-2 > lonesum Task

- From_Maha/NonStart.java
Added nonStart method that returns both strings without their first characters concatenated.
> String1- NonStart file

- from_Huria/TwoFromIndexOrStart.java
The code returns a 2-character substring starting at the given index. If the index is out of range (too small or too close to the end), it safely returns the first 2 characters instead.
> TRA1962: Adding TwoChar -Safe Slice at Index Task

- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/NoTeenSum.java
- From_Manal/SpecialNumberChecker.java
Three int values, a b c, I returned their sum.
if any of the values is a teen -- in the range 13..19 inclusive -- then that value counts as 0, except 15 and 16 do not count as a teens. I Wrote a separate helper "public int fixTeen(int n) {"that takes in an int value and returns that value fixed for the teen rule.
> TRA-2643-NoTeenSum

- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/RoundSum.java
- From_Manal/SpecialNumberChecker.java
I rounded an int value up to the next multiple of 10 if its rightmost digit is 5 or more, so 15 rounds up to 20. Alternately, round down to the previous multiple of 10 if its rightmost digit is less than 5, so 12 rounds down to 10. Given 3 ints, a b c,
I returned the sum of their rounded values. To avoid code repetition, I wrote a separate helper "public int round10(int num) {" and call it 3 times
> TRA-2644-RoundSum

- From_Manal/ArraySumComparision.java
- From_Manal/CloseFar.java
- From_Manal/ConditionalSum.java
- From_Manal/SpecialNumberChecker.java
Three ints, a b c, return true if one of b or c is "close" (differing from a by at most 1), 
while the other is "far", differing from both other values by 2 or more.
> TRA-2645-CloseFar

- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
Two ints, a and b, return their sum. sums in the range 10..19 inclusive, are forbidden, so in that case just return 20.
> TRA-2440: SortaSum

- From_Manal/CloseFar.java
- From_Manal/SpecialNumberChecker.java
three ints, a b c, returned true if one of b or c is "close" (differing from a by at most 1), while the other is "far", differing from both other values by 2 or more.
> TRA- 2645: CloseFar

- From_Manal/NoTeenSum.java
- From_Manal/SpecialNumberChecker.java
Three int values, a b c, return their sum. 
if any of the values is a teen -- in the range 13..19 inclusive -- then that value counts as 0, except 15 and 16 do not count as a teens. I wrote a separate helper "public int fixTeen(int n) {"that takes in an int value and returns that value fixed for the teen rule. In this way, I a void repeating the teen code 3 times
> TRA-2643: NoTeenSum

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/Blackjack.java
- From_Manal/ConditionalSum.java
- From_Manal/SpecialNumberChecker.java
Two int values greater than 0, returned whichever value is nearest to 21 without going over. Return 0 if they both go over.
> TRA-2646-BlackJack

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/EvenlySpaced.java
- From_Manal/SpecialNumberChecker.java
Three ints, a b c, one of them is small, one is medium and one is large. 
Return true if the three values are evenly spaced, so the difference between small and medium is the same as the difference between medium and large.
> TRA-2647-EvenlySpaced

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/LuckySumCalculator.java
- From_Manal/SpecialNumberChecker.java
Three int values, a b c, return their sum. 
if one of the values is 13 then it does not count towards the sum and values to its right do not count.
> TRA-2642-LuckySum

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/SpecialNumberChecker.java
- From_Manal/SumLimit .java
Two non-negative ints, a and b, return their sum, so long as the sum has the same number of digits as a. If the sum has more digits than a, just return a without b.
> TRA-2609-SumLimit

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/LastDigit .java
- From_Manal/SpecialNumberChecker.java
True if two or more of them have the same rightmost digit. The ints are non-negative.
> TRA-2595-LastDigit

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/SpecialNumberChecker.java
- From_Manal/WithoutDoubles.java
If noDoubles is true, if the two dice show the same value, increment one die to the next value, wrapping around to 1 if its value was 6.
> TRA-2598-WithoutDoubles

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/LessByTen .java
- From_Manal/SpecialNumberChecker.java
Three ints, a b c, return true if one of them is 10 or more less than one of the others.
> TRA-2596-LessbyTen

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/LargestValueModFive.java
- From_Manal/SpecialNumberChecker.java
Two int values, return whichever value is larger.  if the two values have the same remainder when divided by 5, then the return the smaller value. However, in all cases, if the two values are the same, return 0
> TRA-2599-MaxMod5

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/GreenTicket.java
- From_Manal/SpecialNumberChecker.java
Agreen lottery ticket, with ints a, b, and c on it. If the numbers are all different from each other, the result is 0.
If all of the numbers are the same, the result is 20. 
If two of the numbers are the same, the result is 10.
> TRA-2603-GreenTicket

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/RedTicket.java
- From_Manal/SpecialNumberChecker.java
A red lottery ticket showing ints a, b, and c, each of which is 0, 1, or 2. If they are all the value 2, the result is 10. Otherwise if they are all the same, the result is 5. Otherwise so long as both b and c are different from a, the result is 1. Otherwise the result is 0.
> TRA-2601-redTicket

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/FizzBuzzFormatter.java
- From_Manal/SpecialNumberChecker.java
return the string form of the number followed by "!".
the int 6 yields "6!". Except if the number is divisible by 3 use "Fizz" instead of the number
if the number is divisible by 5 use "Buzz", and if divisible by both 3 and 5, use "FizzBuzz"
> TRA-2495-fizzString2

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/FizzBuzzWordProcessor.java
- From_Manal/SpecialNumberChecker.java
if the string starts with "f" return "Fizz". If the string ends with "b" return "Buzz". 
If both the "f" and "b" conditions are true, return "FizzBuzz". In all other cases, return the string unchanged
> TRA-2494-fizzString

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/SpecialNumberChecker.java
- From_Manal/TeaParty.java
Return the int outcome of the party encoded as 0=bad, 1=good, or 2=great. A party is good (1) if both tea and candy are at least 5. However, if either tea or candy is at least double the amount of the other one, the party is great (2). 
in all cases, if either tea or candy is less than 5, the party is always bad (0).
> TRA-2493-teaParty

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/SpecialNumberChecker.java
- From_Manal/TeenSumCalculator.java
Two ints, a and b, return their sum. 
"teen" values in the range 13..19 inclusive, are extra lucky. So, if either value is a teen (return 19)
> TRA-2491: teenSum

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/NearTenChecker.java
- From_Manal/SpecialNumberChecker.java
return true if num is within 2 of a multiple of 10
> TRA-2490-nearTen

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/DivisibleByThreeOrFiveNotBoth.java
- From_Manal/SpecialNumberChecker.java
Return true if the given non-negative number is a multiple of 3 or 5, but not both
> TRA-2482-old35

- .github/CODEOWNERS
- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/LoveSix.java
The number 6 is a truly great number. Given two int values, a and b, return true if either one is 6. Or if their sum or difference is 6.
> TRA-2478-love6

- From_Manal/ArraySumComparision.java
- From_Manal/ConditionalSum.java
- From_Manal/SpecialNumberChecker.java
- from_Huria/TwoFromIndexOrStart.java
Given a string and a non-negative int n, we'll say that the front of the string is the first 3 chars, or whatever is there if the string is less than length 3. Return n copies of the front
> TRA-1369: FrontTimes

- from_shatha/MakeTwo.java
Add function to create new length-2 array from elements of two arrays combined, filling from first then second array
> #TRA-2528-Array1-MakeTwo added

- from_shatha/MiddleWay.java
Add middleWay function to return middle elements of two arrays
> #TRA-2255-Array1-middleWay added

- from_Ghaida/WordEnds.java
-Uses String.startsWith(word, i) to detect each match.
-Appends:
-The character before the match (if any).
-The character after the match (if any).
-Skips over matched word segments using i += word.length() - 1.
> #TRA-1341: String-2: wordEnds added

- from_shatha/FixTwoThree.java
Add fix23 function to replace 3 with 0 if it follows a 2
> #TRA-2290-Array1-fix23 added

- From_Manal/EveryNth.txt
I Implemented a method everyNth(String str, int n) that returns a new string made of characters starting at index 0 and then every nth character thereafter.
n is guaranteed to be 1 or more. The input string is non-empty.
> TRA-851: EveryNth – Build String Using Every Nth Character

- from_Ghaida/BaseWithoutMatch.java
This PR introduces the method withoutRemoveMatch(String base, String remove) which removes all case-insensitive occurrences of a given remove substring from the input base string.
> #TRA-2030: String-3. withoutString added

- from_Ghaida/SumNumbers.java
This PR introduces the method sumNumbersInString(String str), which calculates the sum of all consecutive digit sequences (i.e., numbers) found within a given string.
> #TRA-2038: String-3. sumNumbers added

- from_Ghaida/LongestCharacterBlock.java
This pull request introduces the LongestCharacterBlock Java class, which includes the method findLongestBlock(String str). The method calculates the length of the largest block of consecutive identical characters in the input string.
> #TRA-2037: String-3. maxBlock added

- from_Ghaida/SymmetricEndsWithStarts.java
This pull request introduces a new class, SymmetricEndsWithStarts, which contains a method findMatchingEnds. This method identifies the longest prefix of a string that matches its corresponding suffix, enhancing the functionality of string manipulation utilities.
> #TRA-2036: String-3. mirrorEnds added

- from_Ghaida/StartSameEnds.java
This pull request introduces a new function, checkIfStartsameEnds, which checks if the start and end of a given string match and returns the longest matching substring. The function iterates through possible prefix lengths, starting from half the length of the string, to efficiently find the longest matching prefix and suffix.
> #TRA-2035: String-3. sameEnds added

- from_Ghaida/SumDigits.java
- from_Ghaida/sumDigits.java
This pull request introduces a new function, sumDigitsInString, which calculates the sum of all digit characters (0-9) present in a given string. The function iterates through each character of the input string, checks if it is a digit, and accumulates the total sum of these digits.
> #TRA-2034: String-3. sumDigits added

- from_Ghaida/EqualIsNotChecker.java
This pull request addresses issues in the EqualIsNotChecker class, specifically in the isEqualIsOrNot method, which checks if the number of occurrences of the substring "is" is equal to the number of occurrences of the substring "not" in a given string.
> #TRA-2031: String-3. equalIsNot added

- from_Ghaida/HappyGValidator.java
-The method iterates through each character in the string and checks if each 'g' is adjacent to another 'g'.
-If a 'g' is found that is not next to another 'g', the method returns false.
-If all 'g's are happy or if there are no 'g's in the string, the method returns true.
> #TRA-2032: String-3. gHappy added

- from_Ghaida/AdjustedSumCalculator.java
The method calculateAdjustedSum(int a, int b):
-Computes the sum of a and b.
-If the sum is between 10 and 19 inclusive, it returns 20.
-Otherwise, it returns the actual sum.
> #TRA-2292: Logic-1. sortaSum added

- from_Ghaida/SpeedTicketChecker.java
This pull request introduces the SpeedTicketChecker class, which contains logic to determine the level of a speeding ticket based on the driver's speed and whether it is their birthday.
-If it's the driver's birthday, they are allowed an extra 5 mph grace.
-Ticket levels:
-0: No ticket (speed ≤ 60)
-1: Small ticket (61–80)
-2: Big ticket (speed > 80)
> #TRA-2291: Logic-1. caughtSpeeding added

- from_Ghaida/SquirrelPlayChecker.java
This PR adds the SquirrelPlay class, which includes a method to decide if squirrels are likely to play based on the current temperature and whether it’s summer.
-Squirrels play if the temperature is between 60 and 90 degrees, inclusive.
-In summer, the upper limit is relaxed to 100 degrees.
> #TRA-2289: Logic-1. squirrelPlay added

- from_Ghaida/CalculateRedTicketValue.java
Implemented getRedTicketValue method to get the value of the red ticket.
-If all three integers are equal to 2, return 10.
-If all three integers are equal (but not necessarily 2), return 5.
-If the first and second integers are different from the third, return 1.
-In all other cases, return 0.
> #TRA-2318: Logic-1. redTicket added

- from_Ghaida/LastDigitChecker.java
This pull request introduces a new class LastDigitChecker that includes a method isLastDigitSame. This method checks if two or more of them have the same rightmost digit.
> #TRA-2311: Logic-1. lastDigit added

- from_shatha/MakeEnds.java
Add function to create new array with first and last elements of input array
>  #TRA-2496-Array1-makeEnds added

- from_Ghaida/NumbersOrderChecker.java
The checkOrder method evaluates whether three integers (a, b, c) are in increasing order. If the bOk flag is true, it allows b to be less than or equal to a.
> #TRA-2308: Logic-1. inOrder added

- from_Ghaida/SumOfTwoEqualsThird.java
This PR adds the SumOfTwoEqualsThird class, which includes a utility method isSumOfTwoEqualsThird(int a, int b, int c) to check if any two of the three integers sum up to the third.
> #TRA-2307: Logic-1. twoAsOne added

- from_shatha/SumThree.java
Add function to return the sum of all elements in a length-3 integer array
> #TRA-2488-Array1-Sum3 added

- from_Ghaida/NumberDivisibleChecker.java
This PR introduces the NumberDivisibleChecker class, which implements the formatFizzBuzzNumber(int n) method. This method formats integers according to a variation of the classic FizzBuzz problem.
-Returns "FizzBuzz!" if the number is divisible by both 3 and 5.
-Returns "Fizz!" if divisible by 3 only.
-Returns "Buzz!" if divisible by 5 only.
-Otherwise, returns the number followed by an exclamation mark (e.g., "1!").
> #TRA-2306: Logic-1. fizzString2 added

- from_shatha/SameFirstLast.java
check if array has length ≥ 1 and same first and last elements
> #TRA-2484-Array1-sameFirstLast added

- from_Ghaida/StringPrefixSuffixChecker.java
This PR adds the StringPrefixSuffixChecker class, which includes the convertToFizzBuzzString(String str) method. It returns a modified version of the input string based on specific character-based rules inspired by FizzBuzz logic.
-Returns "FizzBuzz" if the string starts with 'f' and ends with 'b'.
-Returns "Fizz" if it starts with 'f' only.
-Returns "Buzz" if it ends with 'b' only.
-Returns the original string if neither condition is met.
> #TRA-2305: Logic-1. fizzString added

- from_shatha/UnLuckyOne.java
Implement unlucky1 function to detect 'unlucky' 1-3 pairs at array boundaries
>  #TRA-2331-Array1-unLucky1 added

- from_shatha/MidThree.java
Implement midThree function to return middle three elements of odd-length array
>  #TRA-2328-Array1-midThree added

- from_shatha/MakeMiddle.java
Implement makeMiddle function to return middle two elements of even-length array
>  #TRA-2325-makeMiddle added

- from_shatha/NoTwoThree.java
Add no23 function to check for absence of 2 and 3 in array
> #tra 2259 Array1- no23

- from_Ghaida/CellAnswerLogic.java
This PR adds the CellAnswerLogic class with the method shouldAnswerCall(boolean isMorning, boolean isMom, boolean isAsleep). This method implements decision logic to determine whether to answer a phone call based on time of day, caller, and current state.
-If you are asleep, do not answer the call.
-If it's morning, answer only if it's your mom.
-If it's not morning and you're awake, answer the call.
> #TRA-2303: Logic-1. answerCell added

- from_shatha/ReverseThree.java
Implement reverse3 function to reverse a 3-element array
> #TRA-2237-Array1-revers3 added

- from_Ghaida/CloseToMultipleChecker.java
This PR adds the CloseToMultipleChecker class with the method isCloseToMultipleOfTen(int num). This method checks if a number is "close" to a multiple of 10 by evaluating whether its remainder modulo 10 is less than or equal to 2, or greater than or equal to 8.
> #TRA-2301: Logic-1. nearTen added

- from_Ghaida/MultipleChecker.java
This PR introduces the MultipleChecker class with the method isExclusiveMultiple(int n) that determines if a number is a multiple of 3 or 5, but not both.
> #TRA-2299: Logic-1. old35 added

- from_Ghaida/MoreThanTwentyChecker.java
This PR introduces the MoreThanTwentyChecker class with the method isOffsetByOneOrTwo(int n) that checks whether the input integer n has a remainder of 1 or 2 when divided by 20.
> #TRA-2298: Logic-1. more20 added

- from_Ghaida/UniqueSum.java
This PR introduces a utility method calculateUniqueSum(int a, int b, int c) in the UniqueSum class. The method returns the sum of three integers, excluding any values that are duplicated among the inputs.
> #TRA-2628: Logic-2 loneSum added

- from_Kaltham/ExtractAndSumNumbers.java
I made a class called ExtractAndSumNumbers and a method called calculateSumOfNumbers that takes a string.
This method finds all the numbers in the string (even multi-digit numbers) and adds them together.
How it works:
It starts with a total sum of 0.
It goes through each character in the string:
If the character is a digit, it adds it to a temporary currentNumber.
If it’s not a digit, it checks if currentNumber has something in it:
If yes, it turns it into an integer, adds it to the sum, and clears currentNumber.
After the loop, if there’s still a number stored, it adds it to the sum.
Finally, it returns the total sum of all numbers found in the string.
> TRA-2660: String-3 >=The solution for sumNumbers Task

- from_Kaltham/LongestBlockCalculator.java
I made a class called LongestBlockCalculator and a method called findLongestRepeatedCharLength that takes a string.
This method finds the longest block of the same character in the string and returns how many times it repeats in a row.
How it works:
If the string is empty, it returns 0.
It starts counting from the first character.
It checks each character with the next one:
If they are the same, it increases the count.
If they are different, it compares the count with the longest block found so far and saves the bigger number. Then it resets the count to 1.
After the loop, it checks one last time in case the longest block was at the end.
It returns the length of the longest block found.
> TRA-2659: String-3 >=The solution for maxBlock Task

- from_Kaltham/MirrorEndsFinder.java
I created a class called MirrorEndsFinder and a method called  extractMirrorEnds that takes a string.
The method finds the matching characters at the start and end of the string — like a mirror.
How it works:
Loop from the start of the string (index i).
For each position i, compare the character at the start (string.charAt(i)) with the character at the end (string.charAt(string.length() - 1 - i)).
If they are the same, add it to result.
If they are different, stop the loop immediately.
Return whatever result contains.
> TRA-2658: String-3 >=The solution for mirrorEnds Task

- From_Horiya_Albusaidi/CountDigits.java
I created countNumberOfSevenDigits method that return the count of the occurrences of 7 as a digit,
> TRA-2574: Solving Recursion-1 > count7 Task

- from_Kaltham/DigitSumCalculator.java
I created a class called DigitSumCalculator, and a method called sumOfDigitsInString that takes a string str.
The method calculates the sum of all digit characters found in the string.
How it works:
It goes through each character in the string.
If the character is a digit (0-9), it converts it to its numeric value.
It adds this numeric value to a running total.
After checking all characters, it returns the total sum.
> TRA-2656: String-3 >=The solution for sumDigits Task

- from_Kaltham/TripleCounter.java
I created a class called TripleCounter and a method called countTripleSequences that takes a string.
The method counts how many times a character repeats three times in a row in the string.
How it works:
It starts with a count of 0.
It loops through the string, stopping 2 characters before the end to avoid errors.
At each position, it checks if the current character and the next two characters are the same.
If yes, it increases the count.
Finally, it returns the total count of such triple sequences found in the string.
> TRA-2654: String-3 >=The solution for countTriple Task

- from_Kaltham/GChecker.java
I created a class called GChecker, and a method called isGHasNeighborG that takes a string str.
The method checks if every 'g' character in the string has another 'g' immediately next to it, either before or after.
How it works:
It goes through each character in the string.
When it finds a 'g', it checks if there is another 'g' right before or right after it.
If any 'g' does not have a neighbor 'g', the method returns false.
If all 'g' characters have neighbors, it returns true.
> TRA-2653: String-3 >=The solution for gHappy Task

- from_Kaltham/WordEndingChecker.java
I created a class called WordEndingChecker, and a method called countWordsEndingWithYOrZ that takes a string str.
The method counts how many words in the string end with the letter 'y' or 'z'.
How it works:
It converts the whole string to lowercase to make checking easier.
Then it loops through each character in the string.
When it finds a 'y' or 'z', it checks if this letter is at the end of the string or if the next character is not a letter (like space or punctuation).
If yes, it means a word ends here, so it increases the count.
At the end, it returns how many words ended with 'y' or 'z'.
> TRA-2650: String-3 >= The solution for countYZ Task

- from_Kaltham/WordNeighbors.java
I made a class called WordNeighbors. It has a method called getCharsAroundWord that takes two strings, str and word.
This method looks in str to find the word word. When it finds word, it takes the character before the word and the character after the word and adds them to a new string.
How it works:
First, it checks if str has word inside.
Then, it goes through str to find all places where word is.
For each place, if there is a character before the word, it adds that character to the result.
Also, if there is a character after the word, it adds that too.
At the end, it returns all these collected characters as one string.
> TRA-2526: String-2 >=The solution for wordEnds Task

- From_Horiya_Albusaidi/TriangleBlocks.java
I created getNumberOfBlocks that return the total number of blocks in such a triangle with the given number of rows.
> TRA-2561: Solving Recursion-1 > triangle Task

- From_Horiya_Albusaidi/CountingBunnyEars.java
I created numberOfEars method that  Recursively return the number of "ears" in the bunny line 1, 2, ... n
> TRA-2560: Solving Recursion-1 > bunnyEars2 Task

- from_Kaltham/RemoveStarsAndNeighbors.java
I created a class called RemoveStarsAndNeighbors, and a method called removeStarsWithNeighbors that takes a string str.
The method removes every '*' character from the string and also removes the characters immediately before and after each '*'.
How it works:
It loops through each character in the string.
For each character that is not '*', it checks if the characters before and after it are also not '*'.
If both neighbors are not '*' (or the character is at the start or end of the string), it keeps the character.
If the character is adjacent to a '*', it skips it.
It builds a new string with only the characters that are not stars and not neighbors of stars.
Returns the resulting string.
> TRA-2524: String-2 >=The solution for  starOut Task

- from_Kaltham/ZipZapCleaner.java
I created a class called ZipZapCleaner, and a method called removeCharBetweenZAndP that takes a string str.
The method removes any character that appears exactly between a 'z' and a 'p' in the string.
How it works:
It first checks if the string length is less than 3; if yes, it returns the string as is (because it can’t have a 'z' and 'p' with a character between).
It uses a StringBuilder to modify the string easily.
It loops through the string, stopping 2 characters before the end.
If it finds a 'z' at position i and a 'p' at position i+2, it deletes the character at position i+1.
Finally, it returns the modified string.
> TRA-2523: String-2 >=The solution for zipZap Task

- from_Kaltham/FindBetweenSandwish.java
I created a class called FindBetweenSandwich, and a method called getBetweenSandwich that takes a string str.
The method finds the substring that is between the first and the last occurrence of the word "bread" in the string.
It searches the string to find the positions (indexes) of the first and last "bread".
It does this by checking every substring of length 5 for the word "bread".
It stores the index of the first "bread" found, and updates the index of the last "bread" found as it continues searching.
After finding both, if there are at least two "bread" occurrences (first and last are different), it returns the substring between them.
Otherwise, it returns an empty string "".
> TRA-2513: String-2 >=The solution for getSandwish Task

- from_Kaltham/RepeatSeparator.java
I created a class called RepeatSeparator, and a method called buildRepeatedString that takes three parameters: a string word, a string sep (separator), and an integer count.
The method builds a new string by repeating the word exactly count times, inserting the sep string between each repetition.
It loops count times.
In each i, it appends word to the result.
If it's not the last repetition, it appends the separator sep.
Finally, it returns the finalstring.
> TRA-2510: String-2 >=The solution for repeatSeparator Task

- From_Horiya_Albusaidi/FibonacciSequence.java
I created getFibonacci method that returns the nth fibonacci number, with n=0 representing the start of the sequence.
> TRA-2558: Solving Recursion-1 > fibonacci Task

- from_Kaltham/XYBalancedChecker.java
I created a class called XYBalancedChecker, and a method called isXYBalanced that takes a string str.
The method checks if the string has every 'x' in the string, there is a 'y' somewhere after it.
It loops backwards through the string.
If it finds a 'y', it sets foundY to true.
If it finds an 'x' and foundY is still false, it returns false because that 'x' has no 'y' after it.
If the loop finishes and find XY Balanced, the function returns true.
> TRA-2506: String-2 >=The solution for xyBalance Task

- from_Kaltham/RepeatPrefix.java
I created a class called RepeatPrefix, and a method called prefixStepRepeat that takes a string str and an integer n.
The method returns a string made by repeatedly adding prefixes of str, starting from length n down to 1.
If n is between 0 and the length of str, it loops from n down to 1.
In each step, it takes the first i characters from str and appends them to the result.
Finally, it returns the concatenated string.
> TRA-2509: String-2 >=The solution for repeatFront Task

- from_Kaltham/RepeatEnd.java
I created a class called RepeatEnd, and a method called repeatSuffix that takes two strings a and b.
The method returns a new string made by repeating the last n characters of str, n times.
It takes the last n characters from the string using substring.
Then it repeats that substring n times using a for loop.
Finally, it returns the repeated string.
> TRA-2508: String-2 =>The solution for repeatEnd Task

- from_Kaltham/CheckerEnd.java
I created a class called CheckerEnd, and a method called isEndsMatch that takes Two string a and b.
The method check if the end of a equal to end of b
first convert a and b string to Lowercase() 
if a length is grater than b length, if condition true, then check
if resultA.substring(resultA.length() - b.length()).equals(resultB.substring(0)), if condition true 
then return true 
if condition one false then, check 
if (resultB.substring(b.length() - a.length()).equals(resultA.substring(0))) if condition true 
then return true 
Otherwise return false
> TRA-2503: String-2 =>The solution for endOther Task

- from_Kaltham/CountCode.java
I created a class called CountCode, and a method called countCodePattern that takes a string str.
The method  count how many times a pattern like "code" appears, where (d) can be any character.
It loops through the string, checking 4-character.
At each position, it checks if the character is 'c', followed by 'o', any character, and then 'e'.
If the pattern matches, it increases the counter.
Finally, it returns the total count of "co-d-e" patterns.
> TRA-2502: String-2 =>The solution for  countCode Task

- from_Kaltham/CountWordHi.java
I created a class called CountWordHi, and a function called countWordHi that takes a string str.
function count how many times that Hi words appears in the string.
The function works as follows:
I create a for loop that loop in each  character
If the string length more that two or equal to Two and the first position of (i) it is (h) and the second position of (i+1) is (i)
so the counter will increase 
Finally, it returns the total count of "hi"
> TRA-2500: String-2 =>The solution for countHi Task

- from_Kaltham/DoubleChars.java
I created a class called DoubleChars, and a function called doubleEachChar that takes a string str.
The goal is to return a new string where each character in the original string is duplicated.
The function works as follows:
It loops through every character in the input string.
For each character, it appends it twice to a StringBuilder.
Finally, it returns the new string with all characters doubled.
> TRA-2499: String-2=> The solution for doubleChar Task

- from_Kaltham/StringTrimmer.java
- from_Kaltham/WithouEndTwo.java
I created a class called WithouEndTwo, and a function called withouEnd2 that takes a string str.
The function checks if the string has a length of 3 or more.
If so, it returns the string without the first and last characters using substring(1, str.length() - 1).
If the string is shorter than 3 characters, it returns an empty string.
> TRA-1265: String-1=>The Solution for withouEnd2 Task

- From_Manal/PrefixChecker.java
- from_Huria/TwoFromIndexOrStart.java
A String, considered the prefix string made of the first N chars of the string. Does that prefix string appear somewhere else in the string? I Assumed that the string is not empty and that N is in the range 1..str.length().
> TRA-2702: PrefixAgain

- from_Kaltham/ConCat.java
- from_Kaltham/StringJoiner.java
I created a class called ConCat, and a function called conCat that takes two strings a and b.
The function concatenates the two strings with one exception:
If the last character of a is the same as the first character of b, it removes the duplicate character from the end of a before concatenating.
If either string is empty, it returns the non-empty one.
If both are empty, it returns an empty string.
> TRA-1275: String-1=>The Solution for ConCat Task

- from_Kaltham/DeFront.java
I created a class called DeFront, and a function called deFront that takes a string str.
The function modifies the first two characters of the string based on the following rules:
If the first two characters are "ab", it returns the original string.
If only the first character is 'a', it keeps it and removes the second character.
If only the second character is 'b', it keeps it and removes the first character.
If neither of the first two characters is 'a' or 'b', it removes both.
If the string has fewer than 2 characters, it returns the string as is.
> TRA-1285: String-1=>The Solution for DeFront Task

- from_Kaltham/RightTwo.java
I created a class called RightTwo, and a function called right2 that takes a string str.
The function checks if the string length is 2 or less; if so, it returns the string unchanged.
Otherwise, it moves the last two characters to the front by taking a substring of the last two characters and appending the rest of the string (excluding the last two).
This effectively rotates the last two characters to the front of the string.
> TRA-1263: String-1=>The Solution for RightTwo Task

- from_Kaltham/ExtraEnd.java
I created a class called ExtraEnd, and a function called extraEnd that takes a string.
If the string has 2 characters or less, the function simply returns the original string repeated 3 times.
Otherwise, it extracts the last two characters using substring, then returns them repeated 3 times.
> TRA-1255: String-1: The solution for ExtraEnd Task

- from_Kaltham/MidThree.java
I created a class called MidThree, and a function called midThree that takes an integer array nums
(with an odd length of at least 3).
The function returns a new array containing the middle three elements of nums.
It calculates the middle index as nums.length / 2, then selects the element before, at, and after that index.
The result is an array of the central three values.
> TRA-2130:Array-1=>The solution for midThree Task

- from_Kaltham/SwapEnds.java
I created a class called SwapEnds, and a function called swapEnds that takes an integer array nums.
The function swaps the first and last elements of the array.
It stores the first element in a temporary variable, assigns the last element to the first position, and then assigns the stored value to the last position.
Finally, it returns the modified array.
> TRA-1983: Array-1=>The solution for swapEnds Task

- From_Horiya_Albusaidi/ShareMapValue.java
I created modifyTheMabValue method that Modify and return the given map as follows: if the key "a" has a value, set the key "b" to have that same value. In all cases remove the key "c", leaving the rest of the map unchanged.
> TRA-2207: Solving Map-1 > mapShare Task

- from_Kaltham/PlusTwo.java
I created a class called PlusTwo, and a function called newArrayFromFirstTwo that takes two integer arrays a and b, 
each of length 2.
The function returns a new array of length 4, which contains the first two elements from a followed by the first two 
elements from b.
It combines both arrays in order.
> TRA-1982: Array-1=>The solution for plusTwo Task

- from_Kaltham/StartOne.java
I created a class called StartOne, and a function called startOne that takes two integer arrays a and b.
The function checks whether each array has at least one element, and if the first element is equal to 1.
It uses a counter:
If a[0] == 1, it increments the counter.
If b[0] == 1, it increments the counter.
Finally, it returns the total count (which can be 0, 1, or 2).
> TRA-1979: Array-1=>The solution for start1 Task

- From_Manal/StarRemover.java
- from_Huria/TwoFromIndexOrStart.java
Returned a version of the given string, where for every star (*) in the string the star and the chars immediately to its left and right are gone. So "ab*cd" yields "ad" and "ab**cd" also yields "ad"
> TRA-2704: StarOut

- from_Kaltham/HasDouble.java
I created a class called HasDouble, and a function called DoubleTwoThree that takes an integer array nums.
The function checks if the array has exactly two elements and whether both are the same and equal to 2 or 3.
If nums has length 2 and both elements are 2, it returns true.
If nums has length 2 and both elements are 3, it returns true.
> TRA-1977: Array-1=>The solution for double23 Task

- from_Kaltham/MakeLast.java
I created a class called MakeLast, and a function called makeLast that takes an integer array nums.
The function creates a new array that is twice as long as the original.
All elements in the new array are set to 0 by default, except the last element, which is set to the last element of nums.
It then returns the new array.
> TRA-1976: Array-1=>The solution for makeLast Task

- from_Kaltham/ExcludeTwoThree.java
I created a class called ExcludeTwoThree, and a function called noTwoThree that takes an integer array nums (assumed to be of length 2).
The function checks if neither of the two elements is 2 or 3.
If both elements are not 2 and not 3, it returns true.
> TRA-1975: Array-1=>The solution for no23 Task

- from_Kaltham/MakeEnds.java
I created a class called MakeEnds, and a function called makeEnds that takes an integer array nums.
The function returns a new array containing only the first and last elements of the input array.
It creates a new array of length 2 with nums[0] and nums[nums.length - 1].
> TRA-1973: Array-1=>The solution for MakeEnds Task

- from_Kaltham/MaxEndThree.java
I created a class called MaxEndThree, and a function called maxEnd3 that takes an integer array nums of length 3.
The function compares the first and last elements of the array.
It then returns a new array of length 3 where all elements are set to the larger of the first or last element.
This ensures the array is filled with the maximum of the two end values.
> TRA-1970: Array-1=>The Solution for MaxEnd3 Task

- from_Kaltham/SameFirstLast.java
I created a class called SameFirstLast, and a function called sameFirstLast that takes an array of integers nums.
The function checks if the array has at least one element and whether the first and last elements are equal.
If both conditions are true, it returns true; otherwise, it returns false.
> TRA-1964: Array-1=>The Solution for SameFirstLast Task

- from_Kaltham/StartWord.java
I created a class called StartWord, and a function called startWord that takes two strings: str and word.
The function checks if the beginning of str matches word except for the first character.
If str is shorter than word, it returns an empty string.
Then, it compares characters of word and str from index 1 onwards.
If all these characters match, it returns the substring of str that has the same length as word.
Otherwise, it returns an empty string.
> TRA-1287: String-1=>The Solution for StartWord Task

- from_Kaltham/SeeColor.java
I created a class called SeeColor, and a function called seeColor that takes a string str.
The function checks if the string starts with "red" or "blue".
If it starts with "red", it returns "red".
If it starts with "blue", it returns "blue".
If neither condition is met, it returns an empty string.
> TRA-1277: String-1=>The Solution for SeeColor Task

- from_Kaltham/EndsLy.java
I created a class called EndsLy, and a function called endsLy that takes a string str.
The function checks if the string has at least 2 characters and ends with the substring "ly".
It uses substring(str.length() - 2) to get the last two characters and compares them to "ly".
If the condition is met, it returns true; otherwise, it returns false.
> TRA-1267: String-1=>The Solution for endsLy Task

- from_Kaltham/LeftTwo.java
I created a class called LeftTwo, and a function called leftTwo that takes a string str.
The function checks if the string length is 2 or less; if so, it returns the string as is.
Otherwise, it moves the first two characters of the string to the end by concatenating the substring from index 2 to the end with the first two characters.
This effectively rotates the first two characters to the end of the string.
> TRA-1262: String-1: The Solution for leftTwo Task

- from_Kaltham/FirstTwo.java
I created a class called FirstTwo, and a function called firstTwo that takes a string.
If the string has two characters or fewer, it returns the original string.
Otherwise, it returns a substring containing only the first two characters using substring(0, 2).
> TRA-1256: String-1: The solution for FirstTwo Task

- from_Kaltham/FirstHalf.java
I created a class called FirstHalf, and a function called firstHalf that takes a string.
The function checks if the length of the string is even.
If it is, it returns the first half of the string using substring(0, str.length() / 2).
If the length is odd, it returns the original string unchanged.
> TRA-1258: String-1: The solution for FirstHalfTask

- from_Hawraa/RotateLeft3.java
- from_Hawraa/RotateLeftThree.java
Implemented a method rotateLeftThree in the RotateLeftThree class that takes an integer array of length 3 and returns a new array with elements rotated one position to the left.
> TRA-1587: Array-1: rotateLeft3 added

- from_Hawraa/MiddleWay.java
- Implemented "middleWay: method:
- The method initializes a new integer array middle of size 2.
- It assigns the second element (index 1) of array "a" to middle[0].
- It assigns the second element (index 1) of array "b" to middle[1].
- returns the middle array.
> TRA-1591: Array-1: MiddleWay added

- from_Hawraa/RejectTwoThree.java
- Implemented a method noTwoOrThree()
- The method checks if neither of the two elements is 2 or 3.
- Returns true if the array does not contain 2 or 3; otherwise, returns false.
> TRA-1594: Array-1: no23 added

- from_Hawraa/MakeLast.java
- Implemented the makeLast method.
- Created a new integer array with double the length of the input array.
- Assigned the last element of the new array to be the last element of the original array.
- All other elements in the new array default to 0.
> TRA-1595: Array-1: makeLast added

- from_Hawraa/CheckTwoThree.java
- Implemented the method hasTwoOrThreeTwice to check if an integer array of length 0, 1, or 2 contains two occurrences of 2 or two occurrences of 3.
- The method:
- Returns true if the array length is exactly 2 and both elements are 2 or both are 3.
- Returns false for arrays of length 0, 1, or any other combination.
> TRA-1597: Array-1: double23 added

- from_Hawraa/FixTwoThree.java
- Implemented the method FixTwoThree()
- The method checks for any occurrence of the number 2 immediately followed by 3 in the array.
- If such a pattern is found, the 3 is replaced with 0.
- Returns the modified array after applying the rule.
> TRA-1598: Array-1: fix23 added

- from_Hawraa/StartOne.java
- Implemented the method startOne that accepts two integer arrays, a and b, of any length.
- The method checks the first element of each array to see if it is 1.
- Returns the count of how many arrays start with the number 1.
> TRA-1599: Array-1: start1 added

- from_Hawraa/BiggerTwo.java
- Implemented the method biggerTwo which takes two integer arrays a and b.
- Calculates the sum of elements in each array.
- Returns the array with the larger sum.
- In case of a tie, returns array a as specified.
> TRA-1600: Array-1: biggerTwo added

- from_Hawraa/MakeMiddle.java
- Implemented the method makeMiddle that accepts an integer array of even length
- The method extracts the middle two elements from the original array.
- Returns a new array of length 2 containing these middle elements.
> TRA-1601: Array-1: makeMiddle added

- from_Hawraa/PlusTwo.java
Implemented plusTwoArray to combine two int arrays of length two into a new array of length four, containing all elements in order.
> TRA-1603: Array-1: plusTwo added

- from_Hawraa/MidThree.java
Implemented midThree to return a new array of 3 elements from the middle of an odd-length int array.
> TRA-1606: Array-1: midThree added

- from_Huria/TwoFromIndexOrStart.java
> #tra 1057 array123

- from_Hawraa/MakeTwo.java
Implemented makeTwoElement to return a new array of length 2 by taking elements from array a followed by elements from array b as needed. The method ensures at least two elements are included, handling cases where a may have 0, 1, or 2+ elements.
> TRA-1612: Array-1: make2 added

- from_Hawraa/FirstElement.java
Implemented firstElement to return a new array containing the first element of each input array a and b, if present. Handles cases where either or both arrays may be empty.
> TRA-1613: Array-1: front11 added

- from_Hawraa/DoubleChar.java
- Implemented method doubleChar().
- The method takes a string input and returns a new string where each character from the original string is duplicated consecutively.
> TRA-2327-String-2: doubleChar added

- from_Hawraa/CatDog.java
- Implemented a method called CountCatDog inside the CatDog class.
- The method scans the input string and counts how many times the words "cat" and "dog" appear.
- It compares both counts and returns true if they are equal, otherwise false.
> TRA-2332: String-2: catDog added

- from_Hawraa/CountCode.java
- Created a method called countCoXeWords in the CountCode class.
- This method counts how many times the pattern "co_e" appears in the input string, where:
- The pattern starts with "co",
- Is followed by any single character, and
- Ends with "e".
> TRA-2334: String-2: countCode added

- from_Hawraa/EndOther.java
- Implemented a method oneEndsWithOther in the EndOther class. And This method checks if either input string appears at the end of the other, without considering case sensitivity.
> TRA-2346: String-2: endOther added

- from_Hawraa/MixString.java
I created a method mixString that combines two strings by alternating their characters and appends any leftover characters from the longer string at the end.
> TRA-2357: String-2: mixString added

- from_Hawraa/RepeatFront.java
I created a method repeatFront that builds a string by taking the first n characters of the input string, then the first n-1, and so on down to 1 character.  I used a loop that counts down from n to 1 and appended the corresponding prefix of the string in each iteration using StringBuilder for efficiency.
> TRA-2363: String-2: repeatFront added

- from_Hawraa/RepeatSeparator.java
I created a method repeatWithSeparator that builds a string by repeating a given word count time, inserting a separator between each repetition except after the last one, using a loop and StringBuilder.
> TRA-2366: String-2: repeatSeparator added

- from_Hawraa/SameStarChar.java
- I implemented starsHaveEqualSides() that returns true if for every "*" in the string, if there are chars both immediately before and after the star, they are the same.
> TRA-2376: String-2: sameStarChar added

- from_Hawraa/OneTwo.java
- I implemented movingChar(), that processes a string in groups of 3 characters. For each group, the first character is moved to the end. This transformation is repeated for all complete 3-character groups in the string.
> TRA-2378: String-2: oneTwo added

- from_Hawraa/ZipZap.java
I implemented ignoreBetweenZP() to remove the middle character from 3-letter substrings that start with 'z' and end with 'p'
> TRA-2380: String-2: zipZap added

- from_Hawraa/StarOut.java
I Created deleteLeftRightStar() that removes every * and the characters immediately before and after it.
> TRA-2382: String-2: starOut added

- from_Hawraa/PlusOut.java
I Implemented replaceCharsExceptWord() that replaces all characters in a string with '+', except for occurrences of a given word which are left unchanged.
> TRA-2384: String-2: plusOut added

- .github/CODEOWNERS
> #tra 1684 last two

- From_Manal/XYZMiddleChecker.java
- from_Huria/TwoFromIndexOrStart.java
"xyz" appear in the middle of the string To define middle
The number of chars to the left and right of the "xyz" must differ by at most one.
> TRA-2802-String-2: XYZMiddle

- From_Maha/FashionRating.java
The method returns a rating (0, 1, or 2) for the outcome of a date based on two people's fashion scores.
If either score is low (≤2), the result is 0; if either is high (≥8), it's 2; otherwise.
> Add logic 1 datefashion

- From_Manal/RepeatFrontBuilder .java
- from_Huria/TwoFromIndexOrStart.java
This method builds a cascading prefix pattern from a given string. Starting with the first n characters, it appends progressively shorter prefixes—n-1, n-2, all the way down to 1—creating a layered effect. For example, "Chocolate" with n = 4 yields "ChocChoChC".
> TRA-2801-RepeatFront

- From_Manal/XYBalanceChecker .java
- from_Huria/TwoFromIndexOrStart.java
This method checks whether a string is "xy-balanced"—meaning every 'x' must be followed by at least one 'y' somewhere later in the string. A single 'y' can balance multiple 'x' characters, but if any 'x' appears after the last 'y', the string is considered unbalanced.
> TRA-2800-String-2: XYBalance

- From_Mulk/FirstTwo.java
I created a public class called FirstTwo and wrote a method named getFirstTwoChars that takes a String as input and returns a String. First, I checked if the input string is empty using str.isEmpty(), and if it was, I returned an empty string. Next, I checked if the string’s length was greater than or equal to 2, and if it was, I returned the first two characters using str.substring(0, 2). If the string had fewer than two characters but wasn’t empty, I returned the string itself.
> solution of FirstTwo task

- From_Mulk/WithoutEnd.java
I created a public class called WithoutEnd and defined a method named removeEdgeCharacters that takes a String as input and returns a String. Inside the method, I first checked if the string length was at least 2; if it was, I returned a new string without the first and last characters by using str.substring(1, str.length() - 1). If the string was shorter than 2 characters, I returned an empty string.
> solution of WithoutEnd task

- From_Mulk/LeftTwo.java
I created a public class called LeftTwo and defined a method named rotateLeftByTwo that takes a string as input and returns a string. Inside the method, I checked if the string had at least two characters; if it did, I rotated the string to the left by two positions by concatenating the substring from index 2 to the end with the first two characters using str.substring(2) + str.substring(0, 2). If the string was shorter than two characters, I returned an empty string.
> solution of LeftTwo task

- From_Mulk/RightTwo.java
I created a public class called RightTwo and defined a method named rotateRightByTwo that takes a string as input and returns a string. Inside the method, I checked if the string has at least two characters; if it does, I rotated the string to the right by two positions by taking the last two characters using str.substring(str.length() - 2) and placing them in front of the rest of the string, which I got with str.substring(0, str.length() - 2). If the string is shorter than two characters, I returned an empty string.
> solution of  RightTwo task

- From_Mulk/TheEnd.java
- From_Mulk/WithouEndTwo.java
- from_Huria/TwoFromIndexOrStart.java
I created a public class called TheEnd and defined a method named selectFirstOrLastChar that takes a string and a boolean value front as input and returns a string. Inside the method, I checked the value of front; if it was true, I returned the first character of the string using str.substring(0, 1). If it was false, I returned the last character using str.substring(str.length() - 1).
> solution of TheEnd task

- From_Mulk/WithouEndTwo.java
I created a public class called WithouEndTwo and defined a method named removeFirstAndLastChar that takes a string as input and returns a string. Inside the method, I first checked if the string was empty or had only one character using str.isEmpty() or str.length() <= 1; if either condition was true, I returned an empty string. Otherwise, I returned the string without its first and last characters by using str.substring(1, str.length() - 1).
> solution of WithouEndTwo task

- From_Mulk/EndsLy.java
I created a public class called EndsLy and defined a method named endsWithLy that takes a string as input and returns a boolean. Inside the method, I first checked if the string was empty, and if so, I returned false. Then, I checked if the string had at least two characters and if the last two characters were "ly" by using str.substring(str.length() - 2).equals("ly"); if both conditions were true, I returned true. Otherwise, I returned false.
> solution of EndsLy task

- From_Mulk/TwoChar.java
I created a public class called TwoChar and defined a method named getTwoCharsAtOrStart that takes a string and an integer index as input and returns a string. Inside the method, I checked if the index was within a valid range — specifically, greater than or equal to 0 and less than or equal to str.length() - 2. If it was, I returned two characters starting at that index using str.substring(index, index + 2). If the index was out of range, I returned the first two characters of the string using str.substring(0, 2).
> solution of  TwoChar task

- From_Mulk/HasBad.java
I created a public class called HasBad and defined a method named hasBadAtStart that takes a string as input and returns a boolean. Inside the method, I checked if the string starts with the word "bad" at index 0 or at index 1. To do this, I first made sure the string was at least 3 characters long to safely check the first 3 characters, and used str.substring(0, 3).equals("bad"). I also checked if the string was at least 4 characters long to safely check from index 1 to 4 using str.substring(1, 4).equals("bad"). If either condition was true, I returned true; otherwise, I returned false.
> solution of HasBad task

- From_Mulk/AtFirst.java
I created a public class called AtFirst and defined a method named getFirstTwoCharsWithPadding that takes a string as input and returns a string. Inside the method, I first checked if the string was empty, and if it was, I returned "@@" as a placeholder. If the string had two or more characters, I returned the first two characters using str.substring(0, 2). If the string had only one character, I added an "@" to the end of it to make it two characters long and returned that result.
> solution of AtFirst task

- From_Mulk/LastTwo.java
I created a public class called LastTwo and defined a method named swapLastTwoChars that takes a string as input and returns a string. First, I checked if the string length was greater than 1, and if it was, I returned a new string with the last two characters swapped by combining the beginning of the string (excluding the last two characters) with the last character followed by the second-to-last character. If the string had one or zero characters, I simply returned it as-is.
> solution of LastTwo task

- From_Mulk/WithoutTwo.java
In the WithoutTwo class, a public method named withoutMatchingEdges is defined to process a string input, str. The method first checks if the string has a length of at least 2 and whether its first two characters match its last two characters. If both conditions are satisfied, it returns the substring starting from the third character. Additionally, if the string's length is exactly 2, it returns an empty string. If neither condition applies, the method simply returns the original string.
> solution of WithoutTwo task

- from_hanin/StringJoinHelper.java
- from_hanin/concat.txt
The concat Cleanly method joins two strings, a and b, into one. If both strings are non-empty and the last character of a matches the first character of b, it avoids duplicating that character by removing the first character from b before concatenation. If there's no overlap or either string is empty, it simply returns the two strings joined together. This method ensures smoother, cleaner string merging when the boundary characters are the same.
> TRA 1666: String-1 > conCat

- From_Maha/NumberChecker.java
eturns true if either input is 6, their sum is 6, or their absolute difference is 6.
> Add logic 1 love 6

- from_hanin/Last two.txt
- from_hanin/TwoCharShifter.java
The shiftLastTwo method returns a new string in which the last two characters of the input string are swapped. If the input string has fewer than two characters, it is returned unchanged. For strings of length two or more, the method preserves the beginning of the string up to the last two characters, then appends the last character followed by the second-to-last character, effectively flipping the last two characters while leaving the rest intact.
> TRA 1667: String-1 > last Two

- From_Mulk/StartWord.java
In this code, the startsLikeWord method inside the StartWord class checks whether the input string str starts with the same characters as the input word, except for the first character. If the length of word is less than or equal to str, and the substring of str from index 1 to the length of word matches the corresponding part of word (also from index 1), it returns the beginning of str up to the length of word; otherwise, it returns an empty string.
> solution of StartWord task

- From_Mulk/FirstLastSix.java
In this code, the checkSixAtEdges method in the FirstLastSix class checks whether the number 6 appears at the beginning or end of the input integer array nums. If the array has at least one element and either the first (nums[0]) or last (nums[nums.length - 1]) element is 6, it returns true; otherwise, it returns false.
> solution of FirstLastSix task

- From_Mulk/SameFirstLast.java
In this code, the equalFirstAndLastElement method in the SameFirstLast class checks if the first and last elements of the input integer array nums are the same. If the array has at least one element and the first element (nums[0]) equals the last element (nums[nums.length - 1]), it returns true; otherwise, it returns false.
> solution of SameFirstLast task

- From_Mulk/MakePi.java
In this code, the generatePiArray method in the MakePi class returns a new integer array containing the first three digits of pi: 3, 1, and 4.
> solution of MakePi task

- From_Mulk/SumThree.java
I created a public class called SumThree with a method named sumFirstThreeElements that takes an integer array as input. Inside the method, I included a condition to check if the array has at least three elements, but didn't implement any logic within that check. Regardless of the condition, the method returns the sum of the first three elements in the array, which may cause an error if the array has fewer than three elements.
> solution of SumThree task

- From_Mulk/ReverseThree.java
I created a class called ReverseThree, and inside it, I wrote a method named reverseThreeElementArray that takes an integer array. I added an if statement to check if the array has at least three elements, but I didn’t put anything inside it. Then, I returned a new array that reverses the order of the first three elements—putting the third one first, the second in the middle, and the first one last.
> solution of ReverseThree task

- From_Mulk/SumTwo.java
I created a class called SumTwo, and inside it, I wrote a method called sumFirstTwoNumbers that takes an integer array. First, I checked if the array is empty, and if it is, I return 0. Then, if the array has two or more elements, I return the sum of the first two numbers. After that, if the array has less than two elements (which means it has exactly one), I return the first element. There’s also another check if the array is empty again, but it doesn’t do anything. At the end, I return 0 just in case.
> solution of SumTwo task

- From_Mulk/MiddleWay.java
I made a class called MiddleWay, and inside it, I wrote a method called extractMiddleElements that takes two integer arrays, a and b. I added a check to see if both arrays have at least three elements, but I didn’t put anything inside the if block. Then, I returned a new array with the middle elements from each array — specifically, the element at index 1 from both a and b.
> solution of MiddleWay task

- From_Mulk/HasTwoThree.java
I created a class called HasTwoThree, and inside it, I wrote a method called checkForTwoOrThree that takes an integer array. I checked if the first or second element is either 2 or 3. If any of those is true, the method returns true; otherwise, it returns false.
> solution of  HasTwoThree task

- From_Mulk/MakeLast.java
I made a class called MakeLast, and inside it, I wrote a method called makeArrayWithLastElementAtEnd that takes an integer array. I checked if the array has at least one element. If it does, I created a new array twice as long as the original, set its last element to be the same as the last element of the input array, and returned this new array. If the input array is empty, I returned null.
> solution of MakeLast task

- From_Mulk/DoubleTwoThree.java
I made a class called DoubleTwoThree, and inside it, I wrote a method called hasDoubleTwoOrDoubleThree that takes an integer array. First, if the array is empty, it returns false. Then, if the array has only one element and that element is 2 or 3, it also returns false since there can’t be a double. Next, if the array has two or more elements, it checks if the first two elements are both 2’s or both 3’s, and returns true if so. Otherwise, it returns false.
> solution of DoubleTwoThree task

- From_Maha/AlarmClock.java
Returns the alarm time based on the day and vacation status.
Weekdays have an earlier alarm unless on vacation, weekends may be later or off.
> Add logic 1 alarmClock

- From_Maha/ArrayPairMaker.java
Generates a new array using the first two available elements from input arrays a and b.
>  Adding Array1-make2 file

- From_Mulk/StartOne.java
I created a class called StartOne, and inside it, I wrote a method named countStartsWithOne that takes two integer arrays, a and b. First, I checked if both arrays have at least one element and if their first elements are 1; if so, I return 2. Then, I checked if either array has a first element of 1 and returned 1 in that case. If neither array starts with 1, I return 0.
> solution of StartOne task

- From_Mulk/PlusTwo.java
I created a class called PlusTwo, and inside it, I wrote a method called mergeTwoPairs that takes two integer arrays, a and b. I checked if both arrays have exactly two elements. If they do, I created a new array that combines all four elements — both from a and b — and returned it. If either array doesn’t have two elements, I return an empty array.
> solution of PlusTwo task

- From_Mulk/MiddThree.java
I created a class called MiddThree, and inside it, I wrote a method called getCenterThreeElements that takes an integer array. I checked if the array has at least three elements. If it does, I calculated the middle index and used it to get the element before, the middle one, and the one after it. Then I returned those three elements as a new array. If the array is too short, I return an empty array.
> solution of MiddThree task

- From_Mulk/MaxTriple.java
I created a class called MaxTriple, and inside it, I wrote a method named maxAmongEndsAndMiddle that takes an integer array. I compared the first element, the middle element, and the last element to find which one is the biggest. If the first is bigger than both the middle and last, I return the first. If the middle is bigger than both the first and last, I return the middle. If the last is bigger than both the first and middle, I return the last. If none of those conditions are true (like a tie), I return 0.
> solution of MaxTriple task

- From_Mulk/FrontPiece.java
I created a class called FrontPiece, and inside it, I wrote a method named getFirstTwoElements that takes an integer array. If the array has two or more elements, I return a new array containing just the first two elements. Otherwise, I return the original array as it is.
> solution of FrontPiece task

- From_Mulk/UnluckyOne.java
I made a class called UnluckyOne, and inside it, I wrote a method called unluckyOneThreeAtStartOrEnd that takes an integer array. I checked if the array has at least two elements and looked for the pattern 1, 3. First, I checked if it appears at the start (index 0 and 1). Then I checked if it's at index 1 and 2. Finally, I checked if it shows up at the end (the last two elements). If any of those match, I return true; otherwise, I return false.
> solution of UnluckyOne task

- From_Mulk/MakeTwo.java
I created a class called MakeTwo, and inside it, I wrote a method called combineFirstTwoElements that takes two integer arrays, a and b. I checked the length of array a to decide how to form a new array of two elements. If a has 2 or 3 elements, I return the first two from a. If a has only 1 element, I return that one along with the first element from b. If a is empty, I return the first two elements from b. If none of these conditions match (just in case), I return an empty array.
> solution of MakeTwo task

- From_Mulk/CigarParty.java
I made a class called CigarParty, and inside it, I wrote a method called checkCigarPartyRules that takes the number of cigars and a boolean for whether it’s the weekend. If it’s the weekend and there are at least 40 cigars, it returns true. Otherwise, if it’s not the weekend, the number of cigars must be between 40 and 60 (inclusive) to return true. If neither condition is met, it returns false.
> Solution of CigarParty task

- From_Mulk/CaughtSpeeding.java
I made a class called CaughtSpeeding with a method checkSpeedingPenalty that takes a speed and a boolean isBirthday. First, if it’s the driver’s birthday, I subtract 5 from the speed to give some leeway. Then I check: if the speed is 81 or more, I return 2 (big ticket). If the speed is between 61 and 80 inclusive, I return 1 (small ticket). Otherwise, I return 0 (no ticket).
> Solution of CaughtSpeeding task

- From_Mulk/SortaSum.java
I created a class called SortaSum, and inside it, I wrote a method called calculateSortaSum that takes two integers, a and b. I added them together and stored the result in sum. If the sum is between 10 and 19 (inclusive), I return 20 instead. Otherwise, I just return the actual sum of a and b.
> Solution of SortaSum task

- From_Mulk/LoveSix.java
- from_Huria/TwoFromIndexOrStart.java
In this task I wrote a code to check the if (a) or (b) are equal to 6 or if their sum or difference is 6. so its true if one of is 6 also its true if their sum or difference is 6. else its false.
> Solution of LoveSix task

- From_Mulk/InOneToTen.java
- from_Huria/TwoFromIndexOrStart.java
in this task I wrote a code to find if the number are in range of one to ten which return true. Also it will return true if its outsidemode and if the number is less or equal to 1, or greater or equal to 10.
> Solution of InOneToTen task

- From_Mulk/SpecialEleven.java
- from_Huria/TwoFromIndexOrStart.java
In this task I  wrote a code to check the multiple of 11 .If a number is a multiple of 11 or if it is one more than a multiple of 11 then return true ,else return false.
> Solution of SpecialEleven task

- From_Mulk/TeenSum.java
- from_Huria/TwoFromIndexOrStart.java
In this task I wrote a code to check if a and b are in a teen value which is in a range 13....19 inclusive so if either value is a teen, that will return 19 also if both a and b are a teen return 19. Else return the sum of a and b (a+b).
> Solution of TeenSum task

- From_Horiya_Albusaidi/DivisibleNumber.java
I created stringBasedOnReminderValue method that accept one integer variable and return the string form of the number followed by "!". So the int 6 yields "6!". Except if the number is divisible by 3 use "Fizz" instead of the number, and if the number is divisible by 5 use "Buzz", and if divisible by both 3 and 5, use "FizzBuzz".
> TRA-2428: Solving Logic-1 > fizzString2 Task

- From_Horiya_Albusaidi/BlueLotteryTickets.java
I created checkBlueTicketsSumValues method that accept Three integer  (a,b,c) values and return  10 If any pair sums to exactly 10, . Otherwise if the ab sum is exactly 10 more than either bc or ac sums, the result is 5. Otherwise the result is 0.
> TRA-2427:Solving Logic-1 > blueTickets Task

- From_Horiya_Albusaidi/SumValues.java
I created checkSumRangeValue method that Given 2 ints, a and b, return their sum. However, sums in the range 10..19 inclusive, are forbidden, so in that case just return 20.
> TRA-2415:Solving Logic-1 > sortaSum Task

- From_Horiya_Albusaidi/GreatNumberChecker.java
I created method called checkNumberSix that  return true if either one is 6. Or if their sum or difference is 6.
> TRA-2401:Solving Logic-1 > love6 Task

- From_Horiya_Albusaidi/MapValueChecker.java
I created replaceMapValues method  that modify and return the map as follows: if the key "potato" has a value, set that as the value for the key "fries". If the key "salad" has a value, set that as the value for the key "spinach".
> TRA-2280: Solving Map-1 > topping3 Task

- From_Horiya_Albusaidi/ModifyMapValue.java
I created checkEqualityOfABValues method that Modify and return the given map as follows: if the keys "a" and "b" are both in the map and have equal values, remove them both.
> TRA-2281: Solving Map1> mapAB2 Task

- from_hanin/ArrayReplace.java
* The ArrayReplace class provides a method that checks for the pattern 2 followed by 3 in the first or second position of a three-element array.  The 3 is replaced with 0. The modified array is then returned.
> TRA 2677: Array-1 > fix23

- from_hanin/ArrayCounter.java
This method simply checks if each of the two input arrays starts with the number 1, and returns a count (0–2) of how many do.
> TRA 2678: Array-1 > Start1

- from_hanin/SumBiggerTwo.java
* The SumBiggerTwo class provides a method to compare two integer arrays (assumed to be of length 2)and return the array with the greater sum of its elements. If both arrays have equal sums, return the a
> TRA 2679:Array-1 > biggerTwo

- from_hanin/ArrayExtractor.java
The Array Joiner class provides a method to create a new array by combining (joined ) the first two elements second array  two elements given arrays. The result is a 4-element array.
> TRA-2681: Array-1 > plusTwo

- from_hanin/ArraySwapper.java
The Array Swapper class provides a method to swap the first and last elements of an integer array. The swap place, and the modified array is returned.
> TRA 2682:Array-1 > swapEnds

- from_hanin/ArrayMaxFinder.java
The class to  Returns the maximum value among the first, middle, and last elements , of the input array. Assumes the array has an odd length of at least 1.
> Tra 2684: Array-1 > maxTriple

- from_hanin/ArrayMiddleExtractor.java
* The Array Middle Extractor class provides a method to extract the middle three elements from an integer array. It assumes the input array has an odd length of at least 3.
> TRA- 2683: Array-1 > midThree

- from_hanin/ArrayFront.java
The ArrayFront class provides a method to find the first two elements of an integer array. If the array has  two elements, it returns the array as is.
> TRA- 2685:Array-1 > frontPiece

- from_hanin/RestaurantDate.java
This class evaluates the outcome of a potential restaurant date based on style scores (from 0 to 10) for both ; if either person has a score of 2 or less, the result is 0 (no), if either has a score of 8 or more, the result is 2 (yes), and in all other cases, the result is 1 (maybe).
> TRA- 2706: Logic-1 > dateFashion

- from_hanin/SquirrelPartyEvaluator.java
This class determines whether a squirrel party is successful based on the number of cigars and whether it's the weekend; on weekdays, the party is successful if there are between 40 and 60 cigars (inclusive), while on weekends, there is no upper limit as long as there are at least 40 cigars.
> TRA-2705: Logic-1 > cigarParty

- from_hanin/TwoElementSelector.java
This method creates a new array of length 2 by taking elements from the first array ` followed by elements from the second array b, to two elements in total, and returns the new array.
> TRA- 2687: Array-1 > make2

- from_hanin/DrivingSpeed.java
The `DrivingSpeed` class determines the severity of a speeding ticket based on a driver's speed and whether it is their birthday. If it is the driver's birthday, they receive an additional 5 mph allowance. The method calculates the adjusted speed by subtracting the birthday allowance (if applicable) and then categorizes the result: a speed of 60 mph or less results in no ticket (returns 0), a speed between 61 and 80 mph inclusive results in a small ticket (returns 1), and speeds above 80 mph result in a big ticket (returns 2).
> TRA- 2708: Logic-1 > caughtSpeeding

- from_hanin/SumCulator.java
The SumCulator class includes a method findSum that takes two integers, `a` and `b`, and computes their sum. However, if the resulting sum falls within the range of 10 to 19 (inclusive), the method overrides the actual sum and returns a fixed value of 20 instead.
> TRA-2709: Logic-1 > sortaSum

- from_hanin/CheckNumber.java
The CheckNumber class evaluates whether an integer `n` falls within a specific range, the method returns true if  n is between 1 and 10 inclusive.
> TRA- 2714:Logic-1 > in1To10

- from_hanin/numberSpecial.java
The numberSpecial class  This logic effectively defines "special" numbers as those that are either divisible by 11 or just one unit greater than such numbers.
> TRA- 2716: Logic-1 > specialEleven

- from_Ghaida/BlackJackScoreEvaluator.java
Implemented a static method calculateBlackJackScore(int a, int b) which:
-Returns 21 if either player has a perfect score.
-Returns the highest valid score under 21 if both are below 21.
-Returns 0 if both scores exceed 21 (bust).
-Returns the valid score if only one player is busted.
> #TRA-2633: Logic-2. blackjack added

- from_hanin/TeenSumChecker.java
The TeenSumChecker class that takes two integers, a and `b and returns their sum—unless either of the numbers is a "10"  If either a or b falls within the teen range, the method returns a fixed value of 19 instead of their actual sum.
> TRA 2732: Logic-1 > teenSum

- from_hanin/CallResponse.java
The `CallResponse` class  determines whether a call should be answered based on three conditions: whether it is morning (isMorning), whether the caller is mom (callerIsMom), and whether the person is asleep (isAsleep).
> TRA-2734:Logic-1 > answerCell

- from_hanin/PartyEvaluator.java
The `PartyEvaluator` the quality of a party based on the quantities of tea and candy available. If either the amount of tea or candy is less than 5, the party is considered bad, and the method returns 0. If one quantity is at least double the other, the party is deemed great, returning 2.the party is rated as good, returning 1.
> TRA 2736: Logic-1 > teaParty

- from_hanin/FizzStringChecker.java
The `FizzStringChecker` class takes a string `str` and returns a special response based on its starting and ending characters. If the string starts with the letter "f" and ends with the letter "b", the method returns `"FizzBuzz"`. If it only starts with "f", it returns `"Fizz"`. If it only ends with "b", it returns `"Buzz"`. If neither  returns the original string.
> TRA 2739:Logic-1 > fizzString

- from_hanin/FizzBuzzNumber.java
The `FizzBuzzNumber`  returns a special string based on the divisibility of the input integer `n`. If `n` is divisible by both 3 and 5 (i.e., by 15), it returns `"FizzBuzz!"`. If it is divisible only by 3, it returns `"Fizz!"`. If it is divisible only by 5, it returns `"Buzz!"`.
> TRA 2748:Logic-1 > fizzString2

- from_hanin/DifferenceChecker.java
The `DifferenceChecker`takes three integers `a`, `b`, and `c`, and returns `true` if the absolute difference between any two of them is 10 or more. By using the `Math.abs` function to calculate differences between each pair,
> TRA- 2767:Logic-1 > lessBy10

- from_hanin/DigitComparator.java
The `DigitComparator` class checks whether at least two out of three given integers `a`, `b`, and `c` share the same last digit. It extracts the rightmost digit of each number using the modulus operator `% 10` and returns `true` Otherwise, it returns `false`.
> TRA-2766:Logic-1 > lastDigit

- from_hanin/OrderChecker.java
The `OrderChecker` class  determines if three integers `a`, `b`, and `c` are in a specific increasing order,the method only checks if `c` is greater than `b` it requires that both `b` is greater than `a` and `c` is greater than `b` for the method to return `true`. This method provides flexible ordering logic depending on the value of `bOk`.
> TRA -2753:Logic-1 > inOrder

- from_hanin/SumChecker.java
The `SumChecker` class takes three integers `a`, `b`, and `c`, and returns `true` if any one of these numbers is equal to the sum of the other two.
> TRA 2751:Logic-1 > twoAsOne

- from_hanin/MaxModCalculator.java
The `MaxModCalculator` class compares two integers `a` and `b` with special rules. If the numbers are equal, it returns 0. If `a` and `b` have the same remainder when divided by 5, it returns the smaller of the two numbers. Otherwise, it returns the larger number.
> TRA 2769:Logic-1 > maxMod5

- from_Ghaida/EvenSpacingChecker.java
This pull request introduces the EvenSpacingChecker class, which provides a static method areEvenlySpaced(int a, int b, int c) to determine if three integers are evenly spaced (i.e., the difference between the numbers is consistent regardless of their order).
> #TRA-2634: Logic-2. evenlySpaced added

- From_Manal/WordEnds .java
This method returns a string made of characters that appear immediately before and after each occurrence of a given non-empty word in a larger string. It skips cases where no adjacent character exists and allows characters to be included twice if they’re between two word occurrences
> TRA-2824: WordEnds

- from_hanin/TicketEvaluator.java
The `TicketEvaluator` evaluates three integer inputs `a`, `b`, and `c` according to specific rules. If all three values are 2, it returns 10. If all three are the same but not all 2, it returns 5. If both `b` and `c` are different from `a`, it returns 1. In all other cases, it returns 0.
> TRA-2770:Logic-1 > RedTicket

- From_Manal/SandwichMaker.java
This method returns the substring found between the first and last occurrence of the word "bread" in the input string. If fewer than two "bread" segments are found, it returns an empty string
> TRA-2822: GetSandwich

- from_hanin/BlueTicketEvaluator.java
The `blueTicket` function takes three integers `a`, `b`, and `c` from a lottery ticket and evaluates the sums of the three possible : `ab`, `bc`, and `ac`. If any of these pair sums is exactly 10, the function returns **10**. If the sum of `ab` is exactly 10 more than either `bc` or `ac`, the function returns **5**. If neither condition is met, the result is **0**.
> TRA-2772 : Logic-1 > blueTicket

- from_hanin/DigitMatcher.java
The `TicketEvaluator` class   evaluates three integer inputs `a`, `b`, and `c` . If all three values are 2, it returns 10. If all three are the same but not all 2s, it returns 5. If both `b` and `c` are different from `a`, it returns 1. In all other cases, it returns 0.
> TRA- 2773: Logic-1 > shareDigit

- from_hanin/TwoCharBuilder.java
- from_hanin/last chars.txt
The lastChars method returns a two-character string composed of the first character of string a and the last character of string b. If either string is empty, an "@" symbol is used as a placeholder for the missing character. If both strings are empty, the method returns "@@". This logic ensures safe string operations and consistent 2-character output, even when dealing with empty input strings.
> TRA 1665: String-1 > lastChars

- from_hanin/SumLimiter.java
The `SumLimiter` class  calculates the sum of two integers `a` and `b`.If the number of digits in the sum is the same as in `a`, it returns the sum. Otherwise, it returns the original value of `a
> Tra 2774:Logic-1 > sumLimit

- From_Manal/CatDogCounter.java
This method checks whether the strings "cat" and "dog" appear the same number of times in the given input string. It returns true if their counts match, and false otherwise
> TRA-2812: CatDog

- From_Manal/StringMixer.java
This method combines two input strings by alternating their characters—first from a, then from b, continuing in order. If one string is longer, its remaining characters are appended at the end of the result
> TRA-2816; MixString

- from_Ghaida/ChocolateMaker.java
This pull request introduces the ChocolateMaker class with a utility method calculateBarsNeeded(int small, int big, int goal) that determines the number of small chocolate bars (1kg each) needed to reach a specific chocolate goal (in kg), given a number of small and big bars (5kg each). If the goal cannot be met with the available bars, the method returns -1.
> #TRA-2635: Logic-2. makeChocolate added

- from_hanin/ArrayLeftRotator.java
The ArrayLeftRotator class performs a 3-element integer array. It returns a new array where the second and third elements are shifted left, and the first element moves to the last position.
> Tra 2667: Array-1 > rotateLeft3

- from_hanin/ArraySumCalculator.java
This Java class that calculates and returns the sum of all elements in  array, length 3.  using a loop, accumulates the sum, and returns the total.
> Tra 2666: Array-1 > sum3

- from_hanin/MaxEdgeThree.java
The MaxEdgeThree class defines  that takes a 3-element array and returns a new array where all values are replaced with the larger of the first or last element. If both are equal, the original array is returned unchanged. This is useful for normalizing array values based on edge elements.
> Tra 2669 :Array-1 > maxEnd3

- from_hanin/FirstTwoSumCalculator.java
The FirstTwoSumCalculator class  that computes the sum of the first two elements in an integer array. If the array has only one element, it returns that single element, and if the array is empty, it returns 0. This method ensures safe access without causing index errors, regardless of array length.
> Tra 2670:Array-1 > sum2

- from_hanin/MiddleInTwoArray.java
The  class includes that takes two integer arrays of length 3 and returns a new array containing their middle elements (i.e., the second element from each).
> Tra 2671:Array-1 > middleWay

- from_hanin/ArrayProcessor.java
* The ArrayProcessor class contains a method that generates a new array, which is double  the length of the input array. All elements in the new array and to be the same as the last element of the original input array.
> Tra 2675: Array-1 > makeLast

- from_hanin/CheckerTwoOrThree.java
This Java class, defines a that checks whether the number 2 or 3 appears in the first two elements of a given integer array. The method returns `true` if either nums[0] or nums[1]is equal to 2 or 3; otherwise, it returns false.
> Tra 2673:Array-1 > has23

- from_Ghaida/SameFirstLastElement.java
This pull request introduces a utility method isSameFirstLastElement that checks whether the first and last elements in an integer array are the same. This method includes a safety check for empty arrays and returns a boolean accordingly.
> #TRA-2858: Array-1. sameFirstLast added

- from_Hawraa/DateFashion.java
Implemented getTableValue()  to decide table outcome at a restaurant: returns 0 if either person’s style is ≤2, 2 if either is ≥8 (unless the low style rule applies), and 1 otherwise
> TRA-2808: Logic-1: dateFashion added

- from_Hawraa/CaughtSpeeding.java
Implemented checkSpeedingLevel() to calculate traffic ticket severity. Speed limits are relaxed by 5 on birthdays. Returns 0 for speeds ≤60, 1 for 61–80, and 2 for anything above 80.
> TRA-2810: Logic-1: caughtSpeeding added

- from_hanin/TeenSumHelper.java
The TeenSumHelper class  calculates the sum of three integers (a, b, and c), with a specific rule applied:If any of the input values are in the "teen" range (13 to 19 inclusive), they are treated as 0 except for the values 15 and 16, which are not considered teens and are counted normally.
> TRA-2778: Logic-2 (Add no teen Sum)

- from_Ghaida/PiPrinter.java
A piAsIntArray() method that returns the first three digits of Pi as an integer array: [3, 1, 4]
> #TRA-2859: Array-1. makePi added

- from_Hawraa/LoveSix.java
Implemented isSixRelated(int a, int b) to return true if either number is 6, or if their sum or absolute difference equals 6; otherwise returns false.
> TRA-2815: Logic-1: love6 added

- from_Hawraa/InOneToTen.java
Implemented checkRangeWithMode()  to check if a number falls within a range. Returns true if n is between 1 and 10 inclusive, or if outsideMode is true, returns true when n is ≤1 or ≥10
> TRA-2817: Logic-1: in1To10 added

- from_Hawraa/MoreTwenty.java
Added isMoreTwenty(int n) to return true if the given non-negative number is 1 or 2 more than a multiple of 20, otherwise false.
> TRA-2820: Logic-1: more20 added

- from_Hawraa/OldThirtyFive.java
Implemented isThreeOrFive(int n) to return true if the given non-negative number is a multiple of 3 or 5, but not both; returns false otherwise.
> TRA-2821: Logic-1: old35 added

- from_hanin/BlackjackHelper.java
The BlackjackHelper class  is two given numbers. It follows the standard blackjack rule: return the number closest to 21 without going over. If both numbers go over 21, return 0
> TRA- 2781:Logic-2 > blackjack

- from_Hawraa/LessTwenty.java
Implemented IsNearMultipleOfTwenty(int n) to return true if the given non-negative number is 1 or 2 less than a multiple of 20, otherwise returns false.
> TRA-2825: Logic-1: less20 added

- from_Hawraa/NearTen.java
Implemented  to return true if the given non-negative number is within 2 of a multiple of 10
> TRA-2826: Logic-1: nearTen added

- From_Maha/NumberCheck.java
eturns true if the number is either 1 or 2 more than a multiple of 20.
Uses modulo to check the remainder when dividing by 20
> Add MORE20 task file

- From_Maha/SpecialNumberChecker.java
Returns true if n is non-negative and either divisible by 11 or one more than a multiple of 11.
The check uses modulo 11 to determine special cases.
> Add special eleven task file

- From_Alharith/BobThere.java
Return true if the string contains a pattern like "bob," where the middle character can be any character.
> #TRA-2469: String2_ BobThere Done

- from_Ghaida/SumArrayElements.java
This pull request introduces a simple utility method, sumNumbers(int[] nums), which returns the sum of the first three elements of an integer array.
> #TRA-2861: Array-1. sum3 added

- from_Ghaida/RotateLeft.java
This pull request introduces a utility method moveFirstToEnd that performs a left rotation on an integer array of exactly three elements. The method moves the first element to the end of the array, effectively rotating the elements to the left.
> #TRA-2862: Array-1. rotateLeft3 added

- from_Ghaida/ReverseArrayElements.java
This pull request adds a utility method reverseElements that takes an array of integers and returns a new array with the elements in reverse order.
> #TRA-2863: Array-1. reverse3 added

- From_Maha/TeenRangeChecker.java
If both numbers are outside the teen range (13 to 19 inclusive), return their sum.
Otherwise (if at least one number is a teen), return 19.
> Adding teen sum file

- From_Maha/NearMultipleChecker.java
Checks if n is either 18 or 19 mod 20 — meaning it's 1 or 2 less than a multiple of 20.
Returns true only for those specific cases.
> Add less20 task file

- from_Ghaida/ReplaceAllWithMaxNumber.java
This pull request adds a utility method transformToMax that transforms a 3-element integer array by replacing all elements with the greater of the first and last values in the array.
> #TRA-2864: Array-1. maxEnd3 added

- from_Ghaida/SumFirstTwoElements.java
This pull request introduces a utility method sumFirstTwoElements(int[] nums) that returns the sum of the first two elements in an integer array.
-Returns 0 if the array is empty.
-Returns the only element if the array has a single item.
-Returns the sum of the first two elements otherwise
> #TRA-2865: Array-1. sum2 added

- from_Ghaida/ArrayMiddleExtractor.java
This pull request introduces the ArrayMiddleExtractor Java class with a utility method getMiddleElements. The method takes two integer arrays of length 3 and returns a new array containing their middle elements.
> #TRA-2866: Array-1. middleWay added

- from_shatha/MakePi.java
Add method to return the first three digits of Pi as an integer array
> #tra 2888-Array1- make pi

- from_shatha/RotateLeftThree.java
- from_shatha/rotateLeftThree.java
Implement left rotation for 3-element int array
> #tra 2889-Array1- rotate left3

- from_shatha/HasTwoThree.java
d function to check if array of length 2 contains a 2 or 3
> #tra 2942-Array1-has23

- from_shatha/DoubleTwoThree.java
Add function to check if array contains two 2s or two 3s
> #tra 2948-Array1-double23

- from_shatha/SwapEnds.java
Add function to swap first and last elements of an integer array
> #tra 2950-Array1-swap ends

- from_shatha/FrontPiece.java
Create function to return first up to two elements from an int array
> #tra 2951-Array1-front piece

- from_shatha/FrontFirstFirst.java
Add function to return array of first elements from two arrays, ignoring empty ones
> #tra 2952Array1-front11

- from_Ghaida/CheckHasTwoOrThree.java
This pull request adds the hasTwoOrThree method, which checks whether the input array (assumed to be of length 2) contains either the number 2 or 3.
> #TRA-2868: Array-1. has23 added

- From_Maha/NumberSumChecker.java
Checks whether the sum of any two integers equals the third and returns true if the condition is met; otherwise returns false.
> Add two as one file

- From_Maha/FizzStringEvaluator.java
Returns "Fizz", "Buzz", or "FizzBuzz" if the string starts with 'f', ends with 'b', or both; otherwise returns the original string.
> Adding fizzString file

- From_Maha/RoundingHelper.java
Added isNearMultipleOfTen method to check if a number is within 2 of any multiple of 10.
> Adding near ten file

- from_Ghaida/DoubleTwoOrThreeChecker.java
Implemented hasDoubleTwoOrThree that returns true if the array has length 2 and both elements are 2 or both are 3.
> #TRA-2871: Array-1. double23 added

- From_Maha/LastDigitChecker.java
Returns true if at least two of the three numbers have the same last digit; otherwise returns false.
> Add lastDigit file

- from_Ghaida/FixTwoThreeIssue.java
This PR introduces a fix to address the issue where a 3 immediately follows a 2 in an integer array. According to the requirements, any 3 that directly follows a 2 should be replaced with 0.
> #TRA-2872: Array-1. fix23 added

- from_Hawraa/FizzString.java
- Added method fizzBuzzByEnds(String str):
- Returns "FizzBuzz" if the string starts with 'f' and ends with 'b'.
- Returns "Fizz" if it starts with 'f' only.
- Returns "Buzz" if it ends with 'b' only.
- Returns the original string otherwise.
> TRA-2830: Logic-1: fizzString added

- from_Hawraa/FizzStringTwo.java
- Added method getFizzBuzzString(int n):
- Returns "FizzBuzz!" if n is divisible by both 3 and 5.
- Returns "Fizz!" if n is divisible by 3 only.
- Returns "Buzz!" if n is divisible by 5 only.
- Returns the number followed by an exclamation mark if none of the above conditions are met.
> TRA-2831: Logic-1: fizzString2 added

- from_Kaltham/EvenNumberCounter.java
I created a class called EvenNumberCounter and a method called countEvenNumbers that takes an array of integers.
The method counts how many numbers in the array are even.
How it works:
It starts with a counter set to 0.
It loops through each number in the array.
For each number, it checks if it is divisible by 2 (even).
If it is even, it adds 1 to the counter.
After checking all numbers, it returns the total count of even numbers.
> TRA-2994: Array-2 > = The solution for countEvens Task

- From_Maha/DifferenceChecker.java
Returns true if any two of the three numbers differ by 10 or more using absolute difference logic.
> Add lessBy10 file

- from_Ghaida/StartingWithOne.java
Implements isStartsWithOne method to count how many arrays start with the value 1.
> #TRA-2873: Array-1. start1 added

- from_Hawraa/LessByTen.java
Implemented the hasDifferenceOfTenOrMore method to check if any two of the three integers differ by 10 or more.
> TRA-2836: Logic-1: lessBy10 added

- from_Hawraa/MaxModFive.java
- Implemented maxUnlessSameModFive(int a, int b):
- Returns 0 if the two numbers are equal.
- If both numbers have the same remainder when divided by 5 (a % 5 == b % 5), returns the smaller of the two.
- Otherwise, returns the larger of the two.
> TRA-2838: Logic-1: maxMod5 added

- From_Maha/DiceRoller.java
Adds withoutDoubles method to sum two 6-sided dice rolls with an option to avoid doubles.
If noDoubles is true and both dice have the same value, the method increments one die (wrapping from 6 to 1) before summing.
> Adding withoutDouble file

- From_Maha/TicketEvaluate.java
Implements green ticket scoring logic based on whether values are all equal, all different, or partially equal.
> Add green Ticket file

- from_Ghaida/SwapEndWithFront.java
I implemented swapFirstIndexWithLast method to swap first index with last index.
> #TRA-2877: Array-1. swapEnds added

- from_Hawraa/GreenTicket.java
- Implemented the getGreenTicketResult method:
- Returns 20 if all three values are the same.
- Returns 10 if any two values are the same.
- Returns 0 if all values are different.
> TRA-2840: Logic-1: greenTicket added

- From_Maha/TicketEvaluation.java
Implements scoring logic based on the sum of value pairs; returns 10 if any pair sums to 10, otherwise evaluates score difference rules.
> Add blueTicket file

- from_Ghaida/MiddleThreeElementsExtractor.java
Implements getMiddleThree() method that returns the three middle elements of an array
-Uses array length division to find the center index
-Returns elements at positions [mid-1, mid, mid+1]
> #TRA-2878: Array-1. midThree added

- from_Kaltham/ConsecutiveTwoOrFourChecker.java
I created a class called ConsecutiveTwoOrFourChecker with a method named hasEitherConsecutiveTwoOrFour that takes an array of integers.
The method checks if the array has either two consecutive 2s or two consecutive 4s, but not both.
How it works:
It starts with two flags: hasConsecutiveTwos and hasConsecutiveFours, both false.
It goes through each number except the last one.
If it finds two 2s in a row, it sets hasConsecutiveTwos to true.
If it finds two 4s in a row, it sets hasConsecutiveFours to true.
After checking all numbers, it returns true if only one of the flags is true, otherwise false.
> TRA-2973: Array-2 > =The solution for either24 Task

- From_Maha/NumberOrderChecker.java
Returns true if numbers are in increasing order; allows skipping the first comparison when bOk is true.
> Adding inOrder file l

- from_Hawraa/BlueTicket.java
- Implemented getBlueTicketResult(int a, int b, int c): 
- Returns 10 if all values are 10
- Returns 5 if (ab == ac + 10) or (ab == bc + 10)
- Returns 0 in all other cases.
> TRA-2841: Logic-1: blueTicket added

- from_Kaltham/SevensChecker.java
I created a class called SevensChecker with a method named hasAdjacentOrOneApartSevens that takes an array of integers.
The method checks if the number 7 appears either next to another 7 or with exactly one number between them.
How it works:
For each number, it checks if it is 7 and the next number is also 7, or the number after next is 7.
If it finds such a case, it returns true.
If it finishes checking the array without finding it, it returns false.
> TRA-2975: Array-2 > =The solution for has77 Task

- from_Hawraa/ShareDigit.java
- Implemented hasCommonDigit(int a, int b):
- Extracts the tens and ones digits of both integers.
- Returns true if any digit in a matches any digit in b.
- Returns false otherwise.
> TRA-2843: Logic-1: shareDigit added

- from_Kaltham/OneTwoChecker.java
I created a class called OneTwoChecker with a method named containsOneFollowedByTwo that takes an array of integers.
The method checks if the array contains a 1 followed by a 2 somewhere.
How it works:
It starts with two flags: foundOne and foundTwo, both false.
It goes through each number except the last one.
If it finds a 1, it sets foundOne to true.
If the next number is 2, it sets foundTwo to true.
After checking all numbers, it returns true if both flags are true, otherwise false.
> TRA-2976: Array-2 > =The solution for has12 Task

- from_Kaltham/ThreeCounter.java
I created a class called ThreeCounter with a method named threeCountPassOne that takes an array of integers.
The method checks if the array contains exactly three 3s, counting each 3 only once and skipping the next number after each 3.
How it works:
It starts a counter threeCount at 0.
If it finds a 3, it increases the counter by 1 and skips the next number.
After checking all numbers, it returns true if the counter equals 3, otherwise false.
> TRA-2978: Array-2 > =The solution for  haveThree Task

- from_Kaltham/TwoChecker.java
I created a class called TwoChecker with a method named allTwosArePaired that takes an array of integers.
The method checks if every 2 in the array is next to another 2.
How it works:
If the number is 2, it checks if there is another 2 either before or after it.
If any 2 is not paired, it returns false.
If all 2s are paired, it returns true.
> TRA-2979: Array-2 > =The solution for twoTwo Task

- from_Hawraa/SumLimit.java
Implemented fixedLengthSum(), that returns the sum of two integers a and b only if the length of the sum (in digits) is equal to the length of a. If the sum’s digit length increases, the method returns a instead.
> TRA-2843: Logic-1: sumLimit added

- from_Kaltham/ArrayEndsChecker.java
I created a class called ArrayEndsChecker with a method named checkSameStartAndEnd that takes an array of integers and a number len.
The method checks if the first len numbers and the last len numbers of the array are the same.
How it works:
It goes through the first len numbers in the array.
For each position, it compares the number with the corresponding number at the end of the array.
If any pair does not match, it returns false.
If all pairs match, it returns true.
> TRA-2980: Array-2 > =The solution for sameEnds Task

- from_Ghaida/UnluckyChecker.java
This PR introduces the UnluckyChecker class which provides a method hasUnluckyPattern(int[] nums) to check for a specific "unlucky" pattern in an integer array — specifically, the pattern 1 immediately followed by 3 in certain positions.
> #TRA-2881: Array-1. unlucky1 added

- From_Alharith/WithoutX.java
If the first or last character of a string is 'x', remove those 'x' characters; otherwise, return the string as is.
> #TRA-1448: String1- WithoutX Done

- From_Alharith/FirstLast6.java
- From_Alharith/FirstLastSix.java
Given an array of ints, return true if 6 appears as either the first or last element in the array. The array will be length 1 or more.
firstLast6([1, 2, 6]) → true
firstLast6([6, 1, 2, 3]) → true
firstLast6([13, 6, 1, 2, 3]) → false
> #TRA-1733: Array1_ FirstLast6 Done

- From_Alharith/CheckSameFirstLast.java
- From_Alharith/SameFirstLast.java
Given an array of ints, return true if the array is length 1 or more, and the first element and the last element are equal.
sameFirstLast([1, 2, 3]) → false
sameFirstLast([1, 2, 3, 1]) → true
sameFirstLast([1, 2, 1]) → true
> #TRA-1734: Array1_ SameFirstLast Done

- From_Alharith/MakePi.java
- From_Alharith/PiGenerator.java
Return an int array length 3 containing the first 3 digits of pi, {3, 1, 4}.
makePi() → [3, 1, 4]
> #TRA-1735: Array1_ MakePi Done

- From_Alharith/CommonEnd.java
Given 2 arrays of ints, a and b, return true if they have the same first element or they have the same last element. Both arrays will be length 1 or more.
commonEnd([1, 2, 3], [7, 3]) → true
commonEnd([1, 2, 3], [7, 3, 2]) → false
commonEnd([1, 2, 3], [1, 3]) → true
> #TRA-1736: Array1_ CommonEnd Done

- From_Alharith/RotateLeft3.java
- From_Alharith/RotateLeftThree.java
Given an array of ints length 3, return an array with the elements "rotated left" so {1, 2, 3} yields {2, 3, 1}.
rotateLeft3([1, 2, 3]) → [2, 3, 1]
rotateLeft3([5, 11, 9]) → [11, 9, 5]
rotateLeft3([7, 0, 0]) → [0, 0, 7]
> #TRA-1738: Array1_ RotateLeft3 Done

- From_Alharith/Sum2.java
- From_Alharith/SumTwo.java
Given an array of ints, return the sum of the first 2 elements in the array. If the array length is less than 2, just sum up the elements that exist, returning 0 if the array is length 0.
sum2([1, 2, 3]) → 3
sum2([1, 1]) → 2
sum2([1, 1, 1, 1]) → 2
> #TRA-1741: Array1_ Sum2 Done

- From_Alharith/MiddleWay.java
Given 2 int arrays, a and b, each length 3, return a new array length 2 containing their middle elements.
middleWay([1, 2, 3], [4, 5, 6]) → [2, 5]
middleWay([7, 7, 7], [3, 8, 0]) → [7, 8]
middleWay([5, 2, 9], [1, 4, 5]) → [2, 4]
> #TRA-1742: Array1_ MiddleWay Done

- From_Alharith/MakeEnds.java
Given an array of ints, return a new array length 2 containing the first and last elements from the original array. The original array will be length 1 or more.
makeEnds([1, 2, 3]) → [1, 3]
makeEnds([1, 2, 3, 4]) → [1, 4]
makeEnds([7, 4, 6, 2]) → [7, 2]
> #TRA-1743: Array1_ MakeEnds Done

- From_Alharith/Has23.java
- From_Alharith/HasTwoOrThree.java
Given an int array length 2, return true if it contains a 2 or a 3.
has23([2, 5]) → true
has23([4, 3]) → true
has23([4, 5]) → false
> #TRA-1744: Array1_ Has23 Done

- From_Alharith/Double23.java
- From_Alharith/DoubleTwoOrThree.java
Given an int array, return true if the array contains 2 twice, or 3 twice. The array will be length 0, 1, or 2.
double23([2, 2]) → true
double23([3, 3]) → true
double23([2, 3]) → false
> #TRA-1748: Array1_ Double23 Done

- From_Alharith/Fix23.java
- From_Alharith/FixTwoThree.java
Given an int array length 3, if there is a 2 in the array immediately followed by a 3, set the 3 element to 0. Return the changed array.
fix23([1, 2, 3]) → [1, 2, 0]
fix23([2, 3, 5]) → [2, 0, 5]
fix23([1, 2, 1]) → [1, 2, 1]
> #TRA-1749: Array1_ Fix23 Done

- From_Alharith/Start1.java
- From_Alharith/StartOne.java
Start with 2 int arrays, a and b, of any length. Return how many of the arrays have 1 as their first element.
start1([1, 2, 3], [1, 3]) → 2
start1([7, 2, 3], [1]) → 1
start1([1, 2], []) → 1
> #TRA-1750: Array1_ Start1 Done

- From_Alharith/MidThree.java
- From_Alharith/MiddleThreeExtractor .java
Given an array of ints of odd length, return a new array length 3 containing the elements from the middle of the array. The array length will be at least 3.
midThree([1, 2, 3, 4, 5]) → [2, 3, 4]
midThree([8, 6, 7, 5, 3, 0, 9]) → [7, 5, 3]
midThree([1, 2, 3]) → [1, 2, 3]
> #TRA-1757: Array1_ MidThree Done

- From_Alharith/FirstTwoFromArrays .java
- From_Alharith/Make2.java
Given 2 int arrays, a and b, return a new array length 2 containing, as much as will fit, the elements from a followed by the elements from b. The arrays may be any length, including 0, but there will be 2 or more elements available between the 2 arrays.
make2([4, 5], [1, 2, 3]) → [4, 5]
make2([4], [1, 2, 3]) → [4, 1]
make2([], [1, 2]) → [1, 2]
> #TRA-1762: Array1_ Make2 Done

- From_Alharith/FirstElementsFromBoth .java
- From_Alharith/Front11.java
Given 2 int arrays, a and b, of any length, return a new array with the first element of each array. If either array is length 0, ignore that array.
front11([1, 2, 3], [7, 9, 8]) → [1, 7]
front11([1], [2]) → [1, 2]
front11([1, 7], []) → [1]
> #TRA-1763: Array1_ Front11 Done

- From_Alharith/CigarParty.java
- From_Alharith/PartyCigarChecker.java
When squirrels get together for a party, they like to have cigars. A squirrel party is successful when the number of cigars is between 40 and 60, inclusive. Unless it is the weekend, in which case there is no upper bound on the number of cigars. Return true if the party with the given values is successful, or false otherwise.
cigarParty(30, false) → false
cigarParty(50, false) → true
cigarParty(70, true) → true
> #TRA-2158: Logic1_ CigarParty Done

- From_Alharith/SquirrelPlay.java
The squirrels in Palo Alto spend most of the day playing. In particular, they play if the temperature is between 60 and 90 (inclusive). Unless it is summer, then the upper limit is 100 instead of 90. Given an int temperature and a boolean isSummer, return true if the squirrels play and false otherwise.
squirrelPlay(70, false) → true
squirrelPlay(95, false) → false
squirrelPlay(95, true) → true
> #TRA-2160: Logic1_ SquirrelPlay Done

- From_Alharith/CaughtSpeeding.java
You are driving a little too fast, and a police officer stops you. Write code to compute the result, encoded as an int value: 0=no ticket, 1=small ticket, 2=big ticket. If speed is 60 or less, the result is 0. If speed is between 61 and 80 inclusive, the result is 1. If speed is 81 or more, the result is 2. Unless it is your birthday -- on that day, your speed can be 5 higher in all cases.
caughtSpeeding(60, false) → 0
caughtSpeeding(65, false) → 1
caughtSpeeding(65, true) → 0
> #TRA-2161: Logic1_ CaughtSpeeding Done

- From_Alharith/DateFashion.java
You and your date are trying to get a table at a restaurant. The parameter "you" is the stylishness of your clothes, in the range 0..10, and "date" is the stylishness of your date's clothes. The result getting the table is encoded as an int value with 0=no, 1=maybe, 2=yes. If either of you is very stylish, 8 or more, then the result is 2 (yes). With the exception that if either of you has style of 2 or less, then the result is 0 (no). Otherwise the result is 1 (maybe).
dateFashion(5, 10) → 2
dateFashion(5, 2) → 0
dateFashion(5, 5) → 1
> #TRA-2159: Logic1_ DateFashion Done

- From_Alharith/SortaSum.java
Given 2 ints, a and b, return their sum. However, sums in the range 10..19 inclusive, are forbidden, so in that case just return 20.
sortaSum(3, 4) → 7
sortaSum(9, 4) → 20
sortaSum(10, 11) → 21
> #TRA-2162: Logic1_ SortaSum Done

- From_Alharith/More20.java
- From_Alharith/MoreThanMultipleOfTwenty.java
Return true if the given non-negative number is 1 or 2 more than a multiple of 20. 
more20(20) → false
more20(21) → true
more20(22) → true
> #TRA-2167: Logic1_ More20 Done

- From_Alharith/Old35.java
- From_Alharith/OldThreeOrFive.java
Return true if the given non-negative number is a multiple of 3 or 5, but not both. Use the % "mod" operator 
old35(3) → true
old35(10) → true
old35(15) → false
> #TRA-2168: Logic1_ Old35 Done

- From_Alharith/Less20.java
- From_Alharith/LessTwenty.java
Return true if the given non-negative number is 1 or 2 less than a multiple of 20. So for example 38 and 39 return true, but 40 returns false. 
less20(18) → true
less20(19) → true
less20(20) → false
> #TRA-2169: Logic1_ Less20 Done

- From_Alharith/TeenRangeSumCalculator .java
- From_Alharith/TeenSum.java
Given 2 ints, a and b, return their sum. However, "teen" values in the range 13..19 inclusive, are extra lucky. So if either value is a teen, just return 19.
teenSum(3, 4) → 7
teenSum(10, 13) → 19
teenSum(13, 2) → 19
> #TRA-2171: Logic1_  TeenSum Done

- From_Alharith/AnswerCell.java
Your cell phone rings. Return true if you should answer it. Normally you answer, except in the morning you only answer if it is your mom calling. In all cases, if you are asleep, you do not answer.
answerCell(false, false, false) → true
answerCell(false, false, true) → false
answerCell(true, false, false) → false
> #TRA-2172: Logic1_ AnswerCell Done

- From_Alharith/TeaParty.java
We are having a party with amounts of tea and candy. Return the int outcome of the party encoded as 0=bad, 1=good, or 2=great. A party is good (1) if both tea and candy are at least 5. However, if either tea or candy is at least double the amount of the other one, the party is great (2). However, in all cases, if either tea or candy is less than 5, the party is always bad (0).
teaParty(6, 8) → 1
teaParty(3, 8) → 0
teaParty(20, 6) → 2
> #TRA-2173: Logic1_ TeaParty Done

- From_Alharith/FizzString2.java
- From_Alharith/NumberFizzBuzzFormatter.java
Given an int n, return the string form of the number followed by "!". So the int 6 yields "6!". Except if the number is divisible by 3 use "Fizz" instead of the number, and if the number is divisible by 5 use "Buzz", and if divisible by both 3 and 5, use "FizzBuzz". Note: the % "mod" operator computes the remainder after division, so 23 % 10 yields 3. What will the remainder be when one number divides evenly into another?
fizzString2(1) → "1!"
fizzString2(2) → "2!"
fizzString2(3) → "Fizz!"
> #TRA-2175: Logic1_ FizzString2 Done

- From_Alharith/TwoAsOne.java
Given three ints, a b c, return true if it is possible to add two of the ints to get the third.
twoAsOne(1, 2, 3) → true
twoAsOne(3, 1, 2) → true
twoAsOne(3, 2, 2) → false
> #TRA-2176: Logic1_ TwoAsOne Done

- From_Alharith/InOrder.java
Given three ints, a b c, return true if b is greater than a, and c is greater than b. However, with the exception that if "bOk" is true, b does not need to be greater than a.
inOrder(1, 2, 4, false) → true
inOrder(1, 2, 1, false) → false
inOrder(1, 1, 2, true) → true
> #TRA-2177: Logic1_ InOrder Done

- From_Alharith/LessBy10.java
Given three ints, a b c, return true if one of them is 10 or more less than one of the others.
lessBy10(1, 7, 11) → true
lessBy10(1, 7, 10) → false
lessBy10(11, 1, 7) → true
> #TRA-2180: Logic1_ LessBy10 Done

- From_Alharith/DigitLengthSumChecker.java
- From_Alharith/SumLimit.java
Given 2 non-negative ints, a and b, return their sum, so long as the sum has the same number of digits as a. If the sum has more digits than a, just return a without b. (Note: one way to compute the number of digits of a non-negative int n is to convert it to a string with String.valueOf(n) and then check the length of the string.)
sumLimit(2, 3) → 5
sumLimit(8, 3) → 8
sumLimit(8, 1) → 9
> #TRA-2187: Logic1_ SumLimit Done

- From_Alharith/DigitSharing.java
- From_Alharith/ShareDigit.java
Given two ints, each in the range 10..99, return true if there is a digit that appears in both numbers, such as the 2 in 12 and 23. (Note: division, e.g. n/10, gives the left digit while the % "mod" n%10 gives the right digit.)
shareDigit(12, 23) → true
shareDigit(12, 43) → false
shareDigit(12, 44) → false
> #TRA-2186: Logic1_ ShareDigit Done

- From_Alharith/BlueTicket.java
You have a blue lottery ticket, with ints a, b, and c on it. This makes three pairs, which we'll call ab, bc, and ac. Consider the sum of the numbers in each pair. If any pair sums to exactly 10, the result is 10. Otherwise if the ab sum is exactly 10 more than either bc or ac sums, the result is 5. Otherwise the result is 0.
blueTicket(9, 1, 0) → 10
blueTicket(9, 2, 0) → 0
blueTicket(6, 1, 4) → 10
> #TRA-2185: Logic1_ BlueTicket Done

- From_Alharith/GreenTicket.java
You have a green lottery ticket, with ints a, b, and c on it. If the numbers are all different from each other, the result is 0. If all of the numbers are the same, the result is 20. If two of the numbers are the same, the result is 10.
greenTicket(1, 2, 3) → 0
greenTicket(2, 2, 2) → 20
greenTicket(1, 1, 2) → 10
> #TRA-2184: Logic1_ GreenTicket Done

- From_Alharith/RedTicket.java
You have a red lottery ticket showing ints a, b, and c, each of which is 0, 1, or 2. If they are all the value 2, the result is 10. Otherwise if they are all the same, the result is 5. Otherwise so long as both b and c are different from a, the result is 1. Otherwise the result is 0.
redTicket(2, 2, 2) → 10
redTicket(2, 2, 1) → 0
redTicket(0, 0, 0) → 5
> #TRA-2183: Logic1_ RedTicket Done

- From_Alharith/MaxMod5.java
- From_Alharith/MaxValueModulo.java
Given two int values, return whichever value is larger. However if the two values have the same remainder when divided by 5, then the return the smaller value. However, in all cases, if the two values are the same, return 0. Note: the % "mod" operator computes the remainder, e.g. 7 % 5 is 2.
maxMod5(2, 3) → 3
maxMod5(6, 2) → 6
maxMod5(3, 2) → 3
> #TRA-2182: Logic1_ MaxMod5 Done

- From_Alharith/MapAB3.java
- From_Alharith/MapValueReplicator.java
Modify and return the given map as follows: if exactly one of the keys "a" or "b" has a value in the map (but not both), set the other to have that same value in the map.
mapAB3({"a": "aaa", "c": "cake"}) → {"a": "aaa", "b": "aaa", "c": "cake"}
mapAB3({"b": "bbb", "c": "cake"}) → {"a": "bbb", "b": "bbb", "c": "cake"}
mapAB3({"a": "aaa", "b": "bbb", "c": "cake"}) → {"a": "aaa", "b": "bbb", "c": "cake"}
> #TRA-2277: MAP1_ MapAB3 Done

- From_Alharith/Topping3.java
- From_Alharith/ToppingValueDuplicator.java
Given a map of food keys and topping values, modify and return the map as follows: if the key "potato" has a value, set that as the value for the key "fries". If the key "salad" has a value, set that as the value for the key "spinach".
topping3({"potato": "ketchup"}) → {"potato": "ketchup", "fries": "ketchup"}
topping3({"potato": "butter"}) → {"potato": "butter", "fries": "butter"}
topping3({"salad": "oil", "potato": "ketchup"}) → {"spinach": "oil", "salad": "oil", "potato": "ketchup", "fries": "ketchup"}
> #TRA-2275: MAP1_ Topping3 Done

- From_Alharith/Topping2.java
- From_Alharith/ToppingRuleApplier.java
Given a map of food keys and their topping values, modify and return the map as follows: if the key "ice cream" has a value, set that as the value for the key "yogurt" also. If the key "spinach" has a value, change that value to "nuts".
topping2({"ice cream": "cherry"}) → {"yogurt": "cherry", "ice cream": "cherry"}
topping2({"spinach": "dirt", "ice cream": "cherry"}) → {"yogurt": "cherry", "spinach": "nuts", "ice cream": "cherry"}
topping2({"yogurt": "salt"}) → {"yogurt": "salt"}
> #TRA-2274: MAP1_ Topping2 Done

- From_Alharith/Topping1.java
- From_Alharith/ToppingReplacer.java
Given a map of food keys and topping values, modify and return the map as follows: if the key "ice cream" is present, set its value to "cherry". In all cases, set the key "bread" to have the value "butter".
topping1({"ice cream": "peanuts"}) → {"bread": "butter", "ice cream": "cherry"}
topping1({}) → {"bread": "butter"}
topping1({"pancake": "syrup"}) → {"bread": "butter", "pancake": "syrup"}
> #TRA-2273: MAP1_ Topping1 Done

- From_Alharith/MapShare.java
Modify and return the given map as follows: if the key "a" has a value, set the key "b" to have that same value. In all cases remove the key "c", leaving the rest of the map unchanged.
mapShare({"a": "aaa", "b": "bbb", "c": "ccc"}) → {"a": "aaa", "b": "aaa"}
mapShare({"b": "xyz", "c": "ccc"}) → {"b": "xyz"}
mapShare({"a": "aaa", "c": "meh", "d": "hi"}) → {"a": "aaa", "b": "aaa", "d": "hi"}
> #TRA-2271: MAP1_ MapShare Done

- From_Alharith/MapBully.java
Modify and return the given map as follows: if the key "a" has a value, set the key "b" to have that value, and set the key "a" to have the value "". Basically "b" is a bully, taking the value and replacing it with the empty string.
mapBully({"a": "candy", "b": "dirt"}) → {"a": "", "b": "candy"}
mapBully({"a": "candy"}) → {"a": "", "b": "candy"}
mapBully({"a": "candy", "b": "carrot", "c": "meh"}) → {"a": "", "b": "candy", "c": "meh"}
> #TRA-2262: MAP1_ MapBully Done

- From_Alharith/MakeBricks.java
We need to build a row of bricks that reaches exactly the goal length in inches. We are given some small bricks (each 1 inch long) and some big bricks (each 5 inches long). Return true if it’s possible to reach the goal length using the available bricks. The problem is trickier than it seems and can be solved without using loops.
> #TRA-2418:Logic2_ MakeBricks Done

- From_Alharith/Blackjack.java
You’re given two positive integers. Return the one closest to 21 without exceeding it. If both numbers are greater than 21, return 0.
> #TRA-2424:Logic2_ BlackJack Done

- From_Alharith/CloseFar.java
Given three integers a, b, and c, return true if either b or c is “close” to a (meaning it differs from a by at most 1), and the other value is “far,” meaning it differs from both a and the close value by 2 or more.
> #TRA-2423:Logic2_ CloseFar Done

- From_Alharith/RoundSum.java
In this problem, you’ll round an integer up to the next multiple of 10 if its last digit is 5 or greater (for example, 15 rounds up to 20). If the last digit is less than 5, round down to the previous multiple of 10 (for example, 12 rounds down to 10).
> #TRA-2422:Logic2_ RoundSum Done

- From_Alharith/DoubleChar.java
Given a string, return a new string where each character in the original string is repeated twice consecutively
> #TRA-2463: String2_ DoubleChar Done

- From_Alharith/CatDog.java
Return true if the number of times "cat" appears in the string is equal to the number of times "dog" appears.
> #TRA-2465: String2_ CctDog Done

- From_Alharith/CountCode.java
Count how many times the substring "code" appears in the given string, but allow any character in place of the letter 'd'—so strings like "cope" or "cooe" also count
> #TRA-2466: String2_ CountCode Done

- From_Alharith/EndOther.java
Given two strings, return true if one of the strings appears at the very end of the other, ignoring case differences (i.e., the comparison is case-insensitive).
> #TRA-2467: String2_ EndOther Done

- From_Alharith/XyzThere.java
Return true if the string contains "xyz" that is not immediately preceded by a period ('.'). For example, "xxyz" counts, but "x.xyz" does not.
> #TRA-2468: String2_ XyzThere Done

- from_Kaltham/ThreeCounter.java
I created a class called ThreeCounter with a method named threeCountPassOne that takes an array of integers.
The method checks if the array contains exactly three 3s, counting each 3 only once and skipping the next number after each 3.
How it works:
It starts a counter threeCount at 0.
If it finds a 3, it increases the counter by 1 and skips the next number.
After checking all numbers, it returns true if the counter equals 3, otherwise false.
> TRA-2978: Array-2 > =The solution for haveThree Task

- from_Ghaida/ArrayCombiner.java
Creates a method combineTwoArrays() that combines two integer arrays into a new array of length 2.
Takes the first elements from array a, then fills remaining positions with elements from array b
> #TRA-2882: Array-1. make2 added

- from_Kaltham/TripleUpChecker.java
I created a class called TripleUpChecker with a method named hasTripleUp that takes an array of integers.
The method checks if the array has three increasing numbers in a row (like 4, 5, 6).
How it works:
It goes through each number up to the third last.
For each position, it checks if the next number is bigger by 1, and the one after that is also bigger by 1.
If it finds such a sequence, it returns true.
If it finishes checking without finding one, it returns false.
> TRA-2981: Array-2 >=This is the solution for tripleUp Task

- From_Mulk/AnswerCell.java
In this method, I return true if I should answer the phone. I check if it’s morning, if it’s my mom, and if I’m asleep. If I’m asleep, I return false in any case. If it’s morning, I only return true if it’s my mom and I’m not asleep. Otherwise, I return true if I’m not asleep, no matter who is calling or what time it is.
> Logic-1 > AnswerCell 

- From_Alharith/XyzMiddle.java
Given a string, determine if "xyz" appears in the middle of the string. The “middle” is defined so that the number of characters before and after "xyz" differ by at most one. This problem can be trickier than it seems.
> #TRA-2729: String2_ XyzMiddle Done

- from_Kaltham/RangeArrayBuilder.java
I created a class called RangeArrayBuilder with a method named buildArrayFromStartUpToEnd that takes two integers: start and end.
The method makes a new array containing all the numbers starting from start up to, but not including, end.
How it works:
First, it figures out how long the array should be by subtracting start from end.
Then, it creates an empty array with that length.
After that, it fills the array by adding numbers one by one, starting at start and increasing by 1 each time.
Finally, it returns the completed array.
> The solution for fizzArray3 Task

- From_Mulk/TeaParty.java
This method returns a party rating based on the amounts of tea and candy. If either tea or candy is less than 5, the party is bad (return 0). If either tea or candy is at least double the other, the party is great (return 2). Otherwise, the party is good (return 1).
> Logic-1 >  TeaParty task

- from_Kaltham/ArrayShifter.java
I created a class called ArrayShifter with a method named shiftLeft that takes an array of integers.
The method shifts all numbers in the array one position to the left, and the first number moves to the end.
How it works:
If the array has 0 or 1 elements, it just returns the same array because there’s nothing to shift.
Otherwise, it creates a new array of the same size.
It goes through each position (except the last) and moves the element at the next index into the current one.
Finally, it places the first element of the original array at the last position.
> TRA-2983: Array-2 >=The solution for shiftLeft Task

- From_Manal/RemoveTens.java
Implements the withoutTen(int[] nums) method to remove all 10s from the input array. Remaining elements are shifted left, and trailing positions are filled with 0.
> TRA-3007: WithoutTen

- From_Manal/AfterFourExtractor.java
Implements the post4(int[] nums) method to return a new array containing all elements that appear after the last occurrence of 4 in the input array.
> TRA-3006: post4

- From_Manal/ArrayShifter.java
Implements the post4(int[] nums) method to return a new array containing all elements that appear after the last occurrence of 4 in the input array.
> TRA-3005: ShiftLeft

- from_Ghaida/SumExcludingThirteen.java
This PR adds the calculateSumExcludingThirteen method in the SumExcludingThirteen class. The method calculates the sum of an array, excluding any occurrence of the number 13 and the element immediately following it.
> #TRA-3032: Array-2. sum13 added

- From_Manal/ArrayEndsChecker.java
Implements the sameEnds(int[] nums, int len) method to return true if the first len elements of the array match the last len elements.
> TRA-3004: SameEnds

- from_Ghaida/SumExcludingRange.java
This PR introduces the calculateSumExcludingRange method in the SumExcludingRange class. The method calculates the sum of elements in an integer array, excluding any numbers between a 6 and the next 7, inclusive.
> #TRA-3033: Array-2. sum67 added

- from_Hawraa/MakeBricks.java
Implemented a method canBuildGoal() to check if a goal length can be achieved using given small (1 unit) and big (5 unit) bricks."
> TRA-3020: Logic-2: makeBricks added

- from_Kaltham/NumbersBeforeFour.java
I created a class called NumbersBeforeFour with a method named getNumbersBeforeFour that takes an array of integers.
The method returns a new array containing all numbers before the first 4 in the original array.
How it works:
It goes through the array and counts how many numbers appear before the first 4.
It creates a new array of that length.
It copies all the numbers before the first 4 into the new array.
Finally, it returns the new array.
> TRA-2985: Array-2 >=The solution for pre4 Task

- from_Ghaida/DoubleTwoChecker.java
This PR introduces the hasDoubleTwo method within the DoubleTwoChecker class. The method checks whether the input array contains two consecutive 2s.
> #TRA-3034: Array-2. has22 added

- From_Mohammed/MapAB3.java
Modify and return the given map as follows: if exactly one of the keys "a" or "b" has a value in the map (but not both), set the other to have that same value in the map.
mapAB3({"a": "aaa", "c": "cake"}) → {"a": "aaa", "b": "aaa", "c": "cake"}
mapAB3({"b": "bbb", "c": "cake"}) → {"a": "bbb", "b": "bbb", "c": "cake"}
mapAB3({"a": "aaa", "b": "bbb", "c": "cake"}) → {"a": "aaa", "b": "bbb", "c": "cake"}
> Map-1: #TRA-2450 MapAB3 done

- from_Ghaida/NoOneOrThreeChecker.java
This PR introduces the checkLuckyThirteen method in the NoOneOrThreeChecker class. The method returns true if the array contains no 1s and no 3s—making it a "lucky" array according to the problem definition.
> #TRA-3035: Array-2. lucky13 added

- From_Alharith/StarOut.java
Return a modified version of the given string where, for each '*', the star and the characters immediately before and after it are removed.
> #TRA-2745: String2_ StarOut Done

- From_Alharith/OneTwo.java
Given a string, create a new string by taking each group of three characters and moving the first character to the end of the group. Ignore any group shorter than three characters at the end of the string.
> #TRA-2740: String2_ OneTwo Done

- From_Mohammed/Topping3.java
Given a map of food keys and topping values, modify and return the map as follows: if the key "potato" has a value, set that as the value for the key "fries". If the key "salad" has a value, set that as the value for the key "spinach".
topping3({"potato": "ketchup"}) → {"potato": "ketchup", "fries": "ketchup"}
topping3({"potato": "butter"}) → {"potato": "butter", "fries": "butter"}
topping3({"salad": "oil", "potato": "ketchup"}) → {"spinach": "oil", "salad": "oil", "potato": "ketchup", "fries": "ketchup"}
> Map-1: #TRA-2448 Topping3 done

- From_Mohammed/Topping2.java
Given a map of food keys and their topping values, modify and return the map as follows: if the key "ice cream" has a value, set that as the value for the key "yogurt" also. If the key "spinach" has a value, change that value to "nuts".
topping2({"ice cream": "cherry"}) → {"yogurt": "cherry", "ice cream": "cherry"}
topping2({"spinach": "dirt", "ice cream": "cherry"}) → {"yogurt": "cherry", "spinach": "nuts", "ice cream": "cherry"}
topping2({"yogurt": "salt"}) → {"yogurt": "salt"}
> Map-1: #TRA-2447 Topping2 done

- From_Mohammed/Topping1.java
Given a map of food keys and topping values, modify and return the map as follows: if the key "ice cream" is present, set its value to "cherry". In all cases, set the key "bread" to have the value "butter".
topping1({"ice cream": "peanuts"}) → {"bread": "butter", "ice cream": "cherry"}
topping1({}) → {"bread": "butter"}
topping1({"pancake": "syrup"}) → {"bread": "butter", "pancake": "syrup"}
> Map-1: #TRA-2446 Topping1 done

- From_Mohammed/MapAB.java
Modify and return the given map as follows: for this problem the map may or may not contain the "a" and "b" keys. If both keys are present, append their 2 string values together and store the result under the key "ab".
mapAB({"a": "Hi", "b": "There"}) → {"a": "Hi", "ab": "HiThere", "b": "There"}
mapAB({"a": "Hi"}) → {"a": "Hi"}
mapAB({"b": "There"}) → {"b": "There"}
> Map-1: #TRA-2445 mapAB done

- From_Mohammed/MapShare.java
Modify and return the given map as follows: if the key "a" has a value, set the key "b" to have that same value. In all cases remove the key "c", leaving the rest of the map unchanged.
mapShare({"a": "aaa", "b": "bbb", "c": "ccc"}) → {"a": "aaa", "b": "aaa"}
mapShare({"b": "xyz", "c": "ccc"}) → {"b": "xyz"}
mapShare({"a": "aaa", "c": "meh", "d": "hi"}) → {"a": "aaa", "b": "aaa", "d": "hi"}
> Map-1: #TRA-2444 mapShare done

- From_Mohammed/MapBully.java
Modify and return the given map as follows: if the key "a" has a value, set the key "b" to have that value, and set the key "a" to have the value "". Basically "b" is a bully, taking the value and replacing it with the empty string.
mapBully({"a": "candy", "b": "dirt"}) → {"a": "", "b": "candy"}
mapBully({"a": "candy"}) → {"a": "", "b": "candy"}
mapBully({"a": "candy", "b": "carrot", "c": "meh"}) → {"a": "", "b": "candy", "c": "meh"}
> Map-1: #TRA-2443 mapBully done

- from_Huria/TwoFromIndexOrStart.java
This method takes an integer n and returns a string based on whether n is divisible by 3, 5, or both. If n is divisible by both 3 and 5, it returns "FizzBuzz!". If it’s only divisible by 3, it returns "Fizz!". If it’s only divisible by 5, it returns "Buzz!". Otherwise, it returns the number n followed by an exclamation mark.
> Logic-1 > FizzStringTow task 

- from_Hawraa/LoneSum.java
- Implemented  sumUniqueValue(int a, int b, int c) method, that checks each input value:
- If a number is not equal to the other two, it is considered unique.
- Only unique numbers are added to the result.
> TRA-30221: Logic-2: loneSum added

- from_Hawraa/LuckySum.java
Implemented the method sumBeforeThirteen(int a, int b, int c) that returns the sum of the input values, stopping the summing process if the number 13 is encountered. Once 13 is found, it and any values after it are ignored.
> TRA-3022: Logic-2: luckySum added

- from_Huria/TwoFromIndexOrStart.java
In this method, I return true if I should answer the phone. I check if it’s morning, if it’s my mom, and if I’m asleep. If I’m asleep, I return false in any case. If it’s morning, I only return true if it’s my mom and I’m not asleep. Otherwise, I return true if I’m not asleep, no matter who is calling or what time it is.
> Logic-1: AnswerCell task

- .github/CODEOWNERS
- From_Maha/ArrayMerger.java
Implements logic to combine two arrays of length 2 into one array of length 4.
>  Adding Array1-plusTwo file

- from_Huria/TwoFromIndexOrStart.java
This method returns a party rating based on the amounts of tea and candy. If either tea or candy is less than 5, the party is bad (return 0). If either tea or candy is at least double the other, the party is great (return 2). Otherwise, the party is good (return 1).
> Logic-1 > TeaParty task

- from_Kaltham/ReplaceLonelyValues.java
I created a class called ReplaceLonelyValues with a method named replaceLonely that takes an array of integers and a value val.
The method replaces any “lonely” occurrences of val—a value that is not the same as its neighbors—with the larger of its two neighbors.
How it works:
It goes through each number in the array, except the first and last.
If the current number equals val and both neighbors are different, it is considered lonely.
It replaces the lonely value with the larger of its two neighbors.
After checking all numbers, it returns the modified array.
> TRA-2987: Array-2 >=The solution for AtAlone Task

- from_Ghaida/NumberArrayGenerator.java
This PR adds the generateNumberSequence method to the NumberArrayGenerator class. The method returns a new array containing a sequence of integers from 0 up to n - 1.
> #TRA-3038: Array-2. fizzArray added

- from_Huria/TwoFromIndexOrStart.java
This method checks the first and last letters of a given string. If the string starts with "f" and ends with "b", it returns "FizzBuzz". If it only starts with "f", it returns "Fizz". If it only ends with "b", it returns "Buzz". If neither, it returns the original string.
> Logic-1> FizzString task

- from_Hawraa/NoTeenSum.java
Implemented two methods: sumWithoutTeens(int a, int b, int c) and fixTeenValue(int n), these work together to compute the sum of three integers, treating most "teen" values (13–19) as 0, except for 15 and 16, which are included in the sum.
> TRA-3023: Logic-2: noTeenSum added

- from_Kaltham/RemoveTens.java
I created a class called RemoveTens with a method named removeTen that takes an array of integers.
The method creates a new array containing all numbers from the original array except the tens.
How it works:
It creates a new array of the same length as the original.
It goes through each number in the original array.
If a number is not 10, it adds it to the new array.
After checking all numbers, it returns the new array.
> TRA-2989: Array-2 >=The solution for withoutTen Task

- from_Ghaida/OnlyOneAndTwoChecker.java
This PR introduces the hasOnlyOnesAndFours method in the OnlyOneAndTwoChecker class. The method checks whether an array contains only the integers 1 and 4, returning true if all elements meet this condition.
> #TRA-3039: Array-2. only14 added

- from_Hawraa/MakeBricks.java
Implemented a method canBuildGoal() to check if a goal length can be achieved using given small (1 unit) and big (5 unit) bricks."
> TRA-3020: Logic-2: makeBricks modified

- From_Mulk/TwoAsOne.java
This method checks if any two of the three integers (a, b, c) add up exactly to the third. If so, it returns true. Otherwise, it returns false.
> Logic-1 > TwoAsOne task

- from_Kaltham/EvenOddSeparator.java
I created a class called EvenOddSeparator with a method named separateEvenAndOdd that takes an array of integers.
The method returns a new array where all even numbers come first, followed by all odd numbers, keeping their original order.
How it works:
It creates a new array of the same length as the original.
It goes through the original array and copies all even numbers to the new array first.
Then it goes through the array again and copies all odd numbers after the even numbers.
Finally, it returns the new array.
> TRA-2991: Array-2 >=The solution for evenOdd Task

- from_Kaltham/FizzBuzzGenerator.java
I created a class called FizzBuzzGenerator with a method named generateFizzBuzz that takes two integers: start and end.
The method returns a new array of strings representing the FizzBuzz sequence from start to end (excluding end).
How it works:
It calculates the length of the array as end - start and creates a new string array.
It goes through each number from start to end.
For each number:
If it is divisible by 15, it adds "FizzBuzz" to the array.
If divisible by 3, it adds "Fizz".
If divisible by 5, it adds "Buzz".
Otherwise, it adds the number itself as a string.
After processing all numbers, it returns the new array.
> TRA-2992: Array-2 >=The solution for fizzBuzz Task

- From_Mulk/InOrder.java
This method checks if three numbers (a, b, c) are in increasing order. If bOk is true, then b doesn’t need to be greater than a — only c > b is required. If bOk is false, then both b > a and c > b must be true. If either condition is met, the method returns true; otherwise, it returns false.
> Logic-1 > InOrder task

- From_Maha/BrickCalculator.java
The method checks if a given number of small and big bricks can be combined to exactly meet a target goal. It calculates the maximum number of big bricks that can be used and then checks if the remaining goal can be filled with the available small bricks.
> Adding makeBricks file

- From_Maha/TeenSumCalculator.java
Implemented noTeenSum to sum three integers, ignoring "teen" numbers except 15 and 16.
Added helper method fixTeen to zero out unwanted teen values.
> Adding noTeenSum file

- from_Kaltham/MaxSpanCalculator.java
I created a class called MaxSpanCalculator with a method named calculateMaxSpan that takes an array of integers.
The method finds the largest span in the array, which is the distance between the first and last occurrence of the same number, including both positions.
How it works:
It goes through each number in the array as the first number.
For that number, it finds the last occurrence of the same number in the array.
It calculates the span as (last index - first index + 1).
If this span is larger than the current maximum, it updates the maximum.
After checking all numbers, it returns the largest span.
> TRA-3161: Array-3 >=The solution for maxSpan Task

- from_Kaltham/NumberAfterFour.java
I created a class called NumberAfterFour with a method named placeFiveAfterFour that takes an array of integers.
The method rearranges the array so that every 4 is immediately followed by a 5, without changing the relative order of the other numbers.
How it works:
When it finds a 4, it checks if the next number is already 5.
If yes, it continues to the next number.
If not, it searches for a free 5 (a 5 not already after a 4).
It swaps that free 5 with the number currently after the 4.
It repeats this process for all 4s in the array.
Finally, it returns the modified array.
> TRA-3163: Array-3 >=The solution for fix45 Task

- from_Hawraa/RoundSum.java
Implemented two methods: roundAndSum(int a, int b, int c) and nearestTen(int num). These methods work together to round each input value to the nearest multiple of 10, then return the total sum.
> TRA-3024: Logic-2: roundSum added

- From_Mulk/LastDigit.java
This method checks if any two of the three integers (a, b, c) have the same last digit. It compares the remainder when each number is divided by 10. If any pair matches, it returns true; otherwise, it returns false.
> Logic-1 > LastDigit

- from_Kaltham/SquareUpBuilder.java
I created a class called SquareUpBuilder with a method named generateSquareUpPattern that takes an integer n.
The method builds a "square-up" pattern inside a one-dimensional array of size n * n.
How it works:
It creates a new array of size n * n.
For each row (from 1 to n), it fills the last i positions of that row with numbers 1 up to i (counting backwards).
The rest of the positions in that row remain 0.
After finishing all rows, it returns the array.
> TRA-3166: Array-3 >=The solution for squareUp Task

- from_Kaltham/ArraySubsetChecker.java
I created a class called ArraySubsetChecker with a method named isInnerSubsetOfOuter that takes two arrays: an outer array and an inner array.
The method checks if all the elements of the inner array exist inside the outer array (regardless of order).
How it works:
It loops through each element in the inner array.
For each element, it checks if that element exists in the outer array.
If found, it increases a counter and moves to the next inner element.
After checking all elements, if the counter equals the length of the inner array, it means all inner elements are found in the outer array → returns true.
> TRA-3165: Array-3 >=The solution for linearIn Task

- From_Mulk/LessByTen.java
This method checks if any of the three integers (a, b, or c) differ from another by at least 10. If the difference between any two numbers is 10 or more (in either direction), it returns true. Otherwise, it returns false.
> Logic-1 > LessByTen task

- from_Hawraa/Blackjack.java
Implemented getNearestToTwentyOne(int a, int b) method, which returns the number closest to 21 without going over. If both inputs exceed 21, the method returns 0.
> TRA-3026: Logic-2: blackjack added

- from_Kaltham/MirrorSubarrayFinder.java
I created a class called MirrorSubarrayFinder with a method named findLongestMirrorLength that takes an array of integers.
The method finds the length of the longest subarray that appears in reverse order elsewhere in the array (a “mirror”).
How it works:
It goes through each number in the array as a starting point.
For each starting point, it compares the numbers with every number from the end of the array moving backwards.
It counts how many consecutive numbers match in reverse order.
If a sequence ends, it updates the maximum length found so far.
After checking all starting points, it returns the length of the longest mirrored subarray.
> TRA-3168: Array-3 >=The solution for maxMirror Task

- from_Hawraa/MakeChocolate.java
Implemented areEvenlySpaced(int a, int b, int c) method, to determines the minimum number of small bars (1kg each) needed to meet a goal using a combination of big bars (5kg each) and small bars.
> TRA-3028: Logic-2: makeChocolate added

- from_Ghaida/ValPresenceChecker.java
This PR introduces the hasValueInEachPair method in the ValPresenceChecker class. The method determines whether a given value val is present in every adjacent pair of elements in the array.
> #TRA-3042: Array-2. isEverywhere added

- From_Mulk/RedTicket.java
This method evaluates a "red lottery ticket" based on three numbers (a, b, c). If all three are 2, it returns 10. If all three numbers are the same (but not all 2), it returns 5. If only b and c are different from a, it returns 1. In all other cases, it returns 0.
> Logic-1 > RedTicket task

- from_Ghaida/EitherTwoPairOrFourPairChecker.java
This PR introduces the checkEitherTwoOrFour method in the hasEitherTwoPairOrFourPair class. The method returns true if the array contains a pair of adjacent 2s or a pair of adjacent 4s, but not both.
> #TRA-3043: Array-2. either24 added

- From_Mulk/ShareDigit.java
This method checks if two two-digit numbers (a and b) share any digit. It compares the tens and ones digits of both numbers, and returns true if they have at least one digit in common; otherwise, it returns false.
> Logic-1 > ShareDigit task

- From_Maha/NumberSpacingChecker.java
The method checks if three numbers are evenly spaced.
It returns true if the difference between them is consistent
> Adding evenlySpace file

- from_Ghaida/FourAfterThreeChecker.java
This PR introduces the ThreeFourReorder method inside the FourAfterThreeChecker class. It ensures that every occurrence of the number 3 in an array is immediately followed by a 4, without adding or removing elements — just rearranging them.
> #TRA-3297: Array-3. fix34 added

- From_Mulk/NoTeensSum.java
in this task I wrote a Java program that sums three numbers while ignoring certain teen values (13–19), except 15 and 16. I used a helper method to filter out the unwanted values before calculating the total.
> Logic-2 > NoTeenSum task

- from_Ghaida/FiveAfterFourChecker.java
This PR adds the fourFiveReorder method inside the FiveAfterFourChecker class. The method ensures that every 4 in the input array is immediately followed by a 5. It does this by rearranging elements in the array without moving any 4s.
> #TRA-3299: Array-3. fix45 added

- From_Mulk/RoundSum.java
I created a Java program that calculates the sum of three numbers after rounding each to the nearest multiple of 10. A helper method, round10, performs the rounding based on standard rounding rules before summing the values.
> Logic-2 > RoundSum task

- from_Ghaida/InnerInOuter.java
This PR adds the isInnerInOuter method in the InnerInOuter class. It checks whether all elements of a sorted inner array appear in the sorted outer array — similar to subset checking.
> #TRA-3301: Array-3. linearIn added

- From_Manal/CompareOnesAndFours.java
this method returns true if the number of 1's is greater than the number of 4's
> TRA-3270: MoreOneFour

- From_Manal/HasAdjacentTwos.java
This method return true if the array contains a 2 next to a 2 somewhere.
> TRA-3269: Has22

- From_Manal/ZeroFront.java
Added a method that rearranges the input array so all 0s appear at the front, while preserving the presence of all original elements. The order of non-zero values is not maintained, as per problem requirements. This solution uses a new array for clarity and separation of zero/non-zero logic.
> TRA-3278: ZeroFront

- from_Ghaida/NumberSquare.java
This PR implements the makeSquarePattern method in the NumberSquare class, which creates an array representing a square pattern of size n. The array is of length n*n and for each group of n elements, the last i elements count down from i to 1, with zeros filling the rest.
> #TRA-3302: Array-3. squareUp added

- From_Manal/EvenOddRearranger.java
This Method rearranges the input array so that all even numbers appear before all odd numbers. The relative order within each group is not preserved, and the method may either modify the original array or return a new one.
> TRA-3279: EvenOdd

- From_Manal/CenteredAverage.java
This Method calculates the "centered" average of an integer array by excluding one instance each of the smallest and largest values, then computing the mean of the remaining elements using integer division. Assumes the input array has a length of 3 or more. This approach ensures outliers do not skew the result, supporting more balanced average calculations.
> TRA-3268: CenteredAverage

- From_Manal/FizzArrayTwo.java
This Method returns a new string array of length n, where each element is the string representation of its index from 0 to n-1. Handles edge case where n == 0 by returning a valid empty array.
> TRA-3271: FizzArrayTwo

- From_Maha/CharacterDuplicator.java
This method takes a string and duplicates each character sequentially.
Useful for creating stylized or encoded versions of input strings.
> Adding doubleChar file

- From_Manal/TwoTwoChecker.java
This Method return true if every 2 that appears in the array is next to another 2.
> TRA-3274: TwoTwo

- From_Manal/HasOneTwoChecker.java
This Method return true if there is a 1 in the array with a 2 somewhere later in the array.
> TRA-3273: HasOneTwo

- from_Hawraa/WordReplace.java
I implemented the replaceWithIsNot(String str) method to replace all whole word occurrences of "is" with "is not" using a regular expression that matches "is" as a separate word.
> TRA-3219: String-3: notReplace added

- From_Manal/EitherTwoOrFourAlternative.java
This Method return true if the array contains a 2 next to a 2 or a 4 next to a 4, but not both.
> TRA-3272: EitherTwoFour

- From_Manal/FizzArrayThree.java
This Method returns a new array containing a sequence of integers starting from start up to but not including end. Handles edge cases such as start == end, returning a valid length-0 array.
> TRA-3276: FizzArrayThree

- from_Huria/HiCounter.java
The code given string and counts how many times the exact sequence "hi" appears, regardless of its position.
> TRA2787: Adding countHi Task

- from_Huria/CatDogBalancer.java
The code Checks if "cat" and "dog" appear an equal number of times in the given string, ensuring perfect pet harmony in the text.
> TRA2788: Adding catDog Task

- From_Mulk/BlackjackScoreChecker.java
I created a Java method that returns the best blackjack score from two values, considering that scores over 21 are invalid. It returns the highest valid score or zero if both are over 21.
> Logic-2 > Blackjack task

- from_Huria/EndMatch.java
The code Checks if one string appears at the very end of the other—without caring about uppercase or lowercase.
> TRA2790: Adding endOther Task

- from_Ghaida/SequenceGroupAnalyzer.java
Implemented calculateClumpCount method to the SequenceGroupAnalyzer class. The method counts the number of “clumps” in an integer array, where a clump is defined as a series of two or more adjacent identical elements.
> #TRA-3305: Array-3. countClumps added

- from_Huria/BobChecker.java
The code Hunts down any "b_b" pattern in the string—where the middle character can be anything! Whether it’s a classic "bob" or a quirky "b9b".
> TRA2792: Adding bobThere Task

- From_Maha/BobPatternChecker.java
Detects the pattern "b_b" in the input string, where any character exists between two 'b's.
Returns true if found.
> Adding bobThere file

- From_Mohammed/AbbaStringBuilder.java
I need to write a function that takes two strings, a and b, then joins them in the pattern abba. That means the first string, then the second string twice, and then the first string again.
> String-1 makeAbba #TRA-3086 done

- From_Mohammed/StringRepeater.java
I need to make a function that takes a string, looks at its last two characters, and then repeats those two characters three times to make a new string. The input string will always have at least 2 characters.
> String-1 stringRepeater #TRA-3090 done

- From_Mohammed/HtmlTagMaker.java
I need to make a function that takes two strings: a tag (like i or cite) and a word (like Yay). The function should return a string that puts the word inside the opening and closing HTML tags. For example, if the tag is i and the word is Yay, the result should be <i>Yay</i>.
> String-1 makeTags #TRA-3088 done

- from_Ghaida/BunnyEarCounter.java
This PR adds the countEars method in the BunnyEarCounter class. The method uses recursion to compute the total number of ears for a given number of bunnies, with each bunny contributing exactly 2 ears.
> #TRA-3372: Recursion-1. bunnyEars added

- from_Huria/StringMixer.java
The code Weaves two strings together by alternating their characters one by one. If one string runs out, the leftovers from the longer string get added at the end.
> TRA2797: Adding mixString Task

- from_Ghaida/TriangularSum.java
This PR introduces the calculateTriangle method in the TriangularSum class. It uses recursion to calculate the total number of blocks in a triangle with a given number of rows, where each row contains one more block than the one above it.
> #TRA-3375: Recursion-1. triangle added

- from_Huria/EndRepeater.java
The code takes the last n characters of a string and repeats them n times to create a catchy echo effect at the end of the text.
> TRA2794: Adding repeatEnd Task

- from_Huria/WordRepeatedWithSeparator.java
The code Creates a big string by repeating a given word multiple times, with a separator sprinkled in between each repetition.
> TRA2796: Adding repeatSeparator Task

- from_Huria/IsPrefixRepeated.java
The code Checks whether the prefix of length N from the start of a string appears again later in the same string. The prefix is compared with all subsequent substrings of equal length. Returns true if a match is found, otherwise false.
> TRA3015: Adding prefixAgain Task

- From_Maha/StringMixer.java
Merges two strings by alternating characters from each.
Handles uneven lengths by appending remaining characters from the longer string.
> Adding mixString file

- from_Huria/IsXyzCentered.java
The code Determines whether the substring "xyz" appears in the middle of a given string.
A substring is considered centered if the number of characters on its left and right differ by at most one. Returns true if "xyz" meets this middle-position rule; otherwise, returns false.
> TRA2910: Adding xyzMiddle Task

- from_Ghaida/PowerCalculator.java
This PR adds a recursive method computePower(int base, int n) that calculates the result of raising a base number to a non-zero positive exponent using recursion.
> #TRA-3379: Recursion-1 .powerN added

- from_Ghaida/CountXChars.java
This PR adds a recursive method countX(String str) that counts how many times the lowercase letter 'x' appears in a given string.
> #TRA-3380: Recursion-1 .countX added

- from_Huria/RemoveBetweenFirstAndLastBreadFinder.java
The code Finds and returns the substring located between the first and last occurrence of the word "bread" in the given string. If fewer than two occurrences of "bread" are found, returns an empty string "". This simulates finding the filling in a sandwich made with two slices of bread.
> TRA2911: Adding getSandwich Task

- from_Ghaida/XtoYTransformer.java
This PR introduces the method replaceXWithY(String str) which recursively replaces all lowercase 'x' characters in the input string with 'y'.
> #TRA-3383: Recursion-1. changeXY added

- from_Ghaida/XRemover.java
This PR adds the RemoveX(String str) method, which recursively removes all lowercase 'x' characters from a given string.
> #TRA-3385: Recursion-1. noX added

- from_Ghaida/ElevenCounter.java
This PR implements the method countElevens(int[] nums, int index), which recursively counts how many times the number 11 appears in an integer array starting from a given index.
> #TRA-3387: Recursion-1. array11 added

- from_Ghaida/TimesTenChecker.java
This PR introduces the method hasTimesTenPair(int[] nums, int index), which recursively checks whether the array contains a value that is followed immediately by that value multiplied by 10 (i.e., nums[i+1] == nums[i] * 10).
> #TRA-3388: Recursion-1. array220 added

- From_Mohammed/StringMerger.java
I need to make a function that takes two strings, a and b. It should return a new string in the form short + long + short. That means the shorter string goes to the outside, and the longer string goes in the middle
> String-1 > StringMerge #TRA-3097

- From_Mohammed/StringRotator.java
I need to write a function that takes a string and moves its first two characters to the end of the string. The string will always have at least 2 characters.
> String-1 > StringRotator #TRA-3098

- from_Huria/RotateFirstCharInTriplets.java
The code Transforms the input string by processing it in groups of three characters. In each triplet, the first character is moved to the end, and the remaining two characters shift left. For example, "abc" becomes "bca".
> TRA3012: Adding oneTwo Task

- From_Mulk/CountHiSubstring.java
I created a class called countHiSubstring with a method that counts how many times the substring "hi" appears in a given string. It loops through the string, checks every pair of characters, and increases the count when it finds "hi". Then it returns the total count.
> String-2 > CountHi task

- From_Mohammed/StringNTwice.java
I need to make a function that takes a string and a number n. It should return a new string made from the first n characters and the last n characters of the given string. The string will always be at least n characters long.
> String-1 > StringNTwice  #TRA-3104

- from_Huria/ZipZapCleaner.java
The code Scans the given string for any three-character pattern starting with 'z' and ending with 'p' (e.g., "zip", "zap", "zop"). For every match, removes the middle character and keeps only "zp". All other characters in the string remain unchanged.
> TRA2913: Adding zipZap Task

- From_Mohammed/EndingChecker.java
I need to make a function that checks if a given string ends with "ly". If it does, return true, otherwise return false.
> String-1 > endsLy  #TRA-3103

- from_Ghaida/CharPairsCounter.java
This PR introduces the method countPairsInString(String str) which recursively counts the number of "pairs" in a string. A "pair" is defined as two identical characters separated by exactly one character (e.g., the first and third characters are the same).
> #TRA-3392: Recursion-1. countPairs added

- From_Mohammed/TwoCharExtractor.java
I need to write a function that takes a string and an index. It should return 2 characters starting from that index. But if the index doesn’t work (too small or too big to take 2 chars), then just return the first 2 characters of the string. The string will always be at least 2 characters long
> String-1 > TwoCharExtractor  #TRA-3106

- From_Mohammed/MiddleThreeExtractor.java
I need to make a function that takes a string of odd length and returns 3 characters from the middle of the string. The string will always be at least 3 characters long.
> String-1 > MiddleThreeExtractor  #TRA-3107

- from_Huria/StarRemover.java
The code Creates a new version of the given string by removing every asterisk (*) and the characters immediately to its left and right. This operation is applied for each * in the string, even when stars appear consecutively.
> TRA2912: Adding starOut Task

- From_Mohammed/CharExtractor.java
I need to write a function that takes a string and a boolean. If the boolean is true, return the first character of the string. If the boolean is false, return the last character. The string will always have at least 1 character.
> String-1 > CharExtractor  #TRA-3100

- From_Mohammed/EdgeRemover.java
I need to write a function that takes a string and removes both the first and last characters. The string can be any length, even empty.
> String-1 > EdgeRemover  #TRA-3101

- from_Huria/WordNeighborExtractor.java
The code Extracts the characters immediately before and after each occurrence of a specified word in the given string. If the word appears at the very start or end, missing neighbors are ignored. A character can be counted twice if it lies between two word occurrences.
> TRA3014: Adding wordEnds Task

- from_Ghaida/HiCounter.java
This PR adds the method countHiSkippingXhi(String str), which recursively counts how many times "hi" appears in a string — excluding occurrences that are immediately preceded by 'x' (i.e. "xhi" substrings are skipped entirely).
> #TRA-3399: Recursion-1. countHi2 added

- From_Horiya_Albusaidi/ArrayElementChecker.java
I created checkFirstEmenetAndLastElementEquality method that return true if the array is length 1 or more, and the first element and the last element are equal.
> TRA-3525: Solving Array-1 > sameFirstLast Task

- From_Horiya_Albusaidi/CreateArrays.java
I created createPiArray method that Return an int array length 3 containing the first 3 digits of pi, {3, 1, 4}.
> TRA-3538: Solving Array-1 > makePi Task

- From_Mulk/CodePatternCounter.java
I made a class called CodePatternCounter with a method that counts how many times a pattern like "coXe" shows up in a string — meaning it starts with "co", ends with "e", and has any letter in between. It loops through the string, checks for that pattern in 4-character sections, and returns the total count.
> String-2 > CountCode task

- From_Horiya_Albusaidi/ArraysCheckerElements.java
I created checkCommenFirstAndEndElement method that  return true if they have the same first element or they have the same last element. Both arrays will be length 1 or more.
> TRA-3582: Solving Array-1 > commonEnd

- from_shatha/ShareDigit.java
Add shareDigit function to check for common digits between two two-digit numbers
> Logic1- shareDigit task added

- From_Horiya_Albusaidi/RotateArrayElement.java
I created rotataArrayElementToLeft method that  return an array with the elements "rotated left" so {1, 2, 3} yields {2, 3, 1}.
> TRA-3584: Solving Array-1 > rotateLeft3 task

- from_Ghaida/SubInStrCounter.java
This PR adds the method countSubMatches(String str, String sub) which recursively counts the number of non-overlapping occurrences of a given substring sub within a larger string str.
> #TRA-3402: Recursion-1. strCount added

- from_shatha/RedTicket.java
Add redTicket function to evaluate result based on specific value patterns and conditions
> Logic1-redTicket task added

- From_Horiya_Albusaidi/ReverseOrder.java
I created reverseArrayElementOrder method that  return a new array with the elements in reverse order, so {1, 2, 3} becomes {3, 2, 1}.
> TRA-3585: Solving Array-1 > reverse3

- From_Horiya_Albusaidi/Summation.java
I crreated sumFirstTwoElementOfArraymethod that  return the sum of the first 2 elements in the array. If the array length is less than 2, just sum up the elements that exist, returning 0 if the array is length 0.
> TRA-3588: Solving Array-1 > sum2 task

- From_Horiya_Albusaidi/CreateArray.java
I Created arrayMadeOfMiddleElementOfAnotherArrays method that return a new array length 2 containing a and b array middle elements.
> TRA-3589: Solving Array-1 > middleWay task

- From_Mohammed/LastFirstHandler.java
I need to write a function that takes two strings, a and b. The result should be made of the first character of a and the last character of b. If one of the strings is empty, then use '@' instead of the missing character.
> String-1 > lastFirstHandler  #TRA-3112

- from_Ghaida/SubStrRangeFinder.java
This PR introduces the method findSubMatchLength(String str, String sub), which recursively computes the length of the largest substring of str that both starts and ends with the substring sub.
> #TRA-3404: Recursion-1. strDist added

- from_shatha/LastDigitt.java
Add lastDigit function to check for matching rightmost digits among three numbers
> Logic1-lastDigit task added

- from_shatha/InOrderEqual.java
Add inOrderEqual function with optional equality allowed via equalOk flag
> Logic1-inOrderEqual task added

- from_shatha/InOrder.java
Implement inOrder check with optional b > a condition based on bOk flag
> Logic1-inOrder task added

- from_shatha/TwoAsOne.java
Add twoAsOne to check if any two values sum to the third
> Logic1-twoAsOne task added

- from_shatha/FizzStringTwo.java
Add fizzString2 to return Fizz/Buzz logic with exclamation
> fizzString2 task added

- from_shatha/FizzString.java
Add fizzString logic based on starting and ending characters
> Logic1-fizzString task added

- from_Hawraa/TwosSumToEight.java
Added sumOfTwosIsEight() method that iterates through an integer array, sums all values equal to 2, and returns true if the total is exactly 8; otherwise returns false.
> TRA-3341-: Array-2: sum28 added

- from_shatha/AnswerCell.java
Add answerCell to determine if a phone call should be answered based on time, caller, and sleep status.
> Logic1-answerCell task added

- from_hanin/ArrayRangeCalculator.java
The method takes an array of integers and finds the difference between the largest and smallest values in the array. It starts by assuming the first element is both the minimum and maximum, then loops through the rest of the array, updating the min and max values as needed. After the loop, it returns the difference between the max and min values.
> TRA- 3627: Array-2 > bigDiff

- from_Hawraa/CenteredAverage.java
I implemented the calculateCenteredAverage() method that finds the centered average of an integer array by summing all elements, removing the largest and smallest values, and dividing the remaining sum by the count of elements left.
> TRA-3336: Array-2: centeredAverage added

- from_Kaltham/CigarPartyChecker.java
I created a class called CigarPartyChecker with a method named isSuccessfulParty that takes two inputs: an integer cigars and a boolean isWeekend.
The method checks if a cigar party is successful.
How it works:
If it is a weekend, the party is successful if there are 40 or more cigars.
If it is not a weekend, the party is successful only if there are between 40 and 60 cigars, inclusive.
The method returns true if the party is successful and false if it is not.
> TRA-3245: Logic-1 >=The solution for cigarParty Task

- from_hanin/TwoPatternFinder.java
The  method checks if the array contains a pair of consecutive 2s. It loops through the array up to the second-to-last element, and if it finds two adjacent elements both equal to 2, it returns true immediately. If no such pair is found, the method returns false.
> TRA- 3633: Array-2 > has22

- from_hanin/SpecificSumChecker.java
The  method checks if the sum of all 2s in an array equals 8. It loops through the array, adding 2 to the sum each time it finds a 2. After processing all elements, it returns true if the total sum of 2s is exactly 8, otherwise it returns false.
> TRA- 3635: Array-2 > sum28

- from_hanin/OneFourCounter.java
The method checks whether the number of 1s in an array is greater than the number of 4s. It loops through the array, counting how many times 1 and 4 appear. After the loop, it returns `true` if there are more 1s than 4s; otherwise, it returns `false`. *(Note: There are small typos in the variable names — `conutFour` and `conutOne` should be `countFour` and `countOne`.)*
> TRA- 3636: Array-2 > more14

- from_Hawraa/SumCalculator.java
I implemented the sumIgnoringSixToSeven() method, that computes the sum of an integer array while ignoring any sections that start with a 6 and extend through the next 7.
> TRA-3338: Array-2: sum67 added

- from_Hawraa/ArrayChecker.java
I implemented the hasDoubleTwo() method that checks if the given array contains two consecutive 2’s and returns true if found, otherwise false.
> TRA-3339: Array-2: has22 added

- from_Hawraa/ArrayWithoutOneOrThree.java
I implemented the withoutOneOrThree method that returns true if the array does not contain the numbers 1 or 3, and false otherwise.
> TRA-3340: Array-2: luky13 added

- from_Hawraa/ArrayBuilder.java
I implemented the createIndexArray method in the ArrayBuilder class, which generates an integer array of size n where each element is set to its index value (0 to n-1).
> TRA-3343: Array-2 : fizzArray added

- from_Kaltham/SumEvaluator.java
I created a class called SumEvaluator with a method named calculateSum that takes two integers, a and b.
The method calculates their sum but has a special rule.
How it works:
It adds a and b to get sum.
If the sum is between 10 and 19, it returns 20 instead of the actual sum.
Otherwise, it returns the normal sum.
> TRA-3249: Logic-1 >=The solution for sortaSum Task

- from_hanin/ValuePresenceChecker.java
The method checks whether a given value `val` appears in **every pair of adjacent elements** in the array. It loops through the array, looking at each consecutive pair (`nums[i]` and `nums[i + 1]`), and if **neither** element in a pair is equal to `val`, it returns `false`. If all adjacent pairs contain the value at least once, the method returns `true`.
> TRA- 3641: Array-2 > isEverywhere

- from_hanin/ArrayDifferenceCounter.java
The method compares two integer arrays of the same length and counts how many times the numbers at the same index differ by **1 or 2** (but are **not equal**). It loops through both arrays, calculates the absolute difference at each index, and if the difference is 1 or 2 (i.e., `<= 2` but not 0), it increments the counter. Finally, it returns the total count of such "close but not equal" matches.
> TRA- 3643: Array-2 > matchUp

- from_hanin/SevensChecker.java
The  method checks whether the number 7 appears twice, either as two consecutive elements or with one number in between. It loops through the array and, at each index, checks if there is a 7 followed immediately by another 7 (nums[i] == 7 && nums[i + 1] == 7), or a 7 with exactly one element between (nums[i] == 7 && nums[i + 2] == 7). If either condition is true, the method returns true. If no such pattern is found, it returns false.
> TRA- 3644: Array-2 > has77

- from_hanin/ParityTripletChecker.java
The  method checks whether the array contains **three consecutive even numbers** or **three consecutive odd numbers**. It loops through the array up to the third-to-last element, and at each index, it checks if the current number and the next two are all even (`% 2 == 0`) or all odd (`% 2 != 0`). If it finds such a sequence, it returns `true`. If no such pattern is found by the end of the loop, it returns `false`.
> TRA- 3646: Array-2 > modThree

- From_Mulk/StringMixer.java
I made a class called StringMixer with a method that takes two strings and merges them by alternating their characters. It goes through both strings up to the length of the shorter one, adds characters from each, then adds the leftover part from the longer string at the end.
> String-2 > MixString task

- from_hanin/ThreeCountChecker.java
The  method checks if the number **3 appears exactly three times** in the array, and **no two 3s are adjacent**. It loops through the array, counts how many times 3 appears, and if it ever finds two 3s next to each other, it immediately returns `false`. After the loop, it returns `true` only if exactly three non-adjacent 3s were found.
> TRA-3647: Array-2 > haveThree

- from_Ghaida/GroupSumChecker.java
This pull request adds a Java implementation of a recursive method canReachTarget, which determines if it is possible to select a group of integers from a given array that adds up to a specified target sum.
> #TRA-3590: Recursion-2. groupSum added

- from_Kaltham/LoveSixChecker.java
I created a class called LoveSixChecker with a method named isLoveSix that takes two integers, a and b.
The method checks if the number 6 is involved in the inputs.
How it works:
It returns true if:
Either number is 6
Their sum is 6
Their difference is 6
> TRA-3251: Logic-1 >=The solution for love6 Task

- from_hanin/NumberSequence.java
The  method creates and returns a new integer array containing a sequence of numbers starting from `start` up to (but not including) `end`. It calculates the length of the new array as `end - start`, then fills the array with consecutive integers beginning at `start`.
> TRA- 3651: Array-2 > fizzArray3

- from_hanin/ArrayShift.java
The method shifts all elements in the array one position to the left, moving the first element to the end. If the array has one or no elements, it returns the array unchanged. Otherwise, it saves the first element, moves each element one step left, and places the saved first element at the end before returning the modified array.
> TRA-3652: Array-2 > shiftLeft

- from_Kaltham/SpecialNumberChecker.java
I created a class called SpecialNumberChecker with a method named isSpecial that takes an integer n.
The method checks if the number is special based on division by 11.
How it works:
If n is a multiple of 11 (n % 11 == 0) → return true.
If n leaves a remainder of 1 when divided by 11 (n % 11 == 1) → return true.
Otherwise, return false.
> TRA-3253: Logic-1 >=The solution for specialEleven Task

- from_Kaltham/NearMultipleChecker.java
I created a class called NearMultipleChecker with a method named isNearMultipleOfTwenty that takes an integer n.
The method checks if the number is close to a multiple of 20.
How it works:
If n leaves a remainder of 1 or 2 when divided by 20, the method returns true.
> TRA-3254: Logic-1 >=The solution for more20 Task

- from_hanin/ZeroReplacer.java
The  method replaces each 0 in the array with the largest odd number that appears **to the right** of that zero. It loops through the array, and when it finds a zero, it searches forward for the biggest odd number. If it finds one, it replaces the zero with that number; if no odd number is found, the zero remains unchanged. The method returns the updated array.
> TRA- 3659: Array-2 > zeroMax

- From_Mulk/SeparatedWordRepeater.java
I created a class called SeparatedWordRepeater that has a method to repeat a word multiple times with a separator between each repeat. It loops based on the count and adds the word each time, adding the separator only between the words, not at the end.
> String-2 > RepeatSeparator task

- from_hanin/EvenOddSeparator.java
The  method rearranges the array so that all even numbers come first, followed by all odd numbers, while preserving their original order within each group. It creates a new array, first fills it with all the even numbers in order, then adds the odd numbers after them. Finally, it returns the new arranged array.
> TRA-3660: Array-2 > evenOdd

- From_Mulk/PrefixRepeater.java
I made a class called PrefixRepeater with a method that checks if the prefix (first n characters) of a string appears again later in the string. It grabs the prefix and then loops through the rest of the string to see if that same prefix shows up again. If it does, it returns true.
> String-2 > PrefixAgain task

- From_Mulk/IsXyzInMiddle.java
I made a class called IsXyzInMiddle with a method that checks if "xyz" appears in the middle of the string. It looks for every "xyz" in the string and compares the number of characters on the left and right. If the difference between them is 0, 1, or -1, it returns true.
> String-2 > XyzMiddle task

- from_Kaltham/CloseToTenChecker.java
I created a class called CloseToTenChecker with a method named isNearMultipleOfTen that takes an integer num.
The method checks if the number is close to a multiple of 10.
How it works:
If num leaves a remainder of 0, 1, 2, 8, or 9 when divided by 10, the method returns true.
> TRA-3257: Logic-1 >=The solution for nearTen Task

- From_Mulk/CheckStarNeighbors.java
I created a class called CheckStarNeighbors with a method that makes sure every star (*) in a string is “balanced” by having the same character immediately before and after it. If it finds any star with different neighbors, it returns false; otherwise, it returns true.
> String-2 > SameStarChar task

- From_Mulk/ThreeCharRotator.java
I made a class called ThreeCharRotator with a method that takes the string and moves the first character of every group of three characters to the end of that group. It processes the string in piece of three and rearranges each piece by shifting the first character to the end.
> String-2 > OneTwo task

- from_Ghaida/GroupSumWithClumps.java
This PR implements a recursive solution to the classic groupSumClump problem from Recursion-2. The method determines if it's possible to choose a group of numbers from an array such that their sum equals a target value — with the added constraint that adjacent equal values must be chosen or skipped as a group (a "clump").
> #TRA-3594: Recursion-2. groupSumClump added

- from_Kaltham/FizzBuzzNumber.java
I created a class called FizzBuzzNumber with a method named getFizzBuzz that takes an integer n.
The method returns a string based on whether n is a multiple of 3, 5, or both.
How it works:
If n is divisible by 3 and 5, it returns "FizzBuzz!".
If n is divisible by 3 only, it returns "Fizz!".
If n is divisible by 5 only, it returns "Buzz!".
Otherwise, it returns the number itself with an exclamation mark (e.g., "7!").
> TRA-3281: Logic-1 >=The solution for fizzString2 Task

- from_Kaltham/OrderChecker.java
I created a class called OrderChecker with a method named isInOrder that takes three integers (a, b, c) and a boolean bOk.
The method checks if the numbers are in increasing order, with a special rule for bOk.
How it works:
If bOk is false → the numbers must be in strict order: a < b < c.
If bOk is true → only c > b is required, and b does not need to be greater than a.
The method returns true if the condition is satisfied, otherwise false.
> TRA-3292: Logic-1 >=The solution for inOrder Task

- from_Ghaida/SplitArrayEqualSum.java
Implemented canBeSplitEqually that determine if it is possible to split the array into two groups such that the sums of the two groups are equal. Every integer must be assigned to one of the two groups.
> #TRA-3596: Recursion-2. splitArray added

- from_Kaltham/OrderEqualityChecker.java
I created a class called OrderEqualityChecker with a method named isInOrderEqual that takes three integers (a, b, c) and a boolean equalOk.
The method checks if the numbers are in increasing order, with a special rule for equality.
How it works:
If equalOk is false → the numbers must be in strict increasing order: a < b < c.
If equalOk is true → the numbers can be increasing or equal: a ≤ b ≤ c.
The method returns true if the condition is satisfied, otherwise false.
> TRA-3293: Logic-1 >=The solution for inOrderEqual Task

- from_Kaltham/LastDigitChecker.java
I created a class called LastDigitChecker with a method named haveSameLastDigit that takes three integers: a, b, and c.
The method checks if any two of the numbers share the same last digit.
How it works:
It compares the last digit of each number using % 10.
If a and b, or a and c, or b and c have the same last digit, it returns true.
Otherwise, it returns false
> TRA-3294: Logic-1 >=The solution for lastDigit Task

- from_Kaltham/DifferenceChecker.java
I created a class called DifferenceChecker with a method named isLessByTen that takes three integers: a, b, and c.
The method checks if any number is at least 10 less than another number.
How it works:
It compares all pairs of numbers.
If any number is 10 or more less than another, it returns true.
> TRA-3295: Logic-1 >=The solution for lessBy10 Task

- from_Kaltham/DiceSumCalculator.java
I created a class called DiceSumCalculator with a method named sumDice that takes two integers (die1 and die2) and a boolean noDoubles.
The method calculates the sum of two dice with a special rule about doubles.
How it works:
If noDoubles is false → it normally returns die1 + die2.
If the dice show the same number and noDoubles is true, it increases die1 by 1 before adding, except when both are 6, then it returns 7.
The method returns the sum as an integer.
> TRA-3298: Logic-1 >=The solution for withoutDoubles Task

- from_Kaltham/MaxModCalculator.java
I created a class called MaxModCalculator with a method named maxModFive that takes two integers: a and b.
The method compares the numbers with a special rule using the remainder when divided by 5.
How it works:
If a and b are equal, it returns 0.
If a and b have the same remainder when divided by 5, it returns the smaller number.
Otherwise, it returns the larger number.
> TRA-3325: Logic-1 >=The solution for maxMod5 Task

- From_Mulk/WordMasker.java
This method replaces all characters in a string with plus signs ('+'), except for occurrences of a specified word, which remain unchanged. It scans the string, identifies each instance of the word, and keeps it while masking everything else. The result is a new string highlighting only the given word.
> String-2 > PlusOut task

- from_Ghaida/SplitByThreeAndFive.java
This PR implements a recursive method canSplitByThreeAndFive to determine if an integer array can be split into two groups with equal sums, respecting these specific constraints:
-All multiples of 5 must be assigned to one group.
-All multiples of 3 (that are not multiples of 5) must be assigned to the other group.
-Numbers not divisible by 3 or 5 can be assigned to either group.
> #TRA-3601: Recursion-2. split53 added

- from_Kaltham/RedTicketGame.java
I created a class called RedTicketGame with a method named getRedTicketScore that takes three integers: a, b, and c.
The method calculates a score for a red ticket game based on the numbers.
How it works:
If all numbers are 2, the score is 10.
If all numbers are the same (but not all 2), the score is 5.
If b and c are different from a, the score is 1.
Otherwise, the score is 0.
> TRA-3326: Logic-1 >=The solution for redTicket Task

- from_Kaltham/GreenTicketGame.java
I created a class called GreenTicketGame with a method named getGreenTicketScore that takes three integers: a, b, and c.
The method calculates a score for a green ticket game based on the numbers.
How it works:
If all numbers are the same, the score is 20.
If any two numbers are the same, the score is 10.
If no numbers are the same, the score is 0.
> TRA-3327: Logic-1 >=The solution for greenTicket Task

- from_Kaltham/BlueTicketGame.java
I created a class called BlueTicketGame with a method named getBlueTicketScore that takes three integers: a, b, and c.
The method calculates a score for a blue ticket game based on the sums of pairs of numbers.
How it works:
It calculates the sums of a + b, b + c, and a + c.
If any sum is exactly 10, the score is 10.
If a + b is 10 more than b + c or a + c, the score is 5.
Otherwise, the score is 0.
> TRA-3328: Logic-1 >=The solution for blueTicket Task

- from_Ghaida/MapValueMoverToB.java
This pull request introduces the moveAtoB method to replicate the behavior described in the "mapBully" problem. The goal is to manipulate a map such that if the key "a" exists, its value is moved to key "b", and the value for "a" is set to an empty string ("").
> #TRA-3744: map-1. mapBully added

- From_Mulk/IgnoreCaseRemover.java
This method removes all occurrences of a specified substring from a base string, ignoring case differences. It repeatedly finds the substring regardless of letter casing and deletes it until none remain. The final string without the specified substring is then returned.
> String-3 > WithoutString task

- from_hanin/ArraySpanCalculator.java
This code finds the maximum span in an array, where a span is the number of elements between the first and last occurrence of the same value (inclusive). It uses two nested loops: the outer loop picks a starting index, and the inner loop searches from the end of the array back to that index for the same value. When a match is found, it calculates the span and updates the maximum span if the new one is larger. Finally, it returns the largest span found.
> TRA- 3730: Array-3 > maxSpan

- from_Huria/RestaurantFashionRules.java
The code decide your chances of getting a restaurant table based on the style ratings (0–10) of you and your date:
If either rating is 2 or less, the answer is 0 (No).
If either rating is 8 or more, the answer is 2 (Yes).
Otherwise, it’s 1 (Maybe).
> TRA3597: Adding dateFashion Task

- From_Mulk/GGroupChecker.java
This method checks if every 'g' in the string has at least one adjacent 'g' either before or after it. It returns false as soon as it finds a 'g' that stands alone, and true if all 'g's are grouped together. The check is case-insensitive.
> String-3 > GHappy task

- from_hanin/ArraySubsetChecker.java
This code checks whether all elements in the `inner` array appear in order within the `outer` array. It uses a pointer `j` to track progress through `inner`. As it loops through `outer`, it advances `j` each time a matching element is found. If `j` reaches the end of `inner`, it means all inner elements were found in order, so it returns `true`; otherwise, it returns `false`.
> TRA-3734: Array-3 > linearIn

- From_Mulk/CountTriple.java
This method counts how many times a character appears three times consecutively in a string. It scans through the string and increments the count each time it finds such a triple sequence. The total count is returned at the end.
> String-3 > CountTriple task

- from_hanin/ClumpCounter.java
This code counts groups of two or more adjacent identical numbers ("clumps") in the array. It scans through the array, detecting when a new clump starts and making sure not to count the same clump multiple times. The total number of clumps found is then returned.
> TRA-3738: Array-3 > countClumps

- From_Horiya_Albusaidi/ChangeCharacterOfWords.java
I created replaceXWithY that compute recursively (no loops) a new string where all the lowercase 'x' chars have been changed to 'y' chars.
> TRA-3790: Solving Recursion-1 > changeXY Task

- From_Alharith/EqualIsNot.java
Given a string, return true if the number of times "is" appears equals the number of times "not" appears. The comparison is case-sensitive.
> #TRA-3422: String3_ EquallsNot Done

- From_Mulk/CommonEndsFinder.java
This method checks for the longest matching substring that appears at both the beginning and end of the input string. It compares prefixes and suffixes of equal length and updates the result when a match is found. The final result contains this common part.
> String-3 > SameEnds task

- from_Kaltham/LoneSumCalculator.java
- from_Kaltham/NoTeenSumCalculator.java
I created a class called LoneSumCalculator with a method named calculateLoneSum that takes three integers: a, b, and c.
The method calculates a “lone sum,” which only includes numbers that are not repeated.
How it works:
If all numbers are different, it returns the sum of a + b + c.
If a number is unique (not equal to the others), it returns that number.
If all numbers are the same, it returns 0.
> TRA-3405: Logic-2 >=The solution for loneSum Task

- from_Huria/SquirrelPlayRules.java
The code determine if the squirrels are playing based on the temperature and season:
Normally, squirrels play if the temperature is between 60 and 90 inclusive.
During summer, the upper limit rises to 100.
Return true if the squirrels are playing, false otherwise.
> TRA3598: Adding squirrelPlay Task

- From_Alharith/SumDigits.java
Given a string, calculate the sum of all digit characters (0–9) that appear in it, ignoring all other characters. If there are no digits, return 0. Use Character.isDigit(char) to identify digits and Integer.parseInt(string) to convert them to integers.
> #TRA-3434: String3_ SumDigits Done

- From_Alharith/MaxBlock.java
Given a string, return the length of the largest block, where a block is a sequence of consecutive identical characters.
> #TRA-3443: String3_ MaxBlock Done

- from_Kaltham/LuckySumCalculator.java
I created a class called LuckySumCalculator with a method named calculateLuckySum that takes three integers: a, b, and c.
The method calculates a sum but ignores numbers after 13.
How it works:
If a is 13, the sum is 0.
If b is 13, the sum is just a.
If c is 13, the sum is a + b.
Otherwise, it returns the sum of a + b + c.
> TRA-3400: Logic-2 >=The solution for luckySum Task

- from_Kaltham/TeenNumberFilter.java
I created a class called TeenNumberFilter with a method named calculateFilteredSum that takes three integers: a, b, and c.
The method calculates the sum of the numbers but ignores most “teen” numbers.
How it works:
It uses a helper method fixTeen for each number.
If a number is a teen (13–19) except 15 or 16, it counts as 0.
Otherwise, the number is counted normally.
Finally, it returns the sum of the three numbers after applying the teen rule.
> TRA-3381: Logic-2 >=The solution for noTeenSum Task

- from_Kaltham/RoundSumCalculator.java
I created a class called RoundSumCalculator with a method named calculateRoundedSum that takes three integers: a, b, and c.
The method calculates the sum of the numbers after rounding each one to the nearest 10.
How it works:
It uses a helper method roundToNearestTen for each number.
If the last digit is 5 or more, the number is rounded up to the next 10.
If the last digit is less than 5, the number is rounded down to the previous 10.
Finally, it adds the three rounded numbers and returns the total.
> TRA-3415: Logic-2 >=The solution for roundSum Task

- from_Ghaida/WordLengthMap.java
This PR adds the method createWordLengthMap, which takes an array of strings and returns a map where each unique word is mapped to its length. 
-Each unique word appears once as a key.
-Each key is associated with the length of that word.
-Duplicate words are ignored after their first occurrence.
> #TRA-3820: Map-2. wordLen added

- from_Ghaida/FirstLastCharMap.java
This PR adds the method mapFirstToLastChar, which constructs a map from an array of strings by using the first character of each string as the key and the last character as the value.
-For each string in the input array:
-Uses the first character as the map key.
-Uses the last character as the map value.
If multiple strings share the same starting letter, the last one encountered determines the final mapping (overwrites previous).
> #TRA-3821: Map-2. pairs added

- From_Mulk/RepeatingCharAnalyzer.java
I wrote a Java method that checks a string and returns the length of the longest sequence of repeating characters by comparing each character with the next and tracking the highest repeat count.
> String-3 > MaxBlock task

- from_Kaltham/BlackjackGame.java
I created a class called BlackjackGame with a method named getBestScore that takes two integers: a and b.
The method returns the best score in a blackjack-style game, where the goal is to be as close as possible to 21 without going over.
How it works:
If both numbers are 21 or less, it returns the larger number.
If a is over 21 but b is 21 or less, it returns b.
If b is over 21 but a is 21 or less, it returns a.
If both are over 21, it returns 0.
> TRA-3463: Logic-2 >=The solution for blackjack Task

- from_Huria/SpecialSumRules.java
The code add two integers a and b, but with a twist:
If the sum is between 10 and 19 inclusive, return 20 instead.
Otherwise, return the normal sum.
> TRA3602: Adding sortaSum Task

- from_Kaltham/EvenlySpaced.java
I created a class called EvenlySpaced with a method named isEvenlySpaced that takes three integers: a, b, and c.
The method checks if the numbers are evenly spaced (like being in a straight line with equal gaps).
How it works:
It finds the smallest, largest, and middle values from the three numbers.
It checks if the distance from the middle to the smallest is the same as the distance from the middle to the largest.
If the distances are equal, it returns true; otherwise, it returns false.
> TRA-3564: Logic-2 >=The solution for evenlySpaced Task

- from_Kaltham/ChocolateMaker.java
I created a class called ChocolateMaker with a method named makeChocolate that takes three integers: small, big, and goal.
The method calculates how to reach a goal amount of chocolate using small bars (1 kg) and big bars (5 kg).
How it works:
It uses as many big bars as possible without exceeding the goal.
It calculates the remaining amount to reach the goal.
If the remaining amount can be covered by small bars, it returns that number.
If it’s not possible to reach the goal, it returns -1.
> TRA-3587: Logic-2 >=The solution for makeChocolate Task

- From_Mulk/SumNumbers.java
I created a Java method that goes through a string and adds up all the whole numbers found in it. It builds numbers from continuous digits, it converts the collected digits into an integer and adds it to the sum. At the end, it also checks if there’s a number left to add before returning the total sum.
> String-3 > SumNumbers task

- from_Huria/GreatNumberSix.java
The code return true if either value is 6.
Return true if their sum is 6.
Return true if their difference (absolute) is 6.
Otherwise, return false.
> TRA3604: Adding love6 Task

- from_Ghaida/WordEvenAppender.java
This PR introduces the method appendEverySecondOccurrence, which constructs a string by appending each word from the input array on every even-numbered appearance. 
-Tracks how many times each word has appeared using a Map<String, Integer>.
-Each time a word is seen for the second, fourth, sixth, etc. time, it's appended to the result.
-Returns the final constructed string.
> #TRA-3825: Map-2. wordAppend added

- From_Mulk/NotReplace.java
I created a Java method that finds the exact word "is" in a string and changes it to "is not," making sure it doesn’t affect words that contain "is" as part of them.
> String-3 > NotReplace task

- from_Ghaida/WordMultipleMap.java
This PR adds the method trackWordDuplicates, which returns a map indicating whether each unique word in an input array appears multiple times. 
-For each word:
-If it's the first occurrence, map it to false.
-If it's seen again, update the map value to true.
-Returns the final map with all word duplication statuses.
> #TRA-3826: Map-2. wordMultiple added

- from_Huria/IsNumberWithinFlexibleRange.java
The code check if a number n falls within the range 1 to 10 inclusive.
Normally, return true if 1 ≤ n ≤ 10.
If outsideMode is true, return true instead when n ≤ 1 or n ≥ 10.
> TRA3605: Adding in1To10 Task

- from_Hawraa/ZeroToNStringArray.java
I implemented generateStringArray(int n) method, that returns an array of strings representing numbers from 0 to n-1
> TRA-3345: Array-2: fizzArray2 added

- from_Huria/IsOneOrTwoMoreThanMultipleOfTwenty.java
The code Check if a given non-negative number is 1 or 2 greater than a multiple of 20.
Return true if it satisfies the rule, otherwise return false.
> TRA3607: Adding more20 Task
