daniyalmehmood/code_creators_git

- from_Huria/MultipleOfThreeOrFiveChecker.java
The code return true if the given non-negative number is a multiple of 3 or a multiple of 5, but not both at the same time.
This is an exclusive check using the % (mod) operator.
> TRA3608: Adding old35 Task

- From_Manal/FactorialCalculator.java
This Methode to return the factorial of n, which is n * (n-1) * (n-2) ... 1. Compute the result recursively (without loops).
> TRA-3739: Recursion-1/Factorial

- from_Ghaida/TripleCopiesOfString.java
This PR adds the tripleStrings method, which modifies a list of strings by replacing each string with three copies concatenated together.
> #TRA-3877: Functional-1. copies3 added

- from_Huria/MultipleOfTenChecker.java
The code check if a given non-negative number is within 2 units of a multiple of 10.
Return true if it is close to a multiple of 10, otherwise return false.
> TRA3610: Adding nearTen Task

- from_Huria/TeenSumCalculator.java
The code compute the sum of two integers a and b with a special rule for “teen” values (13–19):
If either number is a teen, return 19.
Otherwise, return the normal sum.
> TRA3611: Adding teenSum Task

- From_Shaima/StringEndingChecker.java
The code returns true if one string appears at the very end of the other.
> TRA3836 :endOther--Closed Ending Match

- from_Ghaida/RightMostDigit.java
This PR implements the method getRightDigits which transforms each integer in a list by extracting its rightmost digit (using modulo 10).
> #TRA-3881: Functional-1. rightDigit added

- From_Shaima/SubstringCounter.java
The code counts how many times the exact sequence "hi" appears.
> TRA3834: countHi-- Hi Counter

- From_Horiya_Albusaidi/DoublingValues.java
I created doublingArrayElement method that return a list where each integer is multiplied by 2.
> TRA-3885: Solving Functional-1 > doublingTask

- from_Ghaida/RemoveLetterX.java
This PR implements the method removeXFromStrings which removes every 'x' character from each string in a list.
> #TRA-3883: Functional-1. noX added

- from_Huria/TeaAndCandyPartyEvaluator.java
The code decides the success of a party based on the amounts of tea and candy.
Bad (0): If either tea or candy is less than 5.
Good (1): If both are at least 5.
Great (2): If one is at least double the other (while both are still ≥ 5).
Encodes party quality into a single outcome: 0 = Bad, 1 = Good, 2 = Great.
> TRA3613: Adding teaParty Task

- From_Mulk/CenteredAverage.java
I wrote a Java method that calculates the “centered” average of an integer array by summing all numbers, removing the largest and smallest values, and then dividing by the count of the remaining elements.
> Array-2 > CenteredAveragef task

- From_Shaima/SurroundingCharsExtractor.java
The code extracts the characters immediately before and after each occurrence of a specified word in the given string.
> TRA3832: wordEnds--Neighbor Characters Around Word

- From_Horiya_Albusaidi/MultiplicationProcess.java
I created multipliedArrayElementWithItSelf method that return a list where each integer is multiplied with itself.
> TRA-3896: Solving Functional-1 > square Task

- From_Horiya_Albusaidi/AddingChars.java
I created addStarToArrayElement method that return a list where each string has "*" added at its end.
> TRA-3902: Solving Functional-1 > addStar Task

- from_Huria/FizzBuzzFormatter.java
The code formats a number into a fun FizzBuzz-style string:
If divisible by 3, return "Fizz!".
If divisible by 5, return "Buzz!".
If divisible by both 3 and 5, return "FizzBuzz!".
Otherwise, return the number followed by "!".
> TRA3615: Adding fizzString2 Task

- From_Shaima/CharacterDoubler.java
The code creates a new string where every character from the original appears twice in a row.
> TRA3833: doubleChar--Double Trouble

- from_Huria/NumberSequenceValidator.java
The code validates whether three integers form an increasing sequence:
By default, the numbers must be in strictly increasing order (a < b < c).
If equalOk is true, equality between numbers is allowed (a ≤ b ≤ c).
> TRA3618: Adding inOrderEqual Task

- from_Hawraa/NearMatchCounter.java
I Implemented the method countNearMatches(int[] nums1, int[] nums2) to count how many elements at corresponding positions in the two arrays differ by 1 or 2
> TRA-3349: Array-2: matchUp added

- From_Horiya_Albusaidi/CopyStrings.java
I created copiesStringThreeTimes method that return return a list where each string is replaced by 3 copies of the string concatenated together.
> TRA-3905: Solving Functional-1 > copies3 Task

- From_Horiya_Albusaidi/AddingLetters.java
I created addLetterYToStartAndEndOfString method that  return a list where each string has "y" added at its start and end.
> TRA-3906: Solving Functional-1 > moreY Task

- from_Huria/DifferenceAtLeastTen.java
The code determines whether the difference between any two of the given integers is 10 or more. Returns true if such a gap exists, otherwise false.
> TRA3620: Adding lessBy10 Task

- From_Shaima/XyBalanceChecker.java
The code returns true if every 'x' in the string gets its perfect 'y' partner somewhere to the right.
> TRA3839: xyBalance--The XY Balance Inspector

- From_Horiya_Albusaidi/MathOperation.java
I created addingOneToArrayElementAndMultiplyWithTen method that  return a list where each integer is added to 1 and the result is multiplied by 10.
> TRA-3909: Solving Functional-1 > math1 Task

- From_Mulk/SumCalculator.java
I wrote a Java method that sums the numbers in an array while ignoring any sections that start with 6 and go through to the next 7, by skipping all values from 6 up to and including 7 during the loop.
> Array-2 > Sum67 task

- from_Huria/SumWithoutDoubles.java
The code calculates the sum of two 6-sided dice rolls:
Normally, returns the sum of the two dice.
If noDoubles is true and both dice show the same value, increment one die by 1 (wrapping 6 → 1) before summing.
> TRA3621: Adding withoutDoubles Task

- from_Ghaida/NoEndingNine.java
This PR implements the method removeNumbersEndingWithNine, which removes all integers from the input list whose last digit is 9.
-Uses List.removeIf() to filter out numbers ending in 9.
-Checks each number with number % 10 == 9.
-Modifies the list in-place and returns it.
> #TRA-3898: Functional-2. no9 added

- From_Mulk/HasContinuousTwos.java
I wrote a Java method that checks if an array contains two Continuous 2s by looping through the elements and returning true as soon as it finds two 2s in a row, otherwise returning false.
> Array-2 > Has22 task

- from_Huria/CalculateTicketScore.java
The code calculates the score of a red lottery ticket based on its three values (a, b, c, each 0, 1, or 2):
10 points: All values are 2.
5 points: All values are the same (but not all 2).
1 point: Both b and c are different from a.
0 points: Any other combination.
> TRA3623: Adding redTicket Task

- from_Ghaida/NoTeenNumbers.java
This PR implements the method removeTeenNumbers, which removes all "teen" numbers (13 through 19 inclusive) from a list of integers.
> #TRA-3899: Functional-2. noTeen added

- From_Horiya_Albusaidi/RemoveCharactars.java
I created removeXLetterFromElement method that return a list where each string has all its "x" removed.
> TRA-3911: Solving Functional-1 > noX Task

- from_Huria/DigitMatcher.java
The code determines whether two two-digit integers (10..99) share at least one digit.
Use n / 10 to get the left digit.
Use n % 10 to get the right digit.
Returns true if any digit appears in both numbers, otherwise false.
> TRA3626: Adding shareDigit Task

- From_Shaima/StringFrontRepeater.java
The code builds a cascading string by starting with the first n characters, then the first n-1, down to one.
> TRA3841 :repeatFront--Front & Center Cascade

- from_Ghaida/NoDoubleYChecker.java
Implement addYRemoveDoubleY to append 'y' and remove strings containing 'yy'.
-Appends the character 'y' to each string in the list.
-Removes any string containing the substring "yy".
> #TRA-3904: Functional-2. noYY added

- From_Shaima/PrefixChecker.java
The code returns true if the prefix of length N from the start of a string appears again later in the same string.
> TRA3851 : prefixAgain--Prefix Replay Check

- From_Shaima/StarCharacterChecker.java
The code returns true if every * in a string has matching characters on both sides
> TRA3849 :sameStarChar--Star-Matched Neighbors

- From_Mulk/SumTwo.java
- From_Mulk/SumTwoCalculator.java
I wrote a Java method that checks if the total sum of all 2s in an array equals 8 by adding 2 for each occurrence and returning true if the sum matches 8, otherwise false.
> Array-2> Sum28 task

- from_Ghaida/ScoresIncreasingChecker.java
Implemented scoresIncreasing method which:
-Iterates through the array of scores
-Returns false immediately if a score is found to be less than the previous score
-Returns true if the entire array is non-decreasing
> #TRA-3922: AP-1. scoresIncreasing added

- from_Hawraa/TripleSequence.java
I implemented hasTripleUpSequence(int[] nums) to check if the array contains any sequence of three consecutive increasing integers
> TRA-3357: Array-2: tripleUp added

- from_Ghaida/AdjacentHundredsChecker.java
This PR introduces a method hasConsecutiveHundreds that checks if an integer array contains two adjacent elements both equal to 100.
-Iterates through the array up to the second last element
-Returns true immediately if it finds two consecutive elements both equal to 100
-Returns false if no such adjacent pair exists
> #TRA-3923: AP-1. scores100 added

- from_Ghaida/ScoresClumpChecker.java
This PR introduces a method hasClump that checks whether an array contains any group of three consecutive integers where the difference between the first and last element is at most 2.
> #TRA-3924: AP-1. scoresClump added

- From_Mulk/OnesExceedFours.java
I wrote a Java method that counts how many 1s and 4s are in an array and returns true if there are more 1s than 4s, otherwise false.
> Array-2 > More14 task

- From_Shaima/CodeCounter.java
The code counts how many times "co_e" appears in the string.
> TRA3967 :countCode--Code (and Friends) Counter

- from_Ghaida/ScoresAverageCalculator.java
This PR adds the halfScoresAverage method which calculates the average of two halves of an integer array and returns the larger average.
-The input array is split into two halves.
-The method computes the average of each half using a helper method averageHelper.
-Returns the maximum of the two averages.
> #TRA-3925: AP-1. scoresAverage added

- from_Hawraa/RangeArrayBuilder.java
I implemented generateSequenceArray(int start, int end) to create an array containing a sequential range of integers starting from start and ending at end.
> TRA-3358: Array-2: fizzArray3 added

- from_Ghaida/CountWordsByLength.java
This PR introduces the countMatchingLength method that counts how many strings in an array have a specified length.
-Iterates over the input array of words.
-Increments a counter for each word whose length matches the given length parameter.
-Returns the count of such words.
> #TRA-3926: AP-1. wordsCount added

- From_Shaima/WordMasker.java
The code creates a masked version of the given string by replacing every character with a plus sign (+), except for exact matches of the specified word, which remain unchanged.
> TRA3969 : plusOut--Selective Masking with Word Preservation

- From_Mulk/CreateSequence.java
I wrote a Java method that creates and returns an integer array of size n, filled with a sequence of numbers starting from 0 up to n-1.
> Array-2 > FizzArray task

- From_Shaima/ArrayRotator.java
The code returns an array with the elements "rotated left" so {1, 2, 3} yields {2, 3, 1}.
> TRA2637 : RotateLeft3- Move first element to End

- from_Hawraa/ArrayShifterLeft.java
I added shiftElementLeftOnce(int[] nums) which shifts all elements in the array one position to the left, and moving the first element to the end of the array.
> TRA-3359: Array-2: shiftLeft added

- From_Mulk/OnlyOneFour.java
I wrote a Java method that checks if an array contains only 1s and 4s by scanning each element and returning false if any number other than 1 or 4 is found, otherwise true.
> Array-2> Only14 task

- from_Ghaida/FilterWords.java
This PR implements the method excludeWordsOfLength which takes an array of strings and an integer length len. It returns a new array excluding all words that have the exact length len.
> #TRA-3928: AP-1. wordsWithoutList added

- from_Hawraa/MultipleOfTenReplacer.java
I Implemented tenRun(int[] nums) that replaces every element after a multiple of 10 with that multiple, continuing until the next multiple of 10 appears.
> TRA-3360: Array-2: tenRun added

- from_Hawraa/ArrayBeforeFour.java
I implemented getPreFourElements(int[] nums), that return new array containing all elements before the first occurrence of the number 4 in the input array.
> TRA-3361: pre4 added

- From_Horiya_Albusaidi/CheckNegativeNumber.java
I created removeNegativeElement() that return a list of the integers, omitting any that are less than 0.
> TRA-4111: Solving Functional-2 > noNeg Task

- From_Mulk/SumExcludingThirteen.java
I created a Java method that calculates the sum of numbers in an array while skipping any 13 and the number immediately after it by skipping the next element in the loop whenever 13 is found.
> Array-2 > Sum13 task

- From_Manal/BunnyEarsTwo.java
This method recursively calculates the total number of ears across a given number of bunnies, assuming each bunny has exactly 2 ears. The solution avoids loops and multiplication
> TRA-3886-Recursion-1:BunnyEars

- from_Ghaida/ContainsDigitOneChecker.java
This PR adds the method hasDigitOne that checks whether a given integer contains the digit 1.
-Implements a recursive approach to evaluate each digit of the number.
-Base case: returns false if the number is 0.
-Checks if the last digit is 1, returns true if so.
-Otherwise, continues checking by recursively dividing the number by 10.
> #TRA-3929: AP-1. hasOne added

- From_Shaima/SpecialNumberChecker.java
The code returns true if the number is a multiple of 11, or one more than a multiple of 11.
> TRA4112 :specialEleven--Special Eleven Checker

- from_Ghaida/DividesSelfChecker.java
This PR adds the method isDividesSelf that determines whether an integer is "divides itself," i.e., each of its digits (except zero) divides the number without remainder.
-Returns false if the number contains any digit 0 (division by zero is invalid).
-Iterates through each digit of the number by repeatedly taking the remainder mod 10.
-Checks if the original number is divisible by each digit.
-Returns true only if all digits divide the number evenly.
> #TRA-3930: AP-1. dividesSelf added

- From_Maha/SandwichFinder.java
This method finds the first and last "bread" in the string and returns what’s inside them. If there’s no proper pair, it returns an empty string.
> Add getSandwich file

- From_Shaima/SpecialValueChooser.java
The code returns the larger of two integers with special rules:
If both numbers have the same remainder when divided by 5, return the smaller number.
If the numbers are equal, return 0.
Otherwise, return the larger number.
> TRA4128 :maxMod5--Max Value with Mod 5 Rule

- From_Shaima/AlarmScheduler.java
The code decide when the alarm should ring based on the day of the week and whether you’re on vacation.
> TRA4108 :alarmClock--⏰ Smart Alarm Time

- from_Hawraa/TenRemover.java
I implemented withoutTen(int[] nums) to remove all occurrences of the number 10 from the array, shifting the remaining elements to the left and filling the rest with 0s.
> TRA-3365: Array-2: withoutTen added

- from_Ghaida/EvenExtractor.java
This PR introduces the method extractFirstEvens which returns an array containing the first count even numbers found in the input array.
-Iterates through the input array nums.
-Checks each number to see if it's even.
-Collects the first count even numbers into a new array.
-Stops iterating early once the required number of even numbers is collected.
> #TRA-3931: AP-1. copyEvens added

- From_Mulk/ValueInPairs.java
I wrote a Java method that checks if a given value appears in every adjacent pair of elements in an array by looping through each pair and returning false if neither element in a pair matches the value; otherwise, it returns true.
> Array-2 > IsEverywhere task

- From_Shaima/RedLotteryTicketEvaluator.java
The code calculates the score of a red lottery ticket based on its three values (a, b, c, each 0, 1, or 2):
10 points: All values are 2.
5 points: All values are the same (but not all 2).
1 point: Both b and c are different from a.
0 points: Any other combination.
> #TRA-4129 :redTicket--🎟️ Red Lottery Ticket Calculator

- from_Hawraa/ArrayOddReplacer.java
I implemented replaceZeroWithMaxOddRight(int[] nums), replaces every 0 in the array with the largest odd number to its right.
> TRA-3366: Array-2: zeroMax added

- From_Shaima/BlueLotteryTicketEvaluator.java
The code Calculates the score of a blue lottery ticket based on three numbers (a, b, c) and their pair sums:
10 points: If any pair (a+b, b+c, a+c) sums to exactly 10.
5 points: If the sum of a+b is exactly 10 more than either b+c or a+c.
0 points: Any other combination.
> TRA4131 :blueTicket--🔵 Blue Lottery Ticket Pair Sum Calculator

- From_Shaima/AdjustedSumCalculator.java
The code adds two integers a and b, but with a twist: if the sum is between 10 and 19 inclusive, return 20 instead. Otherwise, return the normal sum.
> TRA4107 : sortaSum--➕ Special Sum Rules

- From_Mulk/EitherTwoOrFour.java
I wrote a Java method that checks if an array contains exactly one pair of either two 2s or two 4s by scanning for these pairs and returning false if more than one such pair is found, otherwise true.
> Array-2 > Either24 task

- From_Shaima/FizzBuzzStringChecker.java
The code transforms a given string based on its starting and ending characters:
Returns "Fizz" if the string starts with 'f'.
Returns "Buzz" if the string ends with 'b'.
Returns "FizzBuzz" if both conditions are true.
Otherwise, returns the string unchanged.
> TRA4139 :fizzString--🔤 FizzBuzz String Transformer

- from_Ghaida/EndyNumberExtractor.java
This PR introduces the method getFirstEndyNumbers which returns an array containing the first count numbers from the input array that qualify as "endy" numbers.
*Definition of Endy Number
-A number is considered "endy" if it meets either of the following conditions:
-It is between 0 and 10 (inclusive).
-It is between 90 and 100 (inclusive).
-Iterates through the input array nums.
-Uses the helper method isEndyNumber to check if a number is "endy".
-Collects the first count endy numbers into a new array.
-Stops iteration early once the required count is met.
> #TRA-3932: AP-1. copyEndy added

- From_Mulk/CountCloseValues.java
I wrote a Java method that compares two arrays and counts how many elements at the same positions differ by 2 or less but are not equal, returning the total count.
> Array-2 > MatchUpp task

- From_Maha/StarRemover.java
Removes all '*' characters from the string along with
the characters immediately next to each '*'.
> Add startOut file

- from_Hawraa/FizzBuzzGenerator.java
- Implemented the method createFizzBuzzArray(int start, int end) that generates a FizzBuzz sequence as a String[] over the range [start, end).
- For each number:
- Adds "FizzBuzz" if divisible by both 3 and 5.
- Adds "Fizz" if divisible by 3 only.
- Adds "Buzz" if divisible by 5 only.
- Otherwise, adds the number itself as a string.
> TRA-3368: Array-2: fizzBuzz added

- From_Mulk/HasSevenSeven.java
I wrote a Java method that checks if an array contains two 7s next to each other or with exactly one number between them by scanning the array and returning true if either pattern is found, otherwise false.
> Array-2 > Has77 task

- From_Maha/WordMasker.java
Replaces every character in the string with '+', except for occurrences of the given word which remain unchanged.
> Add PLUSoUT file

- from_Ghaida/ScoreCalculator.java
This PR introduces the method calculateScore, which computes a total score for a student’s answers based on a provided key.
*Scoring Rules:
+4 points for each correct answer.
-1 point for each incorrect answer.
0 points (no change) for unanswered questions (marked with "?").
> #TRA-3934: AP-1. scoreUp added

- From_Mulk/EvenOrOdd.java
I wrote a Java method that scans an array to detect if there are three even or odd numbers in a row, using counters to track consecutive numbers and returning true once three are found.
> Array-2 > ModThree task

- from_Hawraa/SpanCalculator.java
I implemented calculateMaxSpan(int[] nums) to return the largest span between equal values in the array. Run two loops within each other to evaluate index pairs and update the longest span found.
> TRA-4140: Array-3: maxSpan added

- From_Mulk/TwoTwoChecker.java
I wrote a Java method that checks if every 2 in an array is part of a pair (not isolated) by looping through the array and returning false if a 2 is not next to another 2 on either side.
> Array-2 > TwoTwo task

- from_Hawraa/BalanceArray.java
I implemented canBeBalanced(int[] nums), that return true if there is a place to split the array, so that the sum of the numbers on one side is equal to the sum of the numbers on the other side
> TRA-4143: Array-3: canBalance added

- From_Mulk/ThreeIncreasing.java
I wrote a Java method that checks if there are three increasing adjacent numbers somewhere in the array, by checking each number in the array. if we found it returns true, otherwise return false.
> Array-2 > TripleUp task

- From_Manal/SubstringChecker.java
This method to determine whether a given string contains at least n occurrences of a non-empty substring sub, allowing overlaps. The method reduces n when a match is found and advances one character at a time to check all possible positions.
> TRA-3895: Recursion-1/StrCopies

- From_Manal/ArrayCheck.java
Added a recursive method to check whether an array contains a value immediately followed by that value multiplied by 10. The method scans from a given index (starting at 0), advancing one step at a time without loops, and returns true upon the first valid match
> TRA- 3891: Recursion-1/Array220

- From_Mulk/ShiftLeft.java
I wrote a Java method that shifts all elements in an array one position to the left, moving the first element to the end, by creating a new array and copying elements accordingly.
> Array-2 > ShiftLeft task

- from_Hawraa/SquareUpArrayGenerator.java
I implemented generateSquareUpArray(int n), that return an array length n*n with the specific pattern where each row ends with increasing sequence.
> TRA-4145: Array-3: squareUp added

- from_Ghaida/SpecialScoreCalculator.java
This pull request introduces the SpecialScoreCalculator class. The solution involves finding the largest "special" score from two arrays, where a "special" score is defined as a multiple of 10.
-Added getCombinedSpecialScores(int[] a, int[] b):
-Combines the two input arrays and returns the sum of their largest special scores.
-Added helper method getLargestSpecialScore(int[] numbers):
-Iterates through each array to find the largest number divisible by 10.
> #TRA-3936: AP-1. scoresSpecial added

- From_Mulk/AfterFour.java
I wrote a Java method elementsAfterLastFour(int[] nums) that returns a new array containing all elements after the last 4 in the original array.
> Array-2 > Post4 task

- from_Ghaida/HeightChangeWithDoubleIncreases.java
This PR introduces the HeightChangeWithDoubleIncreases class. It calculates the total height change over a specified segment of an array, where increases in height are weighted double compared to decreases.
-Method: calculateWeightedHeightChange(int[] heights, int start, int end)
-Iterates from start to end - 1
-Computes the difference between each consecutive pair:
-If the height increases, the difference is doubled
-If the height decreases or remains the same, the absolute value is used
> #TRA-3938: AP-1. sumHeights2 added

- from_hanin/FactorialCalculator.java
Given an integer n (where n ≥ 1), return the factorial of n, which is the product of all positive integers from n down to 1. This should be computed recursively, meaning the function should call itself with n - 1 until it reaches the base case of n == 1, where it returns 1. For example, factorial(3) returns 3 * factorial(2), which returns 3 * 2 * factorial(1), and finally 3 * 2 * 1 = 6.
> TRA- 4216: Recursion-1 > factorial

- from_Hawraa/MaxMirrorFinder.java
I implemented  grtMaxMirrorLength(int[] nums) method, that calculate the longest mirror section in an array by checking matching sequences from both ends and updating the maximum length found.
> TRA-4147: Array-3: maxMirror added

- From_Mulk/RemoveTen.java
I wrote a Java method that returns a new array where all 10s are removed from their original positions, the remaining numbers keep their order, and zeros are added at the end to maintain the array’s length.
> Array-2 > WithoutTen task

- From_Mulk/OddMaxFill.java
I wrote a Java method that replaces every 0 in an array with the largest odd number to its right, if one exists, by scanning the array and checking for the maximum odd value after each 0.
> Array-2 > ZeroMax task

- .github/CODEOWNERS
- From_Shaima/SquirrelPartyChecker.java
The code determines if a squirrel party is successful based on the number of cigars and whether it’s the weekend.
> TRA4103: cigarParty--🎉 Squirrel Party Success Checker

- from_hanin/DigitSumHalper.java
To solve the sum of digits problem recursively, we break down the number `n` by separating its last digit and the rest. If `n` is 0, we return 0 as the base case. Otherwise, we take the rightmost digit using `n % 10` and add it to the result of the function called on the remaining digits using `n // 10`. This continues until the number becomes 0. For example, `sumDigits(126)` becomes 6 (126 % 10) + `sumDigits(12)`, then 6 + 2 (12 % 10) + `sumDigits(1)`, then 6 + 2 + 1 = 9.
> Tra 4221: Recursion-1 > sumDigits

- From_Shaima/SquirrelPlayChecker.java
The code determines if the squirrels are playing based on the temperature and season.
> TRA4104: squirrelPlay--🐿️ Squirrel Playtime Checker

- from_hanin/SevenCounter.java
To solve the problem of counting how many times the digit 7 appears in a non-negative integer `n`, we use recursion by checking one digit at a time. If `n` is 0, we return 0 as the base case. Otherwise, we check the last digit using `n % 10`. If that digit is 7, we add 1 to the result of `count7(n // 10)`. If it's not 7, we just call `count7(n // 10)` without adding. This process repeats until all digits are checked. For example, `count7(717)` checks 7 → 1, then 1 → 0, then 7 → 1, giving a total of 2.
> TRA- 4222: Recursion-1 > count7

- From_Mulk/FizzBuzzChecker.java
I wrote a Java method that generates a string array representing numbers from start to end, replacing multiples of 3 with "Fizz", multiples of 5 with "Buzz", and multiples of both with "FizzBuzz".
> Array-2 > FizzBuzz task

- From_Shaima/SpeedTicketCalculator.java
The code determines the type of ticket you’ll get based on your speed and whether is it your birthday.
> TRA4106: caughtSpeeding--🚓 Speeding Ticket Category

- From_Shaima/NumberRangeChecker.java
The code check if a number n falls within the range 1 to 10 inclusive.
> TRA4110: in1To10--🔎 Number Within One to Ten

- from_hanin/HiTracker.java
To solve the `countHi` problem recursively,  count how many times the substring `"hi"` appears in a given string. If the string is shorter than 2 characters,  return 0 as the base case because `"hi"` can't appear. Otherwise, we check if the first two characters are `"hi"`; if yes, we add 1 and call the function on the string starting from the next character after `"hi"` (to avoid overlapping) — that is, `countHi(str[2:])`. If the first two characters are not `"hi"`, we call the function on the string starting from the next character (`countHi(str[1:])`). This continues until the entire string is checked. For example, `countHi("xhixhix")` finds `"hi"` twice, so it returns 2.
> Tra 4226: Recursion-1 > countHi

- From_Shaima/TeenSumCalculator.java
The code computes the sum of two integers a and b with a special rule for “teen” values (13–19):
If either number is a teen, return 19.
Otherwise, return the normal sum.
> TRA4117: teenSum--🎲 Lucky Teen Sum Calculator

- From_Shaima/FizzBuzzStringGenerator.java
The code formats a number into a fun FizzBuzz-style string:
If divisible by 3, return "Fizz!".
If divisible by 5, return "Buzz!".
If divisible by both 3 and 5, return "FizzBuzz!".
Otherwise, return the number followed by "!".
> TRA4121 :fizzString2--🔢 FizzBuzz Number Formatter

- From_Shaima/SumChecker.java
The code checks whether any two of the given integers can be added together to exactly equal the third. Returns true if the condition holds, otherwise false.
>  TRA4122 :twoAsOne--🔢 Two-as-One Number Checker

- From_Manal/FibonacciCalculator.java
Added a recursive method getFibonacciNumber(int n) to compute the nth number in the Fibonacci sequence, starting from n = 0. The method uses two base cases (n = 0 returns 0, n = 1 returns 1) and recursively sums the previous two values for all n > 1
> TRA-4232-Recursion-1: fibonacci

- From_Shaima/LastDigitChecker.java
The code checks whether at least two out of three given non-negative integers share the same rightmost digit.
> TRA4125 :lastDigit--🔢 Matching Last Digit Checker

- From_Manal/AllStarSeparator.java
This Method compute recursively a new string where all the adjacent chars are now separated by a "*".
> TRA-4243-Recursion-1: AllStar

- From_Maha/StringRemover.java
Removes all occurrences of a target substring from the base string, ignoring case.
Preserves the order of remaining characters.
> Add withoutString file

- from_hanin/XCleanString.java
This code uses recursion to remove all `'x'` characters from a string. At each step, it checks the first character: if it's `'x'`, it skips it; otherwise, it keeps it and processes the rest of the string the same way. You solve it by writing a function that calls itself on smaller parts of the string until it's empty.
> TRA-4229: Recursion-1 > noX

- from_hanin/SixFinder.java
This code checks recursively if the number `6` exists in an integer array, starting from a given index. At each step, it checks if the current element is `6`; if so, it returns `true`. If not, it moves to the next index by calling itself with `index + 1`. The recursion continues until the end of the array. If no `6` is found, it returns `false`. You solve it by checking the current element and then recursively scanning the rest of the array.
> TRA-4230:Recursion-1 > array6

- from_hanin/StarInserter.java
This code uses  to insert a `"*"` between every pair of adjacent characters in a string. If the string has one or zero characters, it returns the string as is. Otherwise, it takes the first character, adds `"*"`, then recursively processes the rest of the string. To solve it, keep adding `"*"` between characters by combining the first character, `"*"`, and the result of the recursive call on the rest.
> TRA- 4235:Recursion-1 > allStar

- from_hanin/DuplicateSeparator.java
This code adds `"*"` between identical adjacent characters in a string using recursion. It compares the first two characters: if they match, it inserts `"*"` between them and recurses; otherwise, it moves on.
> TRA-4237:Recursion-1 > pairStar

- from_hanin/XShifter.java
This code moves all lowercase `'x'` characters to the end of the string using recursion. If the first character is `'x'`, it processes the rest of the string and adds `'x'` at the end; otherwise, it keeps the character and continues recursively.
> Tra 4238-: Recursion-1 > endX

- from_hanin/PatternFinder.java
This code counts "pairs" in a string using recursion. A pair is two matching characters with one character in between (like `'aXa'`). At each step, it checks if the current character matches the one two positions ahead. If yes, it adds 1 and recurses from the next character; if not, it just recurses.
> Tra-4240: Recursion-1 > countPairs

- from_hanin/ElevenPairCounter.java
This code counts non-overlapping `"11"` substrings in a string using recursion. At each step, it checks if the current and next characters are `"11"`; if yes, it adds 1 and skips the next character to avoid overlap, then continues recursively. Otherwise, it moves one character forward and continues.
> Tra-4245:Recursion-1 > count11

- from_hanin/StringSimplifierStr.java
This code uses recursion to remove consecutive duplicate characters from a string. It compares each character with the next one, keeps it if different, and skips duplicates by moving forward recursively until the whole string is processed.
> Tra 4247:Recursion-1 > stringClean

- from_hanin/RepeatFinder.java
This code counts how many times a given substring appears in a string without overlapping, using recursion. At each step, it checks if the string starts with the substring; if yes, it adds 1 and skips ahead by the substring’s length; if not, it moves forward by one character and continues recursively.
> Tra 4253:Recursion-1 > strCount

- from_hanin/SubstringCounter.java
This code checks recursively if a string contains at least `n` copies of a given substring (including overlapping). At each step, it checks if the string starts with the substring; if yes, it decreases `n` by 1 and continues checking the rest of the string starting from the next character. If not, it just moves forward one character and keeps checking until `n` reaches zero (returns true) or the string ends (returns false).
> Tra 4254:Recursion-1 > strCopies

- From_Shaima/SumLimitChecker.java
The code calculates the sum of two non-negative integers (a and b) with a digit-length restriction.
> TRA4133 : sumLimit--➕ Sum with Digit Limit

- From_Manal/ChangeXtoY.java
Introduced a recursive function to replace all lowercase 'x' characters with 'y' in a given string, without using loops. The method processes one character at a time, preserving non-'x' characters and building the result recursively.
> TRA-4239-Recursion-1: changeXY

- From_Alharith/MaxSpan.java
For a given array, define the "span" of a value as the number of elements between its leftmost and rightmost occurrences, inclusive. A value that appears only once has a span of 1. Return the largest span found in the array. Efficiency is not a priority.
> #TRA-4269: Array3_ MaxSpan is Done

- From_Manal/ArrayContainsSix.java
Added a recursive method to check whether a given array of integers contains the value 6, starting from a specified index. The function traverses the array by incrementing the index with each recursive call, returning true if a 6 is found and false upon reaching the end.
> TRA-4241-Recursion-1: array6

- From_Shaima/DiceSumCalculator.java
The code calculates the sum of two 6-sided dice rolls:
Normally, returns the sum of the two dice.
If noDoubles is true and both dice show the same value, increment one die by 1 (wrapping 6 → 1) before summing.
> TRA4127 :withoutDoubles--🎲 Dice Sum with No Doubles

- From_Alharith/CanBalance.java
Given a non-empty array, return true if there exists an index where the array can be split into two parts with equal sums.
> #TRA-4275: Array3_ CanBalance is Done

- From_Alharith/LinearIn.java
Given two arrays of integers, outer and inner, both sorted in increasing order, return true if all elements of inner appear in outer. An efficient solution uses a single linear pass through both arrays, leveraging their sorted order.
> #TRA-4280: Array3_ LinearLn is Done

- From_Alharith/MaxMirror.java
In an array, a mirror section is a contiguous group of elements that appears somewhere else in the array in reverse order. Return the length of the largest mirror section found.
> #TRA-4294: Array3_ MaxMirror is Done

- From_Manal/PairCounter.java
Added a recursive method to count the number of "pairs" in a string, where a pair is defined as two identical characters separated by one character (e.g."AxA"). The function checks each 3-character window and recurses forward, allowing overlapping pairs to be counted.
> TRA-4244-Recursion-1: countPairs

- From_Manal/StringCleaner.java
Added a recursive method to remove consecutive duplicate characters from a string, returning a "cleaned" version with only one instance of each adjacent character. The function compares each character with the next and skips duplicates, building the result recursively.
> TRA-4246-Recursion-1: stringClean

- from_Haitham/RightDigit.java
The `RightDigit` class defines a method named `replaceWithRightDigit` that takes a list of integers (`List<Integer> nums`) and replaces each number with its **rightmost digit** (i.e., the digit in the units place). It uses the `replaceAll` method with a lambda expression (`n -> n % 10`) to perform the transformation in place. The method then returns the modified list. For example, given the input `[123, 45, 9, 800]`, the output would be `[3, 5, 9, 0]`.
> TRA-4296: RightDigit task is done

- from_Haitham/MathEdit.java
The `MathEdit` class defines a method named `mathAdding` that takes a list of integers (`List<Integer> nums`) and modifies each number by applying the formula **`(1 + n) * 10`**. It uses the `replaceAll` method with a lambda expression (`n -> (1 + n) * 10`) to transform each element in place. The updated list is then returned. For example, given the input `[1, 2, 3]`, the output will be `[20, 30, 40]` because each number is increased by 1 and then multiplied by 10.
> TRA-4293: MathEdit task is done

- from_Haitham/CopiesThree.java
The `CopiesThree` class defines a method named `replaceElementWithThreeCopies` that takes a list of strings (`List<String> strings`) and replaces each element with **three consecutive copies of itself**. It uses the `replaceAll` method along with a lambda expression (`n -> n + n + n`) to perform the transformation directly on the original list. The updated list is then returned. For example, given `["a", "bb", "ab"]`, the method returns `["aaa", "bbbbbb", "ababab"]`.
> TRA-4285: CopiesThree task is done

- from_Haitham/Doubling.java
The Doubling class defines a method named doublingAllNumbers that takes a list of integers (List<Integer> nums) and returns the same list with all elements doubled. It uses the replaceAll method with a lambda expression (n -> n * 2) to iterate over the list and replace each element with its double. The operation modifies the original list in place and returns the updated list. For example, given [1, 2, 3], the method returns [2, 4, 6].
> TRA-4276: Doubling task is done

- from_Haitham/WordEnds.java
The `WordEnds` class defines a method named `wordEndsInString` that searches for all occurrences of a given `word` within the input string `str` and returns a new string made up of the **characters immediately before and after** each occurrence of the word. It uses a loop to check each position in `str` where the `word` could start. When a match is found, it adds the character before the word (if one exists) and the character after the word (if one exists) to a `StringBuilder`. The method handles edge cases where the word is at the beginning or end of the string. For example, `wordEndsInString("abcXY123XYijk", "XY")` would return `"c1j"`.
> TRA-3324: WordEnds Task is done

- from_Haitham/PlusOut.java
The `PlusOut` class defines a method named `plusAdder` that replaces all characters in the input string `str` with `'+'`, **except for occurrences of the specified `word`**, which remain unchanged. The method uses a `while` loop to iterate through the string. If the current position in `str` starts with the given `word`, it appends the `word` to the result and skips ahead by the length of the word. Otherwise, it appends a `'+'` and moves ahead one character. This approach ensures that the `word` is preserved wherever it appears, and all other characters are masked with `'+'`. For example, calling `plusAdder("12xy34", "xy")` would return `"++xy++"`.
> TRA-3323: PlusOut task is done

- from_Haitham/OneTwo.java
The `OneTwo` class contains a method named `ReverseEveryThree` that processes the input string in groups of three characters. For each group, it rearranges the characters by moving the **first character to the end** of the group and appending this modified group to a result string. The method loops through the string in increments of 3, only processing complete 3-character chunks and ignoring any remaining characters at the end that don't form a full group. For example, given the input `"abcdef"`, the method returns `"bcaefd"` (from `"abc" → "bca"` and `"def" → "efd"`).
> TRA-3320: OneTwo task is done

- from_Haitham/SameStarChar.java
The `SameStarChar` class defines a method named `SameStringBetweenStarChar` that checks whether **every `'*'` character** in the input string is surrounded by the **same character on both sides**. It loops through the string starting from index 1 to the second-to-last character, and whenever it finds a `'*'`, it compares the characters immediately before and after it. If any `'*'` is not surrounded by matching characters, the method returns `false`. If all such conditions are satisfied (or if there are no `'*'` characters), it returns `true`. For example, `"ab*ba"` would return `true`, but `"a*bc"` would return `false`.
> TRA-3319: Tra 3319

- from_Haitham/GetSandwich.java
The `GetSandwich` class contains a method named `BreadsWordChecker` that extracts and returns the substring found **between the first and last occurrences** of the word `"bread"` in the input string. It first finds the end index of the first `"bread"` (by using `indexOf` plus 5, the length of `"bread"`), then finds the start index of the last `"bread"` using `lastIndexOf`. If the last `"bread"` comes after the first, it returns the substring between them; otherwise, it returns an empty string. For example, given `"breadjambread"`, it would return `"jam"`.
> TRA-3318: GetSandwich task is done

- from_Haitham/XYZMiddle.java
The `XYZMiddle` class contains a method called `xyzMiddleChecker` that determines whether the substring `"xyz"` appears in the "middle" of the given string. The method first checks if the string length is at least 3 (since `"xyz"` itself is length 3). It then scans the string for occurrences of `"xyz"` and considers an occurrence to be "middle" if its starting index is within 2 characters of the string’s midpoint. Additionally, it checks that the parts of the string before and after `"xyz"` are roughly the same length (differing by less than 2 characters). If such a balanced `"xyz"` is found, the method returns `true`; otherwise, it returns `false`. For example, in `"AAxyzBB"`, `"xyz"` is centered, so the method returns `true`.
> TRA-3317: XYZMiddle task is done

- from_Haitham/RepeatSeparate.java
The `RepeatSeparate` class defines a method named `repeatSeparator` that constructs a new string by repeating a given `word`, separated by a specified `sep` string, exactly `count` times. If `count` is less than 1, it returns an empty string. The method starts by appending the first occurrence of the `word`, then enters a loop to append the separator and the word repeatedly for `count - 1` times. For example, calling `repeatSeparator("Word", "X", 3)` would return `"WordXWordXWord"`. This method uses a `StringBuilder` for efficient concatenation.
> TRA-3315: RepeatSeparate task is done

- from_Haitham/RepeatEnd.java
The `RepeatEnd` class defines a method named `repeatEndByN` that returns a new string made by repeating the **last `n` characters** of the input string `str`, exactly `n` times. It uses a loop to append the same substring—consisting of the last `n` characters—to a `StringBuilder` on each iteration. For example, calling `repeatEndByN("Hello", 3)` would extract `"llo"` and return `"llollo"`. This method is useful for generating repeated suffix patterns from a string.
> TRA-3313: RepeatEnd task is done

- from_Haitham/MixString.java
The `MixString` class contains a method named `mixer` that takes two input strings and returns a new string formed by **alternating characters** from each string. It loops through both strings up to the length of the shorter one, appending one character from each string in turn. After the loop, if one string is longer than the other, the remaining characters from the longer string are appended to the end of the result. For example, calling `mixer("abc", "xyz")` returns `"axbycz"`, and `mixer("Hi", "There")` returns `"HTihere"`. The method uses a `StringBuilder` for efficient string concatenation.
> TRA-3312: MixString task is done

- from_Haitham/BobPatternThere.java
The BobPatternThere class defines a method named bobThere that checks whether the pattern "b_b" appears anywhere in the given string, where the underscores represent any single character. The method loops through the string up to the third-to-last character and checks if the character at the current index is 'b' and the character two positions ahead is also 'b', regardless of the character in between. If such a pattern is found, it returns true; otherwise, it returns false. For example, "bob" or "b9b" would return true, while "bbb" or "abc" would not.
> TRA-3310: BobPatternThere task is done

- from_Haitham/PatternThere.java
The PatternThere class contains a method named xyzThere that checks whether the substring "xyz" appears in the given string not immediately preceded by a period (.). It iterates through the string up to the third-to-last character, checking for the presence of "xyz" starting at each position. If "xyz" is found at the beginning of the string (index 0), it returns true immediately. If found at any later position, it ensures that the character before "xyz" is not a period. If such a valid "xyz" is found, the method returns true; otherwise, it returns false. For example, "abcxyz" would return true, while "abc.xyz" would return false.
> TRA-3309: PatternThere task is done

- From_Maha/ArrayComparer.java
Adds method to check if two arrays share the same first or last element. Returns true if either end matches, otherwise false.
>  Adding Array1-commonEnd file

- From_Maha/ArrayChecker.java
Adds method to check if the first or last element in an array is 6. Returns true if either condition is met, otherwise false.
>  Adding Array1-firstlast6 file

- From_Manal/SubstringDistance.java
Added a recursive method to compute the length of the largest substring in a given string that starts and ends with a specified non-empty substring sub. The function trims characters from the front or back until both ends match sub, then returns the length of the resulting substring.
> TRA-4252-Recursion-1: strDist

- From_Manal/NestingParentheses.java
Added a recursive method nestParen to validate whether a given string is a proper nesting of zero or more pairs of parentheses. The function checks if the first and last characters are matching parentheses and recurses inward, returning true for fully nested structures and false otherwise.
> TRA-4248-Recursion-1: nestParen

- from_Ghaida/MergeTwoArrays.java
This pull request introduces the MergeTwoArrays class, which includes a utility method mergeFirstNFromTwoArrays for merging two sorted string arrays into a new array of size n, ensuring the merged result contains only the first n unique lexicographically ordered elements.
> #TRA-3941: AP-1. mergeTwo added

- .github/CODEOWNERS
- from_Huria/GetDoubledList.java
The code Implement a method getDoubledList that takes a list of integers and returns a new list where each integer is multiplied by 2. The original list should remain unchanged.
> TRA4349: Adding doubling Task

- From_Maha/StringMatcher.java
Finds the longest substring that appears both at the start and end of the given string. Returns an empty string if no matching prefix-suffix exists.
> Add STRING 3- sameEnd file

- from_Hawraa/ScoresIncreasing.java
I implemented isScoresIncreasing(int[] scores), that return true if each score is equal or greater than the one before.
> AP-1: scoresIncreasing added

- From_Shaima/ListSquarer.java
The code returns a new list where each number is squared.
> TRA4395 : square--🔲 Square Each Number in the List

- From_Shaima/AddStarSuffix.java
The code returns a new list where each string has a "*" appended to its end.
> TRA4394 : addStar--⭐ Add Star Suffix to Each String

- from_Huria/WrapWithY.java
The code takes a list of strings and returns a new list where each string is surrounded with "y" — one added at the beginning and one at the end.
> TRA4355: Adding moreY Task

- From_Shaima/StringTripler.java
The code returns a new list where each string is replaced by three copies of itself concatenated together.
> TRA4393 :copies3--🔁 Create Triple String Copies

- From_Maha/StringBlockAnalyzer.java
Finds the longest block of identical consecutive characters in a string.
Tracks maximum length while iterating.
> Add STRING 3- maxBlock file

- From_Maha/WordBalanceChecker.java
Checks if the number of occurrences of "cat" and "dog" are equal in the input string.
Ensures word balance for basic keyword comparison in a text.
> Adding catDog file

- From_Maha/ArrayInspector.java
Return true if the given array contains an unlucky 1 ( 1 immediately followed by a 3 in an array  in the first 2 or last 2 positions in the array) .
> Tra2477 array 1 un lucky1

- From_Maha/MiniArrayMaker.java
Returns a new array containing the first two elements of input. Handles arrays of any length , if the array length is 1 return that element .
>  Adding Array1-frontPiece file

- From_Maha/ArrayMiddleExtractor.java
Extracts the middle three elements from an odd-length array. Returns a new array of length 3
>  Adding Array1-middleThree file

- From_Shaima/AddingY.java
The code returns a new list where each string is surrounded with "y" — one added at the beginning and one at the end.
> TRA4392: moreY--🟡 Wrap Strings wit -y-

- from_Huria/ExtractRightDigits.java
The code takes a list of non-negative integers and returns a new list containing only the rightmost digit of each number. Use the modulo operator (% 10) to extract the last digit.
> TRA4357: Adding rightDigit Task

- From_Shaima/Transformer.java
The code returns a new list where each number is first increased by 1, then multiplied by 10.
> TRA4391: math1--➕ Apply Math Transformation (+1, ×10)

- From_Maha/ArrayCenterExtractor.java
Implements method that return the middle two elements from an even-length array.
>  Adding Array1-makemiddle file

- From_Maha/NumberPairChecker.java
Checks if input array contains exactly two 2s or exactly two 3s. Returns true only if one of those values appears twice.
>  Adding Array1-double23 file

- From_Maha/ArrayLastMaker.java
Adds makeLast method that returns a new array twice the input length. Only the last element is set to match the input’s last value; others default to 0.
>  Adding Array1-makeLast file

- From_Maha/ArrayCheck.java
Adds method to check for presence of 2 or 3 in a 2-element array. Returns true if either value is found, otherwise false
>  Adding Array1-has23 file

- From_Maha/ArrayEndsHelper.java
Adds method to extract first and last elements from an integer array. Ensures compatibility with arrays of length 1 or more as required.
>  Adding Array1-makeEnds file

- From_Maha/MaxEdgeFiller.java
Adds static method to replace all elements in a 3-element array with the larger of the first or last value.
>  Adding Array1-maxEnd3 file

- from_Hawraa/ScoreChecker.java
I implemented the method hasConsecutiveHundreds(int[] scores) that return true if there are scores of 100 next to each other in the array.
> TRA-4259: AP-1: scores100 added

- from_Hawraa/ScoreClumpChecker.java
I implemented the method containsClumpOfThree(int[] scores), that return true if the array contains 3 adjacent scores that differ from each other by at most 2.
> TRA-4260: AP-1: scoresClump added

- From_Shaima/XRemover.java
The code returns a new list where each string has all occurrences of "x" removed.
> TRA4388: noX--❌ Remove All -x- Characters

- from_Huria/BrickBuilder.java
The code determine if it is possible to reach a target goal length using a combination of small (1 inch) and big (5 inch) bricks. Use as many big bricks as possible without exceeding the goal, and check if small bricks can cover the remaining length.
> TRA4439: Adding makeBricks Task

- from_Huria/RoundedSumCalculator.java
The code Round each of three integers to the nearest multiple of 10 (rounding up if the rightmost digit is 5 or more, rounding down otherwise), then return the sum of the rounded values. Use a helper method calculateRoundedSum(int num) to avoid repeating rounding logic.
> TRA4443: Adding roundSum Task

- from_Huria/UniqueSumCalculator.java
The code return the sum of three integers, ignoring any value that appears more than once. Only unique values contribute to the sum.
> TRA4444: Adding loneSum Task

- from_Huria/LuckySumCalculator.java
The code give 3 int values, a b c, return their sum. However, if one of the values is 13 then it does not count towards the sum and values to its right do not count. So, for example, if b is 13, then both b and c do not count.
> TRA4445: Adding  luckySum Task

- from_Hawraa/WordsLengthCounter.java
I implemented the countWordsLength method, which return the count of the number of strings with the given length.
> TRA-4262: AP-1: wordsCount added

- From_Shaima/ChocolatePackageBuilder.java
The code determine how many small chocolate bars (1 kilo each) are needed to reach a goal weight, using as many big bars (5 kilos each) as possible first. Return -1 if the goal cannot be reached with the available bars.
> TRA4376 :makeChocolate --Build a Chocolate Package

- From_Shaima/NumberSpacingChecker.java
The code returns true if the numbers can be arranged so that the difference between the smallest and middle number is the same as the difference between the middle and largest number.
> TRA4375 :evenlySpaced --check if the differences are same

- from_Kaltham/FibonacciCalculator.java
I created a class called FibonacciCalculator with a method named calculateFibonacci that takes an integer n.
The method calculates the n-th Fibonacci number using recursion.
How it works:
If n is 0, it returns 0.
If n is 1, it returns 1.
Otherwise, it returns the sum of Fibonacci(n - 1) + Fibonacci(n - 2).
The recursion continues until it reaches 0 or 1, then sums the results back up to get the final Fibonacci number.
> TRA-4414: Recursion-1 >=The solution for fibonacci Task

- from_Kaltham/BunnyEarsCalculatorAdvanced.java
I created a class called BunnyEarsCalculatorAdvanced with a method named calculateBunnyEars that takes an integer bunnies.
The method calculates the total number of bunny ears using a special rule and recursion.
How it works:
If bunnies > 0, it checks if the bunny is even or odd.
Even-numbered bunnies have 3 ears.
Odd-numbered bunnies have 2 ears.
It adds the ears of the current bunny and calls itself with bunnies - 1.
If bunnies is 0, it returns 0.
The recursion continues until it reaches 0, then the total number of ears is calculated.
> TRA-4415: Recursion-1 >=The solution for bunnyEars2 Task

- From_Shaima/RoundedSumCalculator.java
The code round each of three integers to the nearest multiple of 10, then return the sum of the rounded values.
> TRA4370 : roundSum --Rounded Sum to nearest 10

- from_Huria/CloseFarChecker.java
The code give three integers a, b, and c, return true if one of b or c is "close" to a (difference of at most 1), while the other is "far" from both other numbers (difference of 2 or more).
> TRA4450: Adding closeFar Task

- from_Huria/NumberSpacingChecker.java
The code give three integers, return true if the numbers can be arranged so that the difference between the smallest and middle number is the same as the difference between the middle and largest number.
> TRA4448: Adding evenlySpaced Task

- from_Kaltham/TriangleNumberCalculator.java
I created a class called TriangleNumberCalculator with a method named calculateTriangleNumber that takes an integer rows.
The method calculates the triangle number using recursion.
How it works:
If rows = 0, it returns 0.
Otherwise, it adds rows to the result of the same method called with rows - 1.
This continues until it reaches 0, giving the total sum 1 + 2 + 3 + … + rows.
> TRA-4416: Recursion-1 >=The solution for triangle Task

- From_Shaima/LuckySumCalculator.java
The code returns the sum of 3 values. However, if one of the values is 13 then it does not count towards the sum and values to its right do not count.
> TRA4384: luckySum -- is the sum lucky

- From_Shaima/TeenSumCalculator.java
The code returns the sum of three integers, treating teen values (13..19) as 0, except for 15 and 16, which count normally.
> TRA4373: noTeenSum -- Teen-Free Sum

- from_Kaltham/FactorialCalculator.java
I created a class called FactorialCalculator with a method named calculateFactorial that takes an integer n.
The method calculates the factorial of n using recursion.
How it works:
If n > 1, it multiplies n by the factorial of n - 1.
If n is 1 or less, it returns 1.
The recursion continues until it reaches 1, then the results are multiplied back up to give the final factorial.
> TRA-4410: Recursion-1 >=The solution for factorial Task

- from_Kaltham/BunnyEarsCalculator.java
I created a class called BunnyEarsCalculator with a method named calculateBunnyEars that takes an integer bunnies.
The method calculates the total number of bunny ears using recursion.
How it works:
If bunnies > 0, it adds 2 ears for the current bunny and calls itself with bunnies - 1.
If bunnies is 0, it returns 0.
The recursion continues until it reaches 0, then the total number of ears is calculated by adding 2 for each bunny.
> TRA-4411: Recursion-1 >=The solution for bunnyEars Task

- from_hanin/FixedElementSumChecker.java
The `groupSum` class  checks if a group of numbers from an array can add up to a given target using recursion. Starting from a given index, it tries including or skipping each number to see if the target can be reached. No loops are used—just recursive calls to explore all possible combinations.
> TRA-4361: Recursion-2 > groupSum

- from_Kaltham/NumberDigitSumCalculator.java
I created a class called NumberDigitSumCalculator with a method named calculateDigitSum that takes an integer n.
The method calculates the sum of all digits of the number using recursion.
How it works:
If n > 0, it takes the last digit (n % 10) and adds it to the recursive call of the remaining digits (n / 10).
This process continues until n = 0, where it returns 0 (base case).
The result is the sum of all digits in the number.
> TRA-4417: Recursion-1 >=The solution for Recursion-1 > sumDigits Task

- from_Kaltham/DigitSevenCounter.java
I created a class called DigitSevenCounter with a method named countSevens that takes an integer n.
The method counts how many times the digit 7 appears in the number using recursion.
How it works:
If n > 0, it checks the last digit (n % 10).
If the last digit is 7, it adds 1 and calls the method again on the remaining digits (n / 10).
If not, it simply calls the method again on (n / 10) without adding.
The recursion continues until n = 0, where it returns 0 (base case).
Finally, the sum of all recursive calls gives the total count of digit 7.
> TRA-4418: Recursion-1 >=The solution for Recursion-1 > count7 Task

- from_Kaltham/DigitEightCounter.java
I created a class called DigitEightCounter with a method named countEights that takes an integer n.
The method counts how many times the digit 8 appears in the number using recursion, with a special rule for consecutive eights.
How it works:
If n > 0, it checks the last digit (n % 10).
If the last digit is 8:
It adds 2 if the last two digits are 88 (double eight).
Otherwise, it adds 1.
If the last digit is not 8, it adds 0.
The method then calls itself recursively on the remaining digits (n / 10).
The recursion continues until n = 0, where it returns 0.
The sum of all recursive calls gives the total count of eights, with double counting for consecutive 8s.
> TRA-4419: Recursion-1 >=The solution for Recursion-1 > count8 Task

- from_Kaltham/PowerCalculator.java
I created a class called PowerCalculator with a method named calculatePower that takes two integers: base and n.
The method calculates the value of base raised to the power n using recursion.
How it works:
If n > 0, it multiplies the base by the result of the method called with n - 1.
If n = 0, it returns 1 (because any number to the power of 0 is 1).
The recursion continues until it reaches 0, then the multiplication results are combined to give base^n.
> TRA-4420: Recursion-1 >=The solution for Recursion-1 > powerN Task

- from_Kaltham/XCounter.java
I created a class called XCounter with a method named countXInString that takes a string str.
The method counts how many times the character 'x' appears in the string using recursion.
How it works:
If the string length is greater than 0, it checks the first character.
If it is 'x', it adds 1 and calls the method on the rest of the string (str.substring(1)).
If it is not 'x', it just calls the method on the rest of the string.
The recursion continues until the string is empty, then it returns 0.
The total sum of all recursive calls gives the number of 'x' characters in the string.
> TRA-4421: Recursion-1 >=The solution for Recursion-1 > countX Task

- from_Kaltham/CounterHi.java
I created a class called CounterHi with a method named countHiInString that takes a string str.
The method counts how many times the substring "hi" appears in the string using recursion.
How it works:
If the string has fewer than 2 characters, it returns 0 because "hi" can’t appear.
Otherwise, it checks the first two characters of the string:
If they are "hi", it adds 1 and calls the method on the rest of the string starting from index 2 (str.substring(2)).
If they are not "hi", it calls the method on the rest of the string starting from index 1 (str.substring(1)).
The recursion continues until the string is too short, then all the 1’s are summed to give the total count of "hi".
> TRA-4422: Recursion-1 >=The solution for Recursion-1 > countHi Task

- from_Hawraa/WordsWithoutTarget.java
I implemented removeTargetString(), that removes all occurrences of a specified target string from a given array. And returns a new array containing only the elements that do not match the target.
> TRA-4295: AP-1: wordsWithout added

- From_Mulk/FixThreeFour.java
I created a code that ensures every 3 in the array is directly followed by a 4 by moving elements. It looks for 3s, places a 4 right after them, and moves the replaced numbers to where other 4s originally were.
> Array-3 > Fix34 task

- from_Hawraa/WordsWithoutTarget.java
I implemented removeTargetString(), that removes all occurrences of a specified target string from a given array. And returns a new array containing only the elements that do not match the target.
> TRA-4295: Ap-1: WordsWithoutTarget modified

- From_Abdullah/SleepIn.java
The variable weekday is set to true when it’s a weekday, and vacation is true when we’re on vacation. We can sleep in if it’s not a weekday or if we’re on vacation. The function should return true when we get to sleep in.
> #TRA-4487: WarmUp1_ SleepIn is Done

- from_Hawraa/SpecialScoreCalculator.java
I implemented a method sumLargestScores that returns the sum of the highest scores from two arrays, "a" and "b". A score is considered only if it is divisible by 10. The helper method maxScores is used to find the maximum valid score in each array.
> TRA-4298: AP-1: scoresSpecial added

- From_Abdullah/MonkeyTrouble.java
We have two monkeys, a and b. The parameters aSmile and bSmile show whether each monkey is smiling. We’re in trouble if both are smiling or if neither is smiling. The function should return true when we’re in trouble.
> #TRA-4488: WarmUp1_ MonkeyTrouble is Done

- from_Kaltham/PiReplacer.java
I created a class called PiReplacer with a method named convertPiToDicmalValue that takes a string str.
The method replaces every occurrence of "pi" with "3.14" using recursion.
How it works:
Base case:
If the string length is less than 2, it can’t contain "pi", so return the string as is.
Recursive case:
If the first two characters are "pi", replace them with "3.14" and recursively process the rest of the string starting from index 2.
Otherwise, keep the first character as it is, and recursively process the rest of the string starting from index 1.
The recursion keeps replacing until the entire string is processed.
> TRA-4424: Recursion-1 >=The solution for Recursion-1 > changePi Task

- from_Kaltham/XRemover.java
I created a class called XRemover with a method named removeX that removes all 'x' characters from a given string using recursion.
How it works:
Base case:
If the string is empty, return it as is.
Recursive case:
Check the first character:
If it is 'x', skip it and recursively process the rest of the string.
If it is not 'x', keep it and add the result of recursively processing the rest.
The recursion continues until the string is fully processed.
> TRA-4425: Recursion-1 >=The solution for Recursion-1 > noX Task

- From_Horiya_Albusaidi/StringRemover.java
I created removeRemovedString () that  return a version of the base string where all instances of the remove string have been removed (not case sensitive). You may assume that the remove string is length 1 or more. Remove only non-overlapping instances, so with "xxx" removing "xx" leaves "x".
> TRA-4504: Solving String-3 -> withoutString Task

- from_Kaltham/ArrayContainsSix.java
I created a class called ArrayContainsSix with a method named hasSix that checks if an array of integers contains the number 6.
How it works:
Base case:
If the index reaches the array’s length, it means we’ve checked all elements → return false.
Check current element:
If nums[index] == 6, return true.
Recursive step:
Otherwise, call hasSix(nums, index + 1) to check the next element in the array.
Finally, the method will return true if any element equals 6, or false if the number 6 is not found
> TRA-4426: Recursion-1 >=The solution for Recursion-1 > array6 Task

- From_Mulk/ArrayContains.java
I created a method that checks if all elements of one sorted array (inner) appear in order within another sorted array (outer). It uses two pointers to compare elements and returns true only if all inner elements are found in sequence within outer.
> Array-3 > LinearIn task

- from_Kaltham/StarInserter.java
I created a class called StarInserter with a method named addStarsBetweenChars that inserts a '*' character between every two characters of a string using recursion.
How it works:
Base case:
If the string length is 0 or 1, return the string as is because no stars are needed.
Recursive case:
Take the first character of the string.
Add a '*' after it.
Recursively call the method on the rest of the string (str.substring(1)).
The recursion continues until the string is fully processed, then all parts are combined to form the final string.
> TRA-4429: Recursion-1 >=The solution for Recursion-1 > allStar Task

- From_Mulk/FillPattern.java
I wrote a method that makes an array of size n × n and fills it with a pattern. In each row, it puts numbers starting from 1 up to the row number, placing them at the end of the row to form a step-like pattern.
> Array-3 > SquareUp task

- From_Horiya_Albusaidi/CountingAppearancesOfStrings.java
I created checkEqualityAppearancesOfIsAndNotWords method that return true if the number of appearances of "is" anywhere in the string is equal to the number of appearances of "not" anywhere in the string (case sensitive).
> TRA-4520: Solving String-3 -> equalsISNot Task

- From_Mulk/BuildSeries.java
I made a method that builds an array with a growing number pattern. It starts with 1, then 1 2, then 1 2 3, and so on, up to n. All these numbers are added into one array in order.
> Array-3 > SeriesUp task

- From_Mulk/MaxMirror.java
in this task I wrote a code to check a group of continuous elements such that somewhere in the array, the same group appears in reverse order, if that's found then return the size of the largest mirror section found in the given array.
> Array-3 > maxMirror task

- from_Kaltham/XMover.java
I created a class called XMover with a method named moveXToEnd that moves all 'x' characters in a string to the end using recursion.
How it works:
Base case:
If the string length is 0 or 1, return the string as is because there is nothing to move.
Check first character:
If the first character is 'x', recursively process the rest of the string and then add 'x' at the end.
If the first character is not 'x', keep it at the beginning and recursively process the rest of the string.
The recursion continues until the entire string is processed, resulting in all 'x' characters being moved to the end.
> TRA-4431: Recursion-1 >=The solution for Recursion-1 > endX Task

- From_Horiya_Albusaidi/CheckHappyLetter.java
I created checkIfLetterGHappyOrNot method that  Return true if all the g's in the given string are happy.
> TRA-4521: Solving String-3 -> gHappy Task

- From_Abdullah/SumDouble.java
Take two integer values and return their sum. If the two values are equal, return twice their sum instead.
> #TRA-4490: WarmUp1_ SumDouble is Done

- from_Kaltham/MatchingPairsCounter.java
I created a class called MatchingPairsCounter with a method named findPairs that counts the number of times a character matches the one two places ahead in a string using recursion.
How it works:
Base case:
If the string length is 2 or less, return 0 because there aren’t enough characters to form a pair.
Check current pair:
Compare str.charAt(0) with str.charAt(2).
If they are equal, add 1 and recursively process the string starting from the next character (str.substring(1)).
If they are not equal, just recursively process the string starting from the next character.
The recursion continues until the string is fully processed. The total count gives the number of "matching pairs" in the string.
> TRA-4432: Recursion-1 >=The solution for Recursion-1 > countPairs Task

- from_Kaltham/SubstringCounter.java
I created a class called SubstringCounter with a method named countPatterns that counts how many times the patterns "abc" or "aba" appear in a string using recursion.
How it works:
Base case:
If the string length is 2 or less, return 0 because a 3-character pattern can’t exist.
Check first 3 characters:
If str.substring(0, 3) is "abc" or "aba", add 1 and recursively process the rest of the string starting from the next character (str.substring(1)).
Otherwise, just recursively process the string starting from the next character.
The recursion continues until the string is fully processed. The total count gives the number of "abc" or "aba" patterns in the string.
> TRA-4433: Recursion-1 >=The solution for Recursion-1 > countAbc Task

- from_Hawraa/SumHeightCalculator.java
I implemented getSumHeights(int[] heights, int start, int end), that return the sum of the changes for a walk beginning at the start index and ending at the end index.
> TRA-4301: AP-1: sumHeights added

- from_Ghaida/LowerStrings.java
This PR implements the method toLowerCaseList which converts all strings in a list to lowercase.
> #TRA-3882: Functional-1. lower modified

- from_Hawraa/SumDoubleHeightCalculator.java
I implemented the calculateSumDoubleClimb() method to compute the total height change between two indices in an array. Height increases are weighted double, while decreases are counted normally using their absolute values.
> TRA-4303: AP-1: sumHeights2 added

- from_Ghaida/RemoveLetterX.java
This PR implements the method removeXFromStrings which removes every 'x' character from each string in a list.
> #TRA-3883: Functional-1. noX modified

- from_Kaltham/ParenthesesExtractor.java
I created a class called ParenthesesExtractor with a method named getStringWithinParens that extracts the substring inside the first and last parentheses in a string using recursion.
How it works:
Check the first character:
If the first character is not '(', remove it by calling the method recursively on str.substring(1).
Check the last character:
If the last character is not ')', remove it by calling the method recursively on str.substring(0, str.length() - 1).
Base case:
When the string starts with '(' and ends with ')', return the string as it contains the outer parentheses.
The recursion continues trimming characters from the start or end until the string is enclosed by '(' and ')'.
> TRA-4437: Recursion-1 >=The solution for Recursion-1 > parenBit Task

- from_Kaltham/RepeatedSubstringChecker.java
I created a class called RepeatedSubstringChecker with a method named hasAtLeastNCopies that checks whether a substring sub appears at least n times in a string str, using recursion.
How it works:
Base cases:
If n <= 0, return true because we have already found enough occurrences.
If the string is shorter than the substring, return false because there’s no room left for more occurrences.
Check the start of the string:
If the substring at the start matches sub, count it as one occurrence and decrease n by 1, then continue checking the rest of the string starting from the next character (str.substring(1)).
If it doesn’t match, continue checking the rest of the string without decreasing n.
The recursion continues until either n reaches 0 (enough occurrences found) or the string is exhausted
> TRA-4441: Recursion-1 >=The solution for Recursion-1 > strCopies Task

- from_Kaltham/SubstringDistance.java
I created a class called SubstringDistance with a method named longestSubWithEnds that finds the length of the longest substring of str that starts and ends with a given substring sub, using recursion.
How it works:
Base case:
If the string is shorter than sub, return 0 because it can’t contain the required substring at both ends.
Check both ends:
If the string starts and ends with sub, return the length of the string.
Adjust the string:
If it does not start with sub, remove the first character and recursively check the smaller string.
If it starts with sub but does not end with sub, remove the last character and recursively check the smaller string.
The recursion continues until the longest substring that meets the condition is found.
> TRA-4442: Recursion-1 >=The solution for Recursion-1 > strDist Task

- From_Mulk/ToppingModifier.java
I made a method that changes a map by setting "bread" to "butter" and, if "ice cream" is in the map, it changes its value to "cherry".
> Map-1 > Topping1 task

- from_Hawraa/CommonStringCounter.java
I implemented countSharedStrings to count the number of unique strings that appear in both sorted arrays "a" and "b". It skips duplicates and uses two pointers to efficiently compare elements.
> TRA-307: AP-1: commonTwo added

- from_Kaltham/KeyValueSwapper.java
I created a class called KeyValueSwapper with a method named moveAtoB that modifies a Map<String, String> by moving the value from key "a" to key "b".
How it works:
Check for key "a":
If the map contains "a", take its value and store it under key "b".
Set the value of "a" to an empty string "".
> TRA-4552: Map-1 >=The solution for Map-1 > mapBully Task

- From_Maha/ArrayOperations.java
Calculates the difference between the largest and smallest numbers in the array.
> add bigDiff file

- From_Horiya_Albusaidi/DigitsOperation.java
I create sumDigits method that return the sum of the digits 0-9 that appear in the string, ignoring all other characters. Return 0 if there are no digits in the string
> TRA-4542: Solving String-3 -> sumDigits Task

- from_Kaltham/FoodMapUpdater.java
I created a class called FoodMapUpdater with a method named modifyMapToppings that modifies a Map<String, String> by updating and adding specific keys.
How it works:
Copy "ice cream" value to "yogurt":
If the map contains key "ice cream", create or update the key "yogurt" with the same value as "ice cream".
Update "spinach" value:
If the map contains key "spinach", change its value to "nuts".
> TRA-4556: Map-1 >=The solution for Map-1 >topping2 Task

- From_Maha/ArraySpecialSum.java
Returns the sum of array elements, skipping any 13 and the number immediately following it.
> add Array2-sum13 file

- From_Mulk/FoodPairUpdater.java
I created a method that updates a map: if "potato" exists, its value is copied to "fries", and if "salad" exists, its value is copied to "spinach".
> Map-1 > Topping3 task

- from_Kaltham/MapToppingsUpdater.java
I created a class called MapToppingsUpdater with a method named updateFoodMap that modifies a Map<String, String> by adding or updating keys based on existing ones.
How it works:
Copy "potato" value to "fries":
If the map contains the key "potato", set the value of "fries" to be the same as "potato".
Copy "salad" value to "spinach":
If the map contains the key "salad", set the value of "spinach" to be the same as "salad".
> TRA-4557: Map-1 >=The solution for Map-1 >topping3 Task

- From_Maha/ArrayBlockSum.java
Returns the sum of array elements, ignoring any numbers between 6 and 7 (inclusive).
> Add array-2-sum67

- from_Kaltham/MapABUpdater.java
I created a class called MapABUpdater with a method named fillAandB that modifies a Map<String, String> by filling missing values for keys "a" and "b".
How it works:
Fill "b" if missing:
If the map contains "a" but not "b", set "b" to have the same value as "a".
Fill "a" if missing:
If the map contains "b" but not "a", set "a" to have the same value as "b".
> TRA-4559: Map-1 >=The solution for Map-1 >mapAB3 Task

- from_Kaltham/MapLongestValue.java
I created a class called MapLongestValue with a method named updateCWithLongest that modifies a Map<String, String> based on the lengths of values for keys "a" and "b".
How it works:
Check keys "a" and "b":
If both "a" and "b" exist in the map, compare the lengths of their values.
Update "c" with the longest value:
If "a" is longer than "b", set "c" to the value of "a".
If "b" is longer than "a", set "c" to the value of "b".
Handle equal lengths:
If "a" and "b" have equal lengths, set both "a" and "b" to empty strings ("").
> TRA-4560: Map-1 >=The solution for Map-1 >mapAB4 Task

- From_Mulk/MapBalancer.java
I made a method that fills in missing pairs in a map: if only "a" or only "b" exists, it copies the value to the missing key so both keys have the same value.
> Map-1 > MapAB3 task

- From_Maha/LuckyArrayCheck.java
returns true if the array contains no 1’s and no 3’s.
> Add array-2-lucky13

- From_Maha/ArraySumChecker.java
Checks if the sum of all 2’s in the array equals exactly 8.
> add Array2-sum28 file

- From_Maha/NumberFrequencyChecker.java
Returns true if the array contains more 1’s than 4’s
> Add array-2-more14

- from_Kaltham/WordLengthMap.java
I created a class called WordLengthMap with a method named mapWordsToLength that builds a Map<String, Integer> based on the words in an array.
How it works:
Create a new map:
Start with an empty HashMap<String, Integer> called newMap.
Loop through the array:
For each word in the input array, check if it is already in the map.
Add word with its length:
If the word is not in the map, add it as a key and store its length as the value.
Return the map:
After processing all words, return the completed map.
> TRA-4562: Map-2 >=The solution for Map-2 >wordLen Task

- From_Mulk/MapWordToZero.java
I created a method that takes an array of strings and builds a map where each unique word is a key, and its value is set to 0.
> Map-2 > Word0 task

- from_Kaltham/FirstLastCharMap.java
I created a class called FirstLastCharMap with a method named mapFirstToLastChar that builds a Map<String, String> based on the first and last characters of words in an array.
How it works:
Create a new map:
Start with an empty HashMap<String, String> called newMap.
Loop through the array:
For each word in the input array, get its first and last characters.
Add to the map:
Use the first character as the key and the last character as the value.
This will overwrite any previous entry with the same first character.
Return the map:
After processing all words, return the completed map.
> TRA-4563: Map-2 >=The solution for Map-2 >pairs Task

- From_Maha/SequenceGenerator.java
Creates an array of size n with values from 0 up to n-1.
> add Array2-fizzArray file

- From_Maha/NumberValidator.java
Checks if the array contains only 1s and 4s, returning false if any other number is found.
> Add array-2-only14

- from_Kaltham/FirstCharGrouperMap.java
I created a class called FirstCharGrouperMap with a method named groupByFirstChar that builds a Map<String, String> grouping words by their first character.
How it works:
Create a new map:
Start with an empty HashMap<String, String> called newMap.
Loop through the array of strings:
For each word in the input array:
Extract its first character as a string.
If the map already contains this first character as a key, append the word to the existing value.
If the map does not contain this first character, add it as a new key with the word as its value.
Return the map:
After processing all words, return the map where each key is a first character, and its value is all words starting with that character concatenated together.
> TRA-4565: Map-2 >=The solution for Map-2 >firstChar Task

- from_Kaltham/StringSwapperMap.java
I created a class called StringSwapperMap with a method named swapFirstCharPairs that swaps pairs of strings in an array if they start with the same first character.
How it works:
Create a map to track first characters:
Use a HashMap<String, Integer> called newMap where the key is the first character of a string and the value is the index of the first occurrence of that character.
Loop through the array of strings:
For each string:
Get its first character.
If the first character is not in the map, add it with the current index.
If the first character is already in the map:
Retrieve the index of the previous string with the same first character.
Swap the current string with the string at that stored index.
Remove the first character from the map so that only pairs are swapped once.
Return …
> TRA-4570: Map-2 >=The solution for Map-2 >allSwap Task

- from_Kaltham/FirstStringSwapperMap.java
I created a class called FirstStringSwapperMap with a method named swapFirstOnly that swaps the first pair of strings in an array that start with the same first character, but only once per character.
How it works:
Create a map and a set:
newMap (HashMap<String, Integer>) tracks the first occurrence index of each starting character.
usedSet (HashSet) keeps track of characters whose first swap has already been performed.
Loop through the array of strings:
For each string, get its first character.
If the character is not in newMap, add it with the current index.
If the character is already in newMap but also in usedSet, skip it (no further swaps for this character).
If the character is in newMap but not in usedSet, swap the current string with the previous string stored in newMap.
After …
> TRA-4571: Map-2 >=The solution for Map-2 >firstSwap Task

- From_Mulk/FirstLastMapper.java
I wrote a method that takes an array of strings and builds a map where each key is the first letter of a word, and the value is the last letter of that word. It only adds the first occurrence of each starting letter.
> Map-2 > Pairs task

- From_Mohammed/MakeBricks.java
I need to write a function that decides if we can reach exactly the goal length using small bricks (1 inch each) and big bricks (5 inches each). I have to return true if it’s possible, otherwise false. No loops are needed, just math.
> Logic-2 > makeBricks #TRA-4452 done

- From_Mohammed/LoneSum.java
I need to write a function that adds three numbers a, b, and c. But if any of them are the same as another, we ignore those values (they don’t count in the sum).
> Logic-2 > loneSum #TRA-4453 done

- From_Mohammed/LuckySum.java
I need to write a function that adds three numbers a, b, and c. But if one of the numbers is 13, that number and everything to its right are ignored (not added).
> Logic-2 > luckySum #TRA-4454 done

- From_Mohammed/NoTeenSum.java
I need to make a function noTeenSum(a, b, c) that adds three numbers. But if any number is in the 'teen' range (13–19), then that number counts as 0 — except for 15 and 16, which are allowed and should not be treated as 0. To avoid writing the same teen-checking code three times, I should create a helper method fixTeen(n) that applies this teen rule to a single number, then use it for a, b, and c."
> Logic-2 > noTeenSum #TRA-4455 done

- From_Alharith/Factorial.java
Given an integer n (where n ≥ 1), return the factorial of n. The factorial is the product of all positive integers from n down to 1. Solve it recursively (no loops).
> #TRA-4579: Recursion1_ Factorial is Done

- From_Mohammed/Blackjack.java
I need to make a function that takes two positive integers. The goal is to return the one that is closest to 21 but not over 21. If both numbers are greater than 21, then return 0.
> Logic-2 > BlackJack #TRA-4458 done

- From_Mohammed/MakeChocolate.java
I need to write a function to make a package of exactly goal kilos of chocolate. I have small bars (1 kilo each) and big bars (5 kilos each). The rule is: always try to use as many big bars as possible first, then use small bars for the rest. If it’s not possible to reach exactly the goal, return -1. Otherwise, return how many small bars are used.
> Logic-2 > makeChocolate #TRA-4460 done

- from_Hawraa/MapValueShifter.java
I implemented moveValueFromAToB(Map<String, String> map), that transfers the value associated with key "a" to key "b" in the provided map. After the transfer, the value of key "a" is set to an empty string.
> TRA-4642: Map-1: mapBully added

- From_Mulk/WordCount.java
In this code, you created a method that loops through an array of strings and keeps track of how often each word appears using a map, where the word is the key and the number of times it shows up is the value.
> Map-2 > WordCount task

- from_Hawraa/MapKeyHandler.java
Implemented mapShare(Map<String, String> map), to remove the key "c" and, if key "a" exists, copy its value to key "b" without modifying "a".
> TRA-4647: Map-1: mapShare added

- from_Hawraa/MapConcatenator.java
I implemented mergeAAndBToAB to add a new key "ab" with the concatenated values of "a" and "b" if both keys are present in the map.
> TRA-4648: Map-1: mapAB added

- from_Kaltham/NumberDoubler.java
I created a class called NumberDoubler with a method named doubleValues that takes a list of integers and returns a new list where each number is doubled.
How it works:
Input:
The method receives a List<Integer> called nums.
Use streams:
For each number in the stream, it applies the mapping function n -> n * 2, which multiplies each element by 2.
It then collects the transformed numbers back into a list using collect(Collectors.toList()).
Output:
The method returns the new list with all values doubled.
> TRA-4667: Functional-1 >=The solution for Functional-1 > doubling Task

- from_Hawraa/ToppingUpdater.java
I implemented customizeToppingsMap(Map<String, String> map), to set the key "bread" to have the value "butter". And, if "ice cream" is present in the map, update its value to "cherry".
> TRA-4652: Map-1: topping1 added

- From_Manal/GroupSumFiveSolver.java
Implemented groupSum5(start, nums, target) to determine if a subset of integers can sum to a target value, with two added constraints:
All multiples of 5 must be included in the group.
If a multiple of 5 is immediately followed by a 1, that 1 must be excluded.
Used recursive backtracking to explore valid combinations starting from index start, without loops. This builds on the standard subset-sum pattern with constraint handling.
> TRA-4379-Recursion-2: groupSum5

- From_Alharith/Triangle.java
You have a triangle built from blocks. The first (top) row has 1 block, the second row has 2 blocks, the third row has 3 blocks, and so on. Write a recursive function (without loops or multiplication) that returns the total number of blocks in a triangle with n rows.
> #TRA-4587: Recursion1_ Triangle is Done

- from_Kaltham/StringStarAppender.java
I created a class called StringStarAppender with a method named addStars that takes a list of strings and returns a new list where each string has a "*" appended to the end.
How it works:
Input:
Use streams:
For each string in the stream, it applies the mapping function n -> n + "*", which appends a star (*) to the end of the string.
The modified strings are collected back into a new list using collect(Collectors.toList()).
Output:
The method returns the new list with "*" added to each string.
> TRA-4669: Functional-1 >=The solution for Functional-1 > addStar Task

- From_Manal/SplitOddTenSolver.java
Added splitOdd10(int[] nums) to determine if the array can be split into two groups such that:
One group’s sum is a multiple of 10
The other group’s sum is odd All elements must be assigned to one group or the other.
Used a recursive helper to explore all valid partitions without loops. The method tracks cumulative sums for both groups and checks constraints at the base case.
> TRA-4380: recursion-2/SplitOddTen

- From_Alharith/CountX.java
You need to create a recursive function that counts how many lowercase 'x' characters are in a given string.
If the string is empty, return 0 (this is the base case).
Otherwise, check the first character:
If it’s 'x', count 1 and make a recursive call on the rest of the string.
If it’s not 'x', just make the recursive call without adding to the count.
> #TRA-4597: Recursion1_ CountX is Done

- From_Manal/EqualSumPartitionWithFiveAndThreeRules.java
Added split53(int[] nums) to determine whether the array can be split into two groups with equal sums, subject to the following constraints:
All multiples of 5 must go into one group.
All multiples of 3 (that are not multiples of 5) must go into the other group.
Used recursive backtracking to assign each number to a group while maintaining the constraints. No loops used recursion handles all branching and sum tracking.
> TRA-4383-Recursion-2: split53

- From_Horiya_Albusaidi/LettersChecker.java
I created extractYyFromElement() that return a list where each string has "y" added at its end, omitting any resulting strings that contain "yy" as a substring anywhere.
> TRA-4134: Solving Functional-2 > noYY Task

- from_Kaltham/StringWrapper.java
I created a class called StringWrapper with a method named wrapWithY that takes a list of strings and returns a new list where each string is wrapped with the character "y" at both the beginning and the end.
How it works:
Input:
Use streams:
For each string in the stream, it applies the mapping function n -> "y" + n + "y", which adds "y" before and after the string.
The transformed strings are collected back into a new list using collect(Collectors.toList()).
Output:
The method returns the new list with each string wrapped by "y".
> TRA-4671: Functional-1 >=The solution for Functional-1 > moreY Task

- From_Manal/SplitArraySolver.java
Added splitArray(int[] nums) to determine whether the array can be divided into two groups with equal sums. Every element must be assigned to one group or the other.
Used a recursive helper method to explore all valid partitions by tracking cumulative sums for both groups. No loops used recursion handles all branching and decision-making.
> TRA-4386: Recursion-2/SplitArray

- From_Alharith/ChangeXY.java
Write a recursive function that takes a string and returns a new string where every lowercase 'x' is replaced with a 'y'. At each step, check the first character: if it is 'x', change it to 'y' and recursively process the remaining substring; otherwise, keep the character as it is and continue recursively until the entire string is processed.
> #TRA-4601: Recursion1_ CangeXY is Done

- from_Kaltham/NumberTransformer.java
I created a class called NumberTransformer with a method named incrementAndMultiplyBy10 that takes a list of integers and returns a new list where each integer is first incremented by 1 and then multiplied by 10.
How it works:
Input:
Use streams:
For each integer in the stream, it applies the mapping function n -> (n + 1) * 10, which first adds 1 to the number and then multiplies the result by 10.
The transformed integers are collected back into a new list using collect(Collectors.toList()).
Output:
The method returns the new list with the transformed integers.
> TRA-4672: Functional-1 >=The solution for Functional-1 > math1 Task

- From_Mulk/WordTracker.java
This method builds a string by going through an array of words and appending a word to the result every time it appears an even number of times.
> Map-2 > WordAppend task

- from_Hawraa/MapCleaner.java
I implemented removeMatchingAB to remove keys "a" and "b" from the map if both exist and their values are equal.
> TRA-4659: Map-1: mapAB2 added

- From_Horiya_Albusaidi/MirrorOfString.java
I created checkTheMirrorEndIOfString method that look for a mirror image (backwards) string at both the beginning and end of the given string. In other words, zero or more characters at the very begining of the given string, and at the very end of the string in reverse order (possibly overlapping)
> TRA-4697: Solving String-3 -> mirrorEnd Task

- from_Kaltham/GetRigthDigit.java
I created a class called GetRigthDigit with a method named extractLastDigit that takes a list of integers and returns a new list containing only the last digit of each integer.
How it works:
Input:
Use streams:
For each integer in the stream, it applies the mapping function n -> n % 10, which extracts the rightmost digit (the remainder after dividing by 10).
The resulting digits are collected back into a new list using collect(Collectors.toList()).
Output:
The method returns the new list containing the last digit of each number.
> TRA-4673: Functional-1 >=The solution for Functional-1 > RigthDigit Task

- from_Hawraa/MapLengthComparator.java
I implemented compareABAndModify to compare the lengths of values for keys "a" and "b" if both exist. If one is longer, its value is assigned to key "c". If equal, both "a" and "b" are set to empty strings.
> TRA-4662: Map-1: mapAB4 added

- From_Mulk/FirstCharSwapper.java
This method scans through a list of strings and swaps pairs of words that start with the same first letter. Each letter can only cause one swap, after which it’s no longer used for further swaps.
> Map-2 > AllSwap task

- From_Alharith/NoX.java
Write a recursive function that returns a new string with all 'x' characters removed. At each step, check the first character: if it is 'x', skip it and recursively process the rest of the string; if it is not 'x', keep the character and continue recursively with the remainder of the string until the entire string is processed.
> #TRA-4605: Recursion1_ NoX is Done

- From_Alharith/Array6.java
Write a recursive function that checks if an array contains a 6 starting from a given index. At each step, check the element at the current index: if it is 6, return true; if not, recursively call the function with index+1. Stop recursion when the index reaches the array length, returning false.
> #TRA-4607: Recursion1_ Array6 is Done

- from_Kaltham/StringWithoutX.java
I created a class called StringWithoutX with a method named removeXFromString that removes all occurrences of the character 'x' from each string in a list.
How it works:
Input:
Use streams:
For each string in the stream, it applies the mapping function n -> n.replace("x", ""), which removes all 'x' characters.
The resulting strings are collected back into a new list using collect(Collectors.toList()).
Output:
The method returns the new list containing all the original strings with 'x' removed.
> TRA-4675: Functional-1 >=The solution for Functional-1 > noX Task

- From_Alharith/AllStar.java
Given a string, you can recursively build a new string where every pair of adjacent characters is separated by a "". Start with the first character and, if the string has more than one character, append a "" followed by the result of recursively calling the function on the rest of the string. The base case is when the string has length 0 or 1, in which case you simply return the string itself.
> #TRA-4614: Recursion1_ AllStar is Done

- from_Kaltham/NumberFilter.java
I created a class called NumberFilter with a method named removeNegativeNumbers that filters out negative numbers from a list of integers.
How it works:
Input:
Use streams:
It applies a filter n -> n >= 0 to keep only numbers that are zero or positive.
The filtered numbers are collected back into a new list using collect(Collectors.toList()).
Output:
The method returns the new list containing only non-negative numbers.
> TRA-4676: Functional-2 >=The solution for Functional-2 > noNeg Task

- From_Alharith/PairStar.java
Given a string, add a "*" between any identical letters that are next to each other. Do this using recursion, checking one pair of letters at a time.
> #TRA-4617: Recursion1_ PairStar is Done

- From_Alharith/CountAbc.java
Given a string, recursively count how many times the substrings "abc" or "aba" appear in it.
> #TRA-4635: Recursion1_ CountAbc is Done

- from_Kaltham/NumberRemover.java
I created a class called NumberRemover with a method named removeEndingWith9 that removes numbers ending with the digit 9 from a list of integers.
How it works:
Input:
Use streams:
It applies a filter n -> n % 10 != 9 to keep only numbers whose last digit is not 9.
The filtered numbers are collected back into a new list using collect(Collectors.toList()).
Output:
The method returns the new list containing only numbers that do not end with 9.
> TRA-4677: Functional-2 >=The solution for Functional-2 > no9 Task

- From_Alharith/Count11.java
Given a string, recursively count how many times the substring "11" appears without overlapping.
> #TRA-4637: Recursion1_ Count11 is Done

- from_Kaltham/NumberTeenFilter.java
I created a class called NumberTeenFilter with a method named removeTeens that removes “teen” numbers (13–19) from a list of integers.
How it works:
Input:
Use streams:
It applies a filter n -> n < 13 || n > 19 to keep only numbers not in the teen range (13–19).
The filtered numbers are collected back into a new list using collect(Collectors.toList()).
Output:
The method returns the new list containing only numbers outside the 13–19 range.
> TRA-4678: Functional-2 >=The solution for Functional-2 > noTeen Task

- from_Hawraa/WordLengthMapper.java
I implemented generateLengthMap to create a map where each string from the input array is a key, and its corresponding value is the length of that string.
> TRA-4715: Map-2: wordLen added

- From_Abdullah/PosNeg.java
The PosNeg class defines a method called checkPosNegCondition that evaluates two integers, a and b, along with a boolean flag negative. The method returns true if the values meet specific conditions based on the flag. When negative is false, the method checks whether one number is positive and the other is negative—capturing cases of opposite signs. If negative is true, it instead checks whether both numbers are negative. This dual-purpose logic makes the method flexible for different scenarios involving sign comparison, and it's a great example of how conditional branching can adapt behavior based on input flags.
> #TRA-4495:Warmup1_posNeg is done

- From_Abdullah/NearHundred.java
The NearHundred class contains a method named closeTo100Or200 that determines whether a given integer n is within 10 units of either 100 or 200. Specifically, the method returns true if n falls between 90 and 110 (inclusive), or between 190 and 210 (inclusive). This is achieved using a conditional if statement that checks both ranges. If n satisfies either condition, the method returns true; otherwise, it returns false. This kind of logic is useful in scenarios where proximity to a target value is important, such as validating input ranges or triggering alerts near threshold values.
> #TRA-4494: Warmup1 > NearHundred

- From_Abdullah/Makes10.java
Given two integers a and b, return true if either one is 10, or if their sum equals 10.
>  #TRA-4493: Warmup1 > makes10

- from_Kaltham/RemoveZStrings.java
I created a class called RemoveZStrings with a method named removeZ that removes all strings containing the letter “z” from a list.
How it works:
Input:
Use streams:
It applies a filter n -> !n.contains("z") to keep only strings that do not contain the letter “z”.
The filtered strings are collected back into a new list using collect(Collectors.toList()).
Output:
The method returns a new list containing only the strings without the letter “z”.
> TRA-4679: Functional-2 >=The solution for Functional-2 > noZ Task

- From_Abdullah/NotString.java
Take a string and return a new one with "not " added to the front. If the string already starts with "not", return it unchanged.
(Hint: use .equals() for string comparison.)
> #TRA-4496:Warmup1_notstring is done

- From_Alharith/StringClean.java
Given a string, recursively return a new string where consecutive duplicate characters are reduced to a single instance, so repeated letters appear only once.
> #TRA-4639: Recursion1_ StringClean is Done

- from_Kaltham/ShortStringsFilter.java
I created a class called ShortStringsFilter with a method named filterShort that filters out strings with fewer than 4 characters from a list.
How it works:
Input:
Use streams:
It applies a filter n -> n.length() < 4 to keep only strings whose length is less than 4 characters.
The filtered strings are collected back into a new list using collect(Collectors.toList()).
Output:
The method returns a new list containing only the short strings (length < 4).
> TRA-4680: Functional-2 >=The solution for Functional-2 > noLong Task

- from_Hawraa/FirstLastLetterMapper.java
I implemented generateFirstLastMap to create a map where each key is the first letter of a string from the input array, and the corresponding value is the last letter of that string.
> TRA-4718: Map-2: pairs added

- From_Alharith/StrCount.java
Given a string and a non-empty substring sub, recursively count how many times sub appears in the string without overlapping.
> #TRA-4651: Recursion1_ StrCount is Done

- from_Kaltham/StringAppenderFilter.java
I created a class called StringAppenderFilter with a method named appendYWithoutDoubleY that appends "y" to each string in a list, but excludes any resulting strings that contain "yy".
How it works:
Input:
Use streams:
It maps each string to a new string with "y" appended: n -> n + "y".
It filters out any string that contains "yy": filter(n -> !n.contains("yy")).
The resulting strings are collected into a new list using collect(Collectors.toList()).
Output:
The method returns a new list containing strings with "y" appended, excluding any that end up with "yy".
> TRA-4682: Functional-2 >=The solution for Functional-2 > noYY Task

- From_Alharith/StrDist.java
Given a string and a non-empty substring sub, recursively find the length of the largest substring that starts and ends with sub.
> #TRA-4657: Recursion1_ StrDist is Done

- From_Alharith/BunnyEars.java
Given a number of bunnies, each having two ears, return the total number of ears. Solve this recursively, without using loops or direct multiplication.
> #TRA-4581: Recursion1_ BunnyEars is Done

- From_Alharith/BunnyEars2.java
You have a line of bunnies numbered 1, 2, 3, and so on. The odd-numbered bunnies (1, 3, 5, ...) each have 2 ears, while the even-numbered bunnies (2, 4, 6, ...) each have 3 ears because of a raised foot. Write a recursive function that calculates the total number of ears for n bunnies. Do this without using loops or multiplication.
> #TRA-4585: Recursion1_ BunnyEars2 is Done

- From_Abdullah/FrontBack.java
Given a string, return a new one with the first and last characters swapped.
> #TRA-4498:Warmup1_frontBack is done

- from_Hawraa/WordFrequencyCounter.java
I implemented getWordCounts to create a map that counts the occurrences of each string in the input array. Each word becomes a key, and its value represents the number of times it appears.
> TRA-4719: Map-2: wordCount added

- From_Abdullah/Or35.java
Given a non-negative number, return true if it is divisible by 3 or by 5. Use the % (modulus) operator to check.
> #TRA-4501:Warmup1_or35 is done

- From_Abdullah/Front22.java
Take the first 2 characters of a string and add them to both the beginning and the end of the original string. For example, "kitten" becomes "kikittenki". If the string has fewer than 2 characters, use the entire string instead.
> #TRA-4502:Warmup1_front22 is done

- from_Hawraa/FirstCharConcatenator.java
I implemented concatWordsByFirstChar to build a map where each key is the first character of strings from the input array, and the value is a concatenation of all strings starting with that character.
> TRA-4721: Map-2: firstChar added

- From_Abdullah/In1020.java
Given two integers, return true if either of them is between 10 and 20, inclusive. Otherwise, return false.
> #TRA-4506:Warmup1_in1020 is done

- From_Mulk/NumberListModifier.java
This method takes a list of integers, first adds 1 to each number, then multiplies each updated number by 10, and returns the resulting list.
> Functional-1 > Math1 task

- From_Abdullah/HasTeen.java
A number is considered a "teen" if it is between 13 and 19, inclusive. Given three integers, return true if at least one of them is a teen.
> #TRA-4507:Warmup1_hasTeen is done

- From_Abdullah/DelDel.java
Given a string, check if "del" appears starting at index 1. If it does, return a new string with that "del" removed; otherwise, return the string unchanged.
> #TRA-4509:Warmup1_delDel is done

- From_Abdullah/MixStart.java
Return true if a string starts with "mix", but the first character can be any character. For example, "pix" or "9ix" would also count.
> #TRA-4510:Warmup1_mixStart is done

- From_Abdullah/IntMax.java
Given three integers, a, b, and c, return the largest of the three.
> #TRA-4512:Warmup1_intMax is done

- From_Abdullah/Close10.java
Given two integers, return the one closest to 10. If both are equally close, return 0.
(Hint: use Math.abs(n) to get the absolute value.)
> #TRA-4513:Warmup1_close10 is done

- From_Maha/AdjacentPairsChecker.java
Added a method to check if an array contains either a pair of consecutive 2s or a pair of consecutive 4s, but not both. Returns true only if exactly one of these conditions is met.
> Add array2 either24

- From_Maha/ArrayPairComparator.java
This method counts how many pairs of elements in two arrays differ but are within 2 in value.
It helps identify "close mismatches" between two arrays.
> Add array2 matchUp file

- from_Hawraa/RepeatedWordCollector.java
I implemented appendRepeatedWords to track word occurrences in the input array and append each word to the result string every time it appears an even number of times. The final string includes only those words that have occurred twice, four times, etc.
> TRA-4722: Map-2: wordAppend added

- From_Abdullah/Max1020.java
Given two positive integers, return the larger one if it is within the range 10–20 inclusive. If neither is in that range, return 0.
> #TRA-4515:Warmup1_max1020 is done

- From_Abdullah/StringE.java
Return true if a string contains 1, 2, or 3 occurrences of the character 'e'. Otherwise, return false.
> #TRA-4516:Warmup1_stringE is done

- From_Mulk/RightDigit.java
This method takes a list of integers and replaces each number with its rightmost digit ( nums.replaceAll(s -> s % 10) ) .
> Functional-1 > RightDigit task

- From_Abdullah/LastDigit.java
Given two non-negative integers, return true if they share the same last digit.
(Hint: use the % operator to get the remainder; e.g., 17 % 10 = 7.)
> #TRA-4517:Warmup1_lastDigit is done

- from_Huria/RemoveNegatives.java
The code create a method that filters out all negative integers from a given list. The method should return a new list containing only the non-negative values, preserving their original order.
> TRA4700: Adding noNeg Task

- From_Abdullah/EveryNth.java
Given a non-empty string and an integer N, return a new string made of every Nth character, starting with the character at index 0. N will always be 1 or greater.
> #TRA-4519:Warmup1_everyNth is done

- From_Maha/ConsecutiveParityChecker.java
This method checks whether the array contains three consecutive numbers of the same parity (all even or all odd).
It returns true if such a sequence exists, otherwise false.
> Add array2 modThree file

- From_Mulk/ToLowerCase.java
This method takes a list of strings and converts every string to lowercase (  strings.replaceAll(s -> s.toLowerCase())).
> Functional-1 > Lower task

- from_Muiayed/commonTwo.java
The commonTwo class defines a method that counts how many unique strings appear in both of two sorted arrays, a and b. The method commonTwo uses two pointers (ia and ib) to traverse both arrays simultaneously. When it finds a matching string at both pointers, it increments the count and skips over any duplicate occurrences of that string in both arrays to ensure each common string is counted only once. If the strings don't match, it advances the pointer of the array with the smaller value to maintain sorted order traversal. This efficient approach avoids nested loops and handles duplicates gracefully. In the main method, three examples demonstrate the method: the first returns 2 for common elements "c" and "x", the second returns 3 for "a", "c", and "x", and the third returns 3 for "a", …
> #TRA-4746: AP -1 > commenTwo

- From_Abdullah/EndUp.java
Given a string, return a new string where the last 3 characters are converted to uppercase. If the string has fewer than 3 characters, uppercase the entire string.
(Hint: use str.toUpperCase() to convert to uppercase.)
> #TRA-4518:Warmup1_endUp is done

- from_Muiayed/SumHeights.java
The SumHeights class defines a method that calculates the total vertical movement between consecutive elements in a subarray of heights. The method sumHeights takes an array of integers representing heights, along with two indices: start and end. It loops from the start index up to end - 1, summing the absolute differences between each pair of adjacent heights. This approach captures both upward and downward changes without regard to direction. The result is returned as the total elevation change over the specified range. In the main method, three test cases are printed: the first computes the change from index 2 to 4, resulting in 3 (from 6 to 7 to 2); the second computes the change from index 0 to 1, yielding 2 (from 5 to 3); and the third calculates the total change from index 0 to 4, …
> #TRA-4737: AP -1 > sumHeights

- from_Muiayed/WordsWithout.java
The WordsWithout class defines a method that filters out a specific target word from an array of strings. The method wordsWithout takes two parameters: an array words and a string target. It first counts how many words in the array are not equal to the target, then creates a new array res of that size. In a second loop, it copies each non-target word into the result array. This ensures that the returned array contains only the words that do not match the target. In the main method, three examples are printed: the first call removes "a" and returns ["b", "c"], the second removes "b" and returns ["a", "c", "a"], and the third removes "c" and returns ["a", "b", "a"]. This method is useful for simple filtering tasks where specific values need to be excluded.
If you'd like to make this …
> #TRA-4699: Ap-1 > wordsWithout

- from_Muiayed/ScoreUp.java
The ScoreUp class implements a scoring system for a multiple-choice quiz. The method scoreUp compares two arrays: key, which holds the correct answers, and answers, which contains a student's responses. It loops through each index and applies a scoring rule: if the answer is "?", it’s skipped (no points gained or lost); if the answer matches the key, 4 points are awarded; if it’s incorrect, 1 point is deducted. The final score is returned. In the main method, three test cases are shown: the first call returns 6 (two correct answers and two wrong), the second returns 11 (three correct, one wrong), and the third returns 16 (all correct). This method is useful for evaluating quizzes with partial or skipped responses.
> #TRA-4698: AP -1 > scoreUp

- from_Muiayed/CopyEvens.java
The CopyEvens class defines a method that extracts a specified number of even integers from an input array. The method copyEvens takes an array nums and an integer count, then creates a new array res of size count to store the result. It uses a for-each loop to iterate through nums, checking each number n to see if it's even (n % 2 == 0). If it is, the number is added to the result array, and the index idx is incremented. Once the desired number of even integers is collected (idx == count), the loop breaks. The method then returns the result array. In the main method, three examples are printed: the first call returns [2, 4], the second returns [2, 4, 8], and the third returns [6, 2, 4], demonstrating how the method selectively copies even numbers in order until the count is met.
> #TRA-4694: AP-1 > copyEvens

- from_Muiayed/DividesSelf.java
- from_Muiayed/HasOne.java
The HasOne class defines a method that checks whether a given integer contains the digit 1. The method hasOne uses a while loop to repeatedly extract the last digit of the number using the modulo operator (n % 10). If the digit equals 1, the method returns true immediately. Otherwise, it removes the last digit by dividing n by 10 and continues the loop. If the loop finishes without finding a 1, the method returns false. In the main method, three test cases are printed: hasOne(10) returns true because 10 contains a 1; hasOne(22) returns false since it doesn’t; and hasOne(220) also returns false. This method is useful for digit-based filtering or pattern recognition in numeric data
> #TRA-4692: AP-1 > hasOne

- from_Muiayed/DividesSelf.java
The DividesSelf class defines a method that checks whether every digit of a given number divides the number itself evenly. The method dividesSelf takes an integer n and iterates through each of its digits using a while loop. It extracts the last digit d using t % 10, and immediately returns false if the digit is 0 (since division by zero is undefined) or if n % d != 0, meaning the digit does not divide the number evenly. If all digits pass the check, the method returns true. In the main method, three examples are tested: dividesSelf(128) returns true because 1, 2, and 8 all divide 128 evenly; dividesSelf(12) also returns true; but dividesSelf(120) returns false due to the presence of a zero digit.
> #TRA-4693: AP-1 > dividesSelf

- from_Muiayed/MatchUp.java
The MatchUp class defines a method that compares two arrays of strings and counts how many corresponding elements start with the same character. The method matchUp loops through the arrays a and b, checking each pair of strings at the same index. It ensures neither string is empty, then compares their first characters using charAt(0). If they match, it increments a counter. The method returns the total count of such matches. In the main method, three test cases are printed: the first call returns 1 because only "aa" and "aaa" start with the same character; the second returns 2 since "aa" matches "aaa" and "bb" matches "b"; the third returns 1 because only "cc" and "ccc" match, while the other strings are empty.
> #TRA-4696> AP -1 > MatchUp

- from_Muiayed/WordsFront.java
The WordsFront class defines a method that extracts the first n elements from a given array of strings. The method wordsFront takes an input array words and an integer n, then creates a new array out of length n. Using a for loop, it copies the first n elements from the original array into the new one. Once the loop completes, it returns the new array. In the main method, three test cases demonstrate how the method works: the first call returns the first element ["a"], the second returns the first two elements ["a", "b"], and the third returns the first three elements ["a", "b", "c"]. This method is useful for previewing or slicing arrays, especially when working with lists of words or data segments.
If you’re building a toolkit for string manipulation or want to add dynamic slicing …
>  #TRA-4690: AP-1 > wordFront

- from_Muiayed/WordsCount.java
The WordsCount class defines a method that counts how many strings in a given array have a specific length. The method wordsCount takes an array of strings and an integer len, then iterates through each word using an enhanced for loop. For every word whose length matches len, it increments a counter. After checking all words, it returns the final count. In the main method, three test cases demonstrate the function: the first call counts words of length 1 and returns 2 ("a" and "b"), the second counts words of length 3 and returns 1 ("ccc"), and the third looks for words of length 4, returning 0 since none match. This method is useful for filtering or analyzing text data based on word size, and could easily be extended to support more complex criteria like prefixes, suffixes, or character …
> #TRA-4689: AP-1 > Wordcount

- from_Muiayed/ScoresIncreasing.java
- from_Muiayed/square56.java
This Java program defines a class named `square56` that processes lists of integers using the `two2` method. The method first doubles each number in the list using `replaceAll(n -> n * 2)`, then removes any number whose last digit is 2 by checking `n % 10 == 2`. In the `main` method, three example lists are passed to `two2` and the results are printed. For instance, the list `[1, 2, 3]` becomes `[2, 4, 6]` after doubling, and then `[2, 6]` after removing `4`, which ends in 4. Similarly, `[2, 6, 11]` becomes `[4, 12, 22]`, and then `[4]` after removing `12` and `22`. The final list `[0]` becomes `[0]` and remains unchanged. This program demonstrates how to use functional programming features in Java to transform and filter collections efficiently.
> #TRA-4486 > Functional-2 > square56

- from_Huria/ExcludeEndingWithNine.java
The code define a method that processes a list of non-negative integers and returns a new list with all numbers that do not end with the digit 9. Use the modulo operator % 10 to determine the last digit of each number.
> TRA4701: Adding no9 Task

- From_Manal/MapBully.java
Added mapBully(Map<String, String> map) to modify and return the input map with the following behavior:
If key "a" has a non-empty value, copy it to key "b"
Then set key "a" to the empty string "" This model the idea of "b" being a bully—taking "a"'s value and leaving it empty.
> TRA-4710: map-1/MapBully

- from_Muiayed/noYY.java
This Java program defines a class called `noYY` that filters out strings of length 3 or 4 from a given list. The core method, `no34`, takes a list of strings and uses the `removeIf` method with a lambda expression to eliminate any string whose length is exactly 3 or 4 characters. This operation modifies the original list and returns the filtered result. In the `main` method, three sample lists are created using `Arrays.asList`, wrapped in `ArrayList` to allow modification, and passed to the `no34` method. The filtered results are printed to the console. For example, the list `["a", "bb", "ccc"]` becomes `["a", "bb"]` after removing `"ccc"`, which has a length of 3. This program demonstrates a concise and functional approach to list filtering in Java using modern collection methods.
> #TRA-4484: Functional-2 > noYY

- from_Muiayed/noLong.java
- from_Muiayed/noZ.java
This Java program defines a class named `noZ` that filters out any strings containing the letter "z" from a list. The core method, `noZ`, takes a list of strings and uses the `removeIf` method with a lambda expression to eliminate all elements that include the character "z". In the `main` method, the program tests this functionality with three different lists. For example, the input `["aaa", "bbb", "aza"]` results in `["aaa", "bbb"]` because "aza" contains a "z". Similarly, `["hziz", "hzello", "hi"]` becomes `["hi"]`, and `["hello", "howz", "are", "youz"]` is reduced to `["hello", "are"]`. This approach is concise and leverages Java’s functional programming features to streamline string filtering.
> #TRA-4481: Functional-2 > noZ

- from_Muiayed/noTeen.java
Your Java program defines a class called `noTeen` that filters out all "teen" numbers—specifically integers between 13 and 19 inclusive—from a list. It uses the `removeIf` method with a lambda expression to efficiently eliminate any number within that range. The `main` method demonstrates this functionality by passing several sample lists to the `noTeen` method and printing the results. For example, the list `[12, 13, 19, 20]` becomes `[12, 20]`, while `[15]` becomes an empty list since 15 falls within the teen range. This approach is concise and leverages Java’s functional programming features to simplify list manipulation.
> #TRA-4480: Funcrional-2 > noTeen

- from_Muiayed/no9.java
- from_Muiayed/noNeg.java
The noNeg method is designed to filter out negative numbers from a given list of integers. It uses the removeIf method, which applies a condition to each element and removes those that satisfy it—in this case, any number less than zero. By returning the modified list, the method ensures that only non-negative values remain. This approach is efficient and readable, making use of Java’s functional programming features to simplify list manipulation. It's especially useful in scenarios where data validation or cleanup is required before further processing.
> #TRA-4478: Functional-2 > noNeg

- from_Muiayed/lower.java
Your Java program demonstrates a clean and effective use of functional programming to convert a list of strings to lowercase. The `lower` method uses `replaceAll(s -> s.toLowerCase())` to transform each string in-place, leveraging Java 8’s lambda expressions for concise and readable code. This approach avoids manual iteration and makes the transformation seamless.
The `main` method provides diverse examples:
- `["Hello", "Hi"]` becomes `["hello", "hi"]`
- `["AAA", "BBB", "ccc"]` becomes `["aaa", "bbb", "ccc"]`
- `["KitteN", "ChocolaTE"]` becomes `["kitten", "chocolate"]`
This snippet is a great illustration of how functional programming can simplify common string operations. If you're building a utility class for text normalization or preparing data for case-insensitive comparisons, this …
> #TRA-4476: Functional-1 > lower

- From_Mulk/RemoveX.java
This method takes a list of strings and removes all lowercase 'x' characters from each string.
> Functional-1 > NoX task

- from_Muiayed/math1.java
Your Java program demonstrates a clean and functional approach to transforming a list of integers using the `replaceAll` method. The `math1` method applies the expression `(n + 1) * 10` to each element, effectively incrementing each number by 1 and then multiplying the result by 10. This concise lambda-based transformation showcases the power of Java 8’s functional features, eliminating the need for manual iteration and enhancing readability.
The `main` method provides varied examples, including typical sequences, repeated values, and a single-element list, which helps illustrate the consistency of the transformation. For instance:
- Input `[1, 2, 3]` becomes `[20, 30, 40]`
- Input `[6, 8, 6, 8, 1]` becomes `[70, 90, 70, 90, 20]`
- Input `[10]` becomes `[110]`
Overall, this snippet is a …
> #TRA-4474: Functional-1 > math1

- from_Muiayed/moreY.java
Your Java program demonstrates a neat use of functional programming to wrap each string in a list with the letter `"y"`. The method `moreY` uses `replaceAll(s -> "y" + s + "y")` to transform each element in-place, making the code concise and expressive. This approach avoids manual iteration and highlights the power of lambda expressions introduced in Java 8. The `main` method provides varied examples—from single characters to full words—showing how the transformation applies uniformly across different inputs. Overall, this snippet is a great example of how simple functional logic can produce clear and consistent modifications to collections.
> #TRA-4473: Functional-1 > moreY

- from_Muiayed/copies3.java
Your Java program demonstrates a clear and efficient use of functional programming to transform a list of strings by tripling each element. The `copies3` method utilizes the `replaceAll` function with a lambda expression (`s -> s + s + s`), which modifies the list in-place by concatenating each string with itself three times. This approach avoids traditional loops and enhances readability, especially for developers familiar with Java 8 and beyond. The `main` method provides diverse examples, including single characters, numbers as strings, empty strings, and full words—showcasing the method’s flexibility and correctness across different input types. Overall, this snippet is a great example of how concise functional logic can be used to perform expressive transformations on collections.
> #TRA-4472: Functional-1 > copies3

- from_Muiayed/square.java
Your Java program elegantly demonstrates the use of functional programming to transform a list of integers by squaring each element. By utilizing the `replaceAll` method with a lambda expression (`n -> n * n`), the code modifies the list in place, making it both concise and efficient. This approach eliminates the need for traditional loops and enhances readability, especially for developers familiar with Java 8 and beyond. The `main` method provides clear examples of how the transformation works with positive, negative, and mixed values, showcasing the versatility of the logic. Overall, this snippet is a great example of modern Java practices that blend clarity with functionality.
>  #TRA-4470: Functional-1 > square

- from_Muiayed/doubling.java
The `doubling` class in Java demonstrates a concise and functional approach to modifying a list of integers. The method `doubling` takes a `List<Integer>` and uses the `replaceAll` method with a lambda expression to double each element in place. This eliminates the need for manual iteration and makes the code both readable and efficient. The `main` method showcases how the transformation works across different input scenarios, including a typical list, a list with repeated and negative values, and an empty list. This technique is particularly useful when applying uniform transformations to collections, and it highlights the power of Java’s functional programming features introduced in Java 8.
>  #TRA-4469: Functional-1 > doubling

- From_Manal/ToppingOne.java
Implemented updatesToppings(Map<String, String> map) to enforce consistent topping rules:
If "ice cream" exists, its value is overwritten with "cherry"
"bread" is always set to "butter", regardless of initial state
This ensures predictable defaults for key food items in the map.
> TRA-4711-Map-1: ToppingOne

- from_Muiayed/wordMultiple.java
The `wordMultiple` class in Java is designed to determine whether each string in an array appears more than once. It uses two maps: one to count occurrences (`counts`) and another to store the final result (`map`) with Boolean values. As the method iterates through the array, it updates the count for each string and sets its corresponding Boolean value to `true` if the count reaches two or more. After the loop, a second pass ensures that any string not already in the result map is explicitly marked as `false`. This guarantees that every string from the input is represented in the output, indicating whether it appears multiple times. The approach is efficient and clear, making it ideal for frequency-based checks in text or data analysis.
> #TRA-4466: Map-2 > wordMultiple

- from_Muiayed/pairs.java
The `pairs` class in Java demonstrates how to construct a map that links the first character of each string to its last character. Using a `HashMap`, the method `pairs` iterates through the input array and extracts the first and last characters of each string using `substring(0, 1)` and `substring(s.length() - 1)`, respectively. These are then stored as key-value pairs in the map. If multiple strings share the same starting character, the last one processed will overwrite previous entries due to the nature of the map. This technique is useful for creating compact representations or summaries of string data, especially when categorizing or indexing based on character positions. The sample outputs in the `main` method illustrate how overlapping keys are handled and how the final map …
> #TRA-4465: Map-2 > pairs

- from_Muiayed/firstChar.java
The `firstChar` class in Java efficiently groups strings based on their initial character using a `HashMap`. By extracting the first character of each string with `substring(0, 1)` and using it as a key, the method appends each full string to the existing value associated with that key. This results in a map where each key corresponds to a starting letter, and the value is a concatenated string of all words sharing that initial. The use of `getOrDefault` ensures smooth handling of new keys without requiring explicit checks. This approach is particularly useful for organizing data alphabetically or categorizing entries by prefix, making it a practical technique for text processing and data grouping tasks.
> #TRA-4464: Map-2 > firstChar

- from_Muiayed/word0.java
The `word0` class defines a method that transforms an array of strings into a map where each unique string becomes a key, and its corresponding value is always set to `0`. The method iterates through the input array and uses `putIfAbsent` to ensure that each string is added to the map only once, preserving uniqueness without overwriting existing entries. This approach is useful when you want to initialize a map with default values for a set of keys derived from a list, such as preparing counters or flags for future updates. The `main` method demonstrates this behavior with several test cases, showing how repeated strings are handled gracefully and only appear once in the final map. Overall, the program offers a clean and efficient way to initialize a map structure from an array of …
>  #TRA-4461: Map-2 > word0

- from_Muiayed/mapBully1.java
- from_Muiayed/word0.java
The `mapBully1` class defines a method called `mapBully` that performs a simple transformation on a map of string key-value pairs. The method checks if the key `"a"` exists in the map. If it does, it copies the value of `"a"` into key `"b"` and then clears the value of `"a"` by setting it to an empty string. This behavior mimics the idea of `"a"` being "bullied"—its value is taken and reassigned to `"b"`, leaving `"a"` empty. This kind of logic is useful for enforcing specific data shifts or simulating priority rules between keys. It's a concise example of conditional map manipulation using Java’s `Map` interface.
> #TRA-4413: Map-1 > mapBully

- from_Muiayed/MapAB4.java
This Java program defines a class named MapAB4 that performs conditional logic on a map containing string key-value pairs. The method mapAB4 checks whether both keys "a" and "b" exist in the map. If they do, it compares the lengths of their corresponding values. If the lengths are different, it adds or updates the key "c" with the longer of the two values. However, if the lengths are equal, it clears both "a" and "b" by setting their values to empty strings. This logic allows the map to either highlight the longer value or neutralize both entries when they are of equal length. The main method demonstrates this behavior with three test cases, showing how the map is transformed depending on the relative lengths of the values for "a" and "b". This approach is useful for enforcing conditional …
> #TRA-4409: Map-1 > mapAB4

- From_Manal/ToppingTwo.java
Added updateToppings(Map<String, String> map) to enforce topping consistency:
If "ice cream" has a value, copy it to "yogurt"
If "spinach" has a value, replace it with "nuts"
This ensures "yogurt" mirrors "ice cream" when present, and "spinach" always gets a healthier substitute.
> TRA-4716-Map-1: topping2

- from_Muiayed/Topping2.java
The Java program defines a class named `Topping2` that modifies a map of food items and their toppings based on specific conditions. The method `topping2` checks if the key `"ice cream"` exists in the map, and if so, it sets the value of `"yogurt"` to match the value of `"ice cream"`. Additionally, if the key `"spinach"` is present, its value is replaced with `"nuts"`. These rules demonstrate how to copy values between keys and override existing ones using Java’s `Map` interface. The `main` method showcases three test cases: one where `"ice cream"` is copied to `"yogurt"`, another where both `"ice cream"` and `"spinach"` are modified, and a third where no changes occur because the relevant keys are missing. This approach is useful for enforcing consistent data transformations, especially …
> #TRA-4405: Map-1 > Topping-2

- from_Huria/RemoveStringsContainingZ.java
The code given a list of strings, return a new list that excludes any string containing the character "z". Use the str.contains("z") method to check for the presence of "z" in each string.
> TRA4704 : Adding noZ Task

- from_Muiayed/Topping1.java
This Java program defines a class called `Topping1` that modifies a map of food items and their toppings using the `topping1` method. The method checks whether the map contains the key `"ice cream"` and, if it does, updates its value to `"cherry"`. It also ensures that the key `"bread"` is present with the value `"butter"`, regardless of the map’s initial contents. This kind of logic is useful for enforcing default values or overriding specific entries in a configuration-like structure. The `main` method demonstrates how the map is transformed in three different scenarios: one where `"ice cream"` is present, one with an empty map, and one with unrelated keys. Each output reflects the consistent application of the topping rules, showcasing how conditional updates and insertions work with …
> #TRA-4404: Map-1 > Topping-1

- from_Muiayed/mapAB.java
This Java program defines a class named `mapAB` that modifies a map of food items and their toppings using the `topping1` method. The method checks if the key `"ice cream"` exists in the map, and if so, updates its value to `"cherry"`. Regardless of the map's initial content, it also adds or updates the key `"bread"` with the value `"butter"`. This ensures that certain default toppings are always present or corrected. The `main` method demonstrates this behavior with three different test cases, showing how the map is transformed based on its original entries. This kind of logic is useful for enforcing consistent values in a configuration or menu system, and it highlights how conditional checks and updates can be applied efficiently using Java’s `Map` interface.
> #TRA-4403: Map-1 > mapAB

- from_Muiayed/mapShare.java
The MapShare class demonstrates a simple transformation on a Map<String, String> using conditional logic. The mapShare method checks if the map contains a key "a"; if it does, it copies the value associated with "a" into key "b", effectively sharing "a"'s value. It also removes the key "c" from the map, regardless of whether it exists. This kind of operation is useful when enforcing specific rules or cleanup steps on a data structure before further processing. The main method provides test cases that show how the map changes based on different initial configurations, making it easy to verify the behavior. Overall, this is a concise and practical example of how to manipulate key-value pairs in Java using the Map interface.
> #TRA-4401: Map-1 > mapShare

- from_Muiayed/MaxMirror.java
The `MaxMirror` class defines a method that identifies the longest "mirror" section within an array—meaning the largest group of contiguous elements that appears somewhere else in the array in reverse order. The `maxMirror` method uses a nested loop to compare every possible starting point in the array with every possible ending point in reverse. When matching elements are found, it counts how many consecutive values match in mirrored positions. The maximum count found during this process is returned as the result. This approach is efficient for small arrays and elegantly handles overlapping and nested mirror sections. The `main` method runs several test cases, printing both the input and the maximum mirror length found, making it easy to verify the correctness of the logic. It's a great …
> #TRA-4345: Array-3 > MaxMirror

- from_Muiayed/CanBalance.java
The canBalance method tackles a classic array partitioning problem: determining whether an array of integers can be split into two contiguous parts with equal sums. It starts by calculating the total sum of the array. If the total is odd, it immediately returns false, since an odd number can't be evenly divided. Then it sets a target value—half of the total—and iterates through the array, accumulating a running sum from the left. If at any point this running sum equals the target, it means the array can be split at that index, and the method returns true. Otherwise, it returns false after the loop. This approach is efficient and intuitive, making it a great exercise in cumulative sums, early exits, and control flow. The included test cases demonstrate both successful and unsuccessful …
> #TRA-4341: Array-3 > CanBalance

- From_Manal/ToppingThree.java
Implemented updateToppings(Map<String, String> map) to enforce topping propagation:
If "potato" has a value, copy it to "fries"
If "salad" has a value, copy it to "spinach"
This ensures consistent topping behavior across related food keys.
> TRA-4723-Map-1: topping3

- from_Muiayed/maxSpan.java
The `maxSpan` problem asks you to find the largest span between two identical elements in an array of integers. A span is defined as the number of elements between the first and last occurrence of the same value, inclusive. For example, in the array `[1, 2, 1, 1, 3]`, the value `1` appears first at index 0 and last at index 3, giving a span of 4. The goal is to iterate through the array, identify each unique value, and calculate the distance between its first and last appearance. You then return the maximum span found among all values. If the array is empty, the result should be 0. This problem helps reinforce your understanding of nested loops, array traversal, and conditional logic—great practice for sharpening your Java skills.
> #TRA-4338: Array-3 > maxSpan

- from_Muiayed/WithoutTen.java
- from_Muiayed/ZeroMax.java
The WithoutTen class defines a method that removes all occurrences of the number 10 from an integer array and shifts the remaining elements to the front. The withoutTen method creates a new array of the same length and uses an index pointer idx to insert non-10 values sequentially. Any leftover positions in the result array remain as default zeroes, effectively replacing removed 10s with zero. The main method demonstrates this with examples like [1, 2, 0, 0], [2, 0, 0], and [1, 99, 0], showing how the method filters out 10s while maintaining array length.
> #TRA-4334: Array-2 > WithoutTen

- from_Muiayed/TenRun.java
The TenRun class modifies an array of integers so that every number following a multiple of 10 is replaced by that multiple, until another multiple of 10 appears. The tenRun method uses a variable cur to track the most recent multiple of 10. As it iterates through the array, it updates cur when it encounters a value divisible by 10. If cur is set and the current number isn't a multiple of 10, it replaces that number with cur. This creates a "run" effect where values are overridden by the last seen multiple of 10. The main method showcases this with examples like [2, 10, 10, 10, 20, 20] and [10, 10, 20, 20].
> #TRA-4329: Array-2 > tenRun

- from_Huria/RemoveStringsLengthFourOrMore.java
The code given a list of strings, return a new list that omits any string with a length of 4 or more characters. Only strings shorter than 4 characters should be included in the result.
> TRA4705: Adding noLong Task

- from_Muiayed/FizzArray3.java
The FizzArray3 class defines a method that generates an array of integers starting from a specified start value up to but not including an end value. The fizzArray3 method calculates the length of the array as end - start, then fills it using a for-loop, assigning each element the value start + i. This creates a sequential range of integers, making it useful for tasks like indexing, iteration, or generating test data. The main method demonstrates this functionality with sample inputs, printing arrays like [5, 6, 7, 8, 9], [11, 12, ..., 17], and [1, 2] using Arrays.toString() for readable output.
> #TRA-4327: Array-2 > fizzArrays3

- from_Muiayed/TripleUp.java
The TripleUp class defines a method that checks whether an array contains three consecutive increasing numbers, such as 4, 5, 6. The tripleUp method iterates through the array and compares each group of three adjacent elements. If the second number is exactly one greater than the first, and the third is one greater than the second, the method returns true, indicating a strictly increasing sequence of length three. If no such sequence is found, it returns false. The main method demonstrates this logic with sample arrays, showing how the method detects or rejects the presence of such patterns.
> #TRA-4326: Array-2 > TripleUp

- from_Muiayed/sameEnds.java
The sameEnds class defines a method that checks whether the first len elements of an array match the last len elements in the same order. The sameEnds method uses a loop to compare each element at the beginning of the array (nums[i]) with its corresponding element at the end (nums[nums.length - len + i]). If any pair doesn’t match, the method returns false; otherwise, it returns true after completing the loop. The main method demonstrates this logic with sample arrays, showing how the method evaluates different segment lengths for symmetry between the start and end of the array.
> #TRA-4325: Array-2 > sameEnds

- from_Muiayed/has77.java
The has77 class defines a method that checks whether an array contains two 7s that are either adjacent or separated by one element. The has77 method iterates through the array and looks for two specific patterns: a pair of 7s at consecutive indices (i and i+1), or a pair with one element in between (i and i+2). If either pattern is found, the method returns true; otherwise, it returns false. This logic is useful for detecting specific number arrangements in arrays, and the main method demonstrates it with sample inputs that test both valid and invalid cases.
> #TRA-4320: Array-2 > has77

- from_Muiayed/Either24.java
The Either24 class defines a method that checks whether an array contains either a pair of adjacent 2s or a pair of adjacent 4s—but not both. The either24 method uses two boolean flags, two and four, to track the presence of consecutive 2s and 4s as it iterates through the array. If a pair of 2s is found, two is set to true; similarly, a pair of 4s sets four to true. The method then returns the result of two ^ four, using the XOR operator to ensure that only one of the two conditions is true. The main method demonstrates this logic with sample arrays, showing how the method correctly identifies arrays that contain only one type of adjacent pair and returns false when both are present.
> #TRA-4215: Array-2 > Either 24

- from_Muiayed/IsEverywhere.java
The IsEverywhere class defines a method that checks whether a given value appears in every adjacent pair of elements in an integer array. The isEverywhere method iterates through the array and examines each consecutive pair of elements. If neither element in a pair matches the specified value, the method returns false, indicating the value is not "everywhere." Otherwise, if the value appears in at least one position of every pair, the method returns true. The main method tests this logic with sample arrays and values, demonstrating how the method validates the presence of the value across adjacent pairs.
> #TRA-4214: Array-2> IsEverywhere 

- from_Muiayed/only14.java
The only14 class defines a method that checks whether all elements in a given integer array are either 1 or 4. The only14 method iterates through each element of the array using an enhanced for-loop and returns false immediately if it encounters any number that is not 1 or 4. If the loop completes without finding any invalid values, it returns true, confirming the array contains only the allowed numbers. The main method demonstrates this logic with three test cases, printing true for arrays like {1, 4, 1, 4} and {1, 1}, and false for {1, 4, 2, 4} which includes an invalid value (2).
> #TRA-4212: Array-2 > only14 

- from_Muiayed/FizzArray2.java
sequence of numbers from 0 up to but not including n. The fizzArray2 method initializes a String[] of length n, then fills each index with the string version of its position using String.valueOf(i). This is useful when numeric values need to be stored or displayed as strings, such as in UI elements or formatted output. The main method demonstrates the function with sample inputs, printing arrays like ["0", "1", "2", "3"], ["0", "1", ..., "9"], and ["0", "1"] using Arrays.toString() for readable output.
> #TRA-4210: Array-2 > FizzArray2 

- from_Muiayed/has22.java
The has22 class checks whether an integer array contains a pair of consecutive 2s. The has22 method uses a standard for-loop to iterate through the array, stopping one element before the end to avoid out-of-bounds errors. During each iteration, it checks if the current element and the next one are both equal to 2. If such a pair is found, the method immediately returns true; otherwise, it completes the loop and returns false. The main method demonstrates this logic with various test cases, showing how the method accurately detects adjacent 2s and ignores isolated ones.
> #TRA-4205: Array-2 > has22

- From_Manal/RemoveEqualAB.java
Added removeIfEqual(Map<String, String> map) to clean up redundant key-value pairs:
If both "a" and "b" exist and their values are equal, remove both keys from the map
All other entries remain unchanged
> TRA-4712-Map-1: mapAB2

- From_Maha/PairOfTwos.java
This method checks that every 2 in the array is part of a pair of adjacent 2s.
It returns false if any 2 appears alone.
> Add array2 towTwo file

- from_Muiayed/countEven.java
The countEven class defines a method that counts how many even numbers are present in an integer array. The countEvens method iterates through each element of the array using an enhanced for-loop and checks whether the number is divisible by 2. If it is, the counter is incremented. After scanning the entire array, the method returns the total count of even numbers. This simple yet effective logic ensures accurate detection of even values regardless of array size or content. The main method demonstrates the functionality with various test cases, including arrays with mixed values, all even numbers, and no even numbers, showcasing the method’s reliability across different scenarios.
> #TRA-4200: Array -2 >countEven 

- from_Muiayed/SumDigit.java
The SumDigit class defines a method that calculates the sum of all individual digits present in a given string. The sumDigits method iterates through each character of the input string and checks whether it is a digit using Character.isDigit. If a digit is found, it is converted to an integer and added to a running total. This approach ensures that only numeric characters are considered, and multi-digit numbers are treated as separate digits. The main method demonstrates the functionality with various test cases, including strings with embedded digits and strings without any digits, showcasing the method’s ability to handle diverse input formats.
> #TRA-4199: String-3 > SumDigits

- from_Muiayed/MaxBlock.java
The MaxBlock class is designed to find the length of the largest block of consecutive identical characters within a given string. The maxBlock method begins by checking if the string is empty, returning 0 in that case. Otherwise, it initializes two counters: max to track the longest block found, and current to count the length of the ongoing block. As it iterates through the string, it compares each character with the one before it. If they match, current is incremented and potentially updates max. If not, current resets to 1. This efficient linear scan ensures that the method returns the correct maximum block length. The main method demonstrates the functionality with various examples, including strings with multiple blocks and an empty string.
> #TRA-4195: String-3 > MaxBlock 

- from_Muiayed/MirrorEnds.java
The MirrorEnds class identifies the longest substring at the beginning of a given string that mirrors its counterpart at the end. The mirrorEnds method compares characters from the start and end of the string, moving inward, and continues as long as the characters match. Once a mismatch is found or the entire string is traversed, it returns the substring from the start up to the last matching index. This technique effectively captures symmetrical patterns that reflect across the center of the string. The main method demonstrates this logic with sample inputs, showcasing how mirrored segments like "ab" in "abXYZba" or "aba" in "aba" are extracted.
> #TRA-4194: String-3 > MirrorEnds 

- From_Manal/MapABThree.java
Implemented synchronizeAB(Map<String, String> map) to ensure mutual presence of keys "a" and "b":
If exactly one of "a" or "b" exists, copy its value to the missing key
If both keys are present or absent, the map remains unchanged
This enforces symmetry between "a" and "b" when only one is defined.
> TRA-4717-Map-1: mapAB3

- from_Muiayed/GHappy.java
The GHappy program defines a method that determines whether all instances of the lowercase letter 'g' in a given string are "happy." A 'g' is considered happy if it is immediately preceded or followed by another 'g'. The method iterates through each character in the string, and whenever a 'g' is found, it checks its neighboring characters to ensure at least one of them is also a 'g'. If any 'g' is found to be isolated—without a 'g' on either side—the method returns false. Otherwise, it returns true, confirming that all 'g' characters are part of valid pairs. The main method includes sample test cases that demonstrate the method’s behavior with different string patterns, including happy and unhappy 'g' configurations
> #TRA-4191: String-3 > gHappy

- from_Muiayed/WordEnds.java
The wordEnds method searches through a string for every occurrence of a given word, and for each match, it collects the characters that appear immediately before and after the word (if such characters exist). The method loops through the string and checks at each position whether the substring starting there matches the target word. If a match is found, and there is a character before the word, it is added to the result. Similarly, if there is a character after the word, it is also added. The matched word itself is not included in the output—only the surrounding characters are. For example, wordEnds("abcXY123XYijk", "XY") returns "c13j" because those are the characters that appear before and after each "XY". This method is useful for extracting context around specific word occurrences in …
> #TRA-3872: String-2 > wordEnds 

- from_Muiayed/ZipZap.java
The zipZap method processes a string by identifying every occurrence of a three-character substring that starts with 'z' and ends with 'p', regardless of the middle character. When such a pattern is found, the method removes the middle character and appends only the 'z' and 'p' to the result. It continues this process throughout the entire string, character by character. Any part of the string that does not match this pattern is added to the result unchanged. For example, "zipXzap" becomes "zpXzp", and "zopzop" becomes "zpzp". The purpose of this logic is to simplify specific "z?p" patterns while preserving the rest of the string content.
> #TRA-3863: String - 2> zipZap

- From_Maha/ArrayEndsChecker.java
This method verifies if the first len elements of an array match the last len elements.
It returns true only if both ends are identical. ✅
> Add array2 sameEnds

- from_Muiayed/RepeatSeparator.java
The RepeatSeparator class defines a method called repeatSeparator that constructs a string by repeating a given word a specified number of times, with a separator inserted between each repetition. The method takes three parameters: word, sep, and count. If count is zero, it returns an empty string. Otherwise, it starts by appending the first instance of word to a StringBuilder, then enters a loop to append the separator followed by the word for the remaining count - 1 times. For example, calling repeatSeparator("Word", "X", 3) produces "WordXWordXWord", while repeatSeparator("This", "And", 2) yields "ThisAndThis", and repeatSeparator("This", "And", 1) simply returns "This". This method is useful for generating structured, repeated patterns in strings—perfect for formatting output or …
> #TRA-3856: String-2 > RepeatSeparator 

- from_Muiayed/RepeatFront.java
The RepeatFront class defines a method called repeatFront that constructs a new string by repeatedly appending decreasing-length prefixes of the input string. Given a string str and an integer n, the method starts with the first n characters and appends progressively shorter prefixes down to one character. This is achieved using a loop that runs from n down to 1, appending str.substring(0, k) to a StringBuilder on each iteration. For example, calling repeatFront("Chocolate", 4) produces "ChocChoChC", since it appends "Choc", "Cho", "Ch", and "C" in order. The main method demonstrates this logic with three test cases, showcasing how the method dynamically builds the output based on the input length and the value of n.
> #TRA-3855: String-2 > RepeatFront 

- from_Muiayed/RepeatEnd.java
The RepeatEnd class defines a method called repeatEnd that takes a string and an integer n, then returns a new string formed by repeating the last n characters of the original string exactly n times. It first extracts the substring from the end of the input using str.substring(str.length() - n), then appends this segment to a StringBuilder in a loop that runs n times. In the main method, the program demonstrates this behavior with three examples: "Hello" and 3 produces "llollollo"; "Hello" and 2 gives "lolo"; and "Hello" and 1 results in "o". This showcases how the method dynamically adapts to different values of n while consistently repeating the tail segment
> #TRA-3853: String-2 > RepeatEnd 

- from_Muiayed/MixString.java
The MixString class defines a method that merges two strings by alternating their characters. The method mixString uses a StringBuilder to construct the output, looping through both input strings up to the length of the shorter one. For each index, it appends one character from each string in sequence. After the loop, if either string is longer, the remaining characters from the longer string are appended to the result. In the main method, the program demonstrates this logic with three examples: "abc" and "xyz" produce "axbycz"; "Hi" and "There" produce "HTihere"; and "xxxx" and "There" produce "xTxhxeerre"—showing how the method gracefully handles strings of unequal length.
> #TRA-3852: String-2 > MixString 

- from_Muiayed/XyBalance.java
The XyBalance class defines a method that checks whether every 'x' in a given string is "balanced" by a 'y' that appears after it. The method xyBalance tracks the last positions of 'x' and 'y' as it iterates through the string. If no 'x' is found, the string is considered balanced by default. Otherwise, the method returns true only if the last 'y' appears after the last 'x'. In the main method, the program tests this logic with three examples: "aaxbby" returns true because the final 'y' comes after the last 'x'; "aaxbb" returns false since there's no 'y' to balance the 'x'; and "yaaxbb" also returns false for the same reason.
> #TRA-3831: String-2 > XyBalance 

- from_Muiayed/CatDog.java
The CatDog class contains a method named catDog that checks whether the number of occurrences of the substring "cat" is equal to the number of "dog" in a given string. It does this by iterating through the string in chunks of three characters using substring(i, i + 3) and incrementing counters for each match. The method returns true if the counts are equal, and false otherwise. In the main method, the program tests this logic with three examples: "catdog" (returns true because both appear once), "catcat" (returns false because "cat" appears twice and "dog" not at all), and "1cat1cadodog" (returns true as both "cat" and "dog" appear once).
> #TRA-3817: String-2 > CatDog 

- from_Muiayed/CountHi.java
The CountHi class defines a method that counts how many times the substring "hi" appears in a given string. The method CountHi loops through the input string, checking each pair of consecutive characters using substring(i, i + 2). If the pair matches "hi", it increments a counter. This approach ensures overlapping instances like "hihi" are both counted. In the main method, the program tests this logic with three sample strings: "abc hi ho" (returns 1), "ABChi hi" (returns 2), and "hihi" (returns 2), demonstrating the method’s ability to detect multiple and overlapping occurrences of "hi".
> #TRA-3797: String-2 > CountHi

- from_Muiayed/BlackJack.java
The `BlackJack` class in Java models a simplified version of the classic card game rule where the goal is to get as close to 21 as possible without going over. The method `blackjack(int a, int b)` takes two integer values and returns the one that is closest to 21 without exceeding it. If both values are over 21, the method returns 0, indicating a bust. If only one value is over 21, the other is returned. If neither exceeds 21, the method returns the higher of the two using `Math.max(a, b)`. This logic is concise and effective, demonstrating how conditional statements can be used to enforce game rules and handle edge cases cleanly. It's a great example of how to apply real-world logic in a programming context.
> #TRA-3712: Logic-2 > BlackJack 

- from_Muiayed/LoneSum.java
The `LoneSum` class in Java defines a method that calculates the sum of three integers, but only includes values that are unique among the three. The method `loneSum(int a, int b, int c)` initializes a `sum` variable to zero and then checks each number: if a number is not equal to either of the other two, it is added to the sum. This ensures that any duplicate values are excluded from the total. For example, if all three numbers are the same, the result will be zero; if only one number is unique, only that value will be returned. This approach is useful for filtering out repeated values and focusing on distinct contributions in a set of inputs.
> #TRA-3707: Logic-2 > lonesum

- From_Maha/ConsecutiveSequenceChecker.java
This method checks if the array contains three consecutive increasing numbers in a row.
It returns true if such a sequence exists. ✅
> Add array2 tripleUp file

- from_Muiayed/MakeBricks.java
The `MakeBricks` class in Java defines a method that determines whether it’s possible to reach a specific goal length using a combination of small bricks (1 inch each) and big bricks (5 inches each). The method `makeBricks(int small, int big, int goal)` uses a clever approach: it calculates the maximum number of big bricks that can be used without exceeding the goal (`Math.min(big, goal / 5)`), then subtracts their total length from the goal to see if the remaining length can be covered by the available small bricks. Additionally, it checks whether the total combined length of all bricks is at least equal to the goal. If both conditions are satisfied, the method returns `true`; otherwise, it returns `false`. This concise logic efficiently solves a common resource allocation problem using …
> #TRA-3706: Logic-2 > MakeBricks 

- from_Muiayed/SumLimit.java
The `SumLimit` class in Java defines a method that adds two integers but imposes a constraint based on the number of digits in the result. The method `sumLimit(int a, int b)` calculates the sum of `a` and `b`, then compares the length of the sum (converted to a string) with the length of `a`. If the sum has the same number of digits as `a`, it returns the sum; otherwise, it returns `a`. This logic ensures that the result doesn't exceed a certain digit limit defined by the first number. In the `main` method, the examples illustrate this behavior: `sumLimit(2, 3)` returns 5 because both `a` and the sum have one digit; `sumLimit(8, 3)` returns 8 because the sum (11) has two digits, exceeding the one-digit length of `a`; and `sumLimit(8, 1)` returns 9 since both `a` and the sum have one …
> #TRA-3705: logic-1 > SumLimit 

- From_Manal/MapShare.java
Added mapShare(Map<String, String> map) to modify and return the input map with the following logic:
If key "a" exists, copy its value to key "b"
Always remove key "c" from the map
All other keys remain unchanged
This ensures "b" mirrors "a" when present, and "c" is consistently excluded.
> TRA-4714: Map-1/MapShare

- from_Muiayed/BlueTicket.java
- from_Muiayed/GreenTicket.java
The `BlueTicket` class in Java defines a method that calculates a reward based on the sum of pairs of three input integers. The method `blueTicket(int a, int b, int c)` first computes the sums of three pairs: `ab = a + b`, `bc = b + c`, and `ac = a + c`. If any of these sums equals 10, the method returns 10 as the highest reward. If the sum of `a + b` exceeds either of the other two sums by exactly 10, it returns 5. If neither condition is met, it returns 0. The `main` method demonstrates this logic with examples: `blueTicket(9, 1, 0)` returns 10 because `a + b = 10`; `blueTicket(9, 2, 0)` returns 0 since no condition is satisfied; and `blueTicket(6, 1, 4)` returns 10 because `b + c = 5` and `a + c = 10`. This class showcases how conditional logic and arithmetic can be combined to …
> #TRA3702: Logic-1 > BlueTicket 

- from_Muiayed/MaxMod5.java
The `MaxMod5` class in Java defines a method that compares two integers based on specific rules involving their values and their remainders when divided by 5. The method `maxMod5(int a, int b)` first checks if the two numbers are equal—if so, it returns 0. If they have the same remainder when divided by 5, it returns the smaller of the two numbers. Otherwise, it returns the larger number. This logic introduces a twist to typical comparisons by factoring in modular arithmetic. In the `main` method, the examples illustrate this behavior: `maxMod5(2, 3)` returns 3 because the numbers are different and have different remainders; `maxMod5(6, 2)` returns 6 for the same reason; and `maxMod5(3, 2)` returns 3, again choosing the larger value since the remainders differ. This class is a clever …
> #TRA-3700: Logic-1 > MaxMod5 

- from_Muiayed/LessBy10.java
The `LessBy10` class in Java defines a method that checks whether any two of the three given integers differ by 10 or more. The method `lessBy10(int a, int b, int c)` uses the `Math.abs()` function to calculate the absolute difference between each pair of numbers—`a` and `b`, `b` and `c`, and `a` and `c`. If any of these differences is greater than or equal to 10, the method returns `true`; otherwise, it returns `false`. In the `main` method, the first example returns `true` because the difference between 1 and 11 is 10; the second returns `false` since none of the differences reach 10; and the third returns `true` because the difference between 11 and 1 is also 10. This class provides a simple and efficient way to detect significant gaps between numbers.
> #TRA-3698: Logic-1 > LessBy10 

- from_Muiayed/InOrderEqual.java
The `InOrderEqual` class in Java defines a method that checks whether three integers are in a specific order, either strictly increasing or non-decreasing, based on a boolean flag. The method `inOrderEqual(int a, int b, int c, boolean equalOk)` returns `true` if the values are in the correct order: when `equalOk` is `false`, it requires strict inequality (`a < b < c`), and when `equalOk` is `true`, it allows equality between adjacent values (`a <= b <= c`). This makes the method flexible for different use cases where either strict or relaxed ordering is acceptable. The `main` method demonstrates this with three examples: the first returns `true` because 2, 5, and 11 are strictly increasing; the second returns `false` because 7 is not less than 6; and the third returns `true` because …
> #TRA-3696: Logic-1 > InOrderEqual

- from_Muiayed/TwoAsOne.java
The `TwoAsOne` class in Java demonstrates a simple yet insightful use of arithmetic logic to determine whether any two of three integers can sum up to the third. The method `twoAsOne(int a, int b, int c)` returns `true` if `a + b == c`, `a + c == b`, or `b + c == a`, effectively checking all possible pairwise combinations. This kind of logic is useful in scenarios where relationships between values matter—such as validating equations, solving puzzles, or implementing rule-based systems. The examples in the `main` method illustrate the concept clearly: `twoAsOne(1, 2, 3)` and `twoAsOne(3, 1, 2)` both return `true` because two numbers add up to the third, while `twoAsOne(3, 2, 2)` returns `false` since no such combination exists. The class is a great example of how concise code can express …
> #TRA-3694: Logic-1 > TwoAsOne 

- from_Muiayed/InOrder.java
The `InOrder` class in Java defines a method that checks whether three integers are in a strictly increasing order, with a special exception controlled by a boolean flag. The method `inOrder(int a, int b, int c, boolean bOk)` returns `true` if `b` is greater than `a` and `c` is greater than `b`, unless `bOk` is `true`, in which case the condition `b > a` is ignored. This allows for flexible validation depending on context—such as relaxing rules under certain conditions. The examples in the `main` method illustrate this logic: `inOrder(1, 2, 4, false)` returns `true` because all values are in order; `inOrder(1, 2, 1, false)` returns `false` because `c` is not greater than `b`; and `inOrder(1, 1, 2, true)` returns `true` because the `bOk` flag allows `b` to equal `a`. This method is useful …
> #TRA-3695: Logic-1 > InOrder 

- from_Muiayed/TeaParty.java
The `TeaParty` class in Java uses conditional logic to evaluate the quality of a party based on the amounts of tea and candy provided. The method `teaParty(int tea, int candy)` returns an integer value representing the party's rating: `0` for a bad party, `1` for a good party, and `2` for a great party. A party is considered bad if either tea or candy is less than 5. If one of the items is at least double the other, the party is rated great. Otherwise, it's simply good. This logic reflects a balance between quantity and proportion, emphasizing that abundance alone isn’t enough—there must be harmony. The examples in the `main` method illustrate this well: `teaParty(6, 8)` returns `1` for a decent balance, `teaParty(3, 8)` returns `0` due to insufficient tea, and `teaParty(20, 6)` returns …
> #TRA-3691: Logic-1 > TeaParty 

- from_Muiayed/AnswerCell.java
The `AnswerCell` class in Java models a decision-making process for whether to answer a phone call based on three conditions: time of day, caller identity, and sleep status. The method `answerCell(boolean isMorning, boolean isMom, boolean isAsleep)` returns `false` immediately if the person is asleep, ensuring no calls are answered during rest. If it's morning, the method only returns `true` if the caller is Mom—suggesting a special exception for her. Otherwise, if it's not morning and the person is awake, the call is answered regardless of who’s calling. This logic reflects a realistic and relatable scenario, where priorities shift based on context. The sample outputs in the `main` method demonstrate how these conditions interact: calls are ignored during sleep, selectively answered in …
> #TRA-3690: Logic-1 > AnswerCell 

- from_Muiayed/TeenSum.java
The `TeenSum` class in Java demonstrates a conditional override of arithmetic logic based on a specific age range. The method `teenSum(int a, int b)` checks whether either of the two input integers falls within the "teen" range—defined here as 13 to 19 inclusive. If at least one of the numbers is a teen, the method returns a fixed value of 19, regardless of the actual sum. Otherwise, it returns the normal sum of `a + b`. This approach is useful for enforcing special rules or exceptions in applications like age-based scoring, promotional logic, or custom validation systems. The examples in the `main` method clearly illustrate the behavior: `teenSum(3, 4)` returns 7 since neither number is a teen, while `teenSum(10, 13)` and `teenSum(13, 2)` both return 19 due to the presence of a teen …
> #TRA-3689: Logic-1 > TeenSum 

- From_Mulk/RemoveNine.java
This method removes all numbers from the list that end with the digit 9 and returns the updated list.
> Functional-2 > No9 task

- from_Muiayed/In1To10.java
The `In1To10` class in Java demonstrates a simple yet effective use of conditional logic to evaluate a number based on a mode flag. The method `in1To10(int n, boolean outsideMode)` returns `true` if the number `n` falls within the range 1 to 10 when `outsideMode` is `false`, or if it lies outside that range when `outsideMode` is `true`. This dual behavior allows the method to flexibly switch between inclusive and exclusive range checks, making it useful for scenarios like input validation, boundary testing, or game logic. The `main` method provides clear examples of how the function behaves under different conditions, showcasing its practical application and readability. Overall, the class is a great example of how concise code can deliver versatile functionality.
> #TRA-3683: Logic-1 > In1To10 

- from_Muiayed/AlarmClock.java
The `AlarmClock` class in Java determines what time the alarm should ring based on the day of the week and whether it's a vacation. The method `alarmClock(int day, boolean vacation)` first checks if the given day is a weekend—represented by `0` (Sunday) or `6` (Saturday). If it's a vacation, the alarm is turned "off" on weekends and set to "10:00" on weekdays. If it's not a vacation, the alarm rings at "10:00" on weekends and "7:00" on weekdays. The `main` method tests three scenarios: `alarmClock(1, false)` returns `"7:00"` since it's a weekday and not a vacation; `alarmClock(5, false)` also returns `"7:00"` for the same reason; and `alarmClock(0, false)` returns `"10:00"` because it's Sunday and not a vacation. This class is a great example of using boolean logic and ternary operators …
> #TRA-3681: Logic-1 > AlarmClock 

- from_Muiayed/CaughtSpeeding.java
The `CaughtSpeeding` class in Java determines the severity of a speeding ticket based on the driver's speed and whether it's their birthday. The method `caughtSpeeding(int speed, boolean isBirthday)` adjusts the speed limits by adding a 5 mph grace if it's the driver's birthday. If the adjusted speed is 60 or less, the result is `0` (no ticket); if it's between 61 and 80 inclusive, the result is `1` (small ticket); and if it's above 80, the result is `2` (big ticket). In the `main` method, three cases are tested: `caughtSpeeding(60, false)` returns `0` since the speed is within the limit; `caughtSpeeding(65, false)` returns `1` because the speed exceeds 60 but not 80; and `caughtSpeeding(65, true)` returns `0` as the birthday grace bumps the limit to 65, making the speed acceptable. This …
> #TRA-3679: Logic-1>  CaughtSpeeding 

- from_Muiayed/cigarParty.java
The `cigarParty` class in Java defines a method that determines whether a party is successful based on the number of cigars and whether it’s held on a weekend. The method `cigarParty(int cigars, boolean isWeekend)` uses a conditional expression to apply different rules: on weekends, the party is successful if there are at least 40 cigars, with no upper limit; on weekdays, the number of cigars must be between 40 and 60 inclusive. In the `main` method, three scenarios are tested—30 cigars on a weekday returns `false`, 50 cigars on a weekday returns `true`, and 70 cigars on a weekend also returns `true`. This example illustrates how to apply conditional logic based on multiple inputs and is a great exercise in using ternary operators and boolean expressions effectively.
> #TRA3676: Logic 1 > cigarParty 

- from_Muiayed/Unlucky1.java
- from_Muiayed/cigarParty.java
The `Unlucky1` class in Java checks whether a specific pattern—`1` followed by `3`—appears in certain positions of an integer array. The method `unlucky1(int[] nums)` returns `true` if the pair `1, 3` is found at the beginning (index 0 and 1), just after the beginning (index 1 and 2), or at the end of the array (last two elements). If the array has fewer than two elements, it immediately returns `false`, since the pattern can't exist. In the `main` method, different arrays are tested to demonstrate how the method identifies this “unlucky” sequence. For example, `{1, 3, 4, 5}` returns `true` because the pattern is at the start, while `{1, 1, 1}` returns `false` since the sequence never appears. This example is a clever use of conditional logic and indexing to detect a specific pattern in …
> #TRA-3579: Array-1 > Unlucky1 

- from_Muiayed/Start1.java
The Start1 class in Java is designed to evaluate whether two given arrays begin with the number 1. It contains a method called start1 that takes two integer arrays as input and returns a count of how many of them start with the value 1. The method first checks if each array is non-empty, then examines the first element of each. If the first element of array a is 1, it increments a counter; it does the same for array b. The final count is returned, indicating how many of the arrays meet the condition. This logic is demonstrated in the main method with sample inputs, showcasing how the method handles different scenarios, including empty arrays. It's a clear and practical example of conditional checks and array handling in Java.
> #TRA-3570: Array-1 > Start1 

- from_Muiayed/Has23.java
The Has23 class in Java provides a simple method to check whether a given two-element array contains the number 2 or 3. The method has23(int[] nums) uses logical OR conditions to evaluate both elements of the array and returns true if either matches the target values. In the main method, three test cases demonstrate its functionality: the array {2, 5} returns true because it contains 2; {4, 3} returns true because it contains 3; and {4, 5} returns false since neither value is present. This class is a great example of how to apply conditional checks and boolean logic to array elements, making it ideal for beginners learning how to write concise and effective decision-making code.
> #TRA-3565: Array-1 > Has23 

- from_Muiayed/Front11.java
The Front11 class in Java is a smart example of conditional array construction based on input availability. The method front11(int[] a, int[] b) checks whether each of the two input arrays has at least one element. If so, it creates a new array containing the first element from each non-empty array. The logic uses ternary operators to determine the length of the result array and conditionally assigns values. For instance, if both arrays are non-empty, the result will contain two elements—a[0] and b[0]. If only one is non-empty, the result will contain just that one element. This method is a great exercise in defensive programming and dynamic array handling, ensuring flexibility and correctness regardless of input size.
> #TRA-3581: Array-1 > Front11 

- from_Muiayed/MaxEnd3.java
The MaxEnd3 class in Java showcases a simple yet clever way to fill an array with repeated values based on a comparison. The method maxEnd3(int[] nums) takes an array of three integers and determines the larger value between the first and last elements (nums[0] and nums[2]). It then returns a new array where all three positions are filled with that maximum value. In the main method, the array {1, 2, 3} is passed in, and since 3 is greater than 1, the output becomes 3 3 3. This example is useful for practicing conditional logic, array construction, and method design. It’s a neat way to reinforce how to manipulate arrays based on dynamic values.
> #TRA3560: Array-1 > MaxEnd3 

- from_Muiayed/Reverse3.java
The Reverse3 class in Java is a straightforward example of array manipulation, specifically reversing the order of elements. It defines a method Reverse3(int[] nums) that takes an array of three integers and returns a new array with the elements in reverse order. In the main method, an instance of the class is created, and the method is called with the array {1, 2, 3}. The output is then printed as 3 2 1, demonstrating that the original array has been successfully reversed. This kind of method is useful for practicing array indexing and understanding how to construct new arrays from existing data. It's a clean and effective way to reinforce basic programming concepts like method calls, array access, and output formatting.
> #TRA-3559: Array-1 > Reverse3 

- from_Muiayed/MaxEnd3.java
- from_Muiayed/RotateLeft3.java
The `RotateLeft3` class in Java demonstrates a simple yet effective way to rotate the elements of a three-element array to the left. The method `rotateLeft3(int[] nums)` takes an array of three integers and returns a new array where the first element moves to the end, and the second and third elements shift one position to the left. In the `main` method, the array `{1, 2, 3}` is passed to the method, and the output is printed as `2 3 1`, confirming the rotation. This kind of operation is common in algorithmic challenges and helps reinforce understanding of array indexing, element reordering, and method return values. It's a clean example of how to manipulate fixed-size arrays for specific transformations.
> #TRA-3558: Array-1 > RotateLeft3 

- from_Muiayed/No23.java
The `No23` class in Java defines a method that checks whether the numbers `2` or `3` are absent from a given integer array of length two. The method `No23` returns `true` only if neither of the two elements in the array is equal to `2` or `3`. It performs this check using a compound conditional statement that compares both elements individually. This kind of logic is useful for filtering out unwanted values or validating input against specific constraints. For example, the array `{4, 5}` returns `true` because it contains neither `2` nor `3`, while `{4, 2}` and `{3, 5}` both return `false` due to the presence of one of the restricted values. The method is concise and demonstrates effective use of logical operators for array validation.
> #TRA-3566: Array-1 > No23 

- from_Muiayed/FirstLast6.java
The `FirstLast6` class in Java defines a method that checks whether the number `6` appears at either the beginning or the end of an integer array. This is done by directly comparing the first element (`nums[0]`) and the last element (`nums[nums.length - 1]`) to `6`. If either matches, the method returns `true`; otherwise, it returns `false`. This kind of check is useful in scenarios where specific boundary values carry meaning—such as validating input formats, detecting markers, or applying conditional logic based on array endpoints. For instance, the array `{1, 2, 6}` returns `true` because the last element is `6`, while `{13, 6, 1}` returns `false` since neither the first nor last element is `6`. The method is concise, efficient, and a great example of basic array inspection.
> #TRA-3553: Array-1: FirstLast6 

- From_Maha/ArrayTransformer.java
This method replaces each number in the array with the most recent multiple of 10 that appears earlier.
Numbers before the first multiple of 10 remain unchanged. ✅
> Add array2 tenRun file

- from_Muiayed/lastTwo.java
The `lastTwo` class in Java defines a method that swaps the last two characters of a given string. If the string has fewer than two characters, it returns the string unchanged. This is achieved by slicing the string up to the second-to-last character, then appending the last character followed by the second-to-last character. For example, `"coding"` becomes `"codign"`, `"cat"` becomes `"cta"`, and `"ab"` becomes `"ba"`. This method is a concise demonstration of string manipulation using indexing and substring operations, and can be useful in formatting tasks, playful text transformations, or basic algorithm exercises.
> #TRA-3543: String -1  > lastTwo 

- from_Muiayed/MakeTags.java
The `MakeTags` class in Java defines a method called `makeTags` that dynamically wraps a given word with HTML-style tags. The method takes two parameters: a `tag` and a `word`, and returns a string formatted as `<tag>word</tag>`. This is particularly useful for generating HTML content or simulating markup behavior in text-based applications. In the `main` method, the class demonstrates its functionality by wrapping the word `"Yay"` with different tags—`<i>` for italic and `<cite>` for citation—producing outputs like `<i>Yay</i>` and `<cite>Yay</cite>`. The implementation is concise and effective, showcasing basic string concatenation and object-oriented principles in Java.
> #TRA-3520: String-1 > MakeTags 

- from_Muiayed/StringYeak.java
The `StringYeak` class defines a method called `stringYak` that removes all occurrences of the pattern `"yak"` from a given string. It does this by iterating through each character and checking whether a substring starting at the current index matches the pattern: specifically, it looks for a `'y'` followed by any character and then a `'k'`. If such a pattern is found, the loop skips over those three characters by incrementing the index accordingly. Otherwise, the current character is added to the result string. This approach allows the method to efficiently strip out all `"yak"` sequences without using complex regular expressions, making it a practical example of pattern-based string filtering.
> #TRA-3506: Warmpup-2 > StringYeak 

- from_Muiayed/NoTriples.java
The `NoTriples` class defines a method that checks whether an array of integers contains any "triples"—three consecutive elements with the same value. It loops through the array up to the third-to-last element to avoid out-of-bounds errors, and at each step, it compares the current element with the next two. If all three are equal, the method immediately returns `false`, indicating that a triple was found. If the loop completes without finding such a sequence, it returns `true`, confirming that the array is free of triples. This method is useful for validating data sequences where repetition beyond a certain threshold is undesirable.
> #TRA-3516: Warmpup-2 > NoTriples 

- from_Muiayed/StringBits.java
The `StringBits` class defines a method that constructs a new string by extracting every other character from the original string, starting with the first. It does this by looping through the input string in steps of two and appending each character at even indices to a result string. For example, given the input `"Hello"`, the method would return `"Hlo"` by selecting characters at positions 0, 2, and 4. This approach is useful for simplifying or stylizing strings by reducing their character density while preserving a recognizable pattern.
> #TRA-3505: Warmup-2 > StringBits 

- from_Muiayed/StringMatch.java
The StringMatch class defines a method that compares two strings and counts how many matching two-character substrings they share at the same positions. It begins by determining the shorter length between the two strings to avoid index errors. Then, it iterates through both strings up to that length minus one, extracting two-character substrings from each at every index. If the substrings from both strings are equal at a given position, the method increments a counter. After completing the loop, it returns the total count of matching substrings. This approach is useful for analyzing similarity between strings in terms of short, consecutive character sequences.
> #TRA-3511: Warmpup-2 > StringMatch 

- from_Muiayed/StringTimes.java
The StringTimes class defines a method that takes a string str and an integer n, and returns a new string consisting of str repeated n times. It initializes an empty string result, then uses a for loop to append str to result exactly n times. After the loop completes, the method returns the final concatenated string. This is a simple yet effective way to perform string repetition in Java
> #TRA-3501: Warmup-2 > StringTimes 

- from_Muiayed/HelloName.java
The `HelloName` class in Java defines a simple method called `helloName` that takes a string input representing a person's name and returns a personalized greeting in the format `"Hello [name]!"`. This is achieved through straightforward string concatenation. In the `main` method, the class is instantiated and the `helloName` method is called with sample names like `"Bob"` and `"Alice"`, resulting in output such as `"Hello Bob!"` and `"Hello Alice!"`. This class serves as a basic example of method creation, string manipulation, and object instantiation in Java, making it ideal for beginners learning how to interact with user input and produce dynamic text responses.
> #TRA-3518: String-1 > HelloName 

- from_Muiayed/StringE.java
The `StringE` class in Java contains a method named `stringE` that checks whether a given string contains between one and three occurrences of the lowercase letter `'e'`. It does this by initializing a counter and iterating through each character of the string using a `for` loop. Every time it encounters an `'e'`, it increments the counter. After the loop finishes, the method returns `true` if the count is at least one and no more than three, ensuring the string has a moderate number of `'e'` characters. This kind of logic is useful for validating input based on specific character frequency, such as in word games, filters, or text analysis tools.
> #TRA-3496: Warmup-1 > StringE 

- from_Muiayed/LoneTeen.java
The `LoneTeen` class in Java defines a method called `loneTeen` that evaluates whether exactly one of two given integers falls within the teenage range, specifically between 13 and 19 inclusive. It does this by first checking if each number individually qualifies as a "teen" using boolean expressions. The method then returns `true` only if one of the numbers is a teen and the other is not—achieved through a logical OR of two conditions: one where `a` is a teen and `b` is not, and the other where `b` is a teen and `a` is not. This ensures that the method captures the scenario where only one of the inputs meets the teen criteria, making it useful for filtering or validating age-related conditions in applications.
> #TRA-3488: Warmup-1 > LoneTeen 

- from_Muiayed/Front22.java
The `Front22` class defines a method called `front22` that creatively modifies a given string by adding its first two characters to both the beginning and end. It starts by setting a variable `take` to 2, representing the number of characters to extract from the front. If the string is shorter than two characters, it adjusts `take` to the string’s actual length to avoid errors. Using `substring(0, take)`, it captures the front portion and then constructs a new string by placing this segment before and after the original string. This method is a playful example of string manipulation, often used in coding challenges or text formatting tasks where symmetry or repetition is desired.
> #TRA-3483: Warmup-1 > Front22 

- from_Muiayed/FrontBack.java
The `FrontBack` class defines a method named `frontBack` that rearranges the characters of a given string. Specifically, it swaps the first and last characters while keeping the middle portion intact. If the string has one or zero characters, it returns the string as-is, since there's nothing to swap. For longer strings, it extracts the middle section using `substring(1, str.length()-1)`, then constructs a new string by placing the last character at the front, followed by the middle, and ending with the first character. This method is a simple yet effective example of string manipulation, often useful in formatting tasks, playful text transformations, or coding exercises that build familiarity with Java’s string handling.
> #TRA-3479: Warmup-1 > FrontBack 

- from_Muiayed/EveryNth.java
The `EveryNth` class defines a method that constructs a new string by selecting every nth character from the original input string. The method `everyNth` takes two parameters: a string `str` and an integer `n`, which determines the step size for character selection. It initializes an empty result string and uses a `for` loop to iterate through the original string, starting from index 0 and incrementing by `n` on each pass. At each step, it appends the character at the current index to the result. This approach is useful for sampling or compressing strings, creating stylized text, or extracting patterns at regular intervals. The method showcases a clean and efficient use of loop control and string manipulation in Java.
> #TRA3500: Warmup-1 > EveryNth 

- from_Muiayed/Diff21.java
The `Diff21` class defines a method that calculates the absolute difference between a given integer `n` and the number 21, with a twist. If `n` is less than or equal to 21, the method simply returns the difference `21 - n`. However, if `n` is greater than 21, it returns double the difference—`(n - 21) * 2`. This logic is useful for scenarios where exceeding a threshold incurs a penalty or amplified response. The method is cleanly structured with an `if-else` statement, making it easy to read and understand. It’s a great example of conditional logic applied to numerical comparisons in Java.
> #TRA-3472: Warmup-1 > Diff21 

- from_Muiayed/NearHundred.java
The `NearHundred` class defines a method that checks whether a given integer `n` is close to either 100 or 200. The method `nearHundred` uses the `Math.abs()` function to calculate the absolute difference between `n` and the target values—100 and 200—and returns `true` if that difference is 10 or less for either target. This compact and efficient logic allows for a clear evaluation of proximity, making it useful in scenarios where values near a benchmark need to be flagged. The use of logical OR (`||`) ensures that the condition passes if `n` is near either number, not necessarily both. It's a great example of clean, readable code that leverages built-in math functions for practical decision-making.
> #TRA-3475: Warmup-1 > NearHundred 

- from_Muiayed/MonkeyTrouble.java
The `MonkeyTrouble` class contains a method that determines whether two monkeys are causing trouble based on their facial expressions. The `monkeyTrouble` method takes two boolean parameters—`aSmile` and `bSmile`—which represent whether each monkey is smiling. Trouble occurs when both monkeys are smiling or when neither is smiling. In these cases, the method returns `true`. If only one monkey is smiling, the method returns `false`, indicating no trouble. This logic is implemented using straightforward conditional checks, but it can be simplified to a single line: `return aSmile == bSmile;`, since trouble arises when both expressions match. The method is a great example of how boolean logic can be used to model real-world scenarios in a clean and readable way.
> #TRA-3470: Warmup-1 > MonkeyTrouble 

- from_Muiayed/SleepInChecker.java
The `sleepIn` method in the `SleepInChecker` class determines whether a person can sleep in based on two conditions: whether it is a weekday and whether they are on vacation. The method returns `true` if it is not a weekday or if the person is on vacation—meaning either condition allows for sleeping in. Otherwise, it returns `false`. This logic uses a simple boolean expression with the logical OR operator to evaluate the conditions efficiently. The method demonstrates clean and readable code, with a preference for direct boolean checks like `!weekday` and `vacation` instead of more verbose comparisons. It's a practical example of decision-making using boolean logic in Java.
> #TRA-3469: Warmup-1 > sleepIn 

- from_Muiayed/CloseToTen.java
The `close10` method in the `CloseToTen` class is designed to determine which of two integers is numerically closer to the value 10. It calculates the absolute difference between each number and 10 using `Math.abs`, storing the results in `aDiff` and `bDiff`. The method then compares these differences: if `a` is closer to 10, it returns `a`; if `b` is closer, it returns `b`. In the case where both numbers are equally close to 10, the method returns 0. This logic is useful for proximity-based comparisons and demonstrates a clear use of conditional statements and absolute value calculations in Java.
> #TRA-3493: Warmup-1 > Close10

- from_Muiayed/In3050.java
The `in3050` method in the `In3050` class is designed to evaluate whether two given integers fall within specific numeric ranges. It returns `true` if both integers are either within the range of 30 to 40 inclusive, or within the range of 40 to 50 inclusive. This is accomplished using conditional checks with logical `AND` operators to ensure both values meet the criteria for the same range. If neither condition is satisfied, the method returns `false`. This kind of logic is useful for validating grouped numeric inputs or enforcing range-based rules in applications.
> #TRA-3494: Warmup-1 > in3050 

- From_Maha/ArrayExtractor.java
This method returns a new array containing all elements that appear before the first 4 in the input array.
It stops at the first 4 and excludes it from the result.
> Add array2 pre4 file

- from_Muiayed/lastDigit.java
The `lastDigit` method is a simple yet effective way to compare the last digits of two integers. It works by using the modulo operator `%` to isolate the last digit of each number—specifically, `a % 10` and `b % 10`. If these values are equal, the method returns `true`; otherwise, it returns `false`. This logic is useful in scenarios where pattern recognition or digit-based validation is needed, such as checking for matching codes, verifying user input, or solving number puzzles. For example, if the input values are `27` and `57`, the method returns `true` because both numbers end in `7`. If the inputs are `123` and `45`, it returns `false` since `3` and `5` are different. The method demonstrates a clean and concise use of arithmetic operations and boolean logic in Java.
> #TRA-3498: Warmup-1 > lastDigit 

- from_Muiayed/StartOz.java
The `startOz` method is designed to extract specific characters from the beginning of a string based on simple conditions. It checks whether the first character is `'o'` and whether the second character is `'z'`, and includes them in the result string if they match. This approach allows the method to return a new string that may contain `'o'`, `'z'`, both, or neither, depending on the input. For example, if the input is `"ozone"`, the method returns `"oz"`; if the input is `"ocean"`, it returns `"o"`; and if the input is `"zebra"`, it returns an empty string. This kind of logic is useful for filtering or tagging strings based on specific character patterns, and it demonstrates a clear and concise use of conditional statements and string manipulation in Java.
> #TRA-3491: Warmup-1 > startOz 

- from_Muiayed/Array123.java
This Java class `Array123` includes a method named `array123` that checks for a specific pattern in an integer array.  
It looks for the sequence `1, 2, 3` appearing consecutively anywhere in the array.  
The method uses a loop to scan through the array, stopping two elements before the end to avoid errors.  
At each position, it checks if the current number is `1`, followed by `2`, then `3`.  
If the pattern is found, it returns `true` immediately.  
If the loop finishes without finding the sequence, it returns `false`.
> #TRA-3510: Warmup -2 > Array123 

- From_Mulk/WithoutTeen.java
This method removes all numbers from the list that fall within the teen range (13 through 19) and returns the updated list.
> Functional-2 > NoTeen task

- From_Maha/ArrayModifier.java
This method replaces any occurrence of val that is "not alone" (surrounded by different numbers) with the larger of its neighbors.
It leaves val unchanged if it is part of a sequence of identical values.
> Add array2 notAlone file

- from_shatha/LoneSum.java
Implement loneSum function to return the sum of unique values among three integers, ignoring duplicates.
> Logic2-lonesum task added

- from_shatha/LuckySum.java
Add luckySum function to compute sum of three integers, ignoring 13 and all values to its right.
> Logic2-luckySum task added

- from_shatha/NoTeenSum.java
Add noTeenSum function with fixTeen helper to sum three integers, treating teen values (13–19) as 0, except for 15 and 16
> noTeenSum task added

- from_shatha/RoundSum.java
Add roundSum function with round10 helper to sum three integers after rounding each to the nearest multiple of 10
> roundSum task added

- From_Mulk/WithoutTeen.java
Reverts daniyalmehmood/code_creators_git#4086
> Revert "Functional-2 > NoTeen task"

- from_shatha/BlackJack.java
Add blackjack function to return the value closest to 21 without going over; return 0 if both exceed 21
> blackJack task added

- from_Hawraa/NumberDoubler.java
I Added a doubleValues method that doubles each integer in the list using replaceAll with a lambda.
> TRA-4798: Functional-1: doubling added

- from_shatha/EvenlySpaced.java
Add evenlySpaced function to check if three integers are evenly spaced regardless of order
> evenlySpaced task added

- from_shatha/MakeChocolate.java
Add makeChocolate function to calculate number of small bars needed to reach goal weight, using big bars first; return -1 if not possible
> makeChocolate task added

- From_Shaima/DoubleAndFilter.java
The code returns a new list where each number is multiplied by 2. Omit any resulting numbers that end with the digit 2.
> TRA4853 : two2--Double Values (Excluding Results Ending with 2)

- from_hanin/StringYDecorator.java
- from_hanin/TripleRepeater.java
This method takes a list of strings as input and adds the letter "y" to both the beginning and end of each string. It uses the `replaceAll` method with a lambda expression to modify each string accordingly.
> Tra- 4792: Functional-1 > moreY

- from_hanin/AddOneMultiplyTen.java
- from_hanin/TripleRepeater.java
This method takes a list of integers as input and applies a mathematical operation to each number: It adds 1 to each number, then multiplies the result by 10.It uses the `replaceAll` method with a lambda expression to perform this transformation.
> Tra 4793:Functional-1 > math1

- from_hanin/DigitProcessor.java
This method takes a list of integers as input and replaces each number with its rightmost digit. It uses the modulo operator (% 10) to extract the last digit of each number. For example, 123 becomes 3, and 85 becomes 5.The `replaceAll` method with a lambda expression is used to perform this transformation. The modified list is then returned.
> Tra 4794: Functional-1 > rightDigit

- from_hanin/StringLowerer.java
- from_hanin/TripleRepeater.java
This method takes a list of strings as input and converts each string to lowercase. It uses the `replaceAll` method with a lambda expression that calls `toLowerCase()` on each string.For example, "HELLO" becomes "hello", and "Java" becomes "java".The modified list is then returned.
> Tra 4795:Functional-1 > lower

- from_hanin/CharFilterList.java
- from_hanin/TripleRepeater.java
This method takes a list of strings as input and removes all lowercase 'x' characters from each string. It uses the `replaceAll` method with a lambda expression that calls `replace("x", "")` on each string to eliminate all occurrences of 'x'.For example, "xax" becomes "a", and "xXx" becomes "X" (since only lowercase 'x' is removed).The modified list is then returned.
> Tra 4796: Functional-1 > noX

- from_hanin/ListCleaner.java
- from_hanin/TripleRepeater.java
This method takes a list of integers as input and removes all negative numbers from the list.It uses the `removeIf` method with a lambda expression that checks if a number is less than 0.For example, [-3, 5, -1, 7] becomes [5, 7].The modified list (with only non-negative numbers) is then returned.
> TRA- 4797: Functional-2 > noNeg

- from_hanin/NoNineFilter.java
- from_hanin/TripleRepeater.java
This method takes a list of integers as input and removes all numbers that end with the digit 9. It uses the `removeIf` method with a lambda expression that checks if the last digit (s % 10) equals 9. For example, [19, 29, 30, 42] becomes [30, 42]. The modified list is then returned.
> TRA- 4799: Functional-2 > no9

- From_Shaima/NumberTransformer.java
The code returns a new list where each number is squared and then 10 is added to the result. Omit any resulting numbers that end with the digits 5 or 6.
> TRA4849: square56--Square and Add Ten (Excluding Results Ending with 5 or 6)

- From_Shaima/AddYAndFilter.java
The code returns a new list where each string has "y" appended to its end. However, omit any resulting string that contains "yy" as a substring anywhere.
> TRA4847: noYY--Append -y- Excluding Double -yy-

- from_hanin/TextFilterList.java
- from_hanin/TripleRepeater.java
This method takes a list of strings as input and removes all strings that contain the letter 'z'. It uses the `removeIf` method with a lambda expression that checks if each string contains "z".For example, ["apple", "zebra", "jazz"] becomes ["apple"] because "zebra" and "jazz" contain 'z'.The modified list is then returned.
> Tra 4804: Functional-2 > noZ

- from_hanin/ShortStringFilter.java
- from_hanin/TripleRepeater.java
This method takes a list of strings as input and removes all strings that have a length of 4 or more characters.It uses the `removeIf` method with a lambda expression that checks the length of each string. For example, ["cat", "lion", "dog", "wolf"] becomes ["cat", "dog"] because "lion" and "wolf" have lengths >= 4.The modified list is then returned.
> TRA-4807:Functional-2 > noLong

- from_hanin/TripleRepeater.java
- from_hanin/YAppenderFilter.java
This method takes a list of strings as input and performs two operations:
1. It first appends the letter "y" to the end of each string using `replaceAll`.
2. Then, it removes any resulting strings that contain "yy" (i.e., two consecutive 'y' characters).
For example, ["a", "y", "hey"] becomes ["ay", "heyy"] → then "heyy" is removed → final result: ["ay"].
The modified list is then returned.
> Tra 4812:Functional-2 > noYY

- from_hanin/DoubleFilterList.java
- from_hanin/TripleRepeater.java
This method takes a list of integers and performs two operations:
1. It first doubles each number in the list using `replaceAll(n -> n * 2)`.
2. Then, it removes any numbers that end with the digit 2 (i.e., numbers where n % 10 == 2).
For example, [1, 2, 3, 6] → doubled to [2, 4, 6, 12] → remove numbers ending in 2 → result: [4, 6]
The modified list is then returned.
> Tra 4815:Functional-2 > two2

- From_Shaima/StringLengthFilter.java
The code returns a new list that excludes any strings with a length of 3 or 4 characters. All other strings should remain in the result.
> TRA4844: no34--Remove Strings of Length Three or Four

- From_Shaima/RemoveLongStrings.java
The code returns a new list that omits any string with a length of 4 or more characters. Only strings shorter than 4 characters should be included in the result.
> TRA4843: noLong--Remove Strings of Length Four or More

- from_Hawraa/StringModifier.java
I added an addStarToAllStrings method to append an asterisk (*) to the end of every string in the list using a lambda with replaceAll.
> TRA-4802: Functional-1: addStar added

- From_Manal/FirstSwapByFirstChar.java
Adds the firstSwap method to solve the CodingBat Map-2 challenge. The method processes an array of non-empty strings, swapping pairs that share the same first character—only once per character. A Map<Character, Integer> tracks the index of the first occurrence of each character. Once a swap is triggered, that character is marked as "used" to prevent further swaps. The solution completes in a single pass using efficient map-based tracking.
> TRA-4832: Map-2/FirstSwap

- From_Manal/CreateWordMapWithZero.java
Adds the word0 method to solve the CodingBat Map-2 problem. Given an array of strings, the method returns a Map<String, Integer> where each unique string becomes a key mapped to 0. This sets up a foundation for future counting logic, using a single-pass insertion into a HashMap.
> TRA-4824-Map-2: word0

- from_Muiyaed/StringX.java
This Java class `StringX` contains a method called `stringX` that processes a given string.  
It removes all occurrences of the character `'x'` from the middle of the string,  
but keeps any `'x'` characters that appear at the beginning or end.  
The method loops through each character in the input string using a `for` loop.  
It checks if the current character is `'x'` and if it's not the first or last character.  
If the character is not a middle `'x'`, it adds it to the result string.  
Finally, it returns the modified string with middle `'x'` characters removed.
> #TRA-3512: Warmup-2 > StringX 

- from_Hawraa/StringRepeater.java
I Added a method tripleEachString that modifies a list of strings by repeating each element three times.
> TRA-4805: Functional-1: copies3 added

- from_Muiayed/In1020.java
This Java class Last2 defines a method that counts how many times the last two characters of a given string appear earlier in the string.
The method last2 first checks if the string has fewer than two characters—if so, it returns 0 since no comparison is possible.
It then extracts the last two characters and stores them in a variable called end.
Using a loop, it scans through the string from the beginning up to two characters before the end.
At each step, it compares the current two-character substring with end.
If a match is found, it increments a counter.
Finally, the method returns the total number of matches found before the last occurrence.
> #TRA-3486: Warmup-2 > Last2 

- From_Manal/CountWordFrequency.java
Adds the wordCount method to solve the classic frequency-count problem from CodingBat Map-2. Given an array of strings, the method returns a Map<String, Integer> where each key is a unique string and its value is the number of times it appears in the array. Uses HashMap.merge() for concise accumulation.
> TRA-4825-Map-2: wordCount

- From_Manal/CheckWordMultiple.java
Adds the wordMultiple method to solve the CodingBat Map-2 problem. Given an array of strings, the method returns a Map<String, Boolean> where each key is a unique string and its value is true if the string appears two or more times, otherwise false. Uses a frequency map followed by a transformation pass to set boolean flags.
> TRA-4826-Map-2: wordMultiple

- From_Shaima/RemoveStringsWithZ.java
The code returns a new list that excludes any string containing the character "z".
> TRA4840: noZ--Remove Strings Containing -z-

- From_Manal/GroupWordsByFirstChar.java
Adds the firstChar method to solve the CodingBat Map-2 problem. Given an array of non-empty strings, the method returns a Map<String, String> where each key is the first character of a string, and its value is the concatenation of all strings starting with that character, in input order. This approach uses a single-pass accumulation via HashMap.
> TRA-4828-Map-2: firstChar

- From_Manal/MapFirstToLastChar.java
Adds the pairs method to solve the CodingBat Map-2 problem. Given an array of non-empty strings, the method returns a Map<String, String> where each key is the first character of a string and the value is the last character of the most recent string seen with that first character. Later strings overwrite earlier ones with the same starting character.
> TRA-4830-Map-2: pairs

- From_Shaima/RemoveNumbersEndingWithNine.java
The code returns a new list with all numbers that do not end with the digit 9.
> TRA4836: no9--Exclude Numbers Ending in 9

- From_Shaima/NonNegativeFilter.java
The code returns a new list containing only the non-negative values.
> TRA4833: noNeg--Remove Negative Numbers

- from_Hawraa/YStringFormatter.java
I added a new method addYAroundStrings that updates each string in a list by surrounding it with the character 'y'.
> TRA-4806: Functional-1: moreY added

- from_Hawraa/RightDigitExtractor.java
I added getRightDigitOfEach method, that updates each integer in a list by replacing it with its rightmost digit.
> TRA-4811: Functional-1: rightDigit added

- from_Hawraa/LowercaseConverter.java
I implemented the convertAllToLowercase method that transforms every string in a given list to its lowercase form.
> TRA-4814: Functional-1: lower added

- from_Hawraa/XRemover.java
I added removeAllX method that removes every 'x' character from each string in the input list.
> TRA-4816: Functional-1: noX added

- from_Muiayed/Double23.java
- from_Muiayed/MakeChocolate.java
The `makeChocolate` method is designed to determine how many small chocolate bars (weighing 1 kilogram each) are needed to reach a specific goal weight, given a supply of both small and big bars (with big bars weighing 5 kilograms each). The logic prioritizes using big bars first, without exceeding the target weight. It calculates the maximum number of big bars that can be used and then subtracts their total weight from the goal to find the remaining weight. If the remaining weight can be covered by the available small bars, it returns that number; otherwise, it returns -1 to indicate that the goal cannot be met with the given resources. This approach ensures efficient use of larger bars while verifying that the smaller ones can fill in the gap.
> #TRA-3714: Logic -2 > MakeChocolate

- from_Muiayed/Factorial.java
This Java program defines a class called `Factorial` that calculates the factorial of a given number using recursion. The `main` method calls the `factorial` function with inputs 1, 2, and 3, and prints the results. The `factorial` method itself is a classic example of recursion: it multiplies the current number `n` by the factorial of `n - 1`, continuing until it reaches the base case where `n` equals 1. At that point, it returns 1 and the recursive calls begin to resolve, producing the final result. For example, `factorial(3)` computes as `3 * factorial(2)`, which becomes `3 * 2 * factorial(1)`, and finally `3 * 2 * 1 = 6`. This approach is elegant and concise, though for larger inputs, an iterative version or memoization might be more efficient to avoid stack overflow or redundant …
> #TRA-4867: Recursion-1 > facturial

- from_Muiayed/Fibonacci.java
This Java program defines a class called `Fibonacci` that calculates values in the Fibonacci sequence using recursion. The sequence begins with 0 and 1, and each subsequent number is the sum of the two preceding ones. The `fibonacci` method handles two base cases—returning 0 when `n` is 0 and 1 when `n` is 1. For all other values, it recursively calls itself with `n - 1` and `n - 2`, summing the results to produce the Fibonacci number at position `n`. While this approach is conceptually simple and mirrors the mathematical definition of the sequence, it becomes inefficient for larger values due to repeated calculations. The program’s `main` method demonstrates the function by printing the Fibonacci numbers for inputs 0, 1, 2, and 6, resulting in outputs of 0, 1, 1, and 8 respectively.
> #TRA-4869: Recursion-1 > fibonacci

- from_Muiayed/Triangle.java
This Java program defines a class called Triangle that calculates the total number of blocks in a triangle made of rows, where each row contains a number of blocks equal to its row number. The method triangle uses recursion to compute the sum of blocks from the top row down to the bottom. If the number of rows is zero, it returns 0 as the base case. Otherwise, it adds the current row number to the result of a recursive call with one fewer row. For example, triangle(4) computes as 4 + triangle(3), which becomes 4 + 3 + 2 + 1 + 0 = 10. This approach mirrors the mathematical formula for the sum of the first n natural numbers and effectively demonstrates how recursion can be used to solve cumulative problems in a clear and elegant way.
> #TRA-4871: Recursion-1 > Traingle

- from_Huria/CountEvenIntegers.java
The code returns the number of even integers in the given array.
An integer is even if it is divisible by 2 (i.e., num % 2 == 0).
> TRA4834: Adding countEvens Task

- from_Hawraa/ListFilter.java
I implemented removeNegatives method that removes all negative integers from a given list.
> TRA-4897: Functional-2: noNeg added

- from_Huria/CalculateRangeDifference.java
The code returns the difference between the largest and smallest integers in the given array
> TRA4835: Adding bigDiff Task

- from_Hawraa/TeenRemover.java
I implemented removeTeenValues that removes all "teen" values (13-19) from a given list of integers.
> TRA-4899: Functional-2: noTeen added

- from_Muiayed/Count8.java
This Java program defines a class `Count8` that recursively counts how many times the digit `8` appears in a given integer, with a twist: if an `8` is immediately followed by another `8`, it counts double. The method `count8` checks the last digit using `n % 10`. If it’s `8`, it then checks whether the digit before it (i.e., `(n / 10) % 10`) is also `8`. If so, it adds 2 to the count; otherwise, it adds 1. The recursion continues by stripping off the last digit (`n / 10`) until the base case `n == 0` is reached. For example, `count8(8818)` returns `4` because the first two 8s count as 2 + 1, and the last 8 adds another 1. This clever use of recursion and digit comparison makes the program a great example of how logic can be layered to handle special cases in digit-based problems.
> #TRA-4874: Recursion-1 > count8

- from_Hawraa/LongWordRemover.java
I implemented removeLongStrings(), that removes all strings with a length of 4 or more characters from a given list.
> TRA-4901: Functional-2: noLong added

- from_Hawraa/LengthFilter.java
I implemented a method called removeThreeFourLength that removes any string length 3 or 4.
> TRA-4902: Functional-2: no34 added

- from_shatha/CharacterDoubler.java
Implement doubleChar to duplicate each character in a string
> #tra 4865 double char

- from_Hawraa/FilterAfterMultiply.java
I implemented a method called doubleAndFilterTwoEnd that doubles each number in a list and then removes any numbers that end with the digit 2.
> TRA-4904: Functional-2: two2 added

- from_shatha/CatDogChecker.java
Implement catDog function to check if "cat" and "dog" appear equally often in a string`
> catDog task added

- from_Hawraa/SquarePlusFilter.java
I implemented squareAddTenFilterEnds that squares each number in a list, adds 10 to the result, and then removes any numbers ending with the digits 5 or 6.
> TRA-4905: Functional-2: square56 added

- from_hanin/ScoreChecker.java
- from_hanin/TripleRepeater.java
The `scoresIncreasing` method returns `true` if the array is in non-decreasing order; it checks that each number is greater than or equal to the one before it. If any number is smaller, it returns `false`.
> Tra 4906: AP-1 > scoresIncreasing

- from_hanin/HighScoreChecker.java
The `scores100` method returns `true` if the array contains **two consecutive 100s**; otherwise, it returns `false`. It checks each pair of adjacent elements, and if both are 100, it returns `true`.
> TRA-4907:AP-1 > scores100

- from_hanin/ScoreClumpChecker.java
The `scoresClump` method returns `true` if there is any group of **three adjacent scores** in the array where the **difference between the highest and lowest** is **2 or less**. It checks each middle element and compares the values before and after it to detect such a “clump.”
> TRA-4908: AP-1 > scoresClump

- from_hanin/StringLengthCounter.java
The `wordsCount` method returns the number of strings in the array `words` that have a length equal to the given value `len`. It loops through the array and counts how many words match the specified length.
> TRA-4010: AP-1 > wordsCount

- from_Huria/ContainsNoOnesOrThrees.java
The code returns true if the array contains no 1’s and no 3’s. Otherwise, return false.
> TRA4842 : Adding lucky13 Task

- from_hanin/FilteredWordList.java
The `wordsWithoutList` method creates and returns a list containing all strings from the input array `words` except those whose length matches the given `len`. It iterates through the array, adds only the strings with lengths different from `len` to the list, and returns that list.
> TRA-4912: AP-1 > wordsWithoutList

- from_hanin/NumberDigitAnalyzer.java
The `hasOne` method checks if the integer `n` contains the digit `1`. It converts the number to a string and returns `true` if the string contains `"1"`, otherwise returns `false`.
> TRA-4913: AP-1 > hasOne

- From_Shaima/SumOfTwosChecker.java
The code returns true if the sum of all the 2’s in the array is exactly 8. Otherwise, return false.
> TRA4767: sum28 -- ➕ Check If Sum of All 2s Equals 8

- from_hanin/DivisibilityChecker.java
The `dividesSelf` method checks if every digit in the positive integer `n` divides `n` evenly. It returns `false` if the number contains a `0` digit or if any digit does not evenly divide `n`. Otherwise, it returns `true`.
> TRA-4914: AP-1 > dividesSelf

- from_hanin/EvenNumberCollector.java
The `copyEvens` method returns a new array containing the first `count` even numbers found in the input array `nums`. It scans through `nums` and copies even numbers into the result until it reaches the desired count.
> TRA-4915:AP-1 > copyEvens

- from_shatha/StringComparer.java
Implement endOther to check if one string ends with the other, case-insensitive
> #tra 4929 end other

- from_hanin/NumberRangeSelector.java
The `copyEndy` method returns a new array containing the first `count` numbers from `nums` that are "endy"—meaning they fall within 0 to 10 or 90 to 100. It uses the helper method `isEndy` to check if a number qualifies, copying those that do until the count is reached.
> TRA-4916: AP-1 > copyEndy

- from_hanin/StringArrayComparator.java
The `matchUp` method counts how many times the strings at the same index in arrays `a` and `b` both start with the same non-empty first character. It returns the total count of such matches.
> TRA-4917: AP-1 > matchUp

- from_shatha/XYZThere.java
Add xyzThere function to detect "xyz" not preceded by a period
> #tra 4930 xyz there

- from_hanin/ExamScorer.java
The `scoreUp` method calculates a test score by comparing the student's `answers` to the correct `key`. It adds 4 points for each correct answer, subtracts 1 for each incorrect answer, and gives 0 points for unanswered questions marked with `"?"`.
> TRA-4918:AP-1 > scoreUp

- from_hanin/StringArrayFilter.java
The `wordsWithout` method returns a new array containing all strings from the input `words` except those equal to the `target` string. It first collects the non-target words in a list, then converts that list back to an array.
> TRA-4919:AP-1 > wordsWithout

- from_Huria/BuildIntegerSequence.java
The code returns a new integer array of length n. The array should contain numbers from 0 up to n-1. If n is 0, return an empty array.
> TRA4848 :Adding fizzArray Task

- from_hanin/TrailHeightCalculator.java
The `sumHeights` method calculates the total change in height between the `start` and `end` indexes in the `heights` array by summing the absolute differences between consecutive heights along the path.
> TRA-4921:AP-1 > sumHeights

- from_hanin/HeightChangeAnalyzer.java
The `sumHeights2` method calculates the total height change between `start` and `end` in the `heights` array, but counts uphill steps double while downhill steps count normally, summing these weighted differences along the path.
> TRA-4922: AP-1 > sumHeights2

- from_hanin/TrailStepAnalyzer.java
The `bigHeights` method counts how many "big" steps (height changes of 5 or more) occur between the `start` and `end` indexes in the `heights` array.
> TRA-4923:AP-1 > bigHeights

- from_Huria/OneFourFilter.java
The code returns true if every element in the array is either a 1 or a 4. Otherwise, return false.
> TRA4850: Adding only14 Task

- from_hanin/UserComparator.java
The `userCompare` method compares two users by their names first (alphabetically), and if the names are the same, by their IDs (numerically). It returns -1 if user A comes before B, 1 if after, or 0 if they are equal.
> TRA-4924: AP-1 > userCompare

- from_shatha/StringCounter.java
Create countCode function to count "co*e" patterns with any letter in place of 'd'
> countCode task added

- from_Huria/GenerateNumberStrings.java
The code returns a new string array of length n. The array should contain strings representing numbers from "0" up to "n-1". If n is 0, return an empty array.
> TRA4852: Adding fizzArray2 Task

- from_hanin/CommonStringCounter.java
This method counts how many unique strings appear in both sorted arrays a and b. It uses two pointers to traverse both arrays efficiently, skipping duplicates by checking against the previous matched string. It increments the count only for new common strings.
> TRA-4926: AP-1 > commonTwo

- from_Muiayed/PowerN.java
This Java program demonstrates the concept of recursion by calculating powers of a number using the `powerN` method. The method takes two parameters—`base` and `n`—and recursively multiplies the base by itself `n` times. The base case ensures that when `n` equals 1, the recursion stops and returns the base value. For example, calling `powerN(3, 3)` results in `3 * 3 * 3`, which equals 27. This approach mirrors the mathematical definition of exponentiation and provides a clear, elegant way to understand recursive logic in Java. To make the method more complete, it could be enhanced to handle cases like `n = 0`, where the result should be 1, aligning with mathematical conventions.
> #TRA-4947: Recursion-1 > powerN

- from_Muiayed/CountX.java
This Java program uses recursion to count how many times the character `'x'` appears in a given string. The method `countX` checks the first character of the string: if it's `'x'`, it adds 1 to the count and recursively calls itself on the rest of the string. If it's not `'x'`, it simply continues the recursion without incrementing. The base case is when the string becomes empty—at that point, it returns 0 and the recursion unwinds. For example, `countX("xxhixx")` returns 4 because there are four `'x'` characters in the string. This approach is clean and expressive, showing how recursion can elegantly solve problems involving sequential character analysis.
> #TRA-4948: Recursion-1 > countX

- from_Huria/HasNoOneOrNoFour.java
The code returns true if the array contains no 1’s or no 4’s. Return false if the array contains at least one 1 and at least one 4.
> TRA4854: Adding no14 Task

- from_shatha/XyBalance.java
Add xyBalance function to verify every 'x' is followed by a 'y' later in the string
> xyBalance task added

- from_Muiayed/CountHi.java
This Java class `CountHi` demonstrates two distinct approaches—iterative and recursive—for counting how many times the substring `"hi"` appears in a given string. The iterative method uses a `for` loop to scan through the string and increment a counter whenever `"hi"` is found. It's straightforward and efficient, ideal for beginners or performance-sensitive scenarios. The recursive method, on the other hand, breaks the problem down by checking the first two characters of the string and then calling itself on the remaining substring. If `"hi"` is found, it skips two characters to avoid overlapping matches; otherwise, it moves one character forward. While both methods achieve the same goal, the recursive version offers a more elegant and expressive solution, especially useful for …
> #TRA-4949: Recursion-1 > countHi

- From_Maha/CustomArrayOperations.java
Added `without Ten` method to create a new array that removes all 10s while preserving the order of other numbers.  
Zeros fill the remaining positions; the original array remains unchanged.
>  Adding Array2 WITHOUT10 file

- from_shatha/StringMixer.java
Implement mixString to merge two strings by alternating characters
> mixString task added

- from_Huria/TwoOrFourTwins.java
The code returns true if the array contains a 2 next to a 2 or a 4 next to a 4, but not both.
Return false if the array contains neither or both patterns.
> TRA4856: Adding either24 Task

- from_shatha/StringRepeater.java
Add repeatEnd function to repeat the last n characters of a string n times
> repeatEnd task added

- from_shatha/RepeatFront.java
Implement repeatFront to build a string by repeating decreasing prefixes
> repeatFront task added

- from_shatha/RepeatSeparator.java
Create repeatSeparator to join multiple copies of a word separated by a given separator
> repeatSeparator task added

- from_shatha/StringSearcher.java
Implement prefixAgain to check if prefix of length N appears elsewhere in the string
> prefixAgain task added

- from_shatha/MiddleChecker.java
Add xyzMiddle function to check if "xyz" appears near the middle of the string
> xyzMiddle task added

- from_Muiayed/ChangePi.java
The `changePi` method in Java is a clever use of recursion to solve a string replacement problem. It scans through the input string and replaces every occurrence of the substring `"pi"` with `"3.14"`. The method works by checking the first two characters of the string: if they match `"pi"`, it appends `"3.14"` to the result and continues processing the rest of the string from the third character onward. If the match isn't found, it keeps the first character and recursively processes the remainder. This approach ensures that all instances of `"pi"` are replaced, regardless of their position in the string. The base case—when the string has fewer than two characters—prevents unnecessary checks and ends the recursion. Overall, this method demonstrates how recursion can be used effectively for …
>  #TRA-4952: Recursion-1 > changePi

- from_Muiayed/noX.java
The `NoX` class in Java demonstrates two distinct approaches to removing the character `'x'` from strings. The first method, `noX(String str)`, uses recursion to process each character in the input string. If the current character is `'x'`, it is skipped; otherwise, it is retained and concatenated with the result of the recursive call on the remaining substring. This method is elegant and showcases a clean recursive pattern for string manipulation. The second method, `noX(List<String> strings)`, operates on a list of strings using Java’s functional programming features. It applies a lambda expression to each element of the list, replacing all occurrences of `'x'` with an empty string. This approach is efficient and concise, leveraging the power of `replaceAll` for batch processing. …
> #TRA-4964: Recursion-1 > noX

- from_Muiayed/Array220.java
The `Array220` class in Java uses recursion to determine whether an array contains a value followed immediately by that value multiplied by 10. The method `array220` takes an array of integers and a starting index, then checks each pair of adjacent elements. If it finds a pair where the second element is exactly ten times the first, it returns `true`. Otherwise, it continues checking the next pair by incrementing the index. The recursion stops when the index reaches the second-to-last element, ensuring that there’s always a next element to compare. This approach is efficient and avoids loops, making it ideal for recursive practice problems. It highlights how recursion can be used not just for traversal, but also for evaluating relationships between elements in a sequence.
> #TRA-4967: Recursion-1 > array220

- from_Muiayed/AllStar.java
The `AllStar` class in Java showcases a recursive method for inserting asterisks (`*`) between every pair of adjacent characters in a string. The method `allStar` takes a string as input and checks its length. If the string has one or zero characters, it returns the string as-is—this serves as the base case for the recursion. Otherwise, it takes the first character, appends an asterisk, and then recursively calls itself on the remainder of the string. This process continues until the entire string has been traversed, resulting in a new string where each character is separated by a `*`. For example, `"hello"` becomes `"h*e*l*l*o"`, and `"abc"` becomes `"a*b*c"`. This method is a clean demonstration of how recursion can be used for character-level transformations in strings, especially …
>  #TRA-4968: Recursion-1 > allStar

- from_Muiayed/CountPairs.java
The `CountPairs` class in Java demonstrates a clever use of recursion to identify and count "pairs" within a string—defined as two identical characters separated by exactly one character. The method `countPairs` begins by checking if the string is too short to contain any pairs (less than three characters), in which case it returns zero. Otherwise, it compares the first and third characters. If they match, it counts one pair and recursively processes the rest of the string starting from the next character. If they don’t match, it simply continues the recursion without incrementing the count. This approach ensures that all overlapping and non-overlapping pairs are detected efficiently. For example, the string `"axa"` contains one pair (`'a'` and `'a'` with `'x'` in between), `"axax"` …
> #TRA-4971: Recursion-1 > countPairs

- from_Muiayed/CountAbc.java
The `countAbc` method in this Java program uses recursion to count how many times the substrings `"abc"` or `"aba"` appear in a given string. It works by checking the first three characters of the string. If they match either `"abc"` or `"aba"`, it increments the count by one and continues checking the rest of the string starting from the next character. If there's no match, it simply moves one character forward and continues the recursion. The base case ensures the recursion stops when fewer than three characters remain, since no valid match can occur. For example, `"abc"` returns 1, `"abcxxabc"` returns 2, and `"abaxxaba"` also returns 2. This approach is efficient and elegant, capturing overlapping patterns while keeping the code concise.
> #TRA-4972: Recursion-1 > countABC

- from_Muiayed/Count11.java
The `Count11` class in Java uses recursion to count how many times the substring `"11"` appears in a given string. The method `count11` checks the first two characters of the string. If they match `"11"`, it counts one occurrence and skips ahead by two characters to avoid overlapping matches. If the first two characters don’t match, it moves forward by one character and continues the recursion. The base case ensures the function stops when fewer than two characters remain, since `"11"` can't exist in such a short string. For example, `"11abc11"` returns 2, `"abc11x11x11"` returns 3, and `"111"` returns 1—because the second `"11"` overlaps with the first and is skipped. This method is efficient and precise, making it ideal for counting non-overlapping patterns in strings.
> #TRA-4973: Recursion -1> count11

- from_Muiayed/StrDist.java
The `StrDist` class uses a clever recursive approach to find the length of the largest substring in a given string that starts and ends with a specified substring. The method `strDist` works by trimming characters from the beginning or end of the string until it finds a segment that both starts and ends with the target substring. Once such a segment is found, its length is returned. If the string becomes shorter than the substring during this process, the method returns zero, indicating no valid match. This technique ensures that the widest possible match is captured, making it ideal for identifying the outermost boundaries of repeated patterns. The sample outputs confirm its effectiveness, especially in cases like `"cccatcowcatxx"`, where the method successfully isolates the longest …
> #TRA-4980: Recursion-1 > strDist

- from_Muiayed/GroupNoAdj.java
The `GroupNoAdj` class implements a recursive solution to a variation of the subset sum problem, where adjacent elements in the array cannot both be included in the selected subset. The method `groupNoAdj` explores two possibilities at each step: either include the current element and skip the next one (to avoid adjacency), or exclude the current element and move to the next. The recursion continues until all elements are considered, and the base case checks whether the target sum has been achieved. This approach is particularly useful for problems involving constraints on element selection, such as scheduling tasks with cooldowns or selecting non-conflicting items. It balances thorough exploration with rule enforcement, making it a smart and adaptable recursive pattern.
> #TRA-5004: Recursion -2 > groupSum5

- From_Maha/ArrayProcessor.java
Added replaceZerosWithMaxOdd method which scans the array from right to left, replaces each 0 with the largest odd number to its right, and keeps the rest unchanged.
> Adding zeroMax file

- From_Maha/NumberReorganizer.java
Implemented arrangeEvenBeforeOdd method, which places even numbers first (in original order), followed by odd numbers (in original order).
> Adding evenOdd file

- From_Mulk/RemoveThreeFour.java
This method removes all strings from the list that have a length of 3 or 4, then returns the updated list.
> Functional-2 > No34 task

- from_shatha/StarChecker.java
Add sameStarChar to check matching chars around '*'
> sameStarChar task added

- From_Mulk/AvoidYY.java
This method adds y to the end of each string in the list, removes any strings that contain yy, and returns the updated list.
> Functional-2 > NoYY task

- from_shatha/GroupTransformer.java
Add oneTwo to reorder each 3-char group as 2nd-3rd-1st
> oneTwo task added

- From_Mulk/NoEndingTwo.java
This method multiplies each number in the list by two, removes any numbers that end with the digit two, and returns the updated list.
> Functional-2 > Two2 task

- from_Kaltham/CloseTriplet.java
I created a class called CloseTriplet with a method named hasCloseTriplet that takes an array of integers called scores.
The method checks whether the array contains three numbers within a range of 2 from the first to the third element in the triplet.
How it works:
It loops through the array, checking every sequence of three consecutive elements.
For each triplet, it compares the first and the third elements.
If the difference between the third and the first element is less than or equal to 2, the method returns true.
If no such triplet is found, the method returns false.
This means the method returns true if there is at least one triplet of values close together, and false otherwise.
> TRA-4983: AP-1 >=The solution for scoresClump Task

- from_shatha/StringCleaner.java
Add starOut to remove stars and adjacent chars from string
> starOut task added

- from_Hawraa/FactorialCalculator.java
I implemented computeFactorialOfNumber that returns the factorial of n, which is n * (n-1) * (n-2) ... 1
> TRA-5022: Recursion-1: factorial added

- From_Mulk/SquareFilter.java
This method squares each number in the list, adds ten to each result, removes any numbers that end with five or six, and returns the updated list.
> Functional-2 > Square56 task

- from_shatha/WordEnds.java
Add wordEnds to collect chars before and after each word occurrence
> wordEnds task added

- From_Maha/ArraySpanCalculator.java
Implemented calculateMaxSpan method which determines the largest span in an integer array.
Rules for Max Span:
The span of a number is the distance between its first and last occurrence in the array (inclusive).
For each element, find the farthest matching element to the right and compute the span.
Return the maximum span found among all elements.
> Adding maxSpan file

- from_Kaltham/WordCounter.java
I created a class called WordCounter with a method named countWordsOfLength that takes an array of strings called words and an integer len.
The method counts how many words in the array have a length exactly equal to len.
How it works:
It initializes a counter sum to 0.
It loops through each word in the array.
If a word’s length equals len, it increments the counter.
After checking all words, it returns the counter sum.
This means the method returns the number of words in the array that have the specified length.
> TRA-4985: AP-1 >=The solution for wordsCount Task

- from_Kaltham/FrontWords.java
I created a class called FrontWords with a method named extractFrontWords that takes an array of strings called words and an integer n.
The method extracts the first n words from the array and returns them in a new array.
How it works:
It creates a new array of length n.
It copies the first n elements from the input array into the new array.
It returns the new array containing these words.
This means the method returns an array of the first n words from the original array.
> TRA-4986: AP-1 >=The solution for wordsFront Task

- From_Maha/ArrayBalanceChecker.java
Implemented isBalanced method which returns true if there is a place to split the array into two parts with equal sums.
The method calculates the total sum first, then iterates to check if the sum of the left part equals the sum of the right part.
> Adding canBalance file

- From_Maha/ArrayInclusionChecker.java
Implemented containsAll method which checks if all elements of innerArray exist in outerArray.
Returns true only if every element of innerArray is found in outerArray; otherwise returns false.
> Adding linearIn file 

- from_Hawraa/FibonacciNumberGenerator.java
I added getFibonacciNumber that returns the n Fibonacci number, handling base cases for 0 and 1, and using fibonacci(n - 1) + fibonacci(n - 2) for others.
> TRA-5024: Recursion-1: fibonacci added

- From_Maha/ArraySquareBuilder.java
Implemented buildSquarePattern method which fills an array of size n*n with a specific square pattern.
The pattern places numbers 1 through i at the end of each i-th row, creating a triangular sequence aligned to the right.
> Adding dequareUp file

- from_Kaltham/SelfDivider.java
I created a class called SelfDivider with a method named isDividesSelf that takes an integer n.
The method checks whether the number divides itself, meaning every digit of the number divides the number evenly.
How it works:
It examines each digit of the number using n % 10.
If a digit is 0 or does not divide the number evenly, it returns false.
Otherwise, it removes the last digit by dividing n by 10 and continues checking.
If all digits divide the number evenly, it returns true.
This means the method returns true if the number is a self-dividing number, and false otherwise.
> TRA-4989: AP-1 >=The solution for dividesSelf Task

- from_Kaltham/EvenCopier.java
I created a class called EvenCopier with a method named copyEvens that takes an array of integers called nums and an integer count.
The method returns a new array containing the first count even numbers from the input array.
How it works:
It creates a new array of length count.
It loops through the input array, checking each number.
If a number is even, it adds it to the new array and increments the index.
The process stops once count even numbers are copied or the input array ends.
This means the method returns an array of the first count even numbers from the original array.
> TRA-4990: AP-1 >=The solution for copyEvens Task

- from_Kaltham/EndyNumberExtractor.java
I created a class called EndyNumberExtractor with a method named getFirstNEndyNumbers that takes an array of integers called nums and an integer count.
The method returns a new array containing the first count numbers from the input that are considered “endy”.
How it works:
A number is endy if it is between 0 and 10, or between 90 and 100, as determined by the helper method isEndyNumber.
The method loops through the input array, checking each number with isEndyNumber.
If a number is endy, it is added to the new array until count endy numbers are collected or the array ends.
It then returns the new array.
This means the method extracts the first count endy numbers from the original array.
> TRA-4991: AP-1 >=The solution for copyEndy Task

- from_Hawraa/TriangleBlocksCalculator.java
I added getTotalTriangleBlocks that calculates the total number of blocks in a triangle by summing all rows from the given number down to one.
> TRA-5026: Recursion-1: triangle added

- from_Kaltham/FirstCharMatcher.java
I created a class called FirstCharMatcher with a method named countMatchingFirstChars that takes two arrays of strings, a and b.
The method counts how many corresponding strings in the two arrays start with the same character.
How it works:
It loops through each index of the arrays.
For each pair, it checks that both strings are non-empty and compares their first characters.
If the first characters match, it increments a counter.
After checking all pairs, it returns the total count of matches.
This means the method returns the number of positions where the strings in both arrays start with the same character.
> TRA-4992: AP-1 >=The solution for matchUp Task

- From_Maha/ArrayMirrorFinder.java
Implemented findMaxMirrorLength method which returns the length of the largest subarray that appears in reverse elsewhere in the array.
> Adding maxMirror file

- from_Kaltham/WordsWithoutTarget.java
I created a class called WordsWithoutTarget with a method named removeTargetWord that takes an array of strings words and a string target.
The method returns a new array with all occurrences of the target word removed.
How it works:
It first counts how many words are not equal to the target to determine the new array size.
Then it creates a new array and copies all words that are not the target into it.
Finally, it returns the new array without the target word.
This means the method removes all occurrences of the given target word from the original array.
> TRA-4994: AP-1 >=The solution for wordsWithout Task

- from_Kaltham/SpecialScoreCalculator.java
I created a class called SpecialScoreCalculator with a method named sumLargestSpecial that takes two arrays of integers, a and b.
The method calculates the sum of the largest “special” numbers from each array, where a number is considered special if it is a multiple of 10.
How it works:
It uses a helper method findLargestSpecial to find the largest number divisible by 10 in each array.
findLargestSpecial loops through the array, keeping track of the maximum number divisible by 10.
The main method adds the two largest special numbers from the arrays and returns the sum.
This means the method returns the sum of the largest multiples of 10 from both input arrays.
> TRA-4995: AP-1 >=The solution for scoresSpecial Task

- From_Mulk/TripleCheck.java
This method checks if there is any group of three continuous numbers in the array where the difference between the first and the third is at most two, and returns true if such a group exists, otherwise false.
> AP-1 > ScoresClump task

- from_Kaltham/HeightsCalculator.java
I created a class called HeightsCalculator with a method named sumHeightDifferences that takes an array of integers heights and two integers start and end.
The method calculates the sum of absolute differences between consecutive heights in the specified range.
How it works:
It loops from index start to end - 1.
For each pair of consecutive heights, it calculates the absolute difference and adds it to a running total.
After processing all pairs, it returns the total sum.
This means the method returns the total of all height differences between consecutive elements in the given range.
> TRA-4996: AP-1 >=The solution for sumHeights Task

- From_Manal/StringsWithZRemover.java
- From_Manal/ThreeTimesRepeater.java
Adds the method repeatThreeTimes(List<String> words) to perform a functional transformation on a list of strings. Each string is replaced by three concatenated copies of itself using List.replaceAll.
> TRA-5011: Functional-1/Copies3

- from_Hawraa/DigitSevenCounter.java
I added countDigitSeven(int n) that counts how many times the digit 7 appears in the integer n.
> TRA-5028: Recursion-1: count7 added

- from_Hawraa/CountEightsCalculator.java
I implemented countDigitEight(int n) to count the number of 8s in the integer n, and if two 8s appear next to each other, the second one counts double.
> TRA-5029: Recursion-1: count8 added

- from_Kaltham/UserNameIdComparator.java
I created a class called UserNameIdComparator with a method named compareByNameThenId that takes two users’ names and IDs: aName, aId and bName, bId.
The method compares the users first by name, and if the names are the same, then by ID.
How it works:
It uses compareTo to compare the two names.
If aName is lexicographically smaller than bName, it returns -1; if greater, 1.
If the names are equal, it compares the IDs: smaller ID returns -1, larger returns 1.
If both names and IDs are equal, it returns 0.
This means the method orders users primarily by name, and secondarily by ID.
> TRA-4999: AP-1 >=The solution for userCompare Task

- From_Mulk/ScoresAverage.java
This method calculates the average of the first half and the second half of the array separately, then returns the larger of the two averages.
> AP-1 > ScoresAverage task

- From_Mulk/WordsCounter.java
This method counts the number of strings in the array that have the specified length and returns that count.
> AP-1 > WordsCount task

- from_Hawraa/PowerCalculator.java
I added a recursive method computePower(int base, int n) that calculates base raised to the power of n.
> TRA-5030: Recursion-1: powerN added

- from_shatha/WordEndCounter.java
Add countYZ to count words ending with 'y' or 'z' (case-insensitive)
> countYZ task added

- from_shatha/StringRemover.java
Implement withoutString to remove all non-overlapping case-insensitive substrings
> withoutString task added

- from_shatha/StringBalanceChecker.java
Add equalIsNot to check equal counts of "is" and "not" substrings
> equalIsNot task added

- from_shatha/HappyGChecker.java
Add gHappy to verify all 'g's have adjacent 'g's
> gHappy task added

- from_shatha/TripleCounter.java
Implement countTriple to count chars appearing three times consecutively
> countTriple task added

- from_Huria/EveryTwoHasNeighborTwo.java
The code returns true if every 2 in the array is immediately next to another 2. Return false if any 2 is unpaired.
> TRA4860: Adding twoTwo Task

- from_shatha/StringEndMatcher.java
Implement sameEnds to find longest matching substring at start and end
> sameEnds task added

- From_Mulk/MissingWords.java
This method creates a list containing all the words from the array except those with the specified length and then returns that list.
> AP-1 > WordsWithoutList task

- from_Huria/BeginsAndEndsWithSameSequence.java
The code returns true if the first n numbers of an array are the same as the last n numbers.
> TRA4861 : Adding sameEnds Task

- from_shatha/MirrorSubstringFinder.java
Add mirrorEnds to find mirrored substring at start and end of string
> mirrorEnds task added

- from_Hawraa/HiStringCounter.java
I added countSubstringHi that returns the number of times lowercase "hi" appears in the string.
> TRA-5032: Recursion-1: countHi added

- From_Mulk/HasOne.java
This method checks if the given number contains the digit 1 and returns true if it does, otherwise false.
> AP-1 > HasOne task

- From_Manal/SquareValues.java
This Method return a list where each integer is multiplied by 2.
> TRA-5013-Functional-1: square

- from_Huria/ShiftLeftByOne.java
The code returns a new array (or modifies the given one) with all elements shifted one position to the left. The first element moves to the end of the array. Works for arrays of any length, including single-element arrays.
> TRA4955: Adding shiftLeft Task

- From_Manal/StarAtEndAdder.java
This Method returned a list where each string has "*" added at its end.
> TRA-5016-Functional-1: addStar

- from_Huria/TransformFollowingMultiplesOfTen.java
The code transforms an array so that after each multiple of 10, all subsequent elements are replaced with that multiple until another multiple of 10 appears. The first element and any non-following numbers remain unchanged.
> TRA5076: Adding tenRun Task

- From_Manal/OneAdderThenMultiplyByTen.java
This Method return a list where each integer is added to 1 and the result is multiplied by 10.
> TRA-5017-Functional-1: math1

- From_Mulk/SelfDivider.java
This method checks if a number n is "self-dividing" meaning every digit in the number divides the number evenly. It returns true if all non-zero digits divide the original number without a remainder; otherwise, it returns false.
> AP-1 > DividesSelf task

- from_Huria/ElementsBeforeFirstFour.java
The code returns a new array containing all elements that appear before the first 4 in the original array. Assumes the array contains at least one 4. If the first element is 4, the result will be an empty array.
> TRA5077: Adding pre4 Task

- From_Mulk/EvenExtractor.java
This method creates a new array containing the first count even numbers from the input array nums. It returns the new array once the desired number of even values is copied.
> AP-1 > CopyEvens task

- from_Huria/ContainsAdjacentOrSeparatedSevens.java
The code returns true if an array contains two 7s next to each other or two 7s separated by exactly one element. Otherwise, return false.
> TRA4857: Adding has77 Task

- From_Shaima/ArrayGenerator.java
The code returns a new integer array of length n. The array should contain numbers from 0 up to n-1.
> TRA4769: fizzArray -- 🔢 Create Array of Numbers 0 to n-1

- From_Mulk/EndyExtractor.java
This method builds a new array containing the first count "endy" numbers from the input array nums, where an "endy" number is in the range 0–10 or 90–100. It returns the new array once enough endy numbers are collected.
> AP-1 > CopyEndy task

- From_Shaima/OnesAndFoursChecker.java
The code returns true if every element in the array is either a 1 or a 4. Otherwise, return false.
> TRA4770: only14 -- 🔒 Check If Array Contains Only 1s and 4s

- From_Maha/MapValueMover.java
If the map has key "a", move its value to key "b" and set "a" to empty.
Returns the updated map.
> Adding mapBully file

- From_Maha/MapModifier.java
If the map has key "a", copy its value to "b". 
If the map has key "c", remove it. Returns the updated map.
> Adding mapShare file

- From_Mulk/WordMatchUp.java
This method compares two string arrays and counts how many times the corresponding strings in each array start with the same character (as long as both strings are non-empty). It returns that count.
> AP-1 > MatchUp task

- From_Shaima/EverywhereChecker.java
The code returns true if a given value is everywhere in an array. A value is considered everywhere if for every pair of adjacent elements, at least one of the pair is equal to that value.
> TRA4774: isEverywhere -- 🔎 Check If Value Is Everywhere in Array

- From_Shaima/AdjacentTwoOrFour.java
The code returns true if the array contains a 2 next to a 2 or a 4 next to a 4, but not both.
> TRA4776: either24 -- 🔢 Check for Either 2s or 4s Consecutive (But Not Both)

- from_Kaltham/SubsetSumChecker.java
I created a class called SubsetSumChecker with a method named canAchieveTarget that takes an integer start, an array of integers nums, and an integer target.
The method checks whether it is possible to select a subset of numbers from the array that sums exactly to the target.
How it works:
It uses recursion starting from index start.
At each step, it tries including the current number in the sum or excluding it.
If the end of the array is reached, it returns true only if the remaining target is 0.
If any recursive path reaches the target, it returns true; otherwise, it returns false.
This means the method determines whether a subset of the array can sum to the given target.
> TRA-5099: AP-1 >=The solution for groupSum Task

- From_Mulk/ScoreCalculator.java
This method calculates a quiz score by comparing the answers array to the key. It awards 4 points for each correct answer, subtracts 1 point for each wrong answer (excluding "?"), and gives 0 points for unanswered questions (marked as "?"). It returns the final score.
> AP-1 > ScoreUp task

- From_Mulk/WordRemover.java
This method returns a new array containing all the strings from the input array words, except for those that match the target string. It filters out the target and returns the result.
> AP-1 > WordsWithout task

- From_Maha/ToppingMapper.java
Update toppings in the map: if "potato" exists, copy its value to "fries".  
If "salad" exists, copy its value to "spinach". Returns the updated map.
> Adding topping3 file

- from_Huria/ReplacingAllZerosAtFront.java
The code rearranges an array so that all zeros are moved to the front. The relative order of non-zero numbers does not matter. Works by either modifying the original array or creating a new one.
> TRA5080: Adding  zeroFront Task

- From_Shaima/HaveThreeChecker.java
The code returns  true if the array contains exactly three 3’s, and no two 3’s are next to each other.
> TRA4781:haveThree-- 🔎 Check for Exactly Three Non-Adjacent 3s

- from_Kaltham/SplitFiveThree.java
The class SplitFiveThree has a method canSplitFiveThree that checks if an array can be split into two groups with equal sums under these rules:
Multiples of 5 must go into the first group.
Multiples of 3 (but not 5) must go into the second group.
All other numbers can go into either group.
It uses recursion to assign numbers according to these rules and returns true if a valid split is possible.
> TRA-5106: Recursion-2 >=The solution for split53 Task

- From_Manal/SquareValues.java
- From_Manal/StringsWithZRemover.java
This Method return a list of the strings, omitting any string that contains a "z".
> TRA-5120-Functional-2: noZ

- From_Manal/SquareValues.java
- From_Manal/YAdderAndYYRemover.java
This Method return a list where each string has "y" added at its end, omitting any resulting strings that contain "yy" as a substring anywhere.
> TRA-5121-Functional-2: noYY

- From_Shaima/ArrayLeftShifter.java
The code returns a new array with all elements shifted one position to the left. The first element moves to the end of the array.
> TRA5139: shiftLeft--🔄 Left Shift Array

- From_Shaima/ElementsAfterFour.java
The code returns a new array containing all elements that appear after the last 4 in the original array.
> TRA5136: post4--➡️ Elements After Last 4

- From_Manal/SquareValues.java
- From_Manal/TeenNumbersRemover.java
This Method return a list of those numbers, omitting any that are between 13 and 19 inclusive.
> TRA-5126-Functional-2: noTeen

- From_Shaima/ElementsBeforeFour.java
The code returns a new array containing all elements that appear before the first 4 in the original array.
> TRA5137: pre4--⬅️ Elements Before First 4

- From_Mulk/UniqueScore.java
I created a method that adds the largest multiples of 10 from two arrays. A helper function checks each array to find the highest number divisible by 10.
> AP-1 > ScoresSpecial task

- From_Mulk/ArrayMerger.java
I wrote a method that merges two ordered string arrays into one array of a given size. It compares elements from both arrays and adds the smaller one to the result, skipping duplicates if both elements are the same.
> AP-1 > MergeTwo task

- From_Mulk/CommonElements.java
I wrote a method that counts how many unique strings appear in both arrays. It checks for matches and makes sure not to count the same string more than once by keeping track of what’s already been counted.
> AP-1 > CommonTwo task

- From_Shaima/EvenOddArranger.java
The code rearranges an array so that all even numbers appear before all odd numbers.
> TRA5132: evenOdd--⚖️ Even-Odd Separator

- From_Shaima/ArrayStringGenerator.java
The code returns a new string array of length n. The array should contain strings representing numbers from "0" up to "n-1".
> TRA4771: fizzArray2 -- 🔢 Create String Array of Numbers 0 to n-1

- From_Shaima/FizzBuzzGenerator.java
The code creates an array representing numbers in a given range [start, end). For multiples of 3, the number is replaced with "Fizz", for multiples of 5 with "Buzz", and for multiples of both with "FizzBuzz".
> TRA5131: fizzBuzz--🎉 FizzBuzz Array Generator

- from_Hawraa/ArraySearchUtils.java
I added a recursive method hasSixFromIndex, to check if the number 6 exists in the array starting from a given index, returning true if found and false otherwise.
> TRA-5036: Recursion-1: array6 added

- from_Hawraa/ArrayElevensCounter.java
I implemented countElevens, as a recursive method that counts and returns how many times the number 11 appears in the array.
> TRA-5037: Recursion-1: array11 added

- From_Shaima/ThreeSameParityChecker.java
The code Checks whether an array of integers contains three consecutive numbers that are either all even or all odd. Returns true if such a sequence exists, otherwise false.
> TRA5173:modThree--🔢 Three-in-a-Row Parity Check

- From_Shaima/ArrayMatchCounter.java
The code checks whether the elements differ by 2 or less but are not exactly equal. It returns the count of such "almost matches."
> TRA5172: matchUp--🤏 Almost Matches

- From_Manal/SquareValues.java
- From_Manal/ThreeOrFourLengthRemover.java
This Method return a list of the strings, omitting any string length 3 or 4.
> TRA-5127-Functional-2: no34

- From_Manal/NumbersReplacerAndRemover.java
- From_Manal/SquareValues.java
This update introduces the square56 method, which processes a list of integers by:
Squaring each number and adding 10 to the result.
Filtering out any resulting values that end in 5 or 6.
> TRA-5128-Functional-2: square56
